### ISSUE TITLE
Animate Lottie with react-native-reanimated

### ISSUE THREAD

**Issue by josmmv** [lottie-react-native/lottie-react-native#1003]
I want to animate the progress value, but using react-native-reanimated. I tried the solution mentioned in [this issue #698](https://github.com/lottie-react-native/lottie-react-native/issues/698#issuecomment-873084608), but it doesn't work with the latest version of reanimated.

Is there any other way to implement this?

**Comment by matinzd** [comment]
Can you try react native animated API?

**Comment by josmmv** [comment]
Yes, but the problem arose because I was using react native reanimated and react native animated API in the same file, and that's a bit confusing. And it would be nice to have lottie working with react native reanimated. But in the meantime I created this hook to make things easier 

```typescript
import { useRef } from 'react'
import { Animated, Easing } from 'react-native'

interface Props {
  duration?: number
}

const useAnimateLottie = ({ duration = 2000 }: Props) => {
  const lottie = useRef(new Animated.Value(0))

  const playLottie = () => {
    Animated.timing(lottie.current, {
      toValue: 1,
      duration,
      easing: Easing.linear,
      useNativeDriver: false,
    }).start()
  }

  const reverseLottie = () => {
    Animated.timing(lottie.current, {
      toValue: 0,
      duration,
      easing: Easing.linear,
      useNativeDriver: false,
    }).start()
  }

  return {
    lottie,
    playLottie,
    reverseLottie,
  }
}

export default useAnimateLottie
```

**Comment by matinzd** [comment]
I will take a look into this this weekend if I find some time.

**Comment by matinzd** [comment]
This should get fixed in v6. I will close this for now. 
Feel free to reopen it.

**Comment by matinzd** [comment]
> I've tested with `6.0.0-rc.3` and still encountered the issue.
> 
> 
> 
> ```
> 
>     "lottie-react-native": "6.0.0-rc.3",
> 
>     "react-native-reanimated": "^3.0.2",
> 
>     "react-native": "^0.71.0",
> 
> ```

I have not released the changes yet. Please wait for stable version.

**Comment by matinzd** [comment]
Just released `6.0.0-rc.4`. Please try again and let me know.

**Comment by ZloyRob** [comment]
@matinzd  I tried and it didn't work
```
    "lottie-react-native": "^6.0.0-rc.4",
    "react-native-reanimated": "^3.0.2",
    "react-native": "0.71.4",
```

```
const AnimatedLottieView = Animated.createAnimatedComponent(LottieView);

  const progress = useSharedValue(0);

  const animatedProps = useAnimatedProps(() => {
    return {
      progress: progress.value,
    };
  });

  useEffect(() => {
    progress.value = withTiming(1, {duration: 4000});
  }, [progress]);

  return (
        <AnimatedLottieView
          animatedProps={animatedProps}
          source={require('assets/lottie/test.json')}
        />
);
```

**Comment by matinzd** [comment]
> @matinzd I tried and it didn't work
> 
> ```
>     "lottie-react-native": "^6.0.0-rc.4",
>     "react-native-reanimated": "^3.0.2",
>     "react-native": "0.71.4",
> ```
> 
> ```
> const AnimatedLottieView = Animated.createAnimatedComponent(LottieView);
> 
>   const progress = useSharedValue(0);
> 
>   const animatedProps = useAnimatedProps(() => {
>     return {
>       progress: progress.value,
>     };
>   });
> 
>   useEffect(() => {
>     progress.value = withTiming(1, {duration: 4000});
>   }, [progress]);
> 
>   return (
>         <AnimatedLottieView
>           animatedProps={animatedProps}
>           source={require('assets/lottie/test.json')}
>         />
> );
> ```

Sorry, there was a problem with rc4 release. Try `6.0.0-rc.4`.
