### ISSUE TITLE
Library not working with react native 0.71

### ISSUE THREAD

**Issue by Daggron** [lottie-react-native/lottie-react-native#1017]
### Description

We have recently upgraded to React native 0.71.7 in our application, we use lottie to power some animation on our app.
While we were using react-native version 0.66.5 it was working as expected, but now with the upgrade it is breaking and animation is not happening. We tried upgrading lottie to and rc version v6 which is working fine, but since its an rc version we can't use it in production. 

And rc version is causing alignment issues (Refer to the screen shot shared below)

![image](https://user-images.githubusercontent.com/41940582/234497088-8b9927f3-8dee-4370-ac13-a100592610f2.png)

[Lottie JSON File](https://app.lottiefiles.com/share/411852d8-04e8-4acf-9a37-fb2c6359e7bd)

### Steps to Reproduce

1. Upgrade React native to 0.71.7
2. have a lottie-react-native version "5.1.5", and lottie-ios version  "3.4.1",

**Expected behavior:** [What you expected to happen]
- animation should happen correctly

**Actual behavior:** [What actually happened]
- animation not happening and getting stuck

### Versions

"react-native": "0.71.7",
"lottie-ios": "3.4.1",
"lottie-react-native": "5.1.5",

**Comment by TomCorvus** [comment]
Not sure if this will solve your issue, but lottie-react-native 5.1.5 doesn't need to specify lottie-ios version.

> For lottie-react-native <= 5.1.4 you also need to install lottie-ios@3.4.1 package:
> yarn add lottie-ios@3.4.1

but for higher version, just:
> Install lottie-react-native (latest):
> yarn add lottie-react-native

lottie-react-native 5.1.5 use lottie-ios ^3.4.0 so 3.5.0 version which is the latest 3 minor version.

**Comment by Brittognanaraj** [comment]
Please help about this issue to https://github.com/lottie-react-native/lottie-react-native/issues/1016

**Comment by Daggron** [comment]
> Not sure if this will solve your issue, but lottie-react-native 5.1.5 doesn't need to specify lottie-ios version.
> 
> > For lottie-react-native <= 5.1.4 you also need to install lottie-ios@3.4.1 package:
> > yarn add lottie-ios@3.4.1
> 
> but for higher version, just:
> 
> > Install lottie-react-native (latest):
> > yarn add lottie-react-native
> 
> lottie-react-native 5.1.5 use lottie-ios ^3.4.0 so 3.5.0 version which is the latest 3 minor version.

Holy smokes, this works, Thanks a ton man
