### ISSUE TITLE
Build crashing on React native macos

### ISSUE THREAD

**Issue by HunainHumail** [lottie-react-native/lottie-react-native#1018]
### Description
I have installed react-native-macos in my project. Android and IOS are working fine with react-native-lotte. But when i am trying to build the macos project, the build is crashing.

[Description of the bug]
The following build commands failed:
	SwiftEmitModule normal arm64 Emitting\ module\ for\ lottie_react_native (in target 'lottie-react-native-macOS' from project 'Pods')
(1 failure)

Also when I see my XCODE, getting this error Cannot find type 'UITraitCollection' in scope
### Steps to Reproduce

react-native run-macos

**Expected behavior:** [What you expected to happen]
App should work as it is working for android and ios
**Actual behavior:** [What actually happened]
App is crashing
<img width="1181" alt="Screenshot 2023-05-01 at 3 14 17 PM" src="https://user-images.githubusercontent.com/37023744/235439478-0860f6e3-3e66-4ee6-a0da-0e1c583dfa6e.png">

### Versions
react native: 0.71
react native macos: 0.71

You can get this information from executing `npm version`.

**Comment by matinzd** [comment]
What version of lottie are you using?

**Comment by HunainHumail** [comment]
> What version of lottie are you using?

"lottie-react-native": "^5.1.5",
"react": "18.2.0",
    "react-native": "0.71.7",
    "react-native-macos": "^0.71.0-0",

**Comment by HunainHumail** [comment]
> What version of lottie are you using?

"lottie-react-native": "^5.1.5",
"react": "18.2.0",
"react-native": "0.71.7",
"react-native-macos": "^0.71.0-0",

**Comment by Saadnajmi** [comment]
React Native macOS maintainer here, if we ifdef out the iOS block for macOS, are there any other issues? I took a quick look at the code and it seems to be implemented cross platform

**Comment by matinzd** [comment]
Let me know if this has fixed the issue in rc7. @HunainHumail
