### ISSUE TITLE
[Android] Build failing with RN 0.72

### ISSUE THREAD

**Issue by fabioh8010** [lottie-react-native/lottie-react-native#1022]
### Description

Android build is failing with a project that uses RN 0.72:

```
FAILURE: Build failed with an exception.

* Where:
Script '/Users/fabiohenriques/Documents/Work/OSS/ReactNative/RN0720RC1/node_modules/lottie-react-native/src/android/gradle-maven-push.gradle' line: 108

* What went wrong:
A problem occurred configuring project ':lottie-react-native'.
> Could not set unknown property 'classifier' for task ':lottie-react-native:androidJavadocsJar' of type org.gradle.api.tasks.bundling.Jar.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
error Failed to install the app. Command failed with exit code 1: ./gradlew tasks FAILURE: Build failed with an exception. * Where:
Script '/Users/fabiohenriques/Documents/Work/OSS/ReactNative/RN0720RC1/node_modules/lottie-react-native/src/android/gradle-maven-push.gradle' line: 108 * What went wrong:
A problem occurred configuring project ':lottie-react-native'.
> Could not set unknown property 'classifier' for task ':lottie-react-native:androidJavadocsJar' of type org.gradle.api.tasks.bundling.Jar. * Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights. * Get more help at https://help.gradle.org BUILD FAILED in 3s
> Task :gradle-plugin:compileKotlin UP-TO-DATE
> Task :gradle-plugin:compileJava NO-SOURCE
> Task :gradle-plugin:pluginDescriptors UP-TO-DATE
> Task :gradle-plugin:processResources UP-TO-DATE
> Task :gradle-plugin:classes UP-TO-DATE
> Task :gradle-plugin:jar UP-TO-DATE
> Task :gradle-plugin:inspectClassesForKotlinIC UP-TO-DATE > Configure project :lottie-react-native
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.
5 actionable tasks: 5 up-to-date.
```

Applying this patch on `src/android/gradle-maven-push.gradle` file will solve the problem:

```diff
diff --git a/node_modules/lottie-react-native/src/android/gradle-maven-push.gradle b/node_modules/lottie-react-native/src/android/gradle-maven-push.gradle
index 6c97bcf..166e73b 100644
--- a/node_modules/lottie-react-native/src/android/gradle-maven-push.gradle
+++ b/node_modules/lottie-react-native/src/android/gradle-maven-push.gradle
@@ -105,12 +105,12 @@ afterEvaluate { project ->
   }
 
   task androidJavadocsJar(type: Jar, dependsOn: androidJavadocs) {
-    classifier = 'javadoc'
+    archiveClassifier = 'javadoc'
     from androidJavadocs.destinationDir
   }
 
   task androidSourcesJar(type: Jar) {
-    classifier = 'sources'
+    archiveClassifier = 'sources'
     from android.sourceSets.main.java.sourceFiles
   }
 

```

The building is failing because now RN 0.72 uses Gradle 8.0, and [there is breaking change](https://docs.gradle.org/8.0.2/userguide/upgrading_version_7.html#abstractarchivetask_api_cleanup) where `classifier` was removed and `archiveClassifier` must be used instead.

I tried to fix the problem by myself and raise a PR but wasn't able to find this file in the repo, which makes me wondering if it's something generated during a release.

### Steps to Reproduce

1. Setup a RN project with the 0.72 release candidate.
2. Add `lottie-react-native` library to project.
3. Run the Android build.

**Expected behavior:** The project should build without problems.

**Actual behavior:** The project is failing during build.

### Versions

```
"lottie-react-native": "^5.1.5",
"react": "18.2.0",
"react-native": "0.72.0-rc.1"
```

**Comment by matinzd** [comment]
`gradle-maven-push.gradle` file is removed and it will not be available in the next major release. I will try to apply this patch for v5.

**Comment by matinzd** [comment]
Backported the fix in release [5.1.6](https://github.com/lottie-react-native/lottie-react-native/releases/tag/v5.1.6).

**Comment by rililive** [comment]
Can this also be backported for v4.1.3?

**Comment by matinzd** [comment]
> Can this also be backported for v4.1.3?

Is there any reason for you to keep using the old version? 
We are not going to support v4 anymore.

**Comment by Kamal2301** [comment]
Thank You

**Comment by TassainRasool** [comment]
"react-native": "0.68.5",
"react-native-reanimated": "3.6.1",

getting this error
Caused by: groovy.lang.MissingPropertyException: Could not set unknown property 'classifier' for task ':lottie-react-native:androidJavadocsJar' of type org.gradle.api.tasks.bundling.Jar.

**Comment by nolife08021** [comment]
@TassainRasool  hi, did you fix the error? i facing same error now. 

lottie-react-native : v5.1.4
react-native: v0.74.2

**Comment by TassainRasool** [comment]
@nolife08021 , hello No I couldn't fix the error but I used reanimated library and applied some patch and then it worked fine.

**Comment by nolife08021** [comment]
> @nolife08021 , hello No I couldn't fix the error but I used reanimated library and applied some patch and then it worked fine.

@TassainRasool do you mind to you share me the patch you made ? i still having that issue ..thanks
