### ISSUE TITLE
its un working, in reactnative 0.71.6

### ISSUE THREAD

**Issue by HuziG** [lottie-react-native/lottie-react-native#1027]
### Description

[Description of the bug]

### Steps to Reproduce

1. install the plugin
2. use a simple example form the document
3. but is un working , nothing

**Expected behavior:** [What you expected to happen]
un working

**Actual behavior:** [What actually happened]
working

**This is my Code:**
``` javascript
<View style={tw`mt-1`}>
  <Lottie source={require('../../assets/lottie/136808-ai-orb.json')} autoPlay loop />
  <Text style={tw`text-gray-600`}>Loading...</Text>
</View>
```

**Lottie File Path:**
<img width="337" alt="image" src="https://github.com/lottie-react-native/lottie-react-native/assets/28282506/ec7d6bfd-a754-4b89-afec-c310f2928ed5">

**The Preview:**
![IMG_2332](https://github.com/lottie-react-native/lottie-react-native/assets/28282506/b1b676cf-1db6-4ff5-a4a7-f2204e02681b)

### Versions
"lottie-react-native": "^5.1.6",
"react": "18.2.0",
"react-native": "0.71.6",

You can get this information from executing `npm version`.

**Comment by HuziG** [comment]
i found this, when pod install finish

<img width="474" alt="image" src="https://github.com/lottie-react-native/lottie-react-native/assets/28282506/7eda9752-a863-46f3-b37c-0147e86e6da0">

**Comment by chace20** [comment]
That's the same problem I meet.

The below code is work, but if I wrap `Lottie` in a `View`, then it disappear.
```
<Lottie source={require('../../assets/lottie/136808-ai-orb.json')} autoPlay loop />
```

**Comment by chace20** [comment]
You should set Lottie width and height explicit.

**Comment by HuziG** [comment]
for everyone , i solve this problem.

1. yarn add lottie-react-native@next, the version is 6.0.0-rc.6
2. cd ios , pod install. the ios-lottie will download into the app
3. use xcode reinstall the app
4. finally it is working
5. then we need set the width and height on the <Lottie />, it is very important
