### ISSUE TITLE
Support for dotLottie?

### ISSUE THREAD

**Issue by arasrezaei** [lottie-react-native/lottie-react-native#1032]
Hi, currently there is no way to use dotLottie files with lottie react native.
i think implemention is simple cause native runtimes support it.

**Comment by walterholohan** [comment]
This would be amazing, we have a lot of lottie's in our application and the size has nearly gotten to 26mb. So supporting dotLottie would help us reduce our bundle size drastically

**Comment by dangnguyen1004** [comment]
Hi team, which version does this feat support?
