### ISSUE TITLE
colorFilters not working on Android

### ISSUE THREAD

**Issue by andrewlo** [lottie-react-native/lottie-react-native#1040]
### Description

In `6.0.0-rc.7` setting `colorFilters` doesn't seem to work Android (but works on iOS):

Android:
<img width="170" alt="Screenshot 2023-06-26 at 3 07 53 PM" src="https://github.com/lottie-react-native/lottie-react-native/assets/1470768/cf675f81-17b1-4081-8d45-a1867c5eee19">

iOS:
<img width="176" alt="Screenshot 2023-06-26 at 3 08 30 PM" src="https://github.com/lottie-react-native/lottie-react-native/assets/1470768/e90e3f6e-b116-403b-bc0f-df04dcee45be">

We're trying to update to 6.0.0 in order to fix the progress prop not being animatable (https://github.com/lottie-react-native/lottie-react-native/issues/1003):

### Steps to Reproduce

```
    <LottieView
        loop={false}
        ref={ref => (lottie.current = ref)}
        resizeMode="cover"
        source={NotificationIconLottie}
        style={
          size ? {height: ICON_SIZES[size], width: ICON_SIZES[size]} : undefined
        }
        colorFilters={
          color
            ? [
                {
                  keypath: '*',
                  color: theme.colors[color],
                },
              ]
            : undefined
        }
      />
````

**Expected behavior:** The colour in the Lottie is set as it is on iOS or on version `5.1.6`

**Actual behavior:** Colour doesn't seem to get set on Android

### Versions

```
    "lottie-ios": "4.2.0",
    "lottie-react-native": "6.0.0-rc.7",
```

**Comment by thevoiceless** [comment]
Seeing the same behavior on Android with `v6.0.0-rc.7`
