### ISSUE TITLE
Some lottie animation are visually broken and some causes application crash

### ISSUE THREAD

**Issue by Sebosek** [lottie-react-native/lottie-react-native#1042]
### Description

I've tried some of lottie animations. Some of them are visually incorrect, like https://lottiefiles.com/118238-colour-change and some of them causes application crash, like this one https://lottiefiles.com/148188-a-ghost.
Has anyone faced the same issue? Is something wrong with those animations?

### Steps to Reproduce

1. Download mentioned animations
2. Require lottie json file in sample from 1st step
3. Run the app and preview the animation

** Application code **

```
const lottie = require('../assets/animations/colour-change.json');

export const AppLottieView: FunctionComponent = () => {

  return (
    <Lottie
      source={lottie}
      autoPlay
      loop
    />
  );
};
```

**Expected behavior:**
Both animations play as expected.

**Actual behavior:**
The animation https://lottiefiles.com/118238-colour-change is visually broken, see the screenshot below. The animation https://lottiefiles.com/148188-a-ghost causes the application to crash.

<img width="326" alt="image" src="https://github.com/lottie-react-native/lottie-react-native/assets/372542/bcfe15fd-ee8a-4ebf-b3ca-1d80510b2aca">

### Versions

expo: "48.0.18",
react: "18.2.0",
react-native: "0.71.8",
lottie-react-native: "5.1.4"

**Comment by Sebosek** [comment]
How do you know, what features are used in animation? Is it listed somewhere and I just oversaw it, or do I need open the animation in Adobe or raw JSON and look for any particular JSON property..?

**Comment by matinzd** [comment]
> How do you know, what features are used in animation? Is it listed somewhere and I just oversaw it, or do I need open the animation in Adobe or raw JSON and look for any particular JSON property..?

You need to check it inside Adobe and see what kind of properties are being used. 

Or if you think there is an issue with react native library, you can install lottie app on iOS and android and try the animation there.

https://lottiefiles.com/mobile
