### ISSUE TITLE
6.0.0-rc.7 ios showed empty   RCT_NEW_ARCH_ENABLED=1

### ISSUE THREAD

**Issue by LeoTrusty** [lottie-react-native/lottie-react-native#1043]
### Description

onAnimationFinish is called,  but ios showed empty。    when  change  source={require('./LottieLogo1.json')}  to  source={require('./DynamicText.json)}  ,     Everything goes well,  then you change source={require('./DynamicText.json)}   to   source={require('./LottieLogo1.json')},  it  worked 

### Steps to Reproduce

the bug appear  everytime,  code and env as below

``` js

import LottieView from 'lottie-react-native';
<LottieView
          source={require('./LottieLogo1.json')}
          autoPlay={true}
          loop={true}
          style={{
            width: p(200),
            height: p(200),
          }}
          resizeMode={'contain'}
          enableMergePathsAndroidForKitKatAndAbove
          onAnimationFinish={() => {
            console.log('LottieViews---finished');
          }}
```

**Expected behavior:** [What you expected to happen]

![image](https://github.com/lottie-react-native/lottie-react-native/assets/8004236/2caba50f-d78c-456d-8527-139cf3eb0ff2)

**Actual behavior:** [What actually happened]
![image](https://github.com/lottie-react-native/lottie-react-native/assets/8004236/0435994f-9be4-4134-8280-9a084d3e90a0)

### Versions
  "lottie-ios": "^4.2.0",
   "lottie-react-native": "6.0.0-rc.7",
   "react": "18.2.0",
   "react-native": "0.72.1",

**Comment by ntcong91** [comment]
+ 1 with NewArchEnabled true

**Comment by anilsmaitic01** [comment]
Any updates on this ? I am also getting blank canvas on ios however Android seems to work just fine

**Comment by anilsmaitic01** [comment]
Hey there, I've been scratching my head around and playing with all possible props. I am using the latest unstable build in order to support the new React Native Architecture. 

react: "18.2.0"
react-native: "0.72.2"
lottie-react-native: "^6.0.0-rc.7"

Now my Component looks something like this
```
<AnimatedLottieView
          source={require('@/assets/lottie/animation_loading.json')}
          autoPlay
          loop
          resizeMode="cover"
          // eslint-disable-next-line react-native/no-inline-styles
          style={{width: 200, height: 200}}
          cacheComposition={true}
          autoSize={true}
          enableMergePathsAndroidForKitKatAndAbove
          hardwareAccelerationAndroid
          key={Date.now().toString()}
          testID={Date.now().toString()}
          useNativeLooping
          renderMode="AUTOMATIC"
/>
```

The final result is still unreliable. The animation appears for a moment and disappears when I restart the app. I am not 100% sure since I haven't delved into the native codebase, but my speculation is that this might be a result of an error in the caching mechanism or the loading of the Lottie engine. Perhaps there is a caching issue or a loading issue? I thought this information might be helpful for future patch releases.

Note: Android appears to work just fine

**Comment by matinzd** [comment]
It seems like I may have found a way to recreate this issue. Is it correct that this only occurs during the initial rendering on iOS? If you either trigger a re-render or provide a different source, it should resolve the problem. I can include this information in the list of known issues for those who have new architecture enabled.

**Comment by anilsmaitic01** [comment]
> It seems like I may have found a way to recreate this issue. Is it correct that this only occurs during the initial rendering on iOS? If you either trigger a re-render or provide a different source, it should resolve the problem. I can include this information in the list of known issues for those who have new architecture enabled.

Yes, the initial render does not work at all and when we try out with different Lottie files i.e rerender, it works out of the blue.
