### ISSUE TITLE
Animation does not scale when android display size changes

### ISSUE THREAD

**Issue by antonandreyev** [lottie-react-native/lottie-react-native#1044]
### Description

Animation does not scale properly if the Android system display size changes and the app is not restarted.

### Steps to Reproduce

See the demo
1. launch the app - see all good
2. collapse the app, don't kill
3. change the display size in android settings
4. return to the app
5. see the animation changed it's size
6. kill the app, open again
7. see the animation has correct size

I tried to fix this with resizeMode and also aspectRatio/width/height in styles. But they change the animation appearance only after app restart.

### Code is simple:
```typescript
import { createNativeStackNavigator } from "@react-navigation/native-stack";
import Lottie from "lottie-react-native";

export const SplashScreen = () => {

  return (
    <Lottie
      source={require("../assets/splash.lottie.json")}
      autoPlay
      loop={false}
      style={{ backgroundColor: "white", flex: 1 }}
    />
  );
};

const SplashStack = createNativeStackNavigator();

export const SplashStackNavigator = () => {
  return (
    <SplashStack.Navigator
      screenOptions={{
        headerShown: false,
      }}
    >
      <SplashStack.Screen
        name={ScreenNames.SPLASH_SCREEN}
        component={SplashScreen}
      />
    </SplashStack.Navigator>
  );
};
```

**Expected behavior:** [What you expected to happen]

Animation still have the same size without app restart.

**Actual behavior:** [What actually happened]

Animation changes the size until the app is killed and opened again.

### Demo

https://github.com/lottie-react-native/lottie-react-native/assets/5842508/fba05c8a-1018-4434-8d4d-4e344871bd57

### Versions

-   "react-native": "0.71.7",
-   "lottie-react-native": "^5.1.6",
-   "@react-navigation/native": "^6.1.6",
-   "@react-navigation/native-stack": "^6.9.12",

**Comment by matinzd** [comment]
Here is a possible solution (I don't know the dimensions so this might not work):

```tsx
export const SplashScreen = () => {
  return (
    <View
      style={{
        backgroundColor: 'white',
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
      }}>
      <Lottie
        source={require('../assets/splash.lottie.json')}
        autoPlay
        resizeMode={'contain'}
        loop={false}
      />
    </View>
  )
}
```

**Comment by antonandreyev** [comment]
@matinzd no, not working even if I set fixed dimensions
```ts
  return (
    <View
      style={{
        backgroundColor: "white",
        justifyContent: "center",
        alignItems: "center",
        height: 600,
        width: 380,
        borderWidth: 3,
      }}
    >
      <Lottie
        source={require("../assets/splash.lottie.json")}
        autoPlay
        loop={false}
        resizeMode={"contain"}
      />
    </View>
  );
```
[fixed_dimensions.webm](https://github.com/lottie-react-native/lottie-react-native/assets/5842508/b3c8474a-a31b-4c59-a093-11a2722ce1ee)



> It's not recommended to fill the whole screen with a lottie view.

If that's the case - it should be mentioned somewhere in the docs

**Comment by matinzd** [comment]
Can you try the next RC version and let me know if this issue exists there?

**Comment by antonandreyev** [comment]
@matinzd I tried 6.0.0 and still see the same. I created a repo with example for reproduction: https://github.com/antonandreyev/rn-lottie-android-resize-example

**Comment by matinzd** [comment]
Try giving `LottieView` a constant width and height and remove `flex: 1`  on LottieView.

https://github.com/antonandreyev/rn-lottie-android-resize-example/blob/3e0f6e324652139f1d4767bc80c430b0d95c47f6/src/SplashScreen.tsx#L17

**Comment by antonandreyev** [comment]
The issue is not observed anymore on 6.3.1. Although may be related to us updating the animation file
