### ISSUE TITLE
play works incorrectly in version 6.0.0-rc.7

### ISSUE THREAD

**Issue by zispidd** [lottie-react-native/lottie-react-native#1049]
### Description

on the 5.1.4 version, i can play segments, and frames will not be reset to the first. When I use 6.0.0-rc.7(i need this version because of integration with reanimated), frames reset to 0 when I use ref.current.play()

### Steps to Reproduce

1. install 6.0.0-rc.7 version
2. disable loop and autoplay and put ref
3. when a user presses - play frames, for example, if the animation has 100 frames, play 0-100, then 100-0. frames will be reset to 0

### Code Example

```ts
const variants = {
  default: [0, 15],
  hover: [15, 0],
  like: [15, 100],
  defaultLiked: [100, 115],
  hoverLiked: [115, 100],
  removeLike: [115, 180],
  shake: [181, 213]
}

const Like: React.FC<IProps> = ({ style, isLiked, onPress }) => {
  const [segments, setSegments] = useState<number[]>(isLiked ? variants.defaultLiked : variants.default)
  const ref = useRef<LottieView>(null)

  useEffect(() => {
    ref.current!.play(segments[0], segments[0] + 1)
  }, [])

  const handlePress = () => {
    const segment = isLiked ? variants.removeLike : variants.like
    ref.current!.play(segment[0], segment[1] + 1)
    if (onPress) onPress()
  }

  const onAnimationFinish = () => {
    if (segments === variants.like) setSegments(variants.defaultLiked)
    if (segments === variants.removeLike) setSegments(variants.default)
  }

  return (
    <TouchableOpacity
      activeOpacity={0.7}
      onPress={handlePress}
      style={[styles.item]}
    >
      <LottieView
        source={require('../../animations/like.json')}
        ref={ref}
        style={[styles.item, styles.icon]}
        onAnimationFinish={onAnimationFinish}
        loop={false}
        autoPlay={false}
        resizeMode='cover'
      />
    </TouchableOpacity>
  )
}

const styles = StyleSheet.create({
  item: {
    width: 50,
    height: 50
  },
  icon: {
    flexGrow: 1
  }
})
```

**Expected behavior:**

https://github.com/lottie-react-native/lottie-react-native/assets/41930026/7dc679c3-52d0-40c2-8a13-47a7ad1d9d20

**Actual behavior:**

https://github.com/lottie-react-native/lottie-react-native/assets/41930026/1e55a940-14bc-4f37-a3e1-aa46b806aced

### Versions

"lottie-react-native": "5.1.4",
"react": "18.2.0",
"react-native": "0.71.7",

**Comment by matinzd** [comment]
You can animate `progress` prop instead. Check out the example code in the repository:

https://github.com/lottie-react-native/lottie-react-native/blob/master/apps/paper/src/LottieAnimatedExample.tsx

**Comment by zispidd** [comment]
But I think it's a bug, don't you? It works on the old version, but not on the new one.

**Comment by matinzd** [comment]
> But I think it's a bug, don't you? It works on the old version, but not on the new one. @matinzd 

Yes. I’ll look into that.
