### ISSUE TITLE
6.0.0 does not work with react native web

### ISSUE THREAD

**Issue by ethanneff** [lottie-react-native/lottie-react-native#1064]
### Description

when upgrading from 5.1.6 to 6.0.0

```sh
ERROR in ./node_modules/lottie-react-native/lib/module/specs/LottieAnimationViewNativeComponent.js 1:0-93
Module not found: Error: Can't resolve 'react-native/Libraries/Utilities/codegenNativeComponent' in 'node_modules/lottie-react-native/lib/module/specs'
```

### Steps to Reproduce

1. https://codesandbox.io/s/nervous-http-f332hv?file=/src/App.js

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

You can get this information from executing `npm version`.

```
  npm: '9.5.0',
  node: '18.14.2',
  v8: '10.2.154.26-node.22',
  uv: '1.44.2',
  zlib: '1.2.13',
  brotli: '1.0.9',
  ares: '1.18.1',
  modules: '108',
  nghttp2: '1.51.0',
  napi: '8',
  llhttp: '6.0.10',
  uvwasi: '0.0.14',
  acorn: '8.8.1',
  simdutf: '3.1.0',
  undici: '5.20.0',
  openssl: '3.0.8+quic',
  cldr: '42.0',
  icu: '72.1',
  tz: '2022g',
  unicode: '15.0',
  ngtcp2: '0.8.1',
  nghttp3: '0.7.0'
```

**Comment by matinzd** [comment]
As far as I remember we were not providing react-native-web support.

**Comment by adamhari** [comment]
6.0.0 works with [react-native-web-lottie](https://github.com/react-native-web-community/react-native-web-lottie)
