### ISSUE TITLE
Animation not showing on Ios

### ISSUE THREAD

**Issue by Oladeji233** [lottie-react-native/lottie-react-native#1075]
### Description
I'm working on an Animated splash screen using Expo, but the animation is not working and it's just showing a blank screen.
I tried the animation on Android and it worked. I also created a new project on Expo and tested with the expo go app and it worked. So I guess it has to do with my versions, but I don't know how to go about fixing it.

### Steps to Reproduce
      <LottieView
        ref={animationRef}
        autoPlay
        loop
        style={{
          width: 500,
          height: 500,
          backgroundColor: "#eee",
        }}
        source={require("../assets/animation/splash.json")}
      />

**Expected behavior:** I expect the animation to play

**Actual behavior:**It just shows a blank screen
### Versions
  "lottie": "^0.0.1",
    "lottie-react-native": "^5.1.5",
   "react-native": "0.71.8",
    "expo": "^48.0.0",

**Comment by TheRogue76** [comment]
Heya @Oladeji233 

Thank you for the error report. Can you share your minimal reproduction? The versions you provided mention lottie as 0.0.1.

**Comment by Oladeji233** [comment]
> Heya @Oladeji233
> 
> Thank you for the error report. Can you share your minimal reproduction? The versions you provided mention lottie as 0.0.1.

I actually didn't install the lottie package directly. I installed lottie-react-native as instructed by the docs so I just assumed expo installed the lottie package as part of setting it up. Also I am using Eas development builds, I only used Expo go when I created a new test app to check and it worked.
Thanks for your help.

**Comment by TheRogue76** [comment]
Great to hear. Does that mean your issue is resolved and I can close this?

The Lottie package is no longer a requirement with the latest versions, but It used to be in older versions.

**Comment by Oladeji233** [comment]
Yes you can close it. My solution was to install the version listed in the npm page directly [6.0.0-rc.6](https://www.npmjs.com/package/lottie-react-native/v/6.0.0-rc.6).
