### ISSUE TITLE
[Question] How to get dynamic ratio since 6.x ?

### ISSUE THREAD

**Issue by TomCorvus** [lottie-react-native/lottie-react-native#1078]
### Description

Hi,

Since 6.x, default dimensions are no more.
We have to set fixed dimensions on Lottie View to display the animation.
I created an issue about this but it was closed with the wont fix badge (https://github.com/lottie-react-native/lottie-react-native/issues/1015)

What is the solution to get this behavior with a width: 100% as dimension and get the good ratio automatically?
If I set fixed dimensions on each animation, these dimensions will not be appropriated for larger screens like tablet.

We really need to have a condition for each screen size and for each animation?
Can we get animation dimensions in animation reference object if I use dotLottie files?

Thanks.

**Comment by matinzd** [comment]
Hi Tom,

Unfortunately, it's not possible to get the information from the `.lottie` binary. The best way is to check the aspect ratio on your side when choosing animations or we can expose a method from the library to extract information on the fly about the animation that is being rendered.

**Comment by mlazari** [comment]
If you know the width and height of the animation, you can use [aspectRatio](https://reactnative.dev/docs/layout-props#aspectratio):
```
{
  width: '100%',
  aspectRatio: animationWidth / animationHeight,
}
```

As per the comment above it looks like you can't get the dimensions programatically from .lottie files though, so you'll need to hardcode them.
