### ISSUE TITLE
White background after upgrading to v6

### ISSUE THREAD

**Issue by dshuvalov** [lottie-react-native/lottie-react-native#1079]
### Description

I have an additional white background in my animation after updating to Lottie-react-native v6. I created the issue in the lottie-android repo https://github.com/airbnb/lottie-android/issues/2353

[Description of the bug]

### Steps to Reproduce

```typescript
import mintingUnpackingAnimation from '../../hooks/minting-unpacking.json';

const mintingUnpackingAnimationObj = useMemo(
  () => JSON.parse(JSON.stringify(mintingUnpackingAnimation)),
  // it's intentional to re-create the object for each sticker pack to avoid showing minted stickers from previous pack
  // eslint-disable-next-line react-hooks/exhaustive-deps
  [stickerPack.id]
);

<LottieView
  style={[StyleSheet.absoluteFill]}
  ref={unpackingLottieRef}
  loop={false}
  source={mintingUnpackingAnimationObj}
  onAnimationFinish={onFinishUnpackingAnimation}
  resizeMode="cover"
/>
```

**Expected behavior:** [What you expected to happen]
No additional white background in an animation

**Actual behavior:** [What actually happened]
White background in animation

### Minimal reproduction

Minimal reproduction attached in the original ticket in the lottie-android repo https://github.com/airbnb/lottie-android/issues/2353

### React Native Environment
"lottie-react-native": "^6.1.0",
"react-native": "0.71.6",

### Versions

You can get this information from executing `npm version`.

**Comment by mlazari** [comment]
@dshuvalov Does anything change if you set `renderMode="SOFTWARE"`? I had a different issue on iOS and that fixed it.

**Comment by luanccp** [comment]
I am also facing this issue ➕

**Comment by TulioMeran** [comment]
i am facing that too,

This is my code

` <Lottie
      source={require('../../../assets/animation/loading.json')}
      autoPlay
      loop
      resizeMode="cover"
      renderMode='SOFTWARE'
      colorFilters={[
        {
          keypath: 'Shape Layer 1',
          color: colors.primaryDark,
        },
        {
          keypath: 'Shape Layer 7',
          color: colors.grayDark,
        },
      ]}></Lottie>`

**Comment by mptorz** [comment]
I am also facing this issue. I can't even find anything in the inspector. It just does not render

**Comment by lucaswitch** [comment]
Try the available render modes: HARDWARE or SOFTWARE, set a style to the lottie view.

**Comment by TheRogue76** [comment]
This issue was fixed on Lottie 6.2.0 on Android. As of https://github.com/lottie-react-native/lottie-react-native/pull/1134, the version has been bumped to include the fix. Marking this as complete. Should be out in our next release (Hopefully soon)

**Comment by utiq** [comment]
@TheRogue76 I'm having the same issue in iOS, I'm using lottie-react-native version 6.5.1

**Comment by TheRogue76** [comment]
> @TheRogue76 I'm having the same issue in iOS, I'm using lottie-react-native version 6.5.1

Please open a new issue and fill out the template so I can take a look

**Comment by utiq** [comment]
actually it works now, I think the lottie file I was using was too old

**Comment by Vladislava9009** [comment]
Still face the same((
