### ISSUE TITLE
iOS - Build Failed on empty RN 0.72.3

### ISSUE THREAD

**Issue by krisidmisso** [lottie-react-native/lottie-react-native#1083]
### Description

Build Failed on empty RN 0.72.3

### Steps to Reproduce

1. Install package (`yarn add`, `npx pod-install`)
2. Cannot build

**Expected behavior:** Build application

**Actual behavior:** Cannot build/run the app
Tried commad: `arch -x86_64 react-native run-ios` and `npm run ios`:
```
** BUILD FAILED **

The following build commands failed:
        CompileSwift normal x86_64 /Users/krisidmisso/app/node_modules/lottie-react-native/ios/LottieReactNative/ContainerView.swift (in target 'lottie-react-native' from project 'Pods')
        SwiftCompile normal x86_64 Compiling\ ContainerView.swift /Users/krisidmisso/app/node_modules/lottie-react-native/ios/LottieReactNative/ContainerView.swift (in target 'lottie-react-native' from project 'Pods')
(2 failures)

```

Can build on Android but not iOS.

### Minimal reproduction
Trying on an empty RN project with TS

### React Native Environment
react-native: '0.72.3'

MacBook Pro M1 Pro

### Versions

yarn: '1.22.19',
npm: '8.11.0',
node: '16.16.0',
pod: '1.11.3',

**Comment by EKT2000** [comment]
In ContainerView.swift, I had several lines with following error message 
```
Reference to property '[method]' in closure requires explicit use of 'self' to make capture semantics explicit
```
It looks like there was a scope issue with async functions. I could build again by adding a `self` to the corresponding methods with this error.

Example line (there were several in the file)

Before: (line 363 ContainerView.swift) 
`failureCallback("Unable to decode the Lottie animation object from the fetched URL source: \(error.localizedDescription)")`

Fix:
`self.failureCallback("Unable to decode the Lottie animation object from the fetched URL source: \error.localizedDescription)")` 

I don't know swift, so I will not create a pr until someone with knowledge can assure that this is a way to address the issue.

**Comment by matinzd** [comment]
What is your XCode version? Have you tried opening the project with XCode?

**Comment by EKT2000** [comment]
XCode Version is 14.2. I opened the project with xcode and it showed me several errors like this
![376230CF-0542-44F3-ABDE-5E4D108564C6](https://github.com/lottie-react-native/lottie-react-native/assets/62894951/9c65b11e-fc9e-43e9-ab8b-af58bfec3a48)

**Comment by matinzd** [comment]
I will try to update the code accordingly. It needs to be backward compatible. Thanks for sending this in.

**Comment by TheRogue76** [comment]
Please try https://github.com/lottie-react-native/lottie-react-native/releases/tag/v6.1.1

**Comment by EKT2000** [comment]
The build error still occured. However #1086 this solved it

**Comment by krisidmisso** [comment]
@TheRogue76 I just updated to 6.1.1 and the issue is the same. @matinzd My XCode is 14.2 but I cannot update it because Im afraid I am going to break another project I have with an older RN version (I have the M1 cpu :/).

I manually modified the package according to #1086 and the issue was fixed. Thank you @EKT2000
