### ISSUE TITLE
Animation is not working on iOS after upgrade to the new architecture. RN 0.72.4

### ISSUE THREAD

**Issue by fmorau** [lottie-react-native/lottie-react-native#1092]
### Description

I made an upgrade from lottie-react-native v5 to v6 after upgrade to RN New Architecture.
Upgrade and run of application went well, but the Animation on iOS Stopped working, it does not shown at all

### Steps to Reproduce

1. Create empty react-native project
2. Add lottie-react-native package and add LottieView with this [JSON](https://github.com/sharekey/lottie-animation-issue-72/blob/master/assets/logo.json)

**Expected behavior:** Animation working well on both iOS and Android
**Actual behavior:** iOS does not play the animation, does not even show anything - just white square

### Minimal reproduction

1. Use repo created for this issue: https://github.com/sharekey/lottie-animation-issue-72
2. Install packages and run both iOS and Android

**Expected behavior:** Animation working well on both iOS and Android
**Actual behavior:** iOS does not play the animation, does not even show anything - just white square

<img width="250" alt="Screenshot 2023-08-16 at 13 00 58" src="https://github.com/lottie-react-native/lottie-react-native/assets/25362437/3776c98f-39ac-4ba9-8d49-699efae8d54d">

https://github.com/lottie-react-native/lottie-react-native/assets/25362437/a06bb426-ae67-41e8-a54e-365d63268e18

### React Native Environment

  Node: 18.17.0
  Yarn: 1.22.19
  CocoaPods: 1.12.1
  iOS SDK: - iOS 16.4
  Android Studio: 2022.3 AI-223.8836.35.2231.10406996
  Xcode: 14.3.1/14E300c
  Java: 12.0.2
  Ruby : 2.7.5
  react: 18.2.0
  react-native:0.72.3
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: true
  newArchEnabled: true

### Lottie Version

Version: 6.1.2

**Comment by matinzd** [comment]
Have you taken a look at changelog?

https://github.com/lottie-react-native/lottie-react-native/blob/master/CHANGELOG.md

**Comment by matinzd** [comment]
New architecture is still experimental and I won't recommend using it. Most libraries are still broken on new arch.
Please turn off the new architecture and let me know if it is still not working.

**Comment by fmorau** [comment]
> New architecture is still experimental and I won't recommend using it. Most libraries are still broken on new arch.
> Please turn off the new architecture and let me know if it is still not working.

So, for apps which migrated to new architecture you propose to use other solution than `lottie-react-native`?

**Comment by matinzd** [comment]
Have you tried using `.lottie` file?

**Comment by fmorau** [comment]
> Have you tried using `.lottie` file?

Oh, this JSON is ~5 years old, I'm not sure what can I do with it :)
Should I try to convert it somehow to another type of source? i.e. `.lottie` file?

**Comment by matinzd** [comment]
You can use this link to convert from JSON to dotLottie:

https://lottiefiles.com/tools/lottie-to-dotlottie

**Comment by matinzd** [comment]
Follow instructions here for setting up dotLottie:

https://github.com/lottie-react-native/lottie-react-native/blob/master/docs/api.md#if-you-want-to-use-lottie-files

**Comment by fmorau** [comment]
@matinzd will let you know, when try it out 👍

**Comment by oluwajuwon** [comment]
@fmorau were you able to figure this out?

**Comment by TheRogue76** [comment]
For any of the interested parties and as a matter of transparency to the community, we have traced this down to a problem with the `frame` of the native Lottie animation view sometimes being incorrectly set to zero on iOS the FIRST time it mounts on the new Arch (Gets fixed if you switch between some stuff), we just haven't figured out what has changed in the behavior of the rendering layer of RN to cause this, and what can be done to mitigate it.

We don't want to write logic that can hack around this issue, as it will cause other problems down the line, so it will take some time for us to figure it out.

Please be patient with us while we go through this, this is still very much uncharted territory in many ways

**Comment by heath-clink** [comment]
I found a workaround that's working for my app (and also the repro app), and that is to force a re-render of the LottieView after it mounts.

```js
const [src, setSrc] = React.useState();    
React.useEffect(() => {
   setSrc(require('./assets/logo.json'));
}, []);

return (
...
  <LottieView source={src} .../>
...
```

**Comment by matinzd** [comment]
Yes! That's a workaround for that issue but we haven't really found the reason why it's not running on the first render with a json file.

**Comment by nhaduongc** [comment]
on iOS , the frame of LottieView is not set, so it default zero. 
try to set style={{width: 100, height: 100}} . It work for me

**Comment by dwieners** [comment]
I found another workaround. This forces the animation to start.

```tsx
  const reference = useRef<LottieView>(null);

    useLayoutEffect(() => {
        (async () => {
            await wait(333);
            reference.current?.play();
        })();
    }, []);
    
    return <LottieView ref={reference} source={...} ... />


```

**Comment by iita71737** [comment]
Same as me.

I use react-native 0.72.4 ,  and  "lottie-react-native": "6.3.1",

also got failed in animation .json

a blank space in View :(

**Comment by imransilvake** [comment]
same issue lottie is not working on latest version on RN

**Comment by imransilvake** [comment]
Found the solution:
for some reason, Lottie requires a height

"react-native": "0.72.5",
"lottie-react-native": "^6.3.1",

```
const lottieDots = require('../../../../../../assets/lottie/dots.json');
<Lottie source={lottieDots} style={{ width: 40, height: 43, marginLeft: 12 }} autoPlay loop />
```

**Comment by matinzd** [comment]
Please read breaking changes in v6. 
Requiring width and height is not related to this topic.

**Comment by iita71737** [comment]
> Please read breaking changes in v6.
> Requiring width and height is not related to this topic.

Thank you!
I Got it and worked it in V6 with RN0.72.4

**Comment by saurabhkanswal** [comment]
@iita71737  could you please tell us, how you get it resolved. we are also facing the issue, with dot lottie in ios.

**Comment by iita71737** [comment]
> @iita71737 could you please tell us, how you get it resolved. we are also facing the issue, with dot lottie in ios. Also we are not in new architecture.

```js
"lottie-react-native": "6.2.0",
"react-native": "0.72.4",
...
```

```jsx
import LOTTIES from './lottieFiles/lotties'
...
const { width, height } = Dimensions.get('window')
...

 <FlatList
            data={LOTTIES ? LOTTIES : []}
            keyExtractor={item => item.id}
            renderItem={({ item, index }) => {
              return (
                <View
                  style={{
                    // borderWidth: 1,
                    height: 350,
                    width: width,
                  }}>
                  <LottieView
                    style={{
                      height: 350,
                      width: width,
                    }}
                    source={item.file}
                  ></LottieView>
                  {/* <LottieView source={item.file} autoPlay loop /> */}
                </View>
              )
            }}
          />
```

Following r my lotties file 

```js
const LOTTIES = [
  {
    id: 1,
    name: 'animation1',
    file: require('./116410-hello.json'),
  },
  {
    id: 2,
    name: 'animation2',
    file: require('./133076-welcome.json'),
  },
  {
    id: 3,
    name: 'animation3',
    file: require('./142434-moody-giraffe.json'),
  },
]

export default LOTTIES

`

**Comment by saurabhkanswal** [comment]
@iita71737 
json format lottie is working fine for us, we are only facing issue with dotLottie.
Although thanks for, sharing code.

**Comment by JocheAttah** [comment]
Adding style properties of width and height  solved the issue

**Comment by abbasmoosavi** [comment]
> You can use this link to convert it from JSON to dotLottie:
> 
> https://lottiefiles.com/tools/lottie-to-dotlottie

Wonderful Matin

**Comment by 0xSaurabh** [comment]
@saurabhkanswal did you figure out the issue? I seem to be facing the same issue.

**Comment by TheRogue76** [comment]
@0xSaurabh What version of Lottie are you using? We added a fix for 6.5.0

**Comment by 0xSaurabh** [comment]
Hey @TheRogue76 , we're currently on version `6.5.1`, and the issue is specific to dotLottie files, which are not working in iOS release. Another thing to note is that dotLottie files are working if used from a remote url.

We're not using the new architecture, and have just upgraded to `0.72.6`

**Comment by TheRogue76** [comment]
> Hey @TheRogue76 , we're currently on version `6.5.1`, and the issue is specific to dotLottie files, which are not working in iOS release. Another thing to note is that dotLottie files are working if used from a remote url.
> 
> We're not using the new architecture, and have just upgraded to `0.72.6`

Please open a new Issue with a small reproducible if possible and I can take a stab at it and see what is wrong. I would also love to know if you are using Expo or not and how that setup is currently working (Please put them in the new issue though so we can keep track, not here)
