### ISSUE TITLE
Color filters not working on iOS for some animations on v6

### ISSUE THREAD

**Issue by thevoiceless** [lottie-react-native/lottie-react-native#1093]
### Description

Some animations are not obeying color filters in v6.1.2 on iOS. Many animations still work as expected.
The problematic animation works as expected on Android.
Tested on:
* iPhone SE + iOS 14.8.1
* iPhone X + iOS 16.1.1
* Pixel 4a + Android 13

### Steps to Reproduce

1. Use [Lottie_Navigation_Messages_Fix03.json.zip](https://github.com/lottie-react-native/lottie-react-native/files/12362170/Lottie_Navigation_Messages_Fix03.json.zip); note that the animation is red in the json
2.
```ts
const animation = require('path/to/Lottie_Navigation_Messages_Fix03.json') as AnimationObject
const colorFilters = animation.layers.map((layer) => {
    return {
      keypath: layer.nm,
      color: '#ffffff',
    };
  })
```
3.
```ts
<LottieView
  source={animation}
  colorFilters={colorFilters}
/>
```

**Expected behavior:**

https://github.com/lottie-react-native/lottie-react-native/assets/1574103/dd59cf62-5f4f-4f1c-bfbe-695ef71eb06f

**Actual behavior:** 

https://github.com/lottie-react-native/lottie-react-native/assets/1574103/64ac6652-780e-4c9c-93ed-82cc0278d475

### Minimal reproduction

See above

### React Native Environment

* RN 0.72.3
* No Expo

### Lottie Version

Version: 6.1.2

### Workaround

I found an [old discussion](https://github.com/lottie-react-native/lottie-react-native/issues/671) about color filters, and the workaround appears to mitigate the issue

```ts
const white = [1, 1, 1]

animation.layers?.forEach((layer, layerIndex) => {
  layer.shapes?.forEach((shape, shapeIndex) => {
    shape.it?.forEach((it, itIndex) => {
      if (it.c?.k != null) {
        animation.layers[layerIndex].shapes[shapeIndex].it[itIndex].c.k = white
      }
    })
  })
})

animation.assets?.forEach((asset, assetIndex) => {
  asset.layers?.forEach((layer, layerIndex) => {
    layer.shapes?.forEach((shape, shapeIndex) => {
      shape.it?.forEach((it, itIndex) => {
        if (it.c?.k != null) {
          animation.assets[assetIndex].layers[layerIndex].shapes[shapeIndex].it[itIndex].c.k = white
        }
      })
    })
  })
})
```

**Comment by matinzd** [comment]
Hey!

Can you send me the result of your mapping? The object that is being passed to color filters.

**Comment by thevoiceless** [comment]
@matinzd `JSON.stringify(colorFilters)` comes out to
```
[{"keypath":"IconAnimation_Messages_APPROVED (Justin Revision)","color":"#ffffff"}]
```

**Comment by thevoiceless** [comment]
Good news: It looks like the color filters work correctly when NOT using flipped vectors.

Working version of the animation:
[Lottie_Navigation_Messages_LottieFix02_v4.json.zip](https://github.com/lottie-react-native/lottie-react-native/files/12442943/Lottie_Navigation_Messages_LottieFix02_v4.json.zip)

**Comment by matinzd** [comment]
Ok! Great. Thanks for updating us :) 
Closing it as completed.

**Comment by thevoiceless** [comment]
Just to be clear, I do believe there's a bug here; AFAIK there's no documentation indicating that flipped vectors are unsupported
