### ISSUE TITLE
Android build failing for 6.0.0 and 6.0.2

### ISSUE THREAD

**Issue by jakecurreri** [lottie-react-native/lottie-react-native#1094]
### Description

I've recently installed Lottie into my React Native (0.72.4). Build and animations on iOS function without fault. However, Android refuses to compile. I have cleaned the build folder multiple times. At first, I installed the latest stable release `6.0.2`. Then, I downgraded to `6.0.0` to see if the issue was resolved.

```
Execution failed for task ':tasks'.
> Could not create task ':lottie-react-native:compileDebugAndroidTestKotlin'.
   > Cannot use @TaskAction annotation on method AbstractKotlinCompile.execute() because interface org.gradle.api.tasks.incremental.IncrementalTaskInputs is not a valid parameter to an action method.
```

I've matched Kotlin versions in my `build.gradle` with the version explicitiy stated in 6.0.0: `kotlinVersion = "1.7.10"`. When that did not work, I tried manually linking the project via the [AirBnB Lottie for React Native instructions](http://airbnb.io/lottie/#/react-native). That also did not work.

### React Native Environment

Bare `RN 0.72.4`

### Lottie Version

Version: 6.0.2 (and 6.0.0)

**Comment by jakecurreri** [comment]
Quickly resolved through the self-remedy of describing one's problem.

I was on the right track with `kotlinVersion` research. However, I missed updating my dependencies in `build.gradle` as well.

```
ext {
       ...
        kotlinVersion = "1.7.10"
    }
```

```
dependencies {
        classpath("com.android.tools.build:gradle")
        ...
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.7.10"
    }
```

Hope this helps others with a similar issue.

**Comment by jakecurreri** [comment]
Quickly resolved through the self-remedy of describing one's problem.

I was on the right track with `kotlinVersion` research. However, I missed updating my dependencies in `build.gradle` as well.

```
ext {
       ...
        kotlinVersion = "1.7.10"
    }
```

```
dependencies {
        classpath("com.android.tools.build:gradle")
        ...
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.7.10"
    }
```

Hope this helps others with a similar issue.

**Comment by martinezguillaume** [comment]
You can use
```
classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion"
```
to be sure to be in the correct version 👍

I had the same issue, thanks !
