### ISSUE TITLE
Add web support

### ISSUE THREAD

**Issue by muneebahmedayub** [lottie-react-native/lottie-react-native#1099]
As expo is making web simpler than ever, it would be great to see libraries like `react-native-lottie` to also support web.

**Comment by ram-prasad23** [comment]
Is it working on expo react-native android. It works if i use a version 5.1.4. Now i am using 6.2.0 the animations are not populated.

**Comment by itsyoboieltr** [comment]
I was about to make an issue for the same thing! I believe it would be very important to align this library to the cross-platform goal of React Native, and enable the usage of this library in Expo and web.

The current workaround I am using for my application:

```jsx

const Lottie =
  Platform.OS === 'web'
    ? require('react-lottie-player/dist/LottiePlayerLight')
    : require('lottie-react-native');

 {Platform.OS !== 'web' ? (
  <Lottie
    autoPlay
    loop
    speed={1.5}
    resizeMode={'cover'}
    source={require('../assets/animations/menu.json')}
    style={{ position: 'absolute', width: 500, alignSelf: 'center' }}
  />
) : (
  <Lottie
    play
    loop
    speed={1.5}
    animationData={require('../assets/animations/menu.json')}
    style={{ position: 'absolute', width: 500, alignSelf: 'center' }}
  />
)}
```

This works, but it would be nice to just have a single library that works everywhere :D

**Comment by muneebahmedayub** [comment]
> Is it working on expo react-native android. It works if i use a version 5.1.4. Now i am using 6.2.0 the animations are not populated.

always install packages in expo using `npx expo install <package-name>` and expo recommends using version 5.1.6 so it's better to use 5.1.6
But i tried using 6.2.0 and it works on android, can you give a minimal reproducible so we can have a look what is wrong?

**Comment by muneebahmedayub** [comment]
> I was about to make an issue for the same thing! I believe it would be very important to align this library to the cross-platform goal of React Native, and enable the usage of this library in Expo and web.
> 
> The current workaround I am using for my application:
> 
> ```js
> const Lottie =
>   Platform.OS === 'web'
>     ? require('react-lottie-player/dist/LottiePlayerLight')
>     : require('lottie-react-native');
> 
>  {Platform.OS !== 'web' ? (
>   <Lottie
>     autoPlay
>     loop
>     speed={1.5}
>     resizeMode={'cover'}
>     source={require('../assets/animations/menu.json')}
>     style={{ position: 'absolute', width: 500, alignSelf: 'center' }}
>   />
> ) : (
>   <Lottie
>     play
>     loop
>     speed={1.5}
>     animationData={require('../assets/animations/menu.json')}
>     style={{ position: 'absolute', width: 500, alignSelf: 'center' }}
>   />
> )}
> ```
> 
> This works, but it would be nice to just have a single library that works everywhere :D

yes its a great workaround, i was also planning to use `lottie-react` but as you said it would be good to have a web support in this library as well

**Comment by muneebahmedayub** [comment]
@matinzd hi, we can implement react-lottie at the back for web. I want to work on this, can you assign this to me?
