### ISSUE TITLE
SVG to Lottie converted file does not work on iOS

### ISSUE THREAD

**Issue by Pro-Workouts** [lottie-react-native/lottie-react-native#1103]
### Description
Hi, I tried to convert my SVG to Lottie and used the preset animation(preset-9). This works well on Android, but does not work on iOS. It just displays the static SVG as an image

[Description of the bug]
Not animating the preset-9 on iOS

### Steps to Reproduce

1. Create a new RN app
2. Download the file from 'https://drive.google.com/uc?export=view&id=1nTrUCE7HIiYHv-nwi9sXAQ42U77rfFLB'
3. Paste the `animation.json` file into the assets folder

**Expected behavior:** [What you expected to happen]
Preset-9 Animation to work on iOS as well

**Actual behavior:** [What actually happened]
Displays a static image

### Minimal reproduction
```
import React, {FC, memo} from 'react';
import { StyleSheet, ScrollView} from 'react-native';
import LottieView from 'lottie-react-native';
import animation from './animation.json';

type TProps = {};

const App: FC<TProps> = () => {
  return (
    <ScrollView contentContainerStyle={styles.container} style={{flex: 1}}>
          <LottieView
            source={animation}
            autoPlay
            loop
            style={{height: 250, width: '100%'}}
          />
        );
    </ScrollView>
  );
};

const styles = StyleSheet.create({
  container: {
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  }
});

export default memo(App);
```

https://drive.google.com/uc?export=view&id=1nTrUCE7HIiYHv-nwi9sXAQ42U77rfFLB

### React Native Environment
    "react": "18.2.0",
    "react-native": "0.72.4"

Bare

### Lottie Version

Version: 6.2.0

**Comment by s10mcow** [comment]
I see the same issue on mine using your example file

**Comment by Pro-Workouts** [comment]
> I see the same issue on mine using your example file...
> 
> renderMode="SOFTWARE"
> 
> however seems to make it work!

Thanks a lot, yes this works `renderMode="SOFTWARE"`
