### ISSUE TITLE
passing a ref in LottieView throwing a error 

### ISSUE THREAD

**Issue by ishpaul777** [lottie-react-native/lottie-react-native#1109]
### Description

[Description of the bug]

### Steps to Reproduce

Pass a ref to LottieVew
```jsx
    <LottieView
        ref={animationRef}
        source={illustration}
        // rest of props
     />
```

**Expected behavior:** [What you expected to happen]
no errors in console and ref working as expected

**Actual behavior:** [What actually happened]
error in console and not able to use methds like `play()`, `reset()`

<img width="665" alt="Screenshot 2023-09-26 at 1 05 27 AM" src="https://github.com/lottie-react-native/lottie-react-native/assets/104348397/34e7d4f2-5705-4e90-abb7-d9ac41371fa6">

### Lottie Version

Version: latest

**Comment by matinzd** [comment]
We are providing a class component in the library so that you can use a ref directly on the component. It appears that you are wrapping Lottie in your own instance as a function component, which is causing this issue.

**Comment by ishpaul777** [comment]
Hii @matinzd. thanks for your response. I am using LottieView like below am i doing something wrong, can you please guide me.

``
function IllustratedHeaderPageLayout({backgroundColor, children, illustration, footer, overlayContent, ...propsToPassToHeader}) {
    const animationRef = React.useRef(null);
    
    return (
        <HeaderPageLayout
            backgroundColor={backgroundColor}
            title={propsToPassToHeader.title}
            headerContent={
                <>
                    <LottieView
                        ref={animationRef}
                        source={illustration}
                        style={styles.w100}
                        autoPlay
                        loop
                    />
                    {overlayContent && overlayContent()}
                </>
            }
            headerContainerStyles={[styles.justifyContentCenter, styles.w100]}
            footer={footer}
            // eslint-disable-next-line react/jsx-props-no-spreading
            {...propsToPassToHeader}
        >
            {children}
        </HeaderPageLayout>
    );
}
```

**Comment by ishpaul777** [comment]
Not sure what changed but everyting is working now
