### ISSUE TITLE
Lottie Animations not playing on iOS 17

### ISSUE THREAD

**Issue by jeffersontpadua** [lottie-react-native/lottie-react-native#1111]
On some iOS devices running iOS 17 the lottie animations are not playing and therefore the onAnimationFinish callback is not being called. This issue started manifesting itself quite randomly on devices running iOS 17, and frankly I haven't had a chance to reproduce it yet, but was able to verify that this was the issue after a user reached out to us with a video where the lottie animation was frozen, and this users device it would always happen.

After performing a reset of settings on the device (Settings -> General -> Transfer or Reset iPhone -> Reset -> Reset All Settings) the animations start running normally again, but obviously this is not the ideal scenario.

Starting this as a discussion and a possible bug report in case anyone is facing the same problem.

As a work around, what we've done on our side is to set a timeout on the screens that depend on animation completion to trigger something else

**Comment by wen-kai** [comment]
we are facing the same exact issue. we use a lottie animation for our splash screen and trigger it to hide on the onAnimationFinished event. unfortunately the animation never plays so the splash screen is stuck for those ios17 users affected by the issue. we implemented an alternative animation using RN Animated as a workaround for now.

**Comment by bploetz** [comment]
Just ran into this as well. We ended up implementing a timeout like @jeffersontpadua did but it's a poor user experience obviously. :(

**Comment by kevin-kp** [comment]
Hi @jeffersontpadua 

We are facing the same issue. On what version did you notice this issue?
We are seeing this on 5.1.6; However, since 6.1.0, there is an onAnimationFailure. 
Are you using a version >= 6.1.0 and are you using the onAnimationFailure and still getting the mentioned issue?

**Comment by jeffersontpadua** [comment]
@kevin-kp we're also seeing this issue on 5.1.6. We tried updating to 6.x a few weeks ago but encountered some issues getting it to work on Android and iOS

**Comment by darrenfurr** [comment]
Ran into the same issue with `5.1.0` and our animated splash screen. We also removed the Lottie animations from our Home screen due to a memory leak in iOS 17. We are now actively looking to remove the Lottie dependency all together & use RN Animated.

**Comment by matinzd** [comment]
I will try to investigate this issue after I am back from vacation.

**Comment by jer-sen** [comment]
For me, some Lottie animations where not starting automatically with autoPlay enabled. I had to manually call play() in a setTimeout afters 0s in a useEffect.

**Comment by el-lsan** [comment]
I had the same issue.
Try using `"lottie-react-native": "6.2.0",`.
It worked for me.

**Comment by Aurintas** [comment]
if using react-native >= v0.71, it seems to be enough to enable "Increased Contrast" in `Settings -> Accessibility -> Display & Text Size` for animations to stop working. otherwise, any RN version < v0.71 breaks the animations in iOS 17.

**Comment by kevin-kp** [comment]
@Aurintas Indeed, with that scenario I'm able to reproduce the issue as well.
Just checked with 5.1.6, and I can reproduce the issue now
I do not seem to have the issue with 6.3.1

**Comment by matinzd** [comment]
Please open an issue regarding this on [@airbnb/lottie-ios](https://github.com/airbnb/lottie-ios). @Aurintas

**Comment by EvgenyRub** [comment]
Latest 6.3.1 works well, for me the animation start display after passing width and height to the style prop which was not mandatory in < 6.

**Comment by MarlonAEC** [comment]
> Latest 6.3.1 works well, for me the animation start display after passing width and height to the style prop which was not mandatory in < 6.

This worked for me as soon as I added width and height to the style the animation showed up

**Comment by 15bedirhan** [comment]
> Latest 6.3.1 works well, for me the animation start display after passing width and height to the style prop which was not mandatory in < 6.

For those who want to download the package where Lottie-ios is included by default and width and height style props are not required, try using the following version:

```bash
npm install lottie-react-native@5.1.6
```
