### ISSUE TITLE
resizeMode cover not working in IOS (Dot Lottie)

### ISSUE THREAD

**Issue by saurabhkanswal** [lottie-react-native/lottie-react-native#1114]
Hey,
i am using below version
"lottie-ios": "4.3.0",
"lottie-react-native": "6.3.0",

passing resizeMode "cover" is not working.
Also we have tried downgrading/upgrading both packages, but resizeMode cover is not working.

![File](https://github.com/lottie-react-native/lottie-react-native/assets/26677033/5ae469e0-8d42-4267-97ca-547cc40e60b1)

**Comment by saurabhkanswal** [comment]
Also its only happening for IOS. And working fine when we are using .json file.
But for .lottie its not working in ios.

**Comment by saurabhkanswal** [comment]
![Screenshot 2023-10-05 at 11 52 53 PM](https://github.com/lottie-react-native/lottie-react-native/assets/26677033/01e507ce-69be-45fb-84e7-e0686c982a64)

Although sometime its working as expected, when i save my file.

**Comment by HaidarZ** [comment]
Same issue here (only iOS), it works for the first time, then when getting back to the page it doesn't recognize the `resizeMode`.

**Comment by Bowlerr** [comment]
@EGurney I am getting this exact issue too.
I am using a `.json` though

**Comment by EGurney** [comment]
> @EGurney I am getting this exact issue too. I am using a `.json` though

Welp, that's terrifying! haha

**Comment by xeroxoid** [comment]
Same here, seems to work with `.json` but not with `.lottie`

**Comment by matinzd** [comment]
Is the new arch turned on?
