### ISSUE TITLE
LottieView not showing in a Expo Project

### ISSUE THREAD

**Issue by Droukar** [lottie-react-native/lottie-react-native#1116]
Hi !
I'm trying to use Lottie in my React Native project. But when i'm using <LottieView> it doesn't appear in the app.
Here's my code : 
```js
import LottieView from "lottie-react-native";

export function Lottie() {
    return (
<LottieView
      autoplay
      loop
      source={require("../lottie/loading.json")}
      style={{width: 150}}
    />
    );
}
```

I've tried to re-install all dependencies, it didn't change anything. I've tried to make another app to check if the problem was from the JSON file and the Lottie appear. So I think it's a conflict from one of my package but I can't figure what package. Did someone got the same issue with one of these package ?
```json

"dependencies": {
    "@react-navigation/bottom-tabs": "^6.5.9",
    "@react-navigation/native": "^6.1.8",
    "@react-navigation/native-stack": "^6.9.14",
    "axios": "^1.5.0",
    "expo": "^49.0.13",
    "expo-splash-screen": "~0.20.5",
    "expo-status-bar": "~1.6.0",
    "he": "^1.2.0",
    "html-react-parser": "^4.2.2",
    "lottie-react-native": "5.1.6",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.72.5",
    "react-native-reanimated": "~3.3.0",
    "react-native-safe-area-context": "4.6.3",
    "react-native-screens": "~3.22.0",
    "react-native-vector-icons": "^10.0.0",
    "react-native-web": "~0.19.6"
  },
```

### Lottie Version

Version: 5.1.6

Thanks !

**Comment by marcosrdz** [comment]
Same issue but with vanilla RN

**Comment by segun-flexible** [comment]
Am using Expo SDK 49

It always crash my android if I put big Lottie JSON, but it work if I put small Lottie file

It always work on iOS no matter the file, 

Please help us fix this issue

**Comment by MariuzM** [comment]
Same for me, shows in simulator but not device

**Comment by Sallbro** [comment]
animation is not animating why it so ?

**Comment by X-W-W** [comment]
Try to add style height.
`style={{
                    width: 50,
                    height: 50,
                    justifyContent: 'center',
                    alignItems: 'center',
                }}`

**Comment by GSTJ** [comment]
Adding width/height did solve it for me on Android. Thanks. Not an issue at all on IOS.

**Comment by matinzd** [comment]
Please read breaking changes in v6. You need to specify width and height.
