### ISSUE TITLE
While building the app Xcode 15 an error "ios/LottieReactNative/ContainerView.swift Could not build Objective-C module 'lottie_react_native'"

### ISSUE THREAD

**Issue by KaterinaUK** [lottie-react-native/lottie-react-native#1117]
Hi everyone, I am experiencing an issue after upgrade to XCode 15, I have an error saying "LottieReactNative/ContainerView.swift Could not build Objective-C module 'lottie_react_native'"
I found a few issues but the solution provided did not work:
https://github.com/lottie-react-native/lottie-react-native/issues/734
https://github.com/lottie-react-native/lottie-react-native/issues/906

I tried:
1.  `pod deintegrate && rm -rf podfile.lock && pod update`
2. Quit Xcode.
Delete project's temp files located at ~/Library/Developer/Xcode/DerivedData
Delete ProjectName.xcworkspace
Delete Podfile.lock file and Pods folder
Run pod install.
Open the newly created ProjectName.xcworkspace file and build.

None of these were working for me.
--
<img width="479" alt="Screenshot 2023-10-12 at 11 15 29" src="https://github.com/airbnb/lottie-ios/assets/68429856/7cb0956a-e4d7-4a68-a809-0d18b23920bc">
>

## Which Version of Lottie are you using?

"lottie-ios": "^3.4.0",
"lottie-react-native": "^5.1.4"

## Expected Behavior 
The build should succeed.

## Actual Behavior

<img width="458" alt="Screenshot 2023-10-12 at 11 19 44" src="https://github.com/airbnb/lottie-ios/assets/68429856/bed74e41-136d-4018-bd59-75a6ce1c86af">

## Animation JSON
NA

**Comment by matinzd** [comment]
Can you try v6?

**Comment by matinzd** [comment]
Try updating your project template especially ios folder to the latest changes. Closing this for now as it's not reproducable.

**Comment by BogdanRad** [comment]
Hello, I have same error.. with latest lottie version..

<img width="234" alt="image" src="https://github.com/lottie-react-native/lottie-react-native/assets/40359109/c00df4b3-079b-40d8-a13b-a558f3e1dfe7">

**Comment by neeteshraj** [comment]
i am having same error.

**Comment by JessePinkman-JP** [comment]
@BogdanRad @neeteshraj Have you solved it? I also have this problem.

**Comment by neeteshraj** [comment]
> @BogdanRad @neeteshraj Have you solved it? I also have this problem.

Yes i updated the lottie-react-native and react-native to latest version and it was fixed

**Comment by JessePinkman-JP** [comment]
> > @BogdanRad @neeteshraj Have you solved it? I also have this problem.
> 
> Yes i updated the lottie-react-native and react-native to latest version and it was fixed

Could you please tell me about your lottie-react-native and react-native versions? Thank you very much. ♪(･ω･)ﾉ

**Comment by NandhakumarRock** [comment]
i am having same error.
"Could not build Objective-C module 'lottie_react_native'"

I'm using
    "lottie-ios": "^4.4.1",
    "lottie-react-native": "^6.7.2",
    "react-native": "0.69.1",

**Comment by rhhill1401** [comment]
i am having same error.
"Could not build Objective-C module 'lottie_react_native'"

I'm using
"lottie-ios": "^4.4.1",
"lottie-react-native": "^6.7.2",
"react-native": "073.6",

**Comment by dzengi-com** [comment]
The only temporary solution at the moment is to first remove the package and then install it again. But I would like a real solution to this problem

```
yarn remove lottie-react-native
pod install

yarn add lottie-react-native
pod install
```

**Comment by csori99** [comment]
> The only temporary solution at the moment is to first remove the package and then install it again. But I would like a real solution to this problem
> 
> ```
> yarn remove lottie-react-native
> pod install
> 
> yarn add lottie-react-native
> pod install
> ```

What kind of solution is that bro

**Comment by vishal-affinsys** [comment]
Any update on this?
