### ISSUE TITLE
ViewPropTypes issue fix

### ISSUE THREAD

**Issue by vivekcubet** [lottie-react-native/lottie-react-native#1123]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `lottie-react-native@3.5.0` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/lottie-react-native/src/js/LottieView.js b/node_modules/lottie-react-native/src/js/LottieView.js
index 31800a3..4082656 100644
--- a/node_modules/lottie-react-native/src/js/LottieView.js
+++ b/node_modules/lottie-react-native/src/js/LottieView.js
@@ -6,8 +6,8 @@ import {
   View,
   Platform,
   StyleSheet,
-  ViewPropTypes,
 } from 'react-native';
+import {ViewPropTypes} from 'deprecated-react-native-prop-types';
 import SafeModule from 'react-native-safe-modules';
 import PropTypes from 'prop-types';
 
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by matinzd** [comment]
Please upgrade to the latest version of the library.
