### ISSUE TITLE
Not animated on Expo 49.0.0 Android

### ISSUE THREAD

**Issue by X-W-W** [lottie-react-native/lottie-react-native#1124]
### Description

I use Expo to show my components.
When i tested on android, animation stuck there for no error.
Working properly on Expo IOS and local android project.

### Steps to Reproduce

Use expo's quick start to reproduce:
1.npx create-expo-app my-app
2.yarn/pnpm install lottie-react-native
3.edit app.js
`
import { StatusBar } from 'expo-status-bar';
import { StyleSheet, Text, View } from 'react-native';
import LottieView from 'lottie-react-native';

export default function App() {
  return (
    <View style={styles.container}>
      <Text>Open up App.js to start working on your app!</Text>
      <StatusBar style="auto" />
      <LottieView
        autoPlay={true}
        loop
        style={{
          width: 200,
          height: 200,
          backgroundColor: '#eee',
        }}
        source={require('./assets/test1.json')}
        onAnimationFailure={() => { console.log('failure'); }}
        onAnimationFinish={() => { console.log('finish'); }}
        onAnimationLoop={() => { console.log('loop'); }}
      />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
`
test1.json:https://assets4.lottiefiles.com/packages/lf20_Dz3Jb8.json

**Expected behavior:** animate properly

**Actual behavior:** android stuck there

**Comment by matinzd** [comment]
Have you tried checking it on bare react native project? I am not sure if I got your problem.

**Comment by X-W-W** [comment]
> Have you tried checking it on bare react native project? I am not sure if I got your problem.

Yeah, I tried it on own project directly running in android, it works great.
react-native version is 0.72.5 and expo installed by play store

**Comment by touchesoftware** [comment]
Please reinstall package using "npx expo install lottie-react-native" It will solve this issue after install SDK v49.

**Comment by X-W-W** [comment]
> Please reinstall package using "npx expo install lottie-react-native" It will solve this issue after install SDK v49.

Thanks. It worked after I install "lottie-react-native": "5.1.6". 
I decide to ignore this problem and use 6.4.0 still. lol
