### ISSUE TITLE
Here is the reason why lottie is crashing on Expo android

### ISSUE THREAD

**Issue by segun-flexible** [lottie-react-native/lottie-react-native#1126]
I notice when i make a changes to a lottie in the website, maybe i change the color of the lottie, if i download it and use the JSON in my expo, it will crash on android, but work on ios

Please fix that

**Comment by Srinayan** [comment]
I am facing the same issue with Lottie JSON version 5.7.0 and Lottie React Native version 5.1.6. It works well on iOS, but not on Android. Following is the console error that appears when using android.

`Warning: Cannot update a component (`ForwardRef(BaseNavigationContainer)`) while rendering a different component (`index`). To locate the bad setState() call inside `index`, follow the stack trace as described in https://reactjs.org/link/setstate-in-render`

**Comment by matinzd** [comment]
Please try installing the latest version. Closing this for now! 

> I am facing the same issue with Lottie JSON version 5.7.0 and Lottie React Native version 5.1.6. It works well on iOS, but not on Android. Following is the console error that appears when using android.
> 
> `Warning: Cannot update a component (`ForwardRef(BaseNavigationContainer)`) while rendering a different component (`index`). To locate the bad setState() call inside `index`, follow the stack trace as described in https://reactjs.org/link/setstate-in-render`

There is something wrong in your codebase. Nothing related to lottie.
