### ISSUE TITLE
Not working with Lottie animations that use expressions

### ISSUE THREAD

**Issue by speedpoint0** [lottie-react-native/lottie-react-native#1130]
Hi! I'm using a Lottie animation that uses expressions but it doesn't seem to work with react native. I've tried previewing the Lottie animation on other sites and with vuejs and it works fine.

With react native, i get the following:

<img width="476" alt="Screenshot 2023-11-02 at 11 19 07" src="https://github.com/lottie-react-native/lottie-react-native/assets/11648401/d5471bed-594f-495c-9533-6f38a0f7221c">

Is there anyway around this?

**Comment by matinzd** [comment]
Please refer to [this](https://lottiefiles.com/supported-features) documentation.

<img width="807" alt="Screenshot 2023-11-16 at 21 22 34" src="https://github.com/lottie-react-native/lottie-react-native/assets/24797481/a845a52c-6c65-4b6a-af28-120bfc0bae6b">
