### ISSUE TITLE
Android Error

### ISSUE THREAD

**Issue by Brunowilliang** [lottie-react-native/lottie-react-native#1136]
Hi guys, I'm putting a lottie animation on a screen and on iOS it works fine, but on Android it doesn't work, it just exits the app.

https://github.com/lottie-react-native/lottie-react-native/assets/41432581/bdfd7deb-90fe-4374-abdf-8d4b981b27a9

### Minimal reproduction

```tsx
import React, { useEffect, useRef } from 'react'
import { AnimatedStack } from './ui/Stacks'
import { FadeOut } from 'react-native-reanimated'
import LottieView from 'lottie-react-native'

type Props = {
  setSplashReady: (ready: boolean) => void
}

export default function Splash({ setSplashReady }: Props) {
  const animationRef = useRef<LottieView>(null)

  useEffect(() => {
    const timer = setTimeout(() => {
      setSplashReady(true)
    }, 1000)

    return () => clearTimeout(timer)
  }, [])

  return (
    <AnimatedStack f={1} centered bg={'$primary'} exiting={FadeOut}>
      <LottieView
        ref={animationRef}
        autoPlay
        loop={false}
        style={{ width: '100%' }}
        source={require('../assets/animations/splash.json')}
      />
    </AnimatedStack>
  )
}
```

### React Native Environment
expo and expo go

Version: x.x.x
"lottie-react-native": "5.1.6",
"expo": "~49.0.20",
"react-native": "0.72.6",

**Comment by matinzd** [comment]
Updated version of lottie for Expo Go will be available in SDK 50.
Since then, there is no way for Expo Go users to prevent this crash. Try downgrading to v5 or use Expo custom dev client or bare RN.
