### ISSUE TITLE
Build issue in react-native v0.73 new architecture.

### ISSUE THREAD

**Issue by neeteshraj** [lottie-react-native/lottie-react-native#1138]
### Description
The following build commands failed:
	CompileC /Users/niteshrajkhanal/Library/Developer/Xcode/DerivedData/singlecustomerapp-ggsyyaqexacwdkfzzmjannnihwfm/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/lottie-react-native.build/Objects-normal/arm64/LottieAnimationViewComponentView.o /Users/niteshrajkhanal/Desktop/development/sca-mobile-app/node_modules/lottie-react-native/ios/Fabric/LottieAnimationViewComponentView.mm normal arm64 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'lottie-react-native' from project 'Pods')
(1 failure)

### Steps to Reproduce

1. Create a new react native application.
2. Package.json 
{
  "name": "singlecustomerapp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "ios-15": "npx react-native run-ios --simulator='iPhone 15 Pro'",
    "lint": "eslint .",
    "start": "react-native start",
    "test": "jest",
    "type-check": "tsc",
    "test:report": "jest --collectCoverage --coverageDirectory=\"./coverage\" --ci --reporters=default --reporters=jest-junit --coverage",
    "pod-install": "cd ios && RCT_NEW_ARCH_ENABLED=1 bundle exec pod install && cd ..",
    "gen-release-apk": "cd android && ./gradlew assembleRelease && cd ..",
    "gen-release-bundle": "cd android && ./gradlew bundleRelease && cd ..",
    "bundle-android": "react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle",
    "release-android": "cd android && ./gradlew clean && cd .. && react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle && cd android && ./gradlew assembleRelease && cd ..",
    "adb-log": "adb logcat *:E",
    "prepare": "husky install"
  },
  "dependencies": {
    "@react-native-masked-view/masked-view": "^0.3.0",
    "@react-navigation/bottom-tabs": "^6.5.11",
    "@react-navigation/native": "^6.1.9",
    "@react-navigation/stack": "^6.3.20",
    "@reduxjs/toolkit": "^2.0.1",
    "add": "^2.0.6",
    "axios": "^1.6.2",
    "i18next": "^23.7.8",
    "lottie-ios": "^4.3.4",
    "lottie-react-native": "^6.4.1",
    "react": "^18.2.0",
    "react-i18next": "^13.5.0",
    "react-native": "^0.73.0",
    "react-native-gesture-handler": "^2.14.0",
    "react-native-keychain": "^8.1.2",
    "react-native-linear-gradient": "3.0.0-alpha.0",
    "react-native-mmkv": "^2.11.0",
    "react-native-paper": "^5.11.3",
    "react-native-reanimated": "^3.6.1",
    "react-native-safe-area-context": "4.8.0-rc.0",
    "react-native-screens": "^3.29.0",
    "react-native-svg": "^14.1.0",
    "react-native-svg-transformer": "^1.1.0",
    "react-native-vector-icons": "^10.0.2",
    "react-redux": "^9.0.2",
    "redux-persist": "^6.0.0",
    "yarn": "^1.22.21"
  },
  "devDependencies": {
    "@babel/core": "^7.23.5",
    "@babel/preset-env": "^7.23.5",
    "@babel/runtime": "^7.23.5",
    "@react-native/babel-preset": "^0.74.0",
    "@react-native/eslint-config": "^0.74.0",
    "@react-native/metro-config": "^0.73.2",
    "@react-native/typescript-config": "^0.74.0",
    "@react-navigation/devtools": "^6.0.20",
    "@testing-library/jest-native": "^5.4.3",
    "@testing-library/react-native": "^12.4.1",
    "@types/add": "^2",
    "@types/jest": "^29.5.11",
    "@types/metro-config": "^0.76.3",
    "@types/node": "^20.10.4",
    "@types/react": "^18.2.42",
    "@types/react-test-renderer": "^18.0.7",
    "babel-jest": "^29.7.0",
    "babel-plugin-inline-dotenv": "^1.7.0",
    "babel-plugin-module-resolver": "^5.0.0",
    "babel-plugin-root-import": "^6.6.0",
    "dotenv": "^16.3.1",
    "eslint": "^8.55.0",
    "jest": "^29.7.0",
    "prettier": "^3.1.0",
    "react-native-logs": "^5.0.1",
    "react-test-renderer": "^18.2.0",
    "typescript": "^5.3.3"
  },
  "engines": {
    "node": ">=18"
  },
  "packageManager": "yarn@4.0.2"
}

**Expected behavior:** Project is expected to compile
**Actual behavior:** The following build commands failed:
	CompileC /Users/niteshrajkhanal/Library/Developer/Xcode/DerivedData/singlecustomerapp-ggsyyaqexacwdkfzzmjannnihwfm/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/lottie-react-native.build/Objects-normal/arm64/LottieAnimationViewComponentView.o /Users/niteshrajkhanal/Desktop/development/sca-mobile-app/node_modules/lottie-react-native/ios/Fabric/LottieAnimationViewComponentView.mm normal arm64 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'lottie-react-native' from project 'Pods')
(1 failure)

### React Native Environment
─ npx react-native info                                                     ─╯
info Fetching system and libraries information...
(node:29702) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
System:
  OS: macOS 14.1.1
  CPU: (8) arm64 Apple M1
  Memory: 50.58 MB / 8.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 21.1.0
    path: ~/.nvm/versions/node/v21.1.0/bin/node
  Yarn:
    version: 4.0.2
    path: ~/Desktop/development/sca-mobile-app/node_modules/.bin/yarn
  npm:
    version: 10.2.0
    path: ~/.nvm/versions/node/v21.1.0/bin/npm
  Watchman:
    version: 2023.10.30.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.14.3
    path: /usr/local/opt/ruby-2.7.4/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.0
      - iOS 17.0
      - macOS 14.0
      - tvOS 17.0
      - watchOS 10.0
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.2 AI-222.4459.24.2221.9862592
  Xcode:
    version: 15.0.1/15A507
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.9
    path: /opt/homebrew/opt/openjdk@17/bin/javac
  Ruby:
    version: 2.7.4
    path: /usr/local/opt/ruby-2.7.4/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: ^18.2.0
  react-native:
    installed: 0.73.0
    wanted: ^0.73.0
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: true
  newArchEnabled: true

### Lottie Version

Version: 6.4.1

**Comment by heath-clink** [comment]
This may be an issue with react-native itself (assuming this is the same problem I am running into).

Here's the actual error output from the failed compilation:
```
In file included from /redacted-path/AwesomeProject/node_modules/lottie-react-native/ios/Fabric/LottieAnimationViewComponentView.mm:1:
In file included from /redacted-path/AwesomeProject/node_modules/lottie-react-native/ios/Fabric/LottieAnimationViewComponentView.h:2:
In file included from /redacted-path/AwesomeProject/ios/Pods/Headers/Public/React-RCTFabric/React/RCTViewComponentView.h:15:
In file included from /redacted-path/AwesomeProject/ios/Pods/Headers/Public/React-Fabric/react/renderer/components/view/ViewProps.h:10:
In file included from /redacted-path/AwesomeProject/ios/Pods/Headers/Public/React-Fabric/react/renderer/components/view/HostPlatformViewProps.h:10:
In file included from /redacted-path/AwesomeProject/ios/Pods/Headers/Public/React-Fabric/react/renderer/components/view/BaseViewProps.h:11:
/redacted-path/AwesomeProject/ios/Pods/Headers/Public/React-Fabric/react/renderer/components/view/YogaStylableProps.h:10:10: fatal error: 'yoga/style/Style.h' file not found
#include <yoga/style/Style.h>
         ^~~~~~~~~~~~~~~~~~~~
1 error generated.

**Comment by neeteshraj** [comment]
> This may be an issue with react-native itself (assuming this is the same problem I am running into).
> 
> Here's the actual error output from the failed compilation:
> 
> ```
> In file included from /redacted-path/AwesomeProject/node_modules/lottie-react-native/ios/Fabric/LottieAnimationViewComponentView.mm:1:
> In file included from /redacted-path/AwesomeProject/node_modules/lottie-react-native/ios/Fabric/LottieAnimationViewComponentView.h:2:
> In file included from /redacted-path/AwesomeProject/ios/Pods/Headers/Public/React-RCTFabric/React/RCTViewComponentView.h:15:
> In file included from /redacted-path/AwesomeProject/ios/Pods/Headers/Public/React-Fabric/react/renderer/components/view/ViewProps.h:10:
> In file included from /redacted-path/AwesomeProject/ios/Pods/Headers/Public/React-Fabric/react/renderer/components/view/HostPlatformViewProps.h:10:
> In file included from /redacted-path/AwesomeProject/ios/Pods/Headers/Public/React-Fabric/react/renderer/components/view/BaseViewProps.h:11:
> /redacted-path/AwesomeProject/ios/Pods/Headers/Public/React-Fabric/react/renderer/components/view/YogaStylableProps.h:10:10: fatal error: 'yoga/style/Style.h' file not found
> #include <yoga/style/Style.h>
>          ^~~~~~~~~~~~~~~~~~~~
> 1 error generated.
> ```
> 
> The include error comes within a React-Fabric header

did you find ay solutions yet?

**Comment by heath-clink** [comment]
no not yet.

I did make a repro project though: https://github.com/heath-clink/rn73-lottie-repro

That's just RN0.73 template project with lottie added, and exhibits this build error when using new architecture.

**Comment by heath-clink** [comment]
This may be relevant: https://github.com/facebook/react-native/issues/41938

**Comment by heath-clink** [comment]
The problem according to the react-native issue I linked above is that the required dependencies have changed. Projects should use `install_modules_dependencies(spec)` in their podspec to get the correct dependencies, which this project isn't doing.

So I tried making the following change:

```diff
--- a/node_modules/lottie-react-native/lottie-react-native.podspec
+++ b/node_modules/lottie-react-native/lottie-react-native.podspec
@@ -2,8 +2,6 @@ require 'json'
 
 package = JSON.parse(File.read(File.join(__dir__, "package.json")))
 
-folly_compiler_flags = '-DFOLLY_NO_CONFIG -DFOLLY_MOBILE=1 -DFOLLY_USE_LIBCPP=1 -Wno-comma -Wno-shorten-64-to-32'
-
 Pod::Spec.new do |s|
   s.name                    = package["name"]
   s.version                 = package['version']
@@ -25,20 +23,10 @@ Pod::Spec.new do |s|
   s.swift_version = '5.6'
 
   if ENV['RCT_NEW_ARCH_ENABLED'] == '1' then
-    s.compiler_flags = folly_compiler_flags + " -DRCT_NEW_ARCH_ENABLED=1"
-    s.pod_target_xcconfig    = {
-      "HEADER_SEARCH_PATHS" => "\"$(PODS_ROOT)/boost\"",
-      "OTHER_CPLUSPLUSFLAGS" => "-DFOLLY_NO_CONFIG -DFOLLY_MOBILE=1 -DFOLLY_USE_LIBCPP=1",
-      "CLANG_CXX_LANGUAGE_STANDARD" => "c++17",
+    s.pod_target_xcconfig = {
       "DEFINES_MODULE" => "YES",
     }
-    
-    s.dependency "React-RCTFabric"
-    s.dependency "React-Codegen"
-    s.dependency "RCT-Folly"
-    s.dependency "RCTRequired"
-    s.dependency "RCTTypeSafety"
-    s.dependency "ReactCommon/turbomodule/core"
+    install_modules_dependencies(s)
   else
     s.dependency 'React-Core'
     s.exclude_files = "ios/Fabric"
```

With this patch, the app will build without errors. However, now the LottieView is empty. So there's another breaking change somewhere from 0.72.x to 0.73.x

**Comment by matinzd** [comment]
This issue will be fixed in the next release.
