### ISSUE TITLE
[Request] Update `lottie-android` to 6.2.0

### ISSUE THREAD

**Issue by thevoiceless** [lottie-react-native/lottie-react-native#1142]
### Description

This library [currently uses](https://github.com/lottie-react-native/lottie-react-native/blob/master/packages/core/android/build.gradle#L127) version `6.1.0` of `lottie-android`; version `6.2.0` [was released on 11/18](https://github.com/airbnb/lottie-android/releases)

**Comment by matinzd** [comment]
There is an active PR for that. I reviewed it today.
