### ISSUE TITLE
Braking changes on 6.0.0 have no migration guidelines.

### ISSUE THREAD

**Issue by trne** [lottie-react-native/lottie-react-native#1153]
### Description

Upgrading to latest version of this package makes lottie animation not render on react native.
I know that version `6.0.0` from this package introduced braking changes, since it is mentioned on the change log file of this repo. However there is no clear migration guide, which means that my project is stuck at its previous version.

```
$ git diff package.json

--- a/package.json
+++ b/package.json
@@ -35,8 +35,8 @@
-        "lottie-ios": "3.4.1",
-        "lottie-react-native": "5.1.4",
+        "lottie-ios": "^4.3.4",
+        "lottie-react-native": "^6.5.1",
```

### Steps to Reproduce

1. Upgrade project to latest `lottie-react-native`
2. Check how the lottie animations render within the app
3. Lottie animations are not rendered at all.

**Expected behavior:** I'd expect a clear migration guide

**Actual behavior:** no documentation, hence unable to upgrade

### React Native Environment

```
$ npx react-native info 

info Fetching system and libraries information...
System:
  OS: macOS 14.1.1
  CPU: (10) arm64 Apple M1 Pro
  Memory: 113.59 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.16.0
    path: /opt/homebrew/bin/node
  Yarn:
    version: 1.22.21
    path: ~/Documents/react-native-app/node_modules/.bin/yarn
  npm:
    version: 9.8.0
    path: /opt/homebrew/bin/npm
  Watchman:
    version: 2023.11.06.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.14.3
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.2
      - iOS 17.2
      - macOS 14.2
      - tvOS 17.2
      - visionOS 1.0
      - watchOS 10.2
  Android SDK: Not Found
IDEs:
  Android Studio: 2023.1 AI-231.9392.1.2311.11255304
  Xcode:
    version: 15.2/15C500b
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.17
    path: /Users/jgt/.jenv/shims/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.8
    wanted: 0.72.8
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Lottie Version

Version: 6.5.1

**Comment by TheRogue76** [comment]
Hi @trne,

What exactly do you wish for us to provide? The migration is as follows: update the Lottie components and in their style property clearly define their width and height (Data you can read by just checking the dimensions of your Lottie files)

**Comment by TheRogue76** [comment]
@trne We wrote this up [this](https://github.com/lottie-react-native/lottie-react-native/blob/feature/add-migration-guide-from-v5-to-v6/MIGRATION-5-TO-6.md). Please let us know if that is enough or if you would need to know more, and we can adjust

**Comment by trne** [comment]
@TheRogue76 that worked like charm.
closing this as resolved.
cheers!
