### ISSUE TITLE
Animation not showing on Android

### ISSUE THREAD

**Issue by idanCohenDev** [lottie-react-native/lottie-react-native#1159]
### Description

A Lottie json file rendered in a LottieView component is not displaying in Android environment.

### Steps to Reproduce

**Android devices i tested on:** 

-   Samsung Galaxy S21 5G Android 13
-  Samsung Galaxy A30S Android 11
-  Xiaomi Redmi Note 8 Pro 10

**iOS devices i tested on:** 

-   iPhone 13 Pro iOS 17.2.1
-  iPhone XR iOS 17.2.0
-  iPhone 11 Pro Max iOS 15.5

Create a basic component in your application and render the attached Lottie json file inside a LottieView component.

```
    <View style={{alignItems: 'center', paddingVertical: 32}}>
          <LottieView
            loop
            autoPlay
            source={require('../../assets/lottie/ovum.json')} // Path to the local json file
            style={{width: 102, height: 102}}
          />
     </View>
```
**The Lottie file:** 

[ovum.json](https://github.com/lottie-react-native/lottie-react-native/files/13946752/ovum.json)

**Expected behavior:** 

The Lottie animation should appear on the screen doesn't matter the operating system.

**Actual behavior:** 

The Lottie animation does not appear on Android devices and works perfectly on iOS devices (at least on the devices mentioned above)

### React Native Environment

System:
  OS: macOS 13.5.1
  CPU: (8) arm64 Apple M1
  Memory: 119.94 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 21.2.0
    path: /opt/homebrew/bin/node
  Yarn:
    version: 1.22.19
    path: /opt/homebrew/bin/yarn
  npm:
    version: 10.2.3
    path: /opt/homebrew/bin/npm
  Watchman:
    version: 2023.10.30.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.14.3
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.0
      - iOS 17.0
      - macOS 14.0
      - tvOS 17.0
      - watchOS 10.0
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.3 AI-223.8836.35.2231.11090377
  Xcode:
    version: 15.0.1/15A507
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.21
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.3
    wanted: 0.72.3
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

### Lottie Version

Version: 6.5.1

Thank you for your help :)

**Comment by TheRogue76** [comment]
Hey @idanCohenDev,

Have you tried setting `enableMergePathsAndroidForKitKatAndAbove` to true? Do your Android logcats mention something along the lines of `Animation contains merge paths but they are disabled`?

**Comment by idanCohenDev** [comment]
Hey @TheRogue76 thank you for the quick response!

I have tried setting the `enableMergePathsAndroidForKitKatAndAbove` to true without success.
Also i do not see any logs related to the animation logged in my logcats (i'll provide the logs below).
Furthermore, i tried checking the actual json file in Lottie's "Feature Support Checker
" and it seems to be compatible with all the Android supported features.

If it helps, i have another Lottie animation i use in my application which works fine on Android and iOS (i'll provide that animation as well).

Thank you for the support!

**The logcats:** 

```
12:30:09.989  I  ViewPostIme pointer 0
12:30:10.037  I  ViewPostIme pointer 1
12:30:10.215  I  nativeRelease nativeObject s[520471022560]
12:30:10.215  I  nativeRelease nativeObject e[520471022560]
12:30:10.216  I  assignNativeObject: nativeObject = 0 Surface(name=null)/@0xbda44d9 / android.view.SurfaceControl.readFromParcel:1117 android.view.IWindowSession$Stub$Proxy.relayout:1836 android.view.ViewRootImpl.relayoutWindow:9005 android.view.ViewRootImpl.performTraversals:3360 android.view.ViewRootImpl.doTraversal:2618 android.view.ViewRootImpl$TraversalRunnable.run:9971 android.view.Choreographer$CallbackRecord.run:1010 android.view.Choreographer.doCallbacks:809 android.view.Choreographer.doFrame:744 android.view.Choreographer$FrameDisplayEventReceiver.run:995 
12:30:10.217  I  nativeRelease nativeObject s[520471201760]
12:30:10.217  I  nativeRelease nativeObject e[520471201760]
12:30:10.217  I  nativeRelease nativeObject s[520471022656]
12:30:10.217  I  nativeRelease nativeObject e[520471022656]
12:30:10.218  I  nativeRelease nativeObject s[520471019776]
12:30:10.218  I  nativeRelease nativeObject e[520471019776]
12:30:10.218  I  Relayout returned: old=(0,0,720,1560) new=(0,0,720,1560) req=(720,1560)0 dur=8 res=0x1 s={true 523001630720} ch=false fn=324
```

**The animation file that works:**

[assuta loader.json](https://github.com/lottie-react-native/lottie-react-native/files/13948730/assuta.loader.json)

**Comment by TheRogue76** [comment]
Interesting. I'll try to find some free time and see if this is an issue that's just on our side or it's reproducible with the Native Android Lottie as well and get back to you.

**Comment by idanCohenDev** [comment]
@TheRogue76 Amazing, thank you very much!

I was wondering, maybe i need to do any manual linking of the library. 
In the Github documentation there is no mention for any manual linking ([the github doucmentation](https://github.com/lottie-react-native/lottie-react-native)) but in the Airbnb site ([Airbnb site](https://airbnb.io/lottie/#/react-native)) there are some extra steps mentioned for linking the library to the respective packages.
But at the same time there is an animation that actually works so it's probably isn't it...

Anyway, thank you for the support and i hope to find a solution soon.

**Comment by TheRogue76** [comment]
The doc on Airbnb's website is ancient (our bad, we haven't been in sync as much as we want with Airbnb, we are trying to be better but it's an open source lib and finding people that can contribute is a bit hard), and it is on a todo list of things that we will need to update. The repos current Docs are the most up to date (Merged two PRs for docs in the past two days).

**Comment by TheRogue76** [comment]
No problem. Happy to help.
Side note: I didn't find that particular floating number anywhere in the JSON itself. It could be some intermediate calculation, but that's just a guess at that point. Feel free to let me know how the rest of your debugging and reporting with Lottie Android goes.

**Comment by idanCohenDev** [comment]
Hey @TheRogue76,

Wanted to let you know you solved the issue with the information you provided me with.
Changing `"h": 102.51802825927734` to `"h": 102`  at the start of the json resolved the issue.
Not sure if it's a valid fix but it works for my needs.

Thank you!

**Comment by TheRogue76** [comment]
Sounds good. I'll close the issue then.

**Comment by TheRogue76** [comment]
@idanCohenDev Probably the most useless ping of all time, but the docs on Airbnb are now up-to-date again: https://airbnb.io/lottie/#/react-native

**Comment by chriswickham** [comment]
> 92

Updating `h` to closest integer fixed this issue for me too! Just commenting for visibility.

**Comment by chriswickham** [comment]
> Hey @TheRogue76,
> 
> Wanted to let you know you solved the issue with the information you provided me with. Changing `"h": 102.51802825927734` to `"h": 102` at the start of the json resolved the issue. Not sure if it's a valid fix but it works for my needs.
> 
> Thank you!

Updating h to closest integer fixed this issue for me too! Just commenting for visibility.

**Comment by morellana87** [comment]
> https://airbnb.io/lottie/#/react-native

It worked for me. Thanks

**Comment by morellana87** [comment]
> Hey @TheRogue76,
> 
> Wanted to let you know you solved the issue with the information you provided me with. Changing `"h": 102.51802825927734` to `"h": 102` at the start of the json resolved the issue. Not sure if it's a valid fix but it works for my needs.
> 
> Thank you!

It worked for me! Thank You

**Comment by gogupaul123** [comment]
> Hey [@TheRogue76](https://github.com/TheRogue76),
> 
> Wanted to let you know you solved the issue with the information you provided me with. Changing `"h": 102.51802825927734` to `"h": 102` at the start of the json resolved the issue. Not sure if it's a valid fix but it works for my needs.
> 
> Thank you!

Yeah that fixed it for me too

**Comment by Judge-Paul** [comment]
Worked for me as well, such a weird bug lol
