### ISSUE TITLE
Crash in Android Expo Go App

### ISSUE THREAD

**Issue by utaner** [lottie-react-native/lottie-react-native#1161]
### Description

I'm using **'react-native-lottie'** with Expo. Crashes the app in Expo Go Android. There is no problem on iOS. 

### Error

![image](https://github.com/lottie-react-native/lottie-react-native/assets/24855850/994ef9e9-230a-44f6-9f88-357a680ecf30)

### Usage

```javascript
import LottieView from 'lottie-react-native';
return (
<LottieView source={require('../assets/lottie/profile_anim.json')} autoPlay loop style={{ width: 300, height: 300 }} />
)
```

### Json File

[profile_anim.json](https://github.com/lottie-react-native/lottie-react-native/files/13965085/profile_anim.json)
[Lottie Link](https://lottiefiles.com/animations/profile-persons-dmvUB4tuv0)

### Lottie Version

Version: 5.1.6
I tried upgrading the version. It didn't work.

### Other Versions

Expo: 49.0.15
React Native: 0.72.6

**Comment by bedirhangll** [comment]
same error, also I can't see the animations on iOS

**Comment by bedirhangll** [comment]
same issue 👍

**Comment by matinzd** [comment]
Expo Go is not recommended at the moment and we don't have any plans to support that. 
If you are having issues with Expo Go please open issue in their repository as that version is not maintained and updated regularly. 

**I am locking this issue and any other issues related to Expo Go from now on. The documentations will be updated accordingly.**
