### ISSUE TITLE
dotLottie support for files on native side ?

### ISSUE THREAD

**Issue by ranaavneet** [lottie-react-native/lottie-react-native#1162]
Hi! Is there any way to add dotLottie files on native side in ios/Android folders respectively ?

**Comment by TheRogue76** [comment]
Hi @ranaavneet.
Interesting question. If memory serves right, we do support adding the asset on the native side, and just passing in the name as a prop that would then find the asset from the bundle directly. That worked with JSON animations, never tried it with dotLottie though but please test it out and see if it works.
What is your use case though? If it's a matter of performance, i would like to point out that unlike the JSON animations that are loaded on to the JS thread and sent through the bridge (or with JSI, if you have new arch enabled) to the Native thread, dotLottie animations are loaded on the Native thread directly. If you have another use case though i would love to hear it.

**Comment by ranaavneet** [comment]
Hey @TheRogue76 

Thanks for the reply. Yes performance was my reason, but if dotLottie are anyways loaded on the main thread then it should be fine. 

Actually why I thought about this was because of my use case. 

I have an example where I have a single lottie component with auto play set to false. 
On press of a button I change the source of the lottie file using setState and then immediately in the next line I call the play method on the ref.

Somehow most of the times, on the press, either the previously rendered source shows, or the lottie doesn't play. I guess because the source hasn't changed yet

This is happpening to me if the source is dotLottie. If the source is a JSON, then this doesn't happen. 

I saw in the code that for dotLottie we use Image.resolveAssets. Is it possible, this function is expensive?

**Comment by TheRogue76** [comment]
From your explanation, seems like you are facing a race condition. Changing the animation in setState simply means that the next time the component is re-rendered, the source will be updated. Calling the play function on the ref however invokes it on the current View, meaning that you call it on the existing source (it gets sent through the bridge / JSI immediately before anything else has had the time to be done).

Doing it with JSON is probably just tanking the thread, forcing the JSON through the bridge, setting it and then going to the next line. Where as dotLottie just sends it the URL for the resource to be loaded on the Native thread. 

`Image.resolveAssetSource` is not an expensive operation as far as i know. It simply gives us the Source for that file in the bundled app, that we can then load on the Native side.

For your case, i would recommend avoiding the race condition by calling play on the `onAnimationLoaded` callback of your lottie component.

**Comment by TheRogue76** [comment]
Aaaaand i just realised that we haven't documented `onAnimationLoaded` or `onAnimationError` in our API docs. Our bad. Adding it to the list of things i need to update

**Comment by ranaavneet** [comment]
That makes sense. Forgot the onAnimationLoaded prop. Thanks @TheRogue76

**Comment by TheRogue76** [comment]
Closing this as resolved then!

**Comment by TheRogue76** [comment]
Docs updated!

**Comment by ranaavneet** [comment]
Thanks @TheRogue76!

**Comment by Bhupendra-Joshi** [comment]
Hey @TheRogue76 

We are trying to add dot-Lottie to the native side but it is not working. We're getting the following error on IOS. We've tried both with and without the ".lottie" extension while passing the name as a prop

Error when decoding animation "maintenance.lottie": assetNotFound(name: "maintenance.lottie", bundle: Optional(NSBundle </Users/user/Library/Developer/CoreSimulator/Devices/E98BD1DB-2504-4E11-86F5-BA85892D99F3/data/Containers/Bundle/Application/9457237B-5056-4E1E-954A-2D070548044D/MyApp.app> (loaded)))

**Comment by TheRogue76** [comment]
> Hey @TheRogue76
> 
> We are trying to add dot-Lottie to the native side but it is not working. We're getting the following error on IOS. We've tried both with and without the ".lottie" extension while passing the name as a prop
> 
> Error when decoding animation "maintenance.lottie": assetNotFound(name: "maintenance.lottie", bundle: Optional(NSBundle </Users/user/Library/Developer/CoreSimulator/Devices/E98BD1DB-2504-4E11-86F5-BA85892D99F3/data/Containers/Bundle/Application/9457237B-5056-4E1E-954A-2D070548044D/MyApp.app> (loaded)))

Interesting. If the reason you are adding the dotLottie on the Native side is performance, as I mentioned above, you don't need it, you can simply have it in your code and we do the heavy lifting of loading the animation on our side. But if for whatever reason you need this feature to work with the animation on the native side, do me a favor, open a new issue on the repo, and tag me so I can take a look. I usually don't check on closed issues, so the chances of it slipping from my mind are a bit high. Shouldn't be too much of a hassle to add support for this
