### ISSUE TITLE
Json lottie get err

### ISSUE THREAD

**Issue by JsirForGit** [lottie-react-native/lottie-react-native#1171]
### Description

I have a json for lottie, when i run in online lottie page [(Lottiefiles)](https://app.lottiefiles.com/share/5ad2de8a-cef7-4465-8917-5e84ca53126c) it is ok 
but i run in my rn project, The body of the car is separated from the wheels

### Steps to Reproduce

```
 <Lottie
                ref={animationRef}
                style={styles.lottieWrap}
                source={require('@/assets/lottie/car_in_lottie.json')}
                loop={false} />
```

**Expected behavior:**  It behaves the same as the web page.

**Actual behavior:** The body of the car is separated from the wheels

### React Native Environment
"react": "18.2.0",
"react-native": "0.72.4",

### Lottie Version

"lottie-ios": "4.3.3",
"lottie-react-native": "6.4.1",

**Comment by TheRogue76** [comment]
Hi @JsirForGit. Please provide a reproducible.

**Comment by TheRogue76** [comment]
<img width="559" alt="Screenshot 2024-02-11 at 10 11 11" src="https://github.com/lottie-react-native/lottie-react-native/assets/40071952/f93580ba-0c30-4ee9-be86-9620efbf50f9">

Without the images, all i can see are a couple of lines. This animation is making heavy use of image assets. Please provide a reproducible with those assets included so i can do further investigation
