### ISSUE TITLE
underlying Objective-C module 'Lottie' not found

### ISSUE THREAD

**Issue by umerdogar** [lottie-react-native/lottie-react-native#1173]
### Description

[underlying Objective-C module 'Lottie' not found ]

### Steps to Reproduce

1. [This is my Xcode  Version 15.2 (15C500b)]
2. "lottie-react-native": "^5.0.1",
3. [I updated my xcode , after that I have been recieving this issue in xcode and unable to build my app.]

**Expected behavior:** [What you expected to happen]
It should run in the way it was running before, my loader should run in the app.

**Actual behavior:** [What actually happened]
Build is not made and getting error.

### React Native Environment
My react native version is :  "react-native": "0.69.7",
Lottie Version : "lottie-react-native": "^5.0.1",

### Lottie Version

Version: x.x.x

**Comment by TheRogue76** [comment]
Please provide a reproducer and fill out the template. We can not debug something we can not see

**Comment by umerdogar** [comment]
> Please provide a reproducer and fill out the template. We can not debug something we can not see

Can you please check now??

**Comment by TheRogue76** [comment]
Your Lottie and React Native versions are out of date. Lottie V5.0.1 doesn't work with Xcode 15. Xcode 15 made a lot of changes both for the linker and some other internals. My recommendation? Update the project and dependencies. If you don't want to, downgrade your Xcode. But this is not addressable.
