### ISSUE TITLE
Pod install failed error on mac

### ISSUE THREAD

**Issue by minkgkyaw9899** [lottie-react-native/lottie-react-native#1175]
### Description
I installed lottie-react-native using `npm` package manager
and navigate to ios directory and run `bundle exec pod install` and i got this following error

```bash
Installing Yoga 1.14.0
Installing lottie-ios (4.4.0)
Installing lottie-react-native (6.6.0)
[!] The following Swift pods cannot yet be integrated as static libraries:

The Swift pod `lottie-react-native` depends upon `RCT-Folly.common`, which does not define modules.
To opt into those targets generating module maps (which is necessary to import them from Swift 
when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, 
or specify `:modular_headers => true` for particular dependencies.
```

### React Native Environment
System:
  OS: macOS 14.3
  CPU: (8) arm64 Apple M1
  Memory: 99.02 MB / 8.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 21.5.0
    path: /opt/homebrew/bin/node
  Yarn:
    version: 1.22.21
    path: /usr/local/bin/yarn
  npm:
    version: 10.2.4
    path: /opt/homebrew/bin/npm
  Watchman:
    version: 2023.12.04.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.14.3
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.2
      - iOS 17.2
      - macOS 14.2
      - tvOS 17.2
      - visionOS 1.0
      - watchOS 10.2
  Android SDK:
    API Levels:
      - "31"
      - "33"
      - "34"
    Build Tools:
      - 30.0.3
      - 33.0.0
      - 33.0.1
      - 34.0.0
      - 34.0.0
      - 34.0.0
      - 34.0.0
    System Images:
      - android-33 | Google APIs ARM 64 v8a
      - android-33 | Google Play ARM 64 v8a
      - android-34 | Google APIs ARM 64 v8a
    Android NDK: Not Found
IDEs:
  Android Studio: 2023.1 AI-231.9392.1.2311.11330709
  Xcode:
    version: 15.2/15C500b
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.9
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.3
    wanted: 0.73.3
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

### Lottie Version
react-native@0.73.3
lottie-ios@^4.4.0
lottie-react-native@^6.6.0

**Comment by professorkolik** [comment]
Same here 😞

**Comment by matinzd** [comment]
Hi

Thanks for submitting the issue. As you can see in the log, the way on how to resolve this issue is already given by cocoapods. Try the instructions and let us know if you still have problems with it.

**Comment by minkgkyaw9899** [comment]
Thank you I already solved this issues by adding `use_modular_headers` in podfile but I think it would be better if you make it ready to use after installed package and no need to confiuration manully.

**Comment by matinzd** [comment]
@minkgkyaw9899 

This is not a something we can do on our side. If for any reason you are using some packages that aren't compatible with non modular headers, you have to add it. It's pretty much the same for other libraries. 
I will close this as this issue is now resolved.

**Comment by minkgkyaw9899** [comment]
@matinzd Ok bro thank you
