### ISSUE TITLE
Question. Frame Number?

### ISSUE THREAD

**Issue by oiver555** [lottie-react-native/lottie-react-native#1179]
Im using version 5.1.6 because this is the highest version I am able to use with Expo SDK 49. Everything works fine however, I would like to know is there a way to get the current frame of the LottieView? I tried searching through the values that come from the ref to the LottieView, but I can't find any Animated Values or frame numbers there. I using the play and pause through the ref to the LottieView.

**Comment by TheRogue76** [comment]
Hi @oiver555,
No, Neither we, nor the native dependencies (as far as I know) have any such method. Can I ask why you need this? Maybe I can recommend an alternative for achieving your goal

**Comment by madsrode** [comment]
Hi @oiver555 
It is not exactly the current frame, but you can get the current progress position if you use the AnimatedLottieView show in te example here: https://github.com/lottie-react-native/lottie-react-native?tab=readme-ov-file#usage

**Comment by TheRogue76** [comment]
> Hi @oiver555 It is not exactly the current frame, but you can get the current progress position if you use the AnimatedLottieView show in te example here: https://github.com/lottie-react-native/lottie-react-native?tab=readme-ov-file#usage

Slight clarification, you can set the progress with that prop and have fine-grained control over it, but it won't give you the progress. That one you need to have somewhere separately. You can read more [here](https://github.com/lottie-react-native/lottie-react-native/blob/master/docs/api.md)

**Comment by oiver555** [comment]
Wow thanks much, I eventually found a way around my issue but I'll be sure to remember your comment

**Comment by TheRogue76** [comment]
Sounds good. Best of luck to you.
