### ISSUE TITLE
Cannot convert undefined value to object (Error on Android only)

### ISSUE THREAD

**Issue by Elue-dev** [lottie-react-native/lottie-react-native#1181]
### Description
i am using this component library in my expo react native app and keep getting this error on Android only, but works fine on iOS.
`Cannot convert undefined value to object `

[Description of the bug]
TypeError: Cannot convert undefined value to object

![Media (1)](https://github.com/lottie-react-native/lottie-react-native/assets/79481288/fddafc2b-0ae7-4080-8a25-653478a602b9)

This error is located at:
    in LottieAnimationView (at createAnimatedComponent.js:54)
    in Unknown (at LottieView.js:178)
    in RCTView (at View.js:116)
    in View (at LottieView.js:177)
    in LottieView (at Mentor.tsx:24)
    in RCTView (at View.js:116)
    in View (at createAnimatedComponent.tsx:579)
    in AnimatedComponent(View) (at createAnimatedComponent.tsx:596)
    in Unknown (at Mentor.tsx:19)
    in RCTView (at View.js:116)
    in View
......

### Steps to Reproduce
import LottieView from 'lottie-react-native';

  <SafeAreaView className='flex-1 bg-white'>
      <CustomStatusBar style='dark' />
      <ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={{
        flexGrow: 1,
        paddingHorizontal: 15
      }}
      >
        <View className='flex-1 justify-center items-center'>
            <Animated.View
              style={styles.lottieWrapper}
              entering={FadeInLeft.delay(200).duration(1000).springify()}
              exiting={FadeOutLeft.delay(200).duration(1000).springify()}
            >
              <LottieView
                source={require("../../assets/lottie_animations/coming_soon.json")}
                loop
                autoPlay
              />
            </Animated.View>
        </View>
      </ScrollView>
    </SafeAreaView>
    
    
style:
 lottieWrapper: {
      flex: 1,
      width: width * 0.9,
      height: 290,
    },

i expect the animation to work fine on android just as it did on iOS

### React Native Environment
`  "react": "18.2.0",
    "react-dom": "^18.2.0",
    "react-native": "0.72.6",
    "expo": "~50.0.6",
 "lottie-react-native": "^5.1.6",
`

`
System:
  OS: macOS 12.7.2
  CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
  Memory: 25.24 MB / 16.00 GB
  Shell:
    version: 5.8.1
    path: /bin/zsh
Binaries:
  Node:
    version: 20.11.0
    path: /usr/local/bin/node
  Yarn: Not Found
  npm:
    version: 10.3.0
    path: /usr/local/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.14.3
    path: /Users/nubiaville/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 21.2
      - iOS 15.2
      - macOS 12.1
      - tvOS 15.2
      - watchOS 8.3
  Android SDK: Not Found
IDEs:
  Android Studio: 2023.1 AI-231.9392.1.2311.11255304
  Xcode:
    version: 13.2.1/13C100
    path: /usr/bin/xcodebuild
Languages:
  Java: Not Found
  Ruby:
    version: 3.0.3
    path: /Users/nubiaville/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.4
    wanted: 0.73.4
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

`
I am using Expo Go

### Lottie Version
Version:  5.1.6,

**Comment by TheRogue76** [comment]
Hi @Elue-dev,
I haven't had time to check this issue specifically yet (Will probably fall to the weekend when I get some free time) but I can tell from the get-go that your Lottie React Native package is mismatched with the Expo Go client and Expo 50. The latest Expo Go is running Lottie 6, And we do highly recommend moving away from V5, as it is no longer maintained.
If you need help with the migration, please read [this migration guide](https://github.com/lottie-react-native/lottie-react-native/blob/master/MIGRATION-5-TO-6.md)

**Comment by Elue-dev** [comment]
> Hi @Elue-dev,
> 
> I haven't had time to check this issue specifically yet (Will probably fall to the weekend when I get some free time) but I can tell from the get-go that your Lottie React Native package is mismatched with the Expo Go client and Expo 50. The latest Expo Go is running Lottie 6, And we do highly recommend moving away from V5, as it is no longer maintained.
> 
> If you need help with the migration, please read [this migration guide](https://github.com/lottie-react-native/lottie-react-native/blob/master/MIGRATION-5-TO-6.md)

yes, thanks, did that, i upgraded to version 6 and everything works fine now, I installed version 6 initially but when i used the lottie component, it appeared blank, that was why i had to downgrade to version 5. I later realized that the issue was simply because i didn't give it a height and width of 100%

**Comment by TheRogue76** [comment]
Sounds good then. Closing the issue. Let me know if there are any more problems.
