### ISSUE TITLE
Lottie json crashes on Andriod devices but IOS works fine

### ISSUE THREAD

**Issue by Elliotbaz** [lottie-react-native/lottie-react-native#1184]
This is an issue i think saw a closed thread on this that wasn't solved.  I recently got into using lottio json and i am using Expo.
My ios device this works fine without issue. But the Andriod devices crashes and i cannot see an error, but this happens on any page with the file.

Any fix to this?

**Comment by TheRogue76** [comment]
Hi @Elliotbaz,
Please fill out the issue template. The values we ask for in the template are vital for debugging process, and no work can be done without that data.

**Comment by Muin1234** [comment]
I am facing the same

**Comment by KillianLarcher** [comment]
Same problem here with Android and Expo 49.

**Comment by Flaaj** [comment]
Same here. For some reason I got it working in the past (don't know how, by accident i caused it to work while working on a different issue), but few days ago while making a final build to publish on Play Store, I got the response that app crashes at opening and it happened that lottie animations stopped working again.

iOS works, Android doesn't.

**Comment by tonzari** [comment]
I am also having issues with lotties in Expo Go on Android, yet iOS and web is working fine.

On android, lotties will display and play as expected IF I use require('asset/...').

` <Lottie
            autoPlay
            style={{ width: 200, height: 200 }}
            source={require('./assets/myFirstLottie.json')} // this works
            renderMode='AUTOMATIC'
          />`

However, if I pass an actual object, the lottie does not display

`<Lottie
            autoPlay
            style={{ width: 200, height: 200 }}
            source={someLottieObject} // this does not work on Android but works on iOS and web
            renderMode='AUTOMATIC'
          />`
          
I'm hoping this is useful information. My apologies if it is not relevant.

**Comment by Samide47** [comment]
this dosen't work and crashes the app
<LottieView
          style={{ flex: 1 }}
          source={require('../../assets/animations/pill.json')}
          autoPlay
          speed={0.7}
          loop
        />

this works but not showing the View because no style is added
<LottieView 
          source={require('../../assets/animations/pill.json')}
          autoPlay
          speed={0.7}
          loop
        />
