### ISSUE TITLE
Download lotties json fies not working on expo android. 

### ISSUE THREAD

**Issue by LucasJandrey5** [lottie-react-native/lottie-react-native#1187]
### Description

lotties json files that I downloaded from the website are not reproducing in expo android.

In my phone (Galaxy S23) the animation begin but stop in middle
On android simulator the app crashs

All animations works in https://lottiefiles.github.io/lottie-docs/playground/json_editor/

In json_editor the downloaded files have many errors but works

### Steps to Reproduce

1. Download json anim from Lottie Files site

### Minimal reproduction
Code:
```
import LottieView from "lottie-react-native";

<LottieView
        source={require("./animation.json")}
        style={{ width: "100%", height: "50%" }}
        autoPlay
        loop
      />

```
Tested files:
[animation.json](https://github.com/lottie-react-native/lottie-react-native/files/14393411/animation.json)
[success.json](https://github.com/lottie-react-native/lottie-react-native/files/14393413/success.json)
[anim.json](https://github.com/lottie-react-native/lottie-react-native/files/14393415/anim.json)

### React Native Environment

expo: "^49.0.23"
lottie-react-native: "^6.6.0"
react-native: "0.72.10"

[package.json](https://github.com/lottie-react-native/lottie-react-native/files/14393406/package.json)

### Lottie Version

Version: ^6.6.0

**Comment by LucasJandrey5** [comment]
Hello, thanks for response 

I tried your solution but not works, got same error

I try too follow step by step of expo docs:
 https://docs.expo.dev/versions/latest/sdk/lottie/

But not works too.

Beetween the test interval, i reset cache and reinstal packages with npm install

**Comment by FESEVA** [comment]
Same for me 😭:

Tried with these combinations:

- Expo 50
  - "lottie-react-native": "6.7.0"
  - "react-native": "0.73.6"
  
- Expo 50
  - "lottie-react-native": "6.5.1"
  - "react-native": "0.73.5"

- Expo 50
  - "lottie-react-native": "6.3.1"
  - "react-native": "0.73.5",

Its working on IOS but nothing is displayed on Android Emulator / Device

**Comment by bedirhangull** [comment]
Same issue :( 
`				<LottieView
					autoPlay
				    loop={true}
					ref={lottieRef}
					style={{
						width: '100%',
						height: '100%',
					}}
					source={require('../../assets/animations/animation.json')}
				/>`

    "expo": "~50.0.15",
    "lottie-react-native": "6.5.1",

**Comment by joaomellogomes** [comment]
Same issue here. I've tried a lot different approaches including use **.lottie** files instead of json.
I've noted that other simpler animations in my Android app works fine. They have 51kb and 17kb and works perfectly on Android and IOS, but the animation with 775kb (.json) works on IOS and not on Android, I've also tried to use .lottie (55kb) and the same result on Android. Just wondering, I don't know if it's related to the files sizes.

**Comment by pripoliveira50** [comment]
the same issue..

**Comment by bibhuti9** [comment]
I'm facing the same issue.

```
 "react-native": "0.73.4",
 "lottie-react-native": "^6.4.1",
```

**Comment by bibhuti9** [comment]
I found a solution. Please remove the height and width point values.

Before
```
"h": 121.07,
 "w": 153.26,
```

After
```
"h": 121,
"w": 153,
```

**Comment by alextbogdanov** [comment]
Same issue here.

**Comment by Hulker** [comment]
Same issue also 
"expo": "^51.0.0",
:-(

**Comment by Hulker** [comment]
> Same issue also "expo": "^51.0.0", :-(

I went back and experimented with the code. Previously (before Expo 51), it worked just fine when I only set the height. However, this time adding a width seems to have resolved the problem.

Before:
  ```
<LottieView
                        style={{ height: 170 }}
                        source={require("../assets/lotti/goldlotti1.json")}
                        autoPlay
                        loop={true}
                        resizeMode="cover"
                      /> 
```

After:
```
<LottieView
                        style={{ height: 170,**width:170** }}
                        source={require("../assets/lotti/goldlotti1.json")}
                        autoPlay
                        loop={true}
                        resizeMode="cover"
                      /> 
```

I hope this information is what you were looking for.

**Comment by dmi3y** [comment]
In my case I had to add `style={{width: "100%", height: "100%"}}` (full screen animation), hope will save someone time.

**Comment by TheRogue76** [comment]
Tested the animation both in Lottie RN and Lottie Android
Both run fine. 
https://github.com/user-attachments/assets/0aaae50c-4dac-4121-8f60-9271abc4df28

**Comment by FESEVA** [comment]
> Tested the animation both in Lottie RN and Lottie Android Both run fine. https://github.com/user-attachments/assets/0aaae50c-4dac-4121-8f60-9271abc4df28

Please, Can you share your lottie element config and libraries working version?

It would be helpful
