### ISSUE TITLE
How to remove lottie-react-native for windows

### ISSUE THREAD

**Issue by krystalcl005** [lottie-react-native/lottie-react-native#1201]
### Description

1. I want to remove this package in my react -native project.
2. This package should show the resolution for uninstalling.

### Lottie Version

Version: 5.1.4

**Comment by TheRogue76** [comment]
Hi @krystalcl005,
Simply undo the steps you took to install the package. Remove it from package.json, remove the linking you did on windows (the reverse of the steps taken on the Read Me or better yet, the steps take when this was added to your project in case it was custom) and that's about it. If you wish to add any specific things regarding the installation or the removal, feel free to open the PR.
