### ISSUE TITLE
Lottie json crashes on Andriod devices but IOS works fine

### ISSUE THREAD

**Issue by Elliotbaz** [lottie-react-native/lottie-react-native#1204]
### Description

on my Expo apllication, i use import LottieView from "lottie-react-native"; the animation runs fine on IOS devices, but crashes immediately on Andriod Device

### Steps to Reproduce

1. npm install "lottie-react-native": "5.1.6", (my expo version is  "expo": "~49.0.15")

2. use the lottie like: 
                     <LottieView
                            style={styles.lottie}
                            source={require('../../asserts/animations/splash.json')}
                            autoPlay
                            resizeMode="cover"
                        />

3. the animation would play fine on IOS, but when i run the application on andriod it crashes 

**Expected behavior:** should display the animation as it does on IOS device

**Actual behavior:** crashes when it get to the part i have LottieView

### React Native Environment
my package.json: 
{
  "name": "meeting_app",
  "version": "1.0.0",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "@expo/config-plugins": "~7.2.2",
    "@expo/prebuild-config": "~6.2.4",
    "@react-native-async-storage/async-storage": "^1.21.0",
    "@react-native-community/masked-view": "^0.1.11",
    "@react-native-community/slider": "^4.5.0",
    "@react-native-picker/picker": "^2.6.1",
    "@react-navigation/bottom-tabs": "^6.5.11",
    "@react-navigation/drawer": "^6.6.6",
    "@react-navigation/material-bottom-tabs": "^6.2.19",
    "@react-navigation/native": "^6.1.9",
    "@react-navigation/stack": "^6.3.20",
    "axios": "^1.6.2",
    "expo": "~49.0.15",
    "expo-app-loading": "^2.1.1",
    "expo-av": "~13.4.1",
    "expo-linear-gradient": "~12.3.0",
    "expo-permissions": "^14.4.0",
    "expo-status-bar": "~1.6.0",
    "lottie-react-native": "5.1.6",
    "react": "18.2.0",
    "react-native": "0.72.6",
    "react-native-calendar-strip": "^2.2.6",
    "react-native-gesture-handler": "~2.12.0",
    "react-native-linear-gradient": "^2.8.3",
    "react-native-paper": "^4.12.5",
    "react-native-picker-select": "^9.0.0",
    "react-native-reanimated": "~3.3.0",
    "react-native-safe-area-context": "4.6.3",
    "react-native-screens": "~3.22.0",
    "react-native-vector-icons": "^10.0.2",
    "react-navigation": "^4.4.4"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0"
  },
  "private": true
}

### Lottie Version

Version: 5.1.6

**Comment by TheRogue76** [comment]
Hi @Elliotbaz 
If you are using Expo with Expo Go, then as far as I remember it was updated to use Lottie version 6 by the time SDK 49 came out (I do not know which version they shipped it with), and if you are using the development builds, then you have no binding to that. Either way, Lottie V5 is not supported. And considering Apple's upcoming requirements, staying on it is going to cause problems anyway.
Please follow the migration guide (read [here](https://github.com/lottie-react-native/lottie-react-native/blob/master/MIGRATION-5-TO-6.md)) and let us know if that solves the problem.

**Comment by Elliotbaz** [comment]
hi @TheRogue76, so i have updated my project now 
 "lottie-react-native": "^6.7.0",
 and i have something like this now: 
 
                        <Lottie
                            style={styles.lottie}
                            source={require('../../asserts/animations/splash.json')}
                            autoPlay
                            resizeMode="cover"
                            renderMode='AUTOMATIC'
                        />
                        
                  lottie: {
        width: '100%',
        height: '100%',
        marginRight: '10%',
        marginVertical: '-1%'
    },
    
    but this as previously works on just ios and not andriod
am i missing anything ?

**Comment by TheRogue76** [comment]
Hi @Elliotbaz,
Three questions for you:
1. Can you provide a reproducible repository with just Expo 49 and this? 
2. Are you using Expo go or Expo development builds
3. What is the log when it crashes on Android (Logcat preferably, but the rest are appreciated)

**Comment by Elliotbaz** [comment]
@TheRogue76 
1. i can make a repo that can have this for you. 
2. i am using Expo Go
3. i see no logs, it just shows on my device (both physical and emulator) it just closes the app

**Comment by TheRogue76** [comment]
@Elliotbaz Please do. I can take a look tomorrow and see what I can find

**Comment by Elliotbaz** [comment]
i am closing this issue now, this works fine after the upgrade, i have to upgrade expo and others along side lottie react. just to help other who might have similar issue, here is my package json:

`{
  "name": "meeting-app",
  "version": "1.0.0",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "@expo/metro-runtime": "~3.1.3",
    "@react-native-async-storage/async-storage": "^1.22.3",
    "@react-native-community/slider": "^4.5.0",
    "@react-native-picker/picker": "^2.6.1",
    "@react-navigation/drawer": "^6.6.14",
    "@react-navigation/material-bottom-tabs": "^6.2.27",
    "@react-navigation/native": "^6.1.16",
    "@react-navigation/stack": "^6.3.28",
    "axios": "^1.6.8",
    "expo": "~50.0.13",
    "expo-av": "^13.10.5",
    "expo-linear-gradient": "^12.7.2",
    "expo-splash-screen": "^0.26.4",
    "expo-status-bar": "~1.11.1",
    "lottie-react-native": "^6.7.0",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.73.5",
    "react-native-calendar-strip": "^2.2.6",
    "react-native-gesture-handler": "~2.14.0",
    "react-native-paper": "^5.12.3",
    "react-native-picker-select": "^9.0.1",
    "react-native-reanimated": "~3.6.2",
    "react-native-safe-area-context": "^4.9.0",
    "react-native-web": "~0.19.6"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0"
  },
  "private": true
}
`
