### ISSUE TITLE
Animation flickering & Some animations not even visible on Android

### ISSUE THREAD

**Issue by Lekhrajk** [lottie-react-native/lottie-react-native#1211]
### Description
I just installed latest version from npm  & downloaded some .json lottie animations from lottiefiles but out of 7-8 lottiefiles only 1 is working fine rest showing either glitch in animation or not showing at all.

**Expected behavior:** 
It should display animation as showing in lottiefiles website 

**Actual behavior:**
Please check this screen recording.
https://github.com/lottie-react-native/lottie-react-native/assets/42565741/7008f95e-dfb8-46b9-9231-edda246bda76

### Minimal reproduction
I just followed what is mentioned on the npm package and added some height and width

This is how i am using it

`import LottieView from 'lottie-react-native';
 <LottieView
          source={animFile}
           autoPlay
           loop={true}
           style={{ width: "100%", height: 300, alignSelf: "center", ...style }}
    />`

### React Native Environment
    "system" : "Mac OS m2 pro",
   "device": "Android 13 moto edge neo 40" and "Google pixel 6"
    "react": "18.2.0",
    "react-native": "0.73.6",

### Lottie Version
 "lottie-react-native": "^6.7.0",

**Comment by Lekhrajk** [comment]
Could anyone please help or help me what is the reason behind it. ?

**Comment by TheRogue76** [comment]
Most probably the animation you are using is using unsupported effects. Read more here: https://github.com/lottie-react-native/lottie-react-native?tab=readme-ov-file#troubleshooting
You can also check the logcat errors, it usually says as much if it is using unsupported effects

**Comment by kienpro307** [comment]
> Most probably the animation you are using is using unsupported effects. Read more here: https://github.com/lottie-react-native/lottie-react-native?tab=readme-ov-file#troubleshooting You can also check the logcat errors, it usually says as much if it is using unsupported effects

is there any issue that helps me use those animations despite of using unsupported effects?

**Comment by TheRogue76** [comment]
> > Most probably the animation you are using is using unsupported effects. Read more here: https://github.com/lottie-react-native/lottie-react-native?tab=readme-ov-file#troubleshooting You can also check the logcat errors, it usually says as much if it is using unsupported effects
> 
> is there any issue that helps me use those animations despite of using unsupported effects?

No. If the effect is unsupported in the platform, it is simply not going to work.

**Comment by Samych02** [comment]
I run into the same problem, it might seems strange, but what fixed this problem for me is unminify and format the lottie file (which is in json format).

**Comment by Buibui-Technologies** [comment]
> I run into the same issue. It might seems strange, but what fixed this problem for me is unminifying and formatting the lottie file (which is in json format).

Can you elaborate more on how you fixed it ? I am facing the same issue, my lottie's which were showing well are not even showing right now.
