### ISSUE TITLE
[MACOS App Development][react Native Build Failure] Cannot find type 'Color' in scope

### ISSUE THREAD

**Issue by himanshu-1034** [lottie-react-native/lottie-react-native#1212]
### Description

Our team had built an application using react native that runs on android and IOS. the app was running very fluently. Now there is a requirement to bring that same same UI to MacOS based systems as well so i followed the steps https://microsoft.github.io/react-native-windows/docs/rnm-getting-started and managed to do a pod install with node 16.

but now when i am trying to run the application, i am stuck on this error. browsing is not helping, kindly help whoever gets anything

### Steps to Reproduce

1. [on the react native application already supporting android/ios]
2. [install the dependency of macos]
3. [build the project]
4. [Error saying Cannot find type 'Color' in scope will appear, see the photo]
<img width="891" alt="image" src="https://github.com/lottie-react-native/lottie-react-native/assets/56597293/44187744-684e-432e-8d0c-463f65189681">

**Expected behavior:** 
[I should see the app running]

**Actual behavior:** [Build failure with errors]

### Minimal reproduction

see image

### React Native Environment
The project was already running on android and ios devices, installation of macos was done after that.

"react": "18.2.0",
node version v16.18.0
react native version 
react-native-cli: 2.0.1
react-native: 0.71.2

### Lottie Version
"lottie-ios": "^4.4.1",
 "lottie-react-native": "^6.7.0",

Also, if lottie react native is not supported for macos, can you please head me to the page with the help of which i can avoid installing this pod for macos env.

Thanks in advance!

**Comment by TheRogue76** [comment]
Hey @himanshu-1034
I made the PR, once the newest version is out (6.7.2 or 6.8.0) it should be available.

**Comment by TheRogue76** [comment]
Also, please do not install lottie-ios manually. Please remove it from your package.json, and let LRN pick it's dependency correctly
