### ISSUE TITLE
Xcode will not build project with lottie-react-native@6.7.0 due to lack of PrivacyInfo

### ISSUE THREAD

**Issue by barrymcgee** [lottie-react-native/lottie-react-native#1214]
### Description

```

Showing All Errors Only

Build target lottie-react-native-Lottie_React_Native_Privacy of project Pods with configuration Debug

error: /project/node_modules/lottie-react-native/ios/PrivacyInfo.xcprivacy: No such file or directory (in target 'lottie-react-native-Lottie_React_Native_Privacy' from project 'Pods')

/project/node_modules/lottie-react-native/ios/PrivacyInfo.xcprivacy: No such file or directory

Build failed
```

More context: https://github.com/airbnb/lottie-ios/issues/2297#issuecomment-1994578609

### Lottie Version

Version: 6.7.0

**Comment by TheRogue76** [comment]
Hi @barrymcgee. Can I get a reproducible and a bit more of an explanation of what the specific issue is? This is LRN's podspec:
<img width="480" alt="Screenshot 2024-04-03 at 22 31 48" src="https://github.com/lottie-react-native/lottie-react-native/assets/40071952/809b0676-be0e-453c-b444-aeffb50048cc">
We are not including everything, just Obj-C and Swift files.
Also please do not delete the contents of the issue template next time. We use those for triaging issues, and we can't do much without them.

**Comment by gezquinndesign** [comment]
Looks like this is sorted in 6.7.2.
