### ISSUE TITLE
My Lottie animation not working correctly

### ISSUE THREAD

**Issue by ekremgunes** [lottie-react-native/lottie-react-native#1215]
Some animatons work someone not. Lottie animation not working correctly.I search many website but didn't found to solution.Here are expected and outpu in react native android:

<img src="https://i.stack.imgur.com/o1vTV.png"/>

### React Native Environment

"expo": "~50.0.14", 
windows,
android

(tried on flutter and gettins same result),
(tried with different android devices),
(tried different animations )

### Lottie Version

Version: "^6.5.1"

**Comment by kienpro307** [comment]
i'm having the same problem, there are many lottie files don't work correctly in my app and some don't appear neither, need the issue !

**Comment by ekremgunes** [comment]
> You are also probably using unsupported effects: https://github.com/lottie-react-native/lottie-react-native?tab=readme-ov-file#troubleshooting As far as I know, the flutter implementation of Lottie is a Dart rewrite of Lottie-Android, which is what Lottie React Native uses on Android platforms, so it makes sense that any effect that is not supported in the Android spec would not be supported in the flutter one either.

Thanks sir. So it's problem of lottie . I loved the idea but I can give 2.5 star now.Maybe %75 not working on the site.If i want to use it i need test it :(

**Comment by ekremgunes** [comment]
> i'm having the same problem, there are many lottie files don't work correctly in my app and some don't appear neither, need the issue !

My friend, I am testing with qr code.They have a mobile app.Download and find the working lotties :( I hope they will solve this

![Ekran görüntüsü 2024-04-04 150853](https://github.com/lottie-react-native/lottie-react-native/assets/95303574/f8caf0ba-39a3-4d72-874d-57ac81ffe5f8)

**Comment by TheRogue76** [comment]
We do not work for the same people who own Lottie files. I am not a paid employee. This is a FOSS project. Please provide a reproducible, and I will take a look.

**Comment by AlaaMohammad** [comment]
![image](https://github.com/lottie-react-native/lottie-react-native/assets/8956330/4e8a6a08-3f01-430b-b806-a9d7cc696bc7)
same issue here :(

**Comment by huix9527** [comment]
Same issue here, animation don't even play correctly, who would pay for this product?

**Comment by TheRogue76** [comment]
Closing due to a lack of reproducible. Again, we are not related to Lottie files, so if you are facing an issue with their product, feel free to lodge a complaint with them.
