### ISSUE TITLE
New version Lottie-ios(4.4.2) minimum deployment target

### ISSUE THREAD

**Issue by finalquest** [lottie-react-native/lottie-react-native#1216]
### Description

lottie-ios has released the new version 4.4.2 forcing the minimum deployment target to 13.0.

The react-native-lottie podspec specifies **s.dependency 'lottie-ios', '~> 4.4.1'** and a minimum deployment target of 12.4
A clean install of react-native-lottie will download the new lottie-ios version and trigger a build error.

### Steps to Reproduce

1. Clean pods and lock
2. pod install
3. the version of lottie-ios installed is the new version 4.4.2.

**Expected behavior:** Compile without errors

**Actual behavior:** 

Showing All Errors Only
AnimationViewManagerModule.swift:1:8: Compiling for iOS 12.4, but module 'Lottie' has a minimum deployment target of iOS 13.0:

### React Native Environment
Clean react-native cli project

### Lottie Version

Version: ^6.6.0

**Comment by rafael-urena-yoke** [comment]
Having the same issue with expo EAS throwing the error when trying to build for iOS.

Expo version: sdk49

Lottie Version: ^6.7.0

**Comment by TheRogue76** [comment]
Hey @finalquest and @rafael-urena-yoke. Are you installing the `lottie-ios` package manually (via npm)? The LRN's pod spec does not specify going beyond 4.4.1, and as mentioned in the [migration guide](https://github.com/lottie-react-native/lottie-react-native/blob/master/MIGRATION-5-TO-6.md), you should remove any usage of it.
Let me know if that is NOT the case, and i will take a look.

**Comment by yuval-realy** [comment]
Hey @TheRogue76 
I'm dealing with the same error.
First time that I install lottie-react-native in version 6.7.0.
In Android everything is working great.

(I didn't install lottie-ios manually)
got this error in ios:

`❌  /node_modules/lottie-react-native/ios/LottieReactNative/AnimationViewManagerModule.swift:1:8: compiling for iOS 12.4, but module 'Lottie' has a minimum deployment target of iOS 13.0: /Developer/Xcode/DerivedData/realy-hfcahlcvqnqyjzatzgdegijbjonx/Build/Products/Debug-iphoneos/lottie-ios/Lottie.framework/Modules/Lottie.swiftmodule/arm64-apple-ios.swiftmodule`

**Comment by TheRogue76** [comment]
Alright. Patch Lottie React Native's podspec and make it explicitly 4.4.1 instead of ~> 4.4.1 and i will take a look this weekend

**Comment by finalquest** [comment]
> Alright. Patch package Lottie React Native's podspec and make it explicitly 4.4.1 instead of ~> 4.4.1 and i will take a look this weekend

forcing 4.4.1 in pods works as well.

I dont really know what the best approach is with this.
I dont really grasp the implications of increase the deployment target.
But if thats the simplest thing to do I can make a PR.

**Comment by TheRogue76** [comment]
> > Alright. Patch package Lottie React Native's podspec and make it explicitly 4.4.1 instead of ~> 4.4.1 and i will take a look this weekend
> 
> forcing 4.4.1 in pods works as well.
> 
> I dont really know what the best approach is with this. I dont really grasp the implications of increase the deployment target. But if thats the simplest thing to do I can make a PR.

The thing is I do not understand why the podspec is not being respected the way it is intended. It shouldn't matter that Lottie iOS 4.4.2 came out, it should always use the specifications given. This means either something in the setup is messed up, or my understanding of some part of the code is incorrect.
The implication of bumping the target is that the newer version would not be compatible with certain older versions of React Native out in circulation. Only ones whose target is iOS 13 and above.
Feel free to do a PR and set the version of Lottie iOS to exactly 4.4.1. This should not be a breaking change and can be rolled out easily as 6.7.1. Once we get a better understanding of what went wrong, we can make a decision to either bump Lottie to 4.4.2 and drop older iOS versions, or something else. Appreciate your guys's patience so far.

**Comment by TheRogue76** [comment]
Update: Fixed under https://github.com/lottie-react-native/lottie-react-native/pull/1217. 6.7.1 inbound. Since RN 73 is the first one to bump the iOS target to 13, I will hold off on bumping to 4.4.2 for now until we decide to move the support window for React Native version to minimum 73, or if we do it beforehand, I will make sure to note it in the release notes so people know. Feel free to mark the issue as closed as soon as the release is available

**Comment by TheRogue76** [comment]
https://github.com/lottie-react-native/lottie-react-native/releases/tag/v6.7.1
