### ISSUE TITLE
React-native 074 pod install error 

### ISSUE THREAD

**Issue by rodrigodiasf1984** [lottie-react-native/lottie-react-native#1225]
### Description

I'm getting this error when i do pod install: 

[!] The following Swift pods cannot yet be integrated as static libraries:

The Swift pod `lottie-react-native` depends upon `RCT-Folly`, which does not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.

if i add the **use_modular_headers!** at the top of the Podfile i'm getting all these errors on Xcode
![image](https://github.com/lottie-react-native/lottie-react-native/assets/30758309/b12a8b8b-18ae-4c9e-bfe7-1237c145d663)

if i add the use_frameworks! :linkage => :static, please look at the image attached
![image](https://github.com/lottie-react-native/lottie-react-native/assets/30758309/3ef45e1d-e5ce-48ff-9d4e-8405f9cbcc24)

with the use_frameworks! :linkage => :static i was able to do pod install, but when compiling the project i've got the error at the image

This is my PodFile: 

`def node_require(script)  # Resolve script with node to allow for hoisting
  require Pod::Executable.execute_command('node', ['-p',
    "require.resolve(
      '#{script}',
      {paths: [process.argv[1]]},
    )", __dir__]).strip
end

node_require('react-native/scripts/react_native_pods.rb')
node_require('react-native-permissions/scripts/setup.rb')

platform :ios, min_ios_version_supported
prepare_react_native_project!

setup_permissions([
  'AppTrackingTransparency',
  'Bluetooth',
  'Calendars',
  'CalendarsWriteOnly',
  'Camera',
  'Contacts',
  'FaceID',
  'LocationAccuracy',
  'LocationAlways',
  'LocationWhenInUse',
  'MediaLibrary',
  'Microphone',
  'Motion',
  'Notifications',
  'PhotoLibrary',
  'PhotoLibraryAddOnly',
  'Reminders',
  'Siri',
  'SpeechRecognition',
  'StoreKit',
])

# React Native Maps dependencies

rn_maps_path = '../node_modules/react-native-maps'
pod 'react-native-google-maps', :path => rn_maps_path

pod 'Firebase', :modular_headers => true
pod 'FirebaseCore', :modular_headers => true
pod 'FirebaseCoreInternal', :modular_headers => true
pod 'GoogleUtilities', :modular_headers => true

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
  $RNFirebaseAsStaticFramework = true
end

target 'myapp' do
  config = use_native_modules!
  use_frameworks! :linkage => :static
  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'myappTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
  end
end
`

### Steps to reproduce

Create a project with react-native 0.74 CLI 
install lottie 
open ios folder and pod install 

Ps: cant add lottie at the snack

![image](https://github.com/lottie-react-native/lottie-react-native/assets/30758309/0fc94d14-6341-49e9-ae95-5927a6730f02)

### Snack or a link to a repository

https://snack.expo.dev/?platform=ios

### Lottie React Native version

6.7.2

### React Native version

0.74.0

### Platforms

iOS

### Workflow

React Native

### Architecture

Paper (Old Architecture)

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by TheRogue76** [comment]
> https://snack.expo.dev/?platform=ios

Hi @rodrigodiasf1984 

Your reproducible link is incorrect. Please provide the correct one, and we will take a look. Otherwise the issue will be closed automatically after some time.

**Comment by rodrigodiasf1984** [comment]
Hi @TheRogue76, i cant add the last version of the lottie on the snack, have you saw the error on the attached image?

**Comment by TheRogue76** [comment]
> Hi @TheRogue76, i cant add the last version of the lottie on the snack, have you saw the error on the attached image?

An image and a version are not really helpful when it comes to these things. I am missing a lot here, this is just a snippet of a section of your setup. I need a reproducible to be able to check things out.

**Comment by rodrigodiasf1984** [comment]
@TheRogue76  I've just create a repo, can you please take a look at?  

https://github.com/rodrigodiasf1984/rn074Test

1. run pod install 
2. build the project on Xcode
3. the error shows up

**Comment by TheRogue76** [comment]
@rodrigodiasf1984 That's not the error your reproducible is giving me:
<img width="1512" alt="Screenshot 2024-05-04 at 09 21 43" src="https://github.com/lottie-react-native/lottie-react-native/assets/40071952/9ee5c92a-9eb8-47c5-a113-23d8c4396238">

**Comment by SorooshDeveloper** [comment]
i get this error while doing pod install on react native 0.74.1 : 
`
[!] Error installing lottie-ios
[!] /usr/bin/git clone https://github.com/airbnb/lottie-ios.git /var/folders/10/q1z46hyj75dbvn03g6p2k1b00000gn/T/d20240506-35168-abvjti --template= --single-branch --depth 1 --branch 4.4.1

Cloning into '/var/folders/10/q1z46hyj75dbvn03g6p2k1b00000gn/T/d20240506-35168-abvjti'...
error: RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly: CANCEL (err 8)
error: 3529 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output

`


my podfile : 


`require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!
use_frameworks! :linkage => :static
$RNFirebaseAsStaticFramework = true

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'Soroosh' do
  use_expo_modules!
  post_integrate do |installer|
    begin
      expo_patch_react_imports!(installer)
    rescue => e
      Pod::UI.warn e
    end
  end
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'SorooshTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
  end
end
`

**Comment by matinzd** [comment]
Your Podfile is not configured properly and it has nothing to do with lottie-react-native. @rodrigodiasf1984 

You can apply this patch for the fix on your reproducible:

```diff
diff --git a/ios/Podfile b/ios/Podfile
index d75e5d1..77e26a8 100644
--- a/ios/Podfile
+++ b/ios/Podfile
@@ -35,15 +35,6 @@ setup_permissions([
   'StoreKit',
 ])
 
-# React Native Maps dependencies
-
-rn_maps_path = '../node_modules/react-native-maps'
-pod 'react-native-google-maps', :path => rn_maps_path
-
-pod 'Firebase', :modular_headers => true
-pod 'FirebaseCore', :modular_headers => true
-pod 'FirebaseCoreInternal', :modular_headers => true
-pod 'GoogleUtilities', :modular_headers => true
 
 linkage = ENV['USE_FRAMEWORKS']
 if linkage != nil
@@ -54,13 +45,23 @@ end
 
 target 'rn074andLottie' do
   config = use_native_modules!
-  use_frameworks! :linkage => :static
   use_react_native!(
     :path => config[:reactNativePath],
     # An absolute path to your application root.
     :app_path => "#{Pod::Config.instance.installation_root}/.."
   )
 
+  # React Native Maps dependencies
+
+  rn_maps_path = '../node_modules/react-native-maps'
+  pod 'react-native-google-maps', :path => rn_maps_path
+
+  pod 'Firebase', :modular_headers => true
+  pod 'FirebaseCore', :modular_headers => true
+  pod 'FirebaseCoreInternal', :modular_headers => true
+  pod 'GoogleUtilities', :modular_headers => true
+
+
   target 'rn074andLottieTests' do
     inherit! :complete
     # Pods for testing
```

Then you'll need to run this in your ios folder:


```
USE_FRAMEWORKS=static bundle exec pod install
```

<img width="1383" alt="Screenshot 2024-05-09 at 02 14 02" src="https://github.com/lottie-react-native/lottie-react-native/assets/24797481/e307a372-af7a-429b-a236-e51bbcede378">

I am gonna close this issue.
