### ISSUE TITLE
lottie-ios 4.4.3 not supported

### ISSUE THREAD

**Issue by t1gu1** [lottie-react-native/lottie-react-native#1229]
### Description

If I update lottie-ios to use the latest `4.4.3`, i got that message.
So i keep using the `4.4.1`.

![image](https://github.com/lottie-react-native/lottie-react-native/assets/12479055/6cbff42b-a093-4da1-9032-e64064f1112d)

### Steps to reproduce

1. Install the latest `lottie-ios` `4.4.3`
2. Use the latest `lottie-react-native` `6.7.2`
3. When done, install npm packages and then install ios pods

### Snack or a link to a repository

https://snack.expo.dev/okY_gd5lgE7QPHt_XuzZm

### Lottie React Native version

6.7.2

### React Native version

0.72.10

### Platforms

iOS

### Workflow

React Native

### Architecture

Paper (Old Architecture)

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by palexs** [comment]
I'm having the same issue.

**Comment by maksim-romanov** [comment]
Same issue

**Comment by TheRogue76** [comment]
Hi. As mentioned in the [migration guide](https://github.com/lottie-react-native/lottie-react-native/blob/master/MIGRATION-5-TO-6.md), you should not be installing Lottie iOS manually anymore. Lottie React Native now decides its own Lottie version requirement (Like how it handles it in Android), specifically for cases like 4.4.2, and 4.4.3, where the iOS requirement has been bumped. Please remove it from your package jsons, and you will be good to go.

**Comment by t1gu1** [comment]
Good to know. Thanks!
