### ISSUE TITLE
[Android | Expo 51 | RN 0.74.1] newArchEnabled = true; parseSync is not a function

### ISSUE THREAD

**Issue by MikhailR1337** [lottie-react-native/lottie-react-native#1233]
### Description

I am trying to build android app -> npx expo run:android with newArchEnabled=true
I got an error
<img width="575" alt="image" src="https://github.com/lottie-react-native/lottie-react-native/assets/72802785/44312fd1-fa24-451e-870d-4942c849cb06">

### Steps to reproduce

1. Install the latest lottie-react-native 6.7.2
2. set newArchEnabled=true on gradle.properties file
3. start npx expo run:android

### Snack or a link to a repository

https://snack.expo.dev/@mikhailr1337/lottie-react-native

### Lottie React Native version

6.7.2

### React Native version

0.74.1

### Platforms

Android

### Workflow

React Native

### Architecture

Fabric (New Architecture)

### Build type

None

### Device

Android emulator

### Acknowledgements

Yes

**Comment by shubhamdeol** [comment]
Thanks for opening this issue. I am also facing same issue.

**Comment by shubhamdeol** [comment]
I was able to fix this using
https://github.com/expo/expo/issues/28494#issuecomment-2081770811

**Comment by matinzd** [comment]
Seems like an issue with codegen and not related to just lottie. Please refer to https://github.com/expo/expo/issues/28494#issuecomment-2081770811.
