### ISSUE TITLE
Closing the loop: We believe this was an issue with the lottiefiles.com exporter, and not an issue with the iOS and Android renderer implementations. The LottieFiles team deployed a fix for this on their end.

### ISSUE THREAD

**Issue by omartamer-git** [lottie-react-native/lottie-react-native#1236]
Closing the loop: We believe this was an issue with the lottiefiles.com exporter, and not an issue with the iOS and Android renderer implementations. The LottieFiles team deployed a fix for this on their end.

_Originally posted by @calda in https://github.com/lottie-react-native/lottie-react-native/issues/1194#issuecomment-2155487092_

Hello! This does indeed seem to be fixed for exporting the default color palette for any animation. However, I experienced the same issue again when I chose a different color palette and exported that.

If you guys can alert the lottiefiles.com team about that as well, please!

Thanks a lot for your effort maintaining this repo.

**Comment by TheRogue76** [comment]
Hi,
As mentioned in the issue, we (the maintainers of Lottie React Native) are not affiliated and don't have contact with the lottie files people. I would recommend either using their support system https://help.lottiefiles.com/hc/en-us. You can also mention it on the Lottie iOS or Lottie Android repos, but i would highly recommend just going directly to the source.
