### ISSUE TITLE
[iOS] No support for Xcode 16 beta

### ISSUE THREAD

**Issue by TechXTT** [lottie-react-native/lottie-react-native#1237]
### Description

After Updating to macOS Sequoia I figured that Xcode 15 is not supported, therefore I installed Xcode 16 beta. Upon building the application for iOS, Xcode returned errors with the following format : 'CA...' is only available in iOS 12.0 or newer.
<img width="1209" alt="Screenshot 2024-06-12 at 13 23 12" src="https://github.com/lottie-react-native/lottie-react-native/assets/71842793/e8f655cf-f544-4bd0-8072-9432dbab78e0">
As you could probably guess, I wasn't building for a version below iOS 12.0, and this error hasn't appeared before.
My guess is that as iOS 18.0 is an available version for this Xcode build, that CALayer & etc... that this is the basic error message for an unsupported version.

### Steps to reproduce

1. Update macOS to macOS Sequoia Developer Beta
2. Install Xcode 16 beta (as it is the only supported Xcode version)
3. Try building a version to run to simulator or for archiving

### Snack or a link to a repository

https://snack.expo.dev/j1p75QY3gbOHjnEcG037V

### Lottie React Native version

6.7.2

### React Native version

0.72.4

### Platforms

macOS

### Workflow

React Native

### Architecture

Paper (Old Architecture)

### Build type

Debug app & dev bundle

### Device

iOS simulator

### Acknowledgements

Yes

**Comment by TechXTT** [comment]
@UgurGumushan 
I may have a fix, currently lottie-react-native is using lottie-ios as it's iOS module, the version of lottie-ios currently being used is 4.4.1, the latest is 4.4.3, after updating the required version and deployment target I was able to build it.
Steps to fix:
1. node_modules/lottie-react-native/lottie-react-native.podspec:(lines 26-36)
`
  s.ios.deployment_target   = '13.0' # Change from 12.4 to 13.0
  s.osx.deployment_target   = '10.12'
  s.tvos.deployment_target  = '12.4'

  s.source                  = { :git => "https://github.com/lottie-react-native/lottie-react-native.git", :tag => "v#{s.version}" }
  s.source_files            = "ios/**/*.{h,m,mm,swift}"
  s.resource_bundles = {
    'Lottie_React_Native_Privacy' => ['ios/PrivacyInfo.xcprivacy'],
  }

  s.dependency 'lottie-ios', '4.4.3' # Change from 4.4.1 to 4.4.3
`
2. Reinstall pods

Afterwards it should be able to build

**Comment by UgurGumushan** [comment]
> @UgurGumushan I may have a fix, currently lottie-react-native is using lottie-ios as it's iOS module, the version of lottie-ios currently being used is 4.4.1, the latest is 4.4.3, after updating the required version and deployment target I was able to build it. Steps to fix:
> 
> 1. node_modules/lottie-react-native/lottie-react-native.podspec:(lines 26-36)
> 
> ```
>   s.ios.deployment_target   = '13.0' # Change from 12.4 to 13.0
>   s.osx.deployment_target   = '10.12'
>   s.tvos.deployment_target  = '12.4'
> 
>   s.source                  = { :git => "https://github.com/lottie-react-native/lottie-react-native.git", :tag => "v#{s.version}" }
>   s.source_files            = "ios/**/*.{h,m,mm,swift}"
>   s.resource_bundles = {
>     'Lottie_React_Native_Privacy' => ['ios/PrivacyInfo.xcprivacy'],
>   }
> 
>   s.dependency 'lottie-ios', '4.4.3' # Change from 4.4.1 to 4.4.3
> ```
> 
>  2. Reinstall pods
> 
> Afterwards it should be able to build

Thank you. I confirm this works.

**Comment by TheRogue76** [comment]
Hello everyone,

yes, Switching over the minimum target to iOS 13 will fix this specific issue, however it is considered a breaking change (since it is not compatible with older RN versions which target iOS 12.4, it only works with 73 and 74) which is why we didn't bump to lottie-ios 4.4.3. I'm guessing this is inevitable, since it is happening on Xcode and that will be out of beta relatively soon. I'll write a review on your PR @TechXTT

**Comment by UgurGumushan** [comment]
> Hello everyone,
> 
> yes, Switching over the minimum target to iOS 13 will fix this specific issue, however it is considered a breaking change (since it is not compatible with older RN versions which target iOS 12.4, it only works with 73 and 74) which is why we didn't bump to lottie-ios 4.4.3. I'm guessing this is inevitable, since it is happening on Xcode and that will be out of beta relatively soon. I'll write a review on your PR @TechXTT

It is breaking either way. (Breaking non-change)
maybe you can release the new one as 4.5.0 and offer fixes on 4.4.x
