### ISSUE TITLE
Lottie animation glitch on android

### ISSUE THREAD

**Issue by kareem-adel** [lottie-react-native/lottie-react-native#1250]
### Description

https://github.com/lottie-react-native/lottie-react-native/assets/10797596/cc55557e-4ff8-41b6-a44b-754586caa92e

As shown in the video above, the animation shows a glitch in all the app animations in android only after react native new architecture upgrade enabled with bridgeless enabled.

### Steps to reproduce

use LottieView component as documented.

### Snack or a link to a repository

https://snack.expo.io/

### Lottie React Native version

6.7.2

### React Native version

0.74.3

### Platforms

Android

### Workflow

React Native

### Architecture

Fabric (New Architecture)

### Build type

Debug app & dev bundle

### Device

Android emulator

### Acknowledgements

Yes

**Comment by kareem-adel** [comment]
@TheRogue76 What information is needed ?

**Comment by TheRogue76** [comment]
1. A reproducible (will not be able to do anything without this, and https://snack.expo.io/ is most certainly not a repro)
2. More info. You mention `the animation shows a glitch in all the app animations in android only after react native new architecture upgrade enabled with bridgeless enabled.`. Do these animations work fine if you turn off the new arch, or did you experience the issue when you went from V5 to V6? If it is from V5 to V6, did you try the render mode prop, as mentioned in the [migration guide](https://github.com/lottie-react-native/lottie-react-native/blob/master/MIGRATION-5-TO-6.md)?
