### ISSUE TITLE
Blur effects on lottie files don't work in React Native

### ISSUE THREAD

**Issue by jvgeee** [lottie-react-native/lottie-react-native#1256]
### Description

I have a lottie animation with has a blur effect added to it. You can see the animation [here](https://github.com/jvgeee/expo-camera-bugs/blob/main/assets/lottie/header_gradient.json), and you can preview it in the LottieFiles previewer to view the effect.

When I play the file with lottie-react-native, the blur doesn't work, and I just see two solid orbs floating.

Also note: This is a longstanding issue that I've had with lottie-react-native, not just in the latest versions. I've looked at the feature comparison table and it says that gaussian blur is available on Android, but this isn't the case for me

### Steps to reproduce

1. Create a lottie file with a blur effect
2. Load it into Lottie React Native
3. Notice how it doesn't blur

### Snack or a link to a repository

https://github.com/jvgeee/expo-camera-bugs

### Lottie React Native version

6.7.0

### React Native version

0.74.1

### Platforms

Android, iOS, Web

### Workflow

Expo Dev Client

### Architecture

Paper (Old Architecture)

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by TheRogue76** [comment]
I tested your animation. It appears you are using layer effects, which is not supported. 
<img width="1674" alt="Screenshot 2024-09-21 at 11 29 12" src="https://github.com/user-attachments/assets/3912e249-24e3-4a5b-b165-8c2e6f080513">
Just to be extra sure, i ran it on a pure Android project as well, which is using Lottie Android directly, with the same resultÖ
<img width="498" alt="Screenshot 2024-09-21 at 11 28 24" src="https://github.com/user-attachments/assets/f401f2b4-521d-4af3-83da-adb631762d8e">
