### ISSUE TITLE
java.lang.IllegalStateException: Underflow in restore - more restores than saves - com.airbnb.lottie.model.layer.ImageLayer.drawLayer(ImageLayer.java:58)

### ISSUE THREAD

**Issue by akash13625** [lottie-react-native/lottie-react-native#1258]
### Description

We are facing a native crash for when rendering lottie in our App. We have yet not being able to identify when this crash is occuring. Only that, it is occurring of users with Vivo device.
![Screenshot 2024-07-10 at 5 26 14 PM](https://github.com/lottie-react-native/lottie-react-native/assets/151954928/55ff3f38-4ea2-4cee-9463-43d009e5e03f)
Attaching screenshot of firebase crashlytics for this crash. 
![Screenshot 2024-07-10 at 5 26 38 PM](https://github.com/lottie-react-native/lottie-react-native/assets/151954928/8bcf4ce4-86bd-451f-84ed-11a33445bb9a)

Please see how we can solve this issue.
I found a similar issue in lottie-android repo. But not in react native.
There, we have option to turn on safeMode for such useCases, but that option is not propogated to react native. Please tell if it's possible to do that here, as it will help to turn that off from javascript only.

### Steps to reproduce

NA

### Snack or a link to a repository

NA

### Lottie React Native version

6.5.1

### React Native version

0.71.15

### Platforms

Android

### Workflow

React Native

### Architecture

Paper (Old Architecture)

### Build type

Release app & production bundle

### Device

Real device

### Acknowledgements

Yes

**Comment by TheRogue76** [comment]
Hi @akash13625.  I wrote a PR for exposing the prop to RN. Once it is merged, it will go out with the next release (which will be in a while). If you want to try it out, feel free to use what i have written in the PR and use patch-package to test it out to see if it fixes your issue

**Comment by TheRogue76** [comment]
This is now resolved in V7 With the new `enableSafeModeAndroid`
