### ISSUE TITLE
Animation is broken on IOS

### ISSUE THREAD

**Issue by shakhbozmn** [lottie-react-native/lottie-react-native#1263]
### Description

All animations from lottie.com is broken when i import to my react native project,

![Screenshot 2024-07-18 at 12 54 05 AM](https://github.com/user-attachments/assets/977022e0-a5d4-43ba-b12c-7b5c62e9f912)

the same animation on lottie.com
![Screenshot 2024-07-18 at 12 54 46 AM](https://github.com/user-attachments/assets/a13ebf4b-f73a-454c-a673-2d36db610cc1)

### Steps to reproduce

I provided the snack example where the issue can be produced

1. install the package "lottie-react-native": "6.5.1"
2. run with expo sdk version 50
3. see the broken lottie file

### Snack or a link to a repository

https://snack.expo.dev/@shakhbozms/react-native-lottie-view

### Lottie React Native version

6.5.1

### React Native version

0.73.6

### Platforms

iOS

### Workflow

React Native

### Architecture

Paper (Old Architecture)

### Build type

Debug app & dev bundle

### Device

iOS simulator

### Acknowledgements

Yes

**Comment by jaydeep-pat377** [comment]
same issue.
![Screenshot 2024-07-18 at 12 37 18 PM](https://github.com/user-attachments/assets/f5cd4ed6-769f-4cd8-bdbf-62cd8ecd652d)

**Comment by denis-karviga** [comment]
https://github.com/airbnb/lottie-ios/issues/2345#issuecomment-2016513965

@shakhbozmn see here, looks like this is an issue with lottiefiles.com exporter https://github.com/airbnb/lottie-ios/issues/2345#issuecomment-2155486289

**Comment by shakhbozmn** [comment]
@denis-karviga thanks for the response, you're right this is not issue with the library, actually!
