### ISSUE TITLE
Lottie crashes on android with react native 0.74.3

### ISSUE THREAD

**Issue by rafaelsevla** [lottie-react-native/lottie-react-native#1267]
### Description

I just installed the latest version of lottie (npm i --save lottie-react-native) and run android and it crashes when opening the app.

I try to install the old version (npm i --save lottie-react-native@5.1.6 lottie-ios@3.4.0) and run android and it also happens... Anyone else having the same problem? Do I need to add something to the Android folder/file?

It works fine on iOS (I tested it with 5.1.6)

### Steps to reproduce

npm install lottie-react-native

npm start

npm run android

### Snack or a link to a repository

just create repo and install lottie

### Lottie React Native version

5.1.6 and 6.7.2

### React Native version

0.74.3

### Platforms

Android

### Workflow

React Native

### Architecture

Paper (Old Architecture)

### Build type

None

### Device

Android emulator

### Acknowledgements

Yes

**Comment by matinzd** [comment]
Hey!

Can you try sharing the logcat output of the native crash with Android Studio?

**Comment by rafaelsevla** [comment]
Sorry! I test today again and it works fine! 


Closing issue 😀
