### ISSUE TITLE
Execution failed for task ':lottie-react-native:generateReleaseRFile'

### ISSUE THREAD

**Issue by DoHue97** [lottie-react-native/lottie-react-native#1271]
### Description

i try to run **./gradle assembleRelease** for build apk release and i have the error, anyone help this? 

### Steps to reproduce

Hi All,
i try to run **./gradle assembleRelease** for build apk release and i have the error, anyone help this? 
Execution failed for task ':lottie-react-native:generateReleaseRFile'.
> Could not resolve all files for configuration ':lottie-react-native:releaseCompileClasspath'.
   > Failed to transform react-native-0.71.0-rc.0-release.aar (com.facebook.react:react-native:0.71.0-rc.0) to match attributes {artifactType=android-symbol-with-package-name, com.android.build.api.attributes.BuildTypeAttr=release, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-api}.
      > Could not find react-native-0.71.0-rc.0-release.aar (com.facebook.react:react-native:0.71.0-rc.0).
        Searched in the following locations:
            https://jcenter.bintray.com/com/facebook/react/react-native/0.71.0-rc.0/react-native-0.71.0-rc.0-release.aar

### Snack or a link to a repository

tesst

### Lottie React Native version

5.1.6

### React Native version

0.66.3

### Platforms

Android, iOS, macOS

### Workflow

React Native

### Architecture

Paper (Old Architecture)

### Build type

Release app & dev bundle

### Device

None

### Acknowledgements

Yes

**Comment by DoHue97** [comment]
here is my build.gradle and i added implementation project(':lottie-react-native') in the android/build.gradle file
![image](https://github.com/user-attachments/assets/0c942f9a-f28b-47c4-a5f8-4640ff1066c9)

**Comment by matinzd** [comment]
Please upgrade to the latest version and try again.

**Comment by TheRogue76** [comment]
Unsupported version. Closing
