### ISSUE TITLE
Animation getting stuck

### ISSUE THREAD

**Issue by bhavya-verma28** [lottie-react-native/lottie-react-native#1278]
### Description

I'm trying to render a LottieView, but it gets stuck while loading on the screen. It briefly starts, then freezes, and only resumes playing when there's an interaction with the screen.

### Steps to reproduce

Added LottieView source, autoplay,loop: false,style: flex:1 

### Snack or a link to a repository

-

### Lottie React Native version

6.7.2

### React Native version

0.73.1

### Platforms

Android

### Workflow

React Native

### Architecture

Paper (Old Architecture)

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by TheRogue76** [comment]
No example, no logs of ADB. Can not help without it
