### ISSUE TITLE
[IOS] Module map files not found when upgrading to v6

### ISSUE THREAD

**Issue by jerry7411** [lottie-react-native/lottie-react-native#1283]
### Description

I'm trying to upgrade from v5 to v6 and got this issue when running iOS debug mode (it also happened when trying to build a release too) .  A lot of module map files haven't been found.
Do anyone know what issue is?

module map file '.../Build/Products/Debug-iphonesimulator/FirebaseCoreInternal/FirebaseCoreInternal.modulemap' not found
module map file '.../Build/Products/Debug-iphonesimulator/FirebaseCrashlytics/FirebaseCrashlytics.modulemap' not found
module map file '.../Build/Products/Debug-iphonesimulator/lottie-ios/Lottie.modulemap' not found
module map file '.../Build/Products/Debug-iphonesimulator/lottie-react-native/lottie_react_native.modulemap' not found
module map file '.../Build/Products/Debug-iphonesimulator/react-native-geolocation-service/react_native_geolocation_service.modulemap' not found
Command SwiftGeneratePch emitted errors but did not return a nonzero exit code to indicate failure

### Steps to reproduce

Change from v5 to v6

### Snack or a link to a repository

None

### Lottie React Native version

6.7.2

### React Native version

0.74.5

### Platforms

iOS

### Workflow

React Native

### Architecture

Paper (Old Architecture)

### Build type

Debug app & dev bundle

### Device

iOS simulator

### Acknowledgements

Yes

**Comment by matinzd** [comment]
Sorry this is not related to lottie. As you can see [here](https://github.com/lottie-react-native/lottie-react-native/actions/workflows/ios-fabric-build.yml) and [here](https://github.com/lottie-react-native/lottie-react-native/actions/workflows/ios-paper-build.yml) builds are working on CI with different xcode versions. There might be some problems with your environment. If you can reproduce this in a separate reproducible project let us know. Closing this for now as it's invalid.
