### ISSUE TITLE
Requires deprecated `@dotlottie/react-player`

### ISSUE THREAD

**Issue by gavrilikhin-d** [lottie-react-native/lottie-react-native#1284]
### Description

On web, your library requires deprecated `@dotlottie/react-player` (in favour of `@lottiefiles/dotlottie-react`)

### Steps to reproduce

1. Install your lib
2. try run web without @dotlottie/react-player

### Snack or a link to a repository

https://snack.expo.dev/LO0oqtS1YUX1vF0O9JrK3

### Lottie React Native version

7.0.0

### React Native version

0.75.1

### Platforms

Web

### Workflow

React Native

### Architecture

Fabric (New Architecture)

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by p29hieu** [comment]
You need to install `@dotlottie/react-player` to run on web.
```
yarn add @dotlottie/react-player
```

**Comment by gavrilikhin-d** [comment]
Yes, I know. This library is deprecated and shouldn't be required.
