### ISSUE TITLE
CocoaPods could not find compatible versions for pod "lottie-react-native":

### ISSUE THREAD

**Issue by AndreyBernardoni** [lottie-react-native/lottie-react-native#1285]
### Description

On Android, it works perfectly. 

But when running `pod install`

I receive the following alert:
```
[!] The platform of the target `Medical` (iOS 12.4) may not be compatible with `lottie-ios (4.5.0)` which has a minimum requirement of iOS 13.0 - macOS 10.15 - tvOS 13.0 - visionOS 1.0.

[!] The platform of the target `Medical` (iOS 12.4) may not be compatible with `lottie-react-native (7.0.0)` which has a minimum requirement of iOS 13.4 - macOS 10.15 - tvOS 13.0 - visionOS 1.0.
```

Ignoring the warning, I run yarn start and press the I key to run on my iPhone simulator and I get stuck in this terminal:

```
info 💡 Tip: Make sure that you have set up your development environment correctly, by running react-native doctor. To read more about doctor command visit: https://github.com/react-native-community/cli/blob/main/packages/cli-doctor/README.md#doctor 

Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -workspace Medical.xcworkspace -configuration Debug -scheme Medical -destination id=2B5DBF7B-3DA3-4917-BC89-D8F9E25D9BD2

User defaults from command line:
    IDEPackageSupportUseBuiltinSCM = YES

Prepare packages

ComputeTargetDependencyGraph
note: Building targets in dependency order
note: Target dependency graph (90 targets)
    Target 'Medical' in project 'Medical'
        ➜ Implicit dependency on target 'Pods-Medical' in project 'Pods' via file 'Pods_Medical.framework' in build phase 'Link Binary'

[VARIOUS OTHER IMPLICIT DEPENDENCY]

        ➜ Implicit dependency on target 'React-jsiexecutor' in project 'P[]
```

excerpt from my podfile:
`platform :ios, min_ios_version_supported`

changing to:
`platform :ios, "14.0"`
made the alerts disappear, but I'm still stuck in the terminal

### Steps to reproduce

1. Follow the setup instructions
2. On `pod install` happens alerts
3. `yarn start` and press `i`

### Snack or a link to a repository

https://github.com/AndreyBernardoni/Medical-React-Native

### Lottie React Native version

ˆ7.0.0

### React Native version

0.72.14

### Platforms

Android, iOS

### Workflow

React Native

### Architecture

Paper (Old Architecture)

### Build type

None

### Device

iOS simulator

### Acknowledgements

Yes

**Comment by TheRogue76** [comment]
Hi @AndreyBernardoni,

Lottie RN 7 is [no longer supporting RN 72 and below.](https://github.com/lottie-react-native/lottie-react-native/releases/tag/v7.0.0). One of the reasoning was that RN 72 and below need iOS targets below 13 which Lottie iOS no longer supports
