### ISSUE TITLE
[WEB] after animation ends restarts to start position instead of staying in end position

### ISSUE THREAD

**Issue by alarm109** [lottie-react-native/lottie-react-native#1290]
### Description

On iOS it works correctly when the animation ends the icon stays in the end position:

https://github.com/user-attachments/assets/879df31b-99bf-4862-af39-37e02bf5008f

On Web after the animation ends it restarts to the start position:

https://github.com/user-attachments/assets/3c453477-cbfa-4e9c-8242-70482b82f3cd

As a workaround I could take the Ref and manually start it and stop, so it ends where I want. But it would be nice if it would work the same on the web as on iOS. 

### Steps to reproduce

```ts
    <LottieView source={animationSource} autoPlay loop={false} />
```
```json
{
    "@dotlottie/react-player": "^1.6.19",
    "@lottiefiles/dotlottie-react": "^0.9.1",
    "@lottiefiles/react-lottie-player": "^3.5.4",
    "lottie-react-native": "7.0.0",
}
```

### Snack or a link to a repository

https://snack.expo.dev/@matt_000/animation-stops-lottie

### Lottie React Native version

7.0.0

### React Native version

0.74.3

### Platforms

iOS, Web

### Workflow

Expo Dev Client

### Architecture

Paper (Old Architecture)

### Build type

Debug app & dev bundle

### Device

None

### Acknowledgements

Yes

**Comment by kaumac** [comment]
I'm having the same issue...
There's another lottie react library (don't remember which) that allows you to select the ending frame, I think that'd be a good improvement. But even if it stays at the last frame would be better than going back to the initial frame...

**Comment by kaumac** [comment]
@alarm109 the solution I found for now is to use the imperative control api instead of the "autoPlay" prop.
If you manually play the animation apparently this issue doesn't happen. Not ideal, but works for now.

**Comment by alarm109** [comment]
Yes, I currently solved this problem by manually running the animation, but is more of a workaround for this problem. In my opinion the web and mobile should work the same.

```ts
  useEffect(() => {
    animationRef.current?.play(0, 38);
  }, []);

  return (
    <LottieView ref={animationRef} source={animationSource} loop={false} />
  );
```

**Comment by adamhari** [comment]
The web implementation was re-written with a new player library in `7.1.0`. Can you confirm whether or not this is still an issue after upgrading?

**Comment by alarm109** [comment]
@adamhari, it's working correctly now with version `7.1.0`. Great work 🚀
