### ISSUE TITLE
Unimplemented component : <LottieAnimationView>

### ISSUE THREAD

**Issue by abdullah-tsx** [lottie-react-native/lottie-react-native#1292]
### Description

following documentation getting error on iOS18
Unimplemented component : <LottieAnimationView>
![image](https://github.com/user-attachments/assets/985c1186-5d9f-484c-ac23-8b27774e34e8)

### Steps to reproduce

1. Follow installation guide
yarn add lottie-react-native
npx pod install
`cd ios && RCT_NEW_ARCH_ENABLED=1 bundle exec pod install`
```
import LottieView from 'lottie-react-native';
import React from 'react';

const SplashScreen = () => {
	return (
		<LottieView
			source={require('../../assets/animations/splash.json')}
			autoPlay={true}
			renderMode={'AUTOMATIC'}
			loop={true}
			style={{ flex: 1, width: '100%', height: '100%' }}
		/>
	);
};

export default SplashScreen;

```

### Snack or a link to a repository

https://github.com/abdullah-tsx/lottie-bug

### Lottie React Native version

7.0.0

### React Native version

0.75.4

### Platforms

Android, iOS

### Workflow

React Native

### Architecture

Fabric (New Architecture)

### Build type

Debug app & dev bundle

### Device

Real device

### Acknowledgements

Yes

**Comment by matinzd** [comment]
Hey!

We cannot access your repo link. Can you please fix that?

**Comment by abdullah-tsx** [comment]
> Hey!
> 
> We cannot access your repo link. Can you please fix that?

I have updated the link.

**Comment by brunocentanaro** [comment]
Same for me using ```expo 52 preview``` with ```new arch```

**Comment by matinzd** [comment]
Please remove `lottie-ios` from the list of your dependencies.

**Comment by brunocentanaro** [comment]
It worked for me now, maybe I had to remove the ios folder and run the prebuild again. I did not have lottie-ios

**Comment by savourylie** [comment]
Having the same issue here with Expo 52.

**Comment by matinzd** [comment]
Which version do you have? @savourylie

**Comment by catmans1** [comment]
Having the same issue
```
"lottie-react-native": "^7.1.0",
"react": "18.3.1",
"react-native": "0.76.0",
```
Do need to another setup after install in react native?

**Comment by matinzd** [comment]
Are you using Expo Go? If you are using Expo Go you need to switch to Expo Development Client.

**Comment by catmans1** [comment]
@matinzd No, I don't use expo
React Native only

**Comment by saqlaan** [comment]
Having the same issue with expo go

**Comment by matinzd** [comment]
> Having the same issue with expo go

As I mentioned earlier, you can't use Expo Go with this library if you want to have new architecture turned on.

**Comment by matinzd** [comment]
I ran your project (@abdullah-tsx ) again it's working as expected. Everyone please make sure to run `pod install` before running the app. To make sure that lottie is installed check `Podfile.lock` and see if `lottie-react-native` is listed there. Then make sure to build the app with xcode. 

https://github.com/user-attachments/assets/dcab8ce1-3ed1-4817-9381-a75b9a78f741

I am closing this as I could not reproduce this issue.

**Comment by catmans1** [comment]
For projects using react native, if you run on ios then you have to install the `lottie-ios` library, if android then I think add the `lottie-android` library (I haven't tested this case)

```
"lottie-ios": "^4.5.0",
"lottie-react-native": "^7.1.0",
"react": "18.3.1",
"react-native": "0.76.0",
```

**Comment by matinzd** [comment]
@catmans1 There's no need to manually install `lottie-ios` and `lottie-android` since this library automatically includes them as dependencies in the `podspec` and `build.gradle` files.

**Comment by catmans1** [comment]
@matinzd 
As you run the project (@abdullah-tsx ), I see It is using `lottie-ios`, 
https://github.com/abdullah-tsx/lottie-bug/blame/ea6a12229116905eb1d0e6cfaab3f1566e0aaa74/package.json#L36
could you run the project with remove `lottie-ios` lib and `pod install` again?

**Comment by catmans1** [comment]
It worked fine without install `lottie-ios` lib
```
"lottie-react-native": "^7.1.0",
"react": "18.3.1",
"react-native": "0.76.5"
```

**Comment by garima440** [comment]
> > Having the same issue with expo go
> 
> As I mentioned earlier, you can't use Expo Go with this library if you want to have new architecture turned on.

If i set the new architecture to false, would lottie work? is it that simple? or there is more nuance?

**Comment by matinzd** [comment]
Lottie is working with new architecture as well. You DO NOT need to set it to false.
