### ISSUE TITLE
[deprecated] please do not set `com.airbnb.android.react.lottie` in manifest but in build gradle instead

### ISSUE THREAD

**Issue by maapteh** [lottie-react-native/lottie-react-native#1296]
### Description

With react-native 0.76.0 i get this warning during builds (not influencing my app but still):
```
package="com.airbnb.android.react.lottie" found in source AndroidManifest.xml: /home/runner/work/.../node_modules/lottie-react-native/android/src/main/AndroidManifest.xml.
Setting the namespace via a source AndroidManifest.xml's package attribute is deprecated.
```

### Steps to reproduce

1. see https://github.com/lottie-react-native/lottie-react-native/blob/master/packages/core/android/src/main/AndroidManifest.xml#L2

### Snack or a link to a repository

none

### Lottie React Native version

7.0.0

### React Native version

0.76.0

### Platforms

Android

### Workflow

React Native

### Architecture

Paper (Old Architecture)

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by TheRogue76** [comment]
Yeah this was on purpose. Around the release of React Native 73, there was a conversation about depracating this property. The proper value was added [Here](https://github.com/lottie-react-native/lottie-react-native/blob/4406bc879aaa8a0440476380d8d02e8b45104764/packages/core/android/build.gradle#L38), but i agree, it's time to get rid of the manifest one.
