### ISSUE TITLE
[Question] How to get the current playback progress ? (dotLottie file + imperative API)

### ISSUE THREAD

**Issue by guval-gh** [lottie-react-native/lottie-react-native#1299]
### Description

Hi 👋

I'd like to use lottie to display animations lasting between 20 and 30 seconds.

To do it properly, I want to use dotLottie files for their lightness and I need the user to be able to control the animation: play, pause, see the playback progress, move the playback...

For dotlottie file, play, pause... it's ok and works good 👍:

```typescript
import React, { useRef } from "react";
import LottieView from "lottie-react-native";
import legoAnimation from "../../assets/animations/lego.lottie";
import { Pressable, View } from "react-native";
import { FontAwesome5 } from "@expo/vector-icons";

export default function AnimationWithImperativeApi() {
  const animationRef = useRef<LottieView>(null);

  const play = () => {
    animationRef.current?.play();
  };

  const pause = () => {
    animationRef.current?.pause();
  };

  const stop = () => {
    animationRef.current?.reset();
  };

  const playFromPosition = (position: number) => {
    animationRef.current?.play(position);
  };

  return (
    <View>
      <LottieView
        ref={animationRef}
        source={legoAnimation}
        style={{ width: "100%", height: "80%" }}
      />
        <Pressable onPress={play}>
            <FontAwesome5 name="play" size={25} />
        </Pressable>
        <Pressable onPress={pause}>
            <FontAwesome5 name="pause" size={25} />
        </Pressable>
        <Pressable onPress={stop}>
            <FontAwesome5 name="stop" size={25} />
        </Pressable>
        <Pressable onPress={() => playFromPosition(0.5)}>
            <FontAwesome5 name="forward" size={25} />
        </Pressable>
      </View>
  );
}
```

So, I looked at the api (https://github.com/lottie-react-native/lottie-react-native/blob/master/docs/api.md), but the `progress` and `duration` properties are made to set the values.

Also, in the example given in doc (https://github.com/lottie-react-native/lottie-react-native/tree/master?tab=readme-ov-file#usage) we can see that the `progress` is set and managed by React Native Animated but it's based on a custom and fixed duration value, not dynamic one from the lottie file:

```typescript
import React, { useEffect, useRef, Animated } from "react";
import { Animated, Easing } from "react-native";
import LottieView from "lottie-react-native";

const AnimatedLottieView = Animated.createAnimatedComponent(LottieView);

export default function ControllingAnimationProgress() {
  const animationProgress = useRef(new Animated.Value(0));

  useEffect(() => {
    Animated.timing(animationProgress.current, {
      toValue: 1,
      duration: 5000,
      easing: Easing.linear,
      useNativeDriver: false,
    }).start();
  }, []);

  return (
    <AnimatedLottieView
      source={require("../path/to/animation.json")}
      progress={animationProgress.current}
      style={{width: "100%", height: "100%"}}
    />
  );
}
```

To display an animation with progress bar, I need the current playback progress.

How can I get it right in my case ? Maybe I miss something

Thanks for the reading and help 🙏

### Steps to reproduce

(Not a bug to reproduce)
For the Snack, I created one but the hook useRef seems have some issues on Snack expo.

### Snack or a link to a repository

https://snack.expo.dev/2d6qoodKK1NY-wuTkBV5G

### Lottie React Native version

7.1.0

### React Native version

0.76.1

### Platforms

Android, iOS

### Workflow

React Native

### Architecture

Fabric (New Architecture)

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by christos-dematas** [comment]
Is there any update on this? Have you figured it out?

**Comment by guval-gh** [comment]
Hi @christos-dematas 

No, I haven't found anything for that.
But I don't need it anymore.

Originally, it was to optimize runtime files created with SVGator, but I'm going to go with Rive, which is more suited to my final needs.
