### ISSUE TITLE
add `scale` props

### ISSUE THREAD

**Issue by alikazemkhanloo** [lottie-react-native/lottie-react-native#446]
Hi, I wanted to use [this animation](https://lottiefiles.com/344-filter-button) in my app but the problem is there is lots of padding in the original animation. 
I tried to use `autoSize` and `resizeMode='cover'`, but no success,
my code is:
```JavaScript
const filter = require('../../assets/Filter2.json')
...
<LottieView
                source={filter}
                style={{height:'100%'}}
                speed={2.5}
                ref={(ref)=> this.filterAnimation = ref}
                resizeMode='cover'
                autoSize
                loop={false}
              />
```
if there was a scale prop, I could use that.
I guess it is available in lottie-android as in [this SO answer](https://stackoverflow.com/a/51637543/7787393)

**Comment by emilioicai** [comment]
We might introduce this feature after updating to the latest lottie-android

**Comment by WrathChaos** [comment]
@emilioicai 
Is there any improvement?

**Comment by WrathChaos** [comment]
@emilioicai Why did you close this issue? Is there a fix?

**Comment by emilioicai** [comment]
I closed it because it seemed to me it was quite stale. I will reopen if it's still an issue with the latest version

**Comment by WrathChaos** [comment]
I still could not use lottie because of this issue. Can you please tag me when you open a new one?

**Comment by emilioicai** [comment]
@WrathChaos I just reopened this one

**Comment by Tjerk-Haaye-Henricus** [comment]
Need this too 👍

**Comment by lallaheeee** [comment]
+1

**Comment by kamal-j** [comment]
+1

**Comment by arunim2405** [comment]
any updates?

**Comment by death14stroke** [comment]
Is this feature added? I am facing same issue with animation I am using
