### ISSUE TITLE
Using Animated.Value is choppy on Android

### ISSUE THREAD

**Issue by Tavaru5** [lottie-react-native/lottie-react-native#497]
### Description

On Android, when I try to animate my animation using an `Animated.Value` hooked up to the `progress` prop, it seems to only show individual frames, and doesn't smooth the animation in between. On iOS it looks smooth, and it also looks smooth on Android if I use 
```
ref={animation => {
    this.animation = animation;
}}
```
and call `this.animation.play()` in `componentDidMount`.

**Note:** I understand that I could make this issue less noticeable just by getting an animation with a higher frame count, but I don't want to have to increase the package size that much if I don't have to.

### Steps to Reproduce

I created a new React Native project using `react-native init` and installed lottie-react-native using `yarn add lottie-react-native` and `react-native link lottie-react-native`. I then updated App.js to be as follows:
```
import React, { Component } from 'react';
import {
  Platform,
  StyleSheet,
  Text,
  View,
  Animated,
  PanResponder
} from 'react-native';
import LottieView from 'lottie-react-native';

type Props = {};
export default class App extends Component<Props> {
  translateX = new Animated.Value(0);

  _panResponder = PanResponder.create({
    onMoveShouldSetPanResponderCapture: (evt, gesture) => true,
    onPanResponderMove: (e, { vx, dx }) => {
      const frameToFinger = 0 - dx / 2000;
      if (frameToFinger < 0) {
        this.translateX.setValue(0);
      } else if (frameToFinger > 1) {
        this.translateX.setValue(1);
      } else {
        this.translateX.setValue(0 - dx / 2000);
      }
    }
  });

  componentDidMount() {
    Animated.timing(this.translateX, { toValue: 1, duration: 10000 }).start();
  }

  render() {
    return (
      <LottieView
        progress={this.translateX}
        style={{ flex: 1 }}
        resizeMode="cover"
        source={require('./assets/animation.json')}
        {...this._panResponder.panHandlers}
      />
    );
  }
}
```
I copied one of the animations from the [example directory](https://github.com/react-native-community/lottie-react-native/tree/master/example/js/animations) into `'./assets/animation.json'`, and then ran the app using `react-native run-android`.

**Expected behavior:** I expected the animation to run smoothly from the start, and to also follow my finger smoothly if I touch the screen.

**Actual behavior:** The animation goes frame by frame without smoothing in between. Additionally, if I touch the screen and drag, I can very clearly see the differences between frames.

### Versions

```
├── @babel/core@7.4.5
├── @babel/runtime@7.4.5
├── babel-jest@24.8.0
├── jest@24.8.0
├── lottie-react-native@2.6.1
├── metro-react-native-babel-preset@0.54.1
├── node-pre-gyp@0.12.0 extraneous
├── react@16.8.3
├── react-native@0.59.8
└── react-test-renderer@16.8.3
```

**Comment by muhammad-asad-26** [comment]
Hi Team Lottie,
Is there any suggestions related to above mentioned issue. We are facing the same issue as described above in react native, on iOS our Adobe After Effects animations are working fine but on android the animations are very laggy and it's like something going on frame by frame. Our app is about to go to production but we have been delayed a lot just because of this issue.

Any help will be greatly appreciated.

Regards,
Muhammad Asad

**Comment by jarnove** [comment]
Try this: https://github.com/react-native-community/lottie-react-native/issues/333 (useNativeDriver). This fixed my issue.

**Comment by emilioicai** [comment]
I'm closing this as a version update should solve this issue.
