### ISSUE TITLE
Running the iOS example project fails

### ISSUE THREAD

**Issue by mpeterson2** [lottie-react-native/lottie-react-native#501]
### Description

Running the example project does not work. It seems like the [new](https://github.com/bachand/lottie-react-native/blob/39a205c134de6690bdeee7fa78bfbea67ce6a313/README.md#running-the-example-project) docs on how to get it running are incomplete, so I am following older instructions from [here](https://github.com/bachand/lottie-react-native/blob/39a205c134de6690bdeee7fa78bfbea67ce6a313/README.md#running-the-example-project).

### Steps to Reproduce

1. Clone the project fresh
2. Run `npm install`. This fails due to a syntax error and a lack of `.babelrc`. We can get around this by adding a `.babelrc` of `{"presets": ["react-native", "airbnb"]}`
2. Run `npm run build:pods`. This will fail due to the `Gemile` pinning an old version of `cocoapods`. To get passed this:
   1. Update the gemfile and `bundle install` to use a newer version of `cocoapods` (The version that created the `Gemfile.lock` is `1.6.1` and this will work.
3. Run `npm start`
4. Run `npm run:ios`
   2. There are a few imports in React that fail, I've hacked around them for now:
      1. `fishhook/fishhook.h` not found - Replace with `<React/fishhook.h>`
      2. `RCTAnimation/RCTValueAnimatedNode.h` file not found - Replace with `<React/RCTValueAnimatedNode.h`
5. The app will run, not load the bundle and close a few seconds after

**Expected behavior:** [What you expected to happen]
I should be able to run the scripts error free, the example app should run, load the bundle, and let me see examples.

**Actual behavior:** [What actually happened]
After a decent amount of hacking around, the example app will run, but never loads the bundle and closes/crashes shortly after.

### Versions
Master

**Comment by mrcarjul** [comment]
I just run into the same problem today, i solved it by building the project straight from xcode it sent an error about some pid then i cleaned the project and restarted the simulator/xcode, after i rebuild, and it worked, hope this helps meanwhile.

**Comment by emilioicai** [comment]
I'm closing this as a version update should solve this issue.
