### ISSUE TITLE
gradient stroke

### ISSUE THREAD

**Issue by airguide** [lottie-react-native/lottie-react-native#506]
### Description

After creating a shape with a gradient stroke, it does not show up on the device, if I remove the gradient stroke the circle is visible.

### Steps to Reproduce

1. Create a ellipse
2. Add a gradient stroke and export
3. run on device: does not show
4. remove the gradient stroke and add a stroke
5. run on device: shape visible

rn: 0.59.9
lottie-react-native: "^2.6.1",

**Comment by krystianpach** [comment]
+1

**Comment by artrayd** [comment]
+1

**Comment by chankakit** [comment]
+1

**Comment by vasyl-kovalchuk-eleks** [comment]
+1
