### ISSUE TITLE
Spin Wheel Animation - PNG not rotating with wheel

### ISSUE THREAD

**Issue by avinashlng1080** [lottie-react-native/lottie-react-native#510]
#55 # Description

So I have this JSON that an animator created for me to mimic a 'wheel of fortune' / spin-wheel animation.

The wheel spins but the images that were supposed to be on each segment does not spin along with the wheel.

Can you please give  me insights as to what may be wrong ?  It is the 'bodymovin' version used that it not compatible with react-native ?

### Steps to Reproduce

1. From a clean react native project, just install lottie-react-native.
2. Load the JSON in the Lottie component.
3. Add iOS images into Xcode under the resources folder and for android, create a lottie/spin folder under Android/../assets.
4. The component in your code will resemble the below: 

` <Lottie
        autoPlay
        imageAssetsFolder='lottie/spin'
        source={SpinJson}
        style={{ width, height }}
      />`

**Expected behavior:**
The image should be rotating with the wheel.

**Actual behavior:** [What actually happened]
The wheel spins but the images remain at the same position.

![Screenshot 2019-07-03 at 16 26 17](https://user-images.githubusercontent.com/43164508/60592602-08ddbd80-9db2-11e9-8376-dc8bf82db82c.png)

See attached JSON file: 
[spin copy.json.txt](https://github.com/react-native-community/lottie-react-native/files/3357860/spin.copy.json.txt)

### Versions
    "react-native": "0.59.8",
    "lottie-react-native": "^2.6.1",

**Comment by avinashlng1080** [comment]
@dryganets @ljharb @Kudo @orta  can you please guide me ?

**Comment by rocifier** [comment]
Hi, I have created the animation for this and we are still blocked by the issue. I have uploaded a simplified AEP file here to export the json from, if it helps: https://github.com/airbnb/lottie-android/issues/1338

**Comment by emilioicai** [comment]
I'm closing this as a version update should solve this issue.
