### ISSUE TITLE
Autolinking using rnpm is deprecated and will be removed

### ISSUE THREAD

**Issue by dcosmin2003** [lottie-react-native/lottie-react-native#518]
### Description

It seems that lottie package is using a deprecated method - rnpm - for autolinking.

### Steps to Reproduce

1. install react-native boilerplate
2. add lottie-react-native package
3. build

**Expected behavior:**
No warnings

**Actual behavior:** 
warn The following packages use deprecated "rnpm" config that will stop working from next release:
- lottie-react-native: https://github.com/airbnb/lottie-react-native#readme
Please notify their maintainers about it. You can find more details at https://github.com/react-native-community/cli/blob/master/docs/configuration.md#migration-guide

### Versions
RN 0.60.3
Lottie RN 2.6.1

**Comment by RWOverdijk** [comment]
I'm usually not one to comment on issues that can be +1'd but, it's been a while since this issue was created. What's the status?

**Comment by ivan-jorge001** [comment]
Do we have a. solution for this ?

**Comment by emilioicai** [comment]
I will assign this one to myself

**Comment by emilioicai** [comment]
I'm closing this as a version update should solve this issue.
