### ISSUE TITLE
build failes on release (android)

### ISSUE THREAD

**Issue by ganico** [lottie-react-native/lottie-react-native#520]
my build is working fine on debug but when I tried to build it on release I encounter this: 
"Execution failed for task ':lottie-react-native:verifyReleaseResources'.
> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android r
esource linking failed"

here's the versions that i'm using:
"lottie-ios": "^3.0.3",
"lottie-react-native": "^3.0.2",
"react": "^16.6.3",
"react-native": "^0.59.10",

my iOS is perfectly working but I used to link it manually to make it work, here in android i'm not quite sure what else do I need to do aside from adding it to the dependencies.
<img width="763" alt="Screenshot 2019-07-22 at 12 36 14" src="https://user-images.githubusercontent.com/7714293/61606526-52b51780-ac7d-11e9-9b0b-f0c39815043a.png">

**Comment by gp-birender** [comment]
I am facing the same issue after adding other NPM packages. but if I remove them then its creating it in release mode.

**Comment by cohedz94** [comment]
i custom for my project RN 0.59.10
you try add this on package.json
` "lottie-react-native":"git+ssh://git@gitlab.com:cohedz/lottie-react-native.git"`

in podfile

```
pod 'lottie-ios', '~> 2.5.3'

pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'
```

**Comment by emilioicai** [comment]
I'm closing this as a version update should solve this issue.
