### ISSUE TITLE
resizeMode no longer applying

### ISSUE THREAD

**Issue by lightninglu10** [lottie-react-native/lottie-react-native#529]
### Description

resizeMode used to apply properly, but after upgrading to `react-native-lottie: 2.6.1` resizeMode no longer works in Android.

**Comment by aditya1711** [comment]
Any fix for this?

**Comment by lightninglu10** [comment]
I hadn't found a fix.

**Comment by emilioicai** [comment]
I'm closing this as a version update should solve this issue.
