### ISSUE TITLE
This copy of libswiftCore.dylib requires an OS version prior to 12.2.0. (lldb) 

### ISSUE THREAD

**Issue by inkCrazy** [lottie-react-native/lottie-react-native#531]
### Description

[Description of the bug]
objc[47234]: Class _TtC6Lottie10DebugLayer is implemented in both /Users/inkcrazy/Library/Developer/Xcode/DerivedData/SecurityPlatApp-bmgrbxaxxwpcblbymyouydojiohr/Build/Products/Debug-iphonesimulator/Lottie.framework/Lottie (0x10de85608) and /Users/inkcrazy/Library/Developer/CoreSimulator/Devices/3E006777-043E-4080-AD19-889C392A9E22/data/Containers/Bundle/Application/A445B792-3BB0-4292-9A30-FD1588579EB9/SecurityPlatApp.app/SecurityPlatApp (0x10c212350). One of the two will be used. Which one is undefined.
objc[47234]: Class _TtC6Lottie27AnimationCompletionDelegate is implemented in both /Users/inkcrazy/Library/Developer/Xcode/DerivedData/SecurityPlatApp-bmgrbxaxxwpcblbymyouydojiohr/Build/Products/Debug-iphonesimulator/Lottie.framework/Lottie (0x10de85670) and /Users/inkcrazy/Library/Developer/CoreSimulator/Devices/3E006777-043E-4080-AD19-889C392A9E22/data/Containers/Bundle/Application/A445B792-3BB0-4292-9A30-FD1588579EB9/SecurityPlatApp.app/SecurityPlatApp (0x10c2123b8). One of the two will be used. Which one is undefined.
This copy of libswiftCore.dylib requires an OS version prior to 12.2.0.
2019-07-29 17:20:10.056197+0800 SecurityPlatApp[47234:281621] This copy of libswiftCore.dylib requires an OS version prior to 12.2.0.
### Steps to Reproduce

1. [First Step]
I have solved the problem by check this link: https://stackoverflow.com/questions/52536380/why-linker-link-static-libraries-with-errors-ios
2. [Second Step]
Trying to solve a problem by this link:https://stackoverflow.com/questions/55361057/this-copy-of-libswiftcore-dylib-requires-an-os-version-prior-to-12-2-0
But it failed!!!
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions
```
You can get this information from executing `npm version`.
localhost:~ inkcrazy$ npm -v
6.9.0
```

### other:
    "lottie-ios": "3.0.3",
    "lottie-react-native": "^3.0.2",
    "react-native": "0.59.10",

**Comment by congnguyen91** [comment]
After running "sudo gem update cocoapods" => pod install OK.
Then I had the same issue.

**Comment by inkCrazy** [comment]
> After running "sudo gem update cocoapods" => pod install OK.
> Then I had the same issue.
> "react-native": 0.60.4
> "lottie-react-native": 3.1.0
> "lottie-ios": 3.0.7

my cocoapods is nothing to update, i guess......And my "react-native": "0.59.10",

**Comment by andreassavva** [comment]
Try adding an empty .swift file in the root directory of the project. Solved it for me.

**Comment by emilioicai** [comment]
as @andreassavva try following this process: https://stackoverflow.com/a/56176956/3265176

**Comment by neoanurag** [comment]
Go to BuildSettings -> Linking -> runpath search path and add

/usr/lib/swift

as your 1st argument like this
![Screenshot 2019-08-27 at 1 08 50 PM](https://user-images.githubusercontent.com/51991025/63752108-481a1d80-c8ce-11e9-88d1-aebe5789dfda.png)

**Comment by wamry** [comment]
I had the same issue with my own library, i wish there was a better solution that doesn't involve this workaround
