### ISSUE TITLE
Error on IOS build

### ISSUE THREAD

**Issue by rodrigowpl** [lottie-react-native/lottie-react-native#538]
### Description

![image](https://user-images.githubusercontent.com/18172307/62783996-db142480-ba93-11e9-9355-694ed51039f0.png)

### Steps to Reproduce

1. Install lottie-react-native and lottie-ios
2. run pod install
3. run your ios app

**Expected behavior:**
Compile correctly when running app

**Actual behavior:** [What actually happened]
Throws an error shown in print above

### Versions

lottie-react-native:3.1.0
lottie-ios:3.0.3

```
System:
    OS: macOS 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 1.37 GB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 8.12.0 - /usr/local/bin/node
    Yarn: 1.17.3 - ~/.yarn/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
    Android SDK:
      API Levels: 23, 25, 26, 27, 28
      Build Tools: 23.0.1, 23.0.2, 25.0.0, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.2, 28.0.3
      System Images: android-25 | Google APIs Intel x86 Atom, android-26 | Google APIs Intel x86 Atom_64, android-26 | Google Play Intel x86 Atom, android-27 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.4 => 0.60.4 
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7
```

**Comment by rodrigowpl** [comment]
What I've tried:

- Remove Pods and Podfile.lock
- run pod install --repo-update
- clear all caches

Basically everything work well and this starts happen when autolinking tried compile lottie dependencies

**Comment by fastcony** [comment]
meet save issue here, waiting for solution,  I tried add lottie framework into embed library either. not sure it related mojave system, swift version.

**Comment by emilioicai** [comment]
I'm closing this as a version update should solve this issue.
