### ISSUE TITLE
unknown app crash , maybe incompatible android version

### ISSUE THREAD

**Issue by callmejm** [lottie-react-native/lottie-react-native#541]
### Description
App crash with unknown problem, suspect the library is not compatible to android version 

### Steps to Reproduce

1. `abd logcat`
2. open app
3. app crash
`08-15 06:47:08.264  8686  8686 W com.testlottie: Accessing hidden method Landroid/text/SpannableStringInternal;->length()I (light greylist, linking)
08-15 06:47:08.265  8686  8686 W com.testlottie: Accessing hidden field Landroid/view/View;->mAccessibilityDelegate:Landroid/view/View$AccessibilityDelegate; (light greylist, reflection)
08-15 06:47:08.328  1889  3868 I ActivityManager: Killing 3518:com.google.android.gms.unstable/u0a15 (adj 906): empty for 1801s
08-15 06:47:08.335  1889  1916 W libprocessgroup: kill(-3518, 9) failed: No such process
08-15 06:47:08.383  1889  1916 W libprocessgroup: kill(-3518, 9) failed: No such process
08-15 06:47:08.427  8686  8704 W LOTTIE  : Lottie doesn't support expressions.
08-15 06:47:08.432  1889  1916 W libprocessgroup: kill(-3518, 9) failed: No such process
08-15 06:47:08.471  1889  1916 W libprocessgroup: kill(-3518, 9) failed: No such process
08-15 06:47:08.477  1729  1729 I Zygote  : Process 3518 exited due to signal (9)
08-15 06:47:08.501  8686  8697 I com.testlottie: NativeAlloc concurrent copying GC freed 3559(448KB) AllocSpace objects, 14(1580KB) LOS objects, 49% free, 2MB/5MB, paused 9.555ms total 140.674ms
08-15 06:47:08.509  8686  8704 W LOTTIE  : Animation contains merge paths. Merge paths are only supported on KitKat+ and must be manually enabled by calling enableMergePathsForKitKatAndAbove().
08-15 06:47:08.511  1889  1916 W libprocessgroup: kill(-3518, 9) failed: No such process
08-15 06:47:08.511  1889  1916 I libprocessgroup: Successfully killed process cgroup uid 10015 pid 3518 in 176ms
08-15 06:47:08.515  1606  1606 D gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 241664
08-15 06:47:08.527  1728  1915 D         : HostConnection::get() New Host Connection established 0xf068f1c0, tid 1915
08-15 06:47:08.528  1606  1606 D gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 241664
08-15 06:47:08.537  1606  1606 D gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 241664
08-15 06:47:08.565  8686  8712 D EGL_emulation: eglMakeCurrent: 0xe6805780: ver 3 1 (tinfo 0xe68038d0)
08-15 06:47:08.606  8686  8704 W LOTTIE  : Lottie doesn't support expressions.
08-15 06:47:08.613  8686  8704 W LOTTIE  : Lottie doesn't support expressions.
08-15 06:47:08.624  8686  8704 W LOTTIE  : Animation contains merge paths. Merge paths are only supported on KitKat+ and must be manually enabled by calling enableMergePathsForKitKatAndAbove().
08-15 06:47:08.670  8686  8704 W LOTTIE  : Animation contains merge paths. Merge paths are only supported on KitKat+ and must be manually enabled by calling enableMergePathsForKitKatAndAbove().
08-15 06:47:08.674  8686  8704 W LOTTIE  : Lottie doesn't support expressions.
08-15 06:47:08.711  8686  8704 W LOTTIE  : Animation contains merge paths. Merge paths are only supported on KitKat+ and must be manually enabled by calling enableMergePathsForKitKatAndAbove().
08-15 06:47:08.823  8686  8704 I chatty  : uid=10086(com.testlottie) AsyncTask #1 identical 18 lines
08-15 06:47:08.832  8686  8704 W LOTTIE  : Animation contains merge paths. Merge paths are only supported on KitKat+ and must be manually enabled by calling enableMergePathsForKitKatAndAbove().
08-15 06:47:08.837  1889  2011 I GnssLocationProvider: WakeLock acquired by sendMessage(REPORT_SV_STATUS, 0, com.android.server.location.GnssLocationProvider$SvStatusInfo@d6444bd)
08-15 06:47:08.838  1889  1910 I GnssLocationProvider: WakeLock released by handleMessage(REPORT_SV_STATUS, 0, com.android.server.location.GnssLocationProvider$SvStatusInfo@d6444bd)
08-15 06:47:08.846  8686  8704 W LOTTIE  : Animation contains merge paths. Merge paths are only supported on KitKat+ and must be manually enabled by calling enableMergePathsForKitKatAndAbove().
08-15 06:47:08.891  8686  8704 I chatty  : uid=10086(com.testlottie) AsyncTask #1 identical 7 lines
08-15 06:47:08.899  8686  8704 W LOTTIE  : Animation contains merge paths. Merge paths are only supported on KitKat+ and must be manually enabled by calling enableMergePathsForKitKatAndAbove().
08-15 06:47:09.006  8686  8686 W LOTTIE  : Animation contains merge paths but they are disabled.
08-15 06:47:09.079  8686  8686 I chatty  : uid=10086(com.testlottie) identical 30 lines
08-15 06:47:09.083  8686  8686 W LOTTIE  : Animation contains merge paths but they are disabled.
08-15 06:47:09.449  8686  8686 D AndroidRuntime: Shutting down VM
08-15 06:47:09.453  8686  8686 E AndroidRuntime: FATAL EXCEPTION: main
08-15 06:47:09.453  8686  8686 E AndroidRuntime: Process: com.testlottie, PID: 8686
08-15 06:47:09.453  8686  8686 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.PointF com.airbnb.lottie.model.content.ShapeData.getInitialPoint()' on a null object reference
08-15 06:47:09.453  8686  8686 E AndroidRuntime:        at com.airbnb.lottie.model.content.ShapeData.interpolateBetween(ShapeData.java:65)
08-15 06:47:09.453  8686  8686 E AndroidRuntime:        at com.airbnb.lottie.animation.keyframe.ShapeKeyframeAnimation.getValue(ShapeKeyframeAnimation.java:23)
08-15 06:47:09.453  8686  8686 E AndroidRuntime:        at com.airbnb.lottie.animation.keyframe.ShapeKeyframeAnimation.getValue(ShapeKeyframeAnimation.java:11)
08-15 06:47:09.453  8686  8686 E AndroidRuntime:        at com.airbnb.lottie.animation.keyframe.BaseKeyframeAnimation.getValue(BaseKeyframeAnimation.java:125)
08-15 06:47:09.453  8686  8686 E AndroidRuntime:        at com.airbnb.lottie.animation.content.ShapeContent.getPath(ShapeContent.java:61)
08-15 06:47:09.453  8686  8686 E AndroidRuntime:        at com.airbnb.lottie.animation.content.FillContent.draw(FillContent.java:88)
08-15 06:47:09.453  8686  8686 E AndroidRuntime:        at com.airbnb.lottie.animation.content.ContentGroup.draw(ContentGroup.java:161)
08-15 06:47:09.453  8686  8686 E AndroidRuntime:        at com.airbnb.lottie.animation.content.ContentGroup.draw(ContentGroup.java:161)
08-15 06:47:09.453  8686  8686 E AndroidRuntime:        at com.airbnb.lottie.model.layer.ShapeLayer.drawLayer(ShapeLayer.java:30)
08-15 06:47:09.453  8686  8686 E AndroidRuntime:        at com.airbnb.lottie.model.layer.BaseLayer.draw(BaseLayer.java:198)
08-15 06:47:09.453  8686  8686 E AndroidRuntime:        at com.airbnb.lottie.model.layer.CompositionLayer.drawLayer(CompositionLayer.java:100)
08-15 06:47:09.453  8686  8686 E AndroidRuntime:        at com.airbnb.lottie.model.layer.BaseLayer.draw(BaseLayer.java:198)
08-15 06:47:09.453  8686  8686 E AndroidRuntime:        at com.airbnb.lottie.LottieDrawable.draw(LottieDrawable.java:312)
08-15 06:47:09.453  8686  8686 E AndroidRuntime:        at android.widget.ImageView.onDraw(ImageView.java:1360)
08-15 06:47:09.453  8686  8686 E AndroidRuntime:        at android.view.View.draw(View.java:20207)
08-15 06:47:09.453  8686  8686 E AndroidRuntime:        at android.view.View.buildDrawingCacheImpl(View.java:19478)
08-15 06:47:09.453  8686  8686 E AndroidRuntime:        at android.view.View.buildDrawingCache(View.java:19338)
08-15 06:47:09.453  8686  8686 E AndroidRuntime:        at android.view.View.updateDisplayListIfDirty(View.java:19059)
08-15 06:47:09.453  8686  8686 E AndroidRuntime:        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
08-15 06:47:09.453  8686  8686 E AndroidRuntime:        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
08-15 06:47:09.453  8686  8686 E AndroidRuntime:        at android.view.View.updateDisplayListIfDirty(View.java:19042)
08-15 06:47:09.453  8686  8686 E AndroidRuntime:        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
08-15 06:47:09.453  8686  8686 E AndroidRuntime:        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
08-15 06:47:09.453  8686  8686 E AndroidRuntime:        at android.view.View.updateDisplayListIfDirty(View.java:19042)
08-15 06:47:09.453  8686  8686 E AndroidRuntime:        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
08-15 06:47:09.453  8686  8686 E AndroidRuntime:        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
08-15 06:47:09.453  8686  8686 E AndroidRuntime:        at android.view.View.updateDisplayListIfDirty(View.java:19042)
08-15 06:47:09.453  8686  8686 E AndroidRuntime:        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
08-15 06:47:09.453  8686  8686 E AndroidRuntime:        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
08-15 06:47:09.453  8686  8686 E AndroidRuntime:        at android.view.View.updateDisplayListIfDirty(View.java:19042)
08-15 06:47:09.453  8686  8686 E AndroidRuntime:        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
08-15 06:47:09.453  8686  8686 E AndroidRuntime:        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
08-15 06:47:09.453  8686  8686 E AndroidRuntime:        at android.view.View.updateDisplayListIfDirty(View.java:19042)
08-15 06:47:09.453  8686  8686 E AndroidRuntime:        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
08-15 06:47:09.453  8686  8686 E AndroidRuntime:        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
08-15 06:47:09.453  8686  8686 E AndroidRuntime:        at android.view.View.updateDisplayListIfDirty(View.java:19042)
08-15 06:47:09.453  8686  8686 E AndroidRuntime:        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
08-15 06:47:09.453  8686  8686 E AndroidRuntime:        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
08-15 06:47:09.453  8686  8686 E AndroidRuntime:        at android.view.View.updateDisplayListIfDirty(View.java:19042)
08-15 06:47:09.453  8686  8686 E AndroidRuntime:        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
08-15 06:47:09.453  8686  8686 E AndroidRuntime:        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
08-15 06:47:09.453  8686  8686 E AndroidRuntime:        at android.view.View.updateDisplayListIfDirty(View.java:19042)
08-15 06:47:09.453  8686  8686 E AndroidRuntime:        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:686)
08-15 06:47:09.453  8686  8686 E AndroidRuntime:        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:692)
08-15 06:47:09.453  8686  8686 E AndroidRuntime:        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:801)
08-15 06:47:09.453  8686  8686 E AndroidRuntime:        at android.view.ViewRootImpl.draw(ViewRootImpl.java:3311)
08-15 06:47:09.453  8686  8686 E AndroidRuntime:        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3115)
08-15 06:47:09.453  8686  8686 E AndroidRuntime:        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2484)
08-15 06:47:09.453  8686  8686 E AndroidRuntime:        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1460)
08-15 06:47:09.453  8686  8686 E AndroidRuntime:        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7183)
08-15 06:47:09.453  8686  8686 E AndroidRuntime:        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
08-15 06:47:09.453  8686  8686 E AndroidRuntime:        at android.view.Choreographer.doCallbacks(Choreographer.java:761)
08-15 06:47:09.453  8686  8686 E AndroidRuntime:        at android.view.Choreographer.doFrame(Choreographer.java:696)
08-15 06:47:09.453  8686  8686 E AndroidRuntime:        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
08-15 06:47:09.453  8686  8686 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:873)
08-15 06:47:09.453  8686  8686 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
08-15 06:47:09.453  8686  8686 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:193)
08-15 06:47:09.453  8686  8686 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6669)
08-15 06:47:09.453  8686  8686 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
08-15 06:47:09.453  8686  8686 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
08-15 06:47:09.453  8686  8686 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
08-15 06:47:09.459  1889  3162 W ActivityManager:   Force finishing activity com.testlottie/.MainActivity
08-15 06:47:09.487  1889  1913 I ActivityManager: Showing crash dialog for package com.testlottie u0`

### Take Note

1.  Lottie doesn't support expressions
2.  Animation contains merge paths. Merge paths are only supported on KitKat+ and must be manually enabled by calling enableMergePathsForKitKatAndAbove().
3.  java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.PointF com.airbnb.lottie.model.content.ShapeData.getInitialPoint()' on a null object reference

**Expected behavior:** animation run without problem

**Actual behavior:** app crash

### Versions
`lottie-react-native@3.0.1`
`react-native@0.59.10`

@emilioicai

**Comment by cohedz94** [comment]
i custom for my project RN 0.59.10
you try add this on package.json
 "lottie-react-native":"git+ssh://git@gitlab.com:cohedz/lottie-react-native.git"

in podfile
pod 'lottie-ios', '~> 2.5.3'

pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'

**Comment by curt-tophatter** [comment]
@cohedz94 If you fixed this for your app, why not issue a PR back to this project?
