### ISSUE TITLE
Failed build on RN 0.60.5

### ISSUE THREAD

**Issue by yawnr** [lottie-react-native/lottie-react-native#550]
After `yarn install`ing, and attempting to `pod install`, you are given an error about needing to add `use_modular_headers!` to the `Podfile`.

After doing so, the `pod install` succeeds, but the build eventually fails with
`import of module 'glog.glog.log_severity' appears within namespace 'google'`

**Comment by sahil290791** [comment]
This worked: https://github.com/react-native-community/lottie-react-native/issues/536#issuecomment-532071951

**Comment by asimonv** [comment]
I did yarn install + added
```
  pod 'lottie-ios', :path => '../node_modules/lottie-ios'
  pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'
```

to Podfile + created dummy swift file + Always Embedded Swift Standard Libraries in Build Settings + updated cocoapods (1.7.5) + pod install to make it work.

**Comment by 914813666** [comment]
1. your need add  `use_modular_headers!` to Podfile , and Modify React , See pic
![](https://tva1.sinaimg.cn/large/006y8mN6gy1g75sr7id38j30t20swdos.jpg) 
2.add a swift file and xxx-Bridging-Header.h to your project

**Comment by GitXwj** [comment]
I followed your steps or pod insatll failed. @914813666

**Comment by GitXwj** [comment]
I upgraded cocoapod to 1.7.5 and he solved my problem.

**Comment by yawnr** [comment]
Thanks all, will take a look at your proposed solutions.

That being said, I feel like this is something that still needs to be addressed given the complexity of the workaround.

**Comment by javiercr** [comment]
Updating cocoapods to 1.8.4 also fixed this for me.

**Comment by ironworkshop** [comment]
Updating to cocoapods to 1.8.4 and performing the steps in: [https://github.com/react-native-community/lottie-react-native/issues/536#issuecomment-532071951](url) fixed it for me. Did a build folder clean as well.

**Comment by ninjz** [comment]
This worked for me https://github.com/facebook/react-native/issues/26217#issuecomment-536118532

**Comment by JimmySorza** [comment]
https://github.com/react-native-community/lottie-react-native/issues/536#issuecomment-589564657 just add `use_frameworks!` to Podfile
