### ISSUE TITLE
Animation stopped after navigate between screen

### ISSUE THREAD

**Issue by voortexx** [lottie-react-native/lottie-react-native#560]
### Description

Hello  !  I'm facing something weird.
My animation is showing right. But when i navigate on an other screen and then come back to the first one my animation is freeze.
This happens only on Android.
I'm using 2.6.1 because of linking restriction.

### Versions

react-native:  0.59.9
lottie-react-native:  2.6.1
react-navigation: 3.11.0

**Comment by voortexx** [comment]
I fix this by adding :
`useEffect(() => {
    const playAnimation = navigation.addListener('didFocus', () => {
      this.animation.play();
    });
    return () => playAnimation.remove();
  }, []);`

But i am not sure if it's the right behaviour

**Comment by Psiiirus** [comment]
@voortexx thanks! worked for me.

Just in case someone is wondering how to use this fix.
Wrap your <LottieView /> into an functional component and pass the navigation into it

```
...
import React, {Component, useEffect} from 'react';
...

function FixLottieView({navigation}) {

    useEffect(() => {
        const playAnimation = navigation.addListener('didFocus', () => {
            this.animation.play();
        });
        return () => playAnimation.remove();
    }, []);

    return <LottieView
                autoPlay={true}
                speed={.5}
                loop
                source={require('MYAPP/assets/animations/swipe-down.json')}
            />;
}

**Comment by kaduelinho** [comment]
I'm having the same issue, but i couldn't make it work with this way.

Here is my code:

const LottieAnimation =
  ({ src, imageFolder, from = 0, to = 30, speed = 1 }) =>
    class Anim extends React.Component {
      componentDidMount() {
        this.animation.play(from, to);
      }

      render() {
        return (
          <LottieView
            ref={(animation) => this.animation = animation}
            loop
            source={src}
            speed={speed}
            {...this.props}
            imageAssetsFolder={imageFolder}
          />
        );
      }
    };

**Comment by Psiiirus** [comment]
Hi @kaduelinho ,
this is my lates code i hope it helps.

```

function WrappedLoopAnimation({navigation, opacity}) {

    let animation = null; //React.createRef();
    let timeOutId = null;

    useEffect(() => {
        if (!animation || !animation.play)
            return;

        if (timeOutId)
            clearTimeout(timeOutId);

        timeOutId = setTimeout(() => {
            if (animation)
                animation.play();
        }, 1700);

        const playAnimation = navigation.addListener('didFocus', () => {
            if (animation)
                animation.play();
        });

        return () => playAnimation.remove();
    });

    return <LottieView
                    ref={myAnimation => {
                        animation = myAnimation;
                    }}
                    speed={.4}
                    loop
                    style={{
                        height: 300,
                    }}
                    source={require('s/assets/animations/swipe-down.json')}
                />;
}
```

**Comment by matinzd** [comment]
This should be fixed. Please let us know if you are still facing the issue.
