### ISSUE TITLE
Can't build on IOS

### ISSUE THREAD

**Issue by mahdidavoodi7** [lottie-react-native/lottie-react-native#574]
after i execute `pod install` and when i want to run the app with `react-native run-ios` this error shows up :

`Build system information
error: SWIFT_VERSION '5.0' is unsupported, supported versions are: 3.0, 4.0, 4.2. (in target 'lottie-ios')`

Any help will be appreciated .

**Comment by Jeeva111** [comment]
Check out [https://stackoverflow.com/questions/55585062/xcode-keeps-showing-1-swift-version-5-0-is-unsupported-supported-versions-a](url)

**Comment by greg7gkb** [comment]
Dupe: https://github.com/react-native-community/lottie-react-native/issues/574
