### ISSUE TITLE
Export AnimationObject

### ISSUE THREAD

**Issue by thewaver** [lottie-react-native/lottie-react-native#576]
### Description

`AnimationObject` is not exported, but required to properly type `source` prop in custom component.

### Versions

lottie-react-native: 3.0.3
lottie-ios: 3.0.2
react-native: 0.60.0

(please let me know if there are any other relevant packages)

**Comment by emilioicai** [comment]
Can you share some code?

**Comment by Foskas** [comment]
Any updates on this ?

**Comment by thewaver** [comment]
> Can you share some code?

```jsx
interface AnimatedImageProps {
  source: any; // string | AnimationObject | { uri: string; };
  style?: StyleProp<ViewStyle>;
}

const AnimatedImage: React.FC<AnimatedImageProps> = props => (
  <View style={props.style}>
    <LottieView
      style={{ width: '100%' }}
      source={props.source}
      resizeMode="contain"
      autoPlay
      loop
    />
  </View>
);
```

Basically there's a wrapper for `<LottieView>` which forwards props to it. As we are using Typescript in our project we need the proper types for the wrapper props interface.

**Comment by thewaver** [comment]
Alternatively - or complementarily - you could export `AnimatedLottieViewProps`.

**Comment by Foskas** [comment]
@thewaver I saw the source code for the AnimationObject type and created the type on my side of the code, that's also a solution.

**Comment by thewaver** [comment]
That is not a reliable solution for a commercial development environment. If the native interface changes your code will break.

**Comment by klandell** [comment]
It would be extraordinarily helpful if the AnimationObject interface were exported.

**Comment by timoisalive** [comment]
Yes, I'd also be happy if the `AnimatedLottieViewProps` were exported.
