### ISSUE TITLE
Changing speed dynamically?

### ISSUE THREAD

**Issue by ezranbayantemur** [lottie-react-native/lottie-react-native#579]
Hello everyone, I'm trying to change animation dynamically.
I've tried to change it via setState but it still played on previous speed.

I'm sharing sample code for it:

```
class App extends React.Component {
  constructor() {
    super()
    this.state = { speed: 0.5 }
  }

  render() {
    return (
      <SafeAreaView>
        <LottieView
          source={require("./animations/6567-scanning-nearby.json")}
          autoPlay
          speed={this.state.speed}
        />


          <TouchableOpacity onPress={() => this.setState({ speed: 1.5 })}>
              <Text style={{ fontSize: 20 }}>Tap for start scan</Text>
          </TouchableOpacity>
           ...
           ...
           ...
```

If I checked the reference before and after change speed, it looks like change. But on the screen it stays same.
![Screen Shot 2019-10-18 at 11 21 31](https://user-images.githubusercontent.com/42299721/67078415-ebcece00-f199-11e9-90d9-bfb9c17a4917.jpg)

Is there any way to do it?

**Verisons:**
```
    "lottie-ios": "3.1.3",
    "lottie-react-native": "^3.2.1",
    "react": "16.9.0",
    "react-native": "0.61.2"
```

**Platform:** iOS

**Comment by PabloNicolaas** [comment]
I think u are forgetting your props:

constructor(props) {
    super(props)
    this.state = { speed: 0.5 }
  }

therefor a simpler syntax would be:
state = { speed: 0.5 }

**Comment by Joao360** [comment]
Did you have any issues on the animation not starting on iOS? In my case the speed starts at 0 and based on the user interaction the speed goes up but the animation never starts.

On android this works fine

**Comment by LucidNinja** [comment]
Is there an update on this issue? I'm having the same problem. I want the user to be able to control the speed, but it doesn't seem to be making a difference?

I am using it like this. FYI, `isAutoPlay` is set by the user with a `TouchableOpacity` in the `onPress` prop, and I can confirm that the state of `isAutoPlay` changes accordingly.

```
const [isAutoPlay, setIsAutoPlay] = useState(false);
const speed = isAutoPlay ? 1 : 4;

<LottieView
  onAnimationFinish={progressSteps}
  source={src}
  ref={animation}
  speed={speed}
  loop={false}
  style={{ width: windowWidth }}
  />
```

**Comment by mesutaltuncu** [comment]
I have same problem too.
When I change speed it seems doesn't effect it at all. Still running on previous speed.

Any way to fix it. 
And also document says we can use pause function but it doesn't work. this.animation.pause() is not function.

**Comment by LucidNinja** [comment]
@mesutaltuncu - pausing should work. Show us your code.

**Comment by mesutaltuncu** [comment]
`<LottieView
                                    source={require('../../animations/Small.json')}
                                    speed={this.state.counterAnimaStatus}
                                    ref={animation => { this.animation = animation }}
                                    autoPlay={false}
                                    cacheStrategy={"strong"}
                                    loop={false}
                                    style={styles.questionTimer} />`
this.animation.play() and this.animation.reset() is working however pause() is not a function appears when I use it.

**Comment by LucidNinja** [comment]
@mesutaltuncu I'm having the same issue!

**Comment by PabloNicolaas** [comment]
this worked for me`  state = { checked: false, animSpeed: 1 }

  playAnimation = (startFrame, endFrame) => {
    this.animation.reset()
    this.animation.play(startFrame, endFrame)
  }

  triggerAnimation = () => {
    if (this.state.checked) {
      if(Platform.OS === 'ios') {
        this.setState({ checked: false })
        this.playAnimation(10, 0)
      } else {
        this.setState({ checked: false, animSpeed: -2 })
        this.playAnimation()
      }
    } else {
      this.setState({ checked: true, animSpeed: 1 })
      this.playAnimation();
    }
  }

  renderAnimation = () => {
    return (
      <View pointerEvents="none" style={styles.svgContainer} >
        <LottieView
          ref={animation => { this.animation = animation }}
          loop={false}
          speed={this.state.animSpeed}
          source={require('./animations/radiobutton-animation.json')}
          style={styles.animationContainer} 
        />
      </View>
    )
  }

  render() {
    const checked = `what ${this.state.checked}`
    return (
      <TouchableWithoutFeedback onPress={this.triggerAnimation}>
          <View style={styles.radioButtonContainer}>
            {this.renderAnimation()}
          </View>
      </TouchableWithoutFeedback> 
    );
  }
}`

seems like IOS needs the startFrame and endFrame to run. pausing workes too if i call this.animation.pause. maybe this helps someone :)

**Comment by AnmolShrma** [comment]
@PabloNicolaas is it possible to render a sequence of Lottie files in a single LottieView component through source?

**Comment by adorum** [comment]
> @PabloNicolaas is it possible to render a sequence of Lottie files in a single LottieView component through source?

have you solved the multiple lottie files in single lottie component instance?
