### ISSUE TITLE
Duik animation not working on mobile but works fine in LottieFiles preview on web

### ISSUE THREAD

**Issue by NeilMcGuiness** [lottie-react-native/lottie-react-native#589]
### Description

I have created a run cycle animation in After Effects using the Duik extension to rig the character (created in Adobe Illustrator). I have then exported this animation using Bodymovin (with Guides and Hidden layers selected in the settings). The result of this is a JSON animation which DOES work in Lottiefiles web preview. 

However, the animation does not work on either the Previewer in the Lottie app (Android) or when loaded into a <LottieView> Object in React-Native (Also Android). 

I'm confused because I've read elsewhere that Duik animations work with Lottie. If it is the case that they don't work with lottie-react-native then this should be outlined in the documentation clearly. My Lottie preview app gives a bunch of warnings about not supporting layer effects and so on, but I wish this was warned about before.
 
### Steps to Reproduce

1. Create animation in AE using Duik
2. Render to JSON object with bodymovin and confirm that it works in Lottie preview on web
3. Load Json object into <LottieView> object in React-Native or Lottie mobile previewer

**Expected behavior:** The animation to perform similarly to how it did in the web previewer

**Actual behavior:** The rigged animated layers were static and broken.

### Versions

lottie-react-native : 3.2.1
npm: 6.11.3
react-native: 0.61.3

**Comment by aprilgao** [comment]
I've met the same problem, it is said by Bodymovin that Duik expressions do not supported by iOS / Android native players, I've tried Easy Bake for AE to bake the expressions to keyframes, you may have a try.
