### ISSUE TITLE
Animation stop when I use native module RNScrypt

### ISSUE THREAD

**Issue by kangbb** [lottie-react-native/lottie-react-native#595]
### Description

It looks like a conflict between two native modules. 

I want to exec a long time task, and give a animation to user at the same time. The task is simple, just encrypting, but i use a native module:

[https://github.com/Crypho/react-native-scrypt](https://github.com/Crypho/react-native-scrypt)

### Steps to Reproduce

1. I start a lottie animation
2. I start the task.
3. Then, the animation stop, after task finish, animation run again.

**Expected behavior:** [What you expected to happen]

Run the animation when the task execs.

**Actual behavior:** [What actually happened]

The animation stop when the task exec.

### Versions

npm version:

```sh
{
  npm: '6.12.0',
  ares: '1.15.0',
  brotli: '1.0.7',
  cldr: '35.1',
  http_parser: '2.8.0',
  icu: '64.2',
  llhttp: '1.1.4',
  modules: '72',
  napi: '5',
  nghttp2: '1.39.2',
  node: '12.13.0',
  openssl: '1.1.1d',
  tz: '2019a',
  unicode: '12.1',
  uv: '1.32.0',
  v8: '7.7.299.13-node.12',
  zlib: '1.2.11'
}
```
for lottie:

```sh
"lottie-ios": "^3.1.5",
"lottie-react-native": "^3.3.2",
"react-native": "0.61.4"
```

**Comment by emilioicai** [comment]
Can you share some code for this?
