### ISSUE TITLE
CPU load optimization in iOS is very poor

### ISSUE THREAD

**Issue by mitaxe** [lottie-react-native/lottie-react-native#597]
### Description

When animation is running in Xcode I see CPU jumps from 5-10% to 70-80%. And it doesn't depend on animation. If animation is running every one second I also see the same CPU load. Sometimes it jumps to 90%.

In Android everything is good. The CPU load is about 20-30%, sometimes even less. (10-15%)

**Expected behavior:** 
CPU load optimization in iOS

**Actual behavior:** 
The CPU load optimization in iOS is very poor.
The CPU load in Android is OK.

### Versions
iOS version 13.2.

"react-native": "0.61.2",
"lottie-ios": "3.1.5",
"lottie-react-native": "^3.3.1",

**Comment by ayouidaniel** [comment]
+1

**Comment by BohdanIvanov** [comment]
+1

**Comment by mitaxe** [comment]
Any updates on this?

**Comment by emilioicai** [comment]
wouldn't this issue better live in `lottie-ios`?

**Comment by mitaxe** [comment]
I don't know, but I created a copy there.
