### ISSUE TITLE
Add React Native for Windows vNext support

### ISSUE THREAD

**Issue by stmoy** [lottie-react-native/lottie-react-native#601]
### Description

[Description of the bug]
[React Native for Windows](https://github.com/microsoft/react-native-windows) enables React Native apps to target Windows via UWP. React Native for Windows is under active development by Microsoft. Most recently, the platform has been updated to leverage high-performance C++ (known as "RNW vNext"). Now that the RNW vNext supports native modules as a platform, we have identified several key native modules to add Windows support for (including lottie-react-native) to help validate that the platform has the right set of capabilities and to bootstrap the community of modules that target Windows.

Microsoft devs are signed up to help build out this implementation, but we wanted to track this work here as well to help provide some transparency that we're doing this work and hoping to contribute back to the repo. 

https://github.com/microsoft/react-native-windows/issues/3278

### Steps to Reproduce

N/A

**Expected behavior:** React-Native-Lottie works great on Windows 😁

**Actual behavior:** No support... yet!

### Versions

You can get this information from executing `npm version`.

**Comment by stmoy** [comment]
Also: hello from the React Native Windows team at Microsoft 👋

**Comment by emilioicai** [comment]
Hey @stmoy , great news! Thanks a lot, if you need any help on my side just give me a shout, I'm eager to see lottie animations running on windows 😄
