### ISSUE TITLE
Add alpha support for color filters

### ISSUE THREAD

**Issue by andrewtremblay** [lottie-react-native/lottie-react-native#602]
Feature request based on this comment in the original PR for color filters

https://github.com/react-native-community/lottie-react-native/pull/584

> Would love to have support for alpha when setting colors with colorFilters in an specific layer
> 
> ```
> return UIColor(
>    red: CGFloat((rgbValue & 0xFF0000) >> 16) / 255.0,
>    green: CGFloat((rgbValue & 0x00FF00) >> 8) / 255.0,
>    blue: CGFloat(rgbValue & 0x0000FF) / 255.0,
>    alpha: CGFloat(1.0) 
> )
> ```
> 
> Here the alpha is set always to 1.0
https://github.com/react-native-community/lottie-react-native/pull/584#issuecomment-569533448

Not the original commenter, but I agree that the alpha channel should also be exposed if possible.

**Comment by SimoneCarnio** [comment]
try this #674
