### ISSUE TITLE
There are no ability to set color (with colorFilters) for layer that are colored with gradient.

### ISSUE THREAD

**Issue by ghost** [lottie-react-native/lottie-react-native#609]
# Gradient color support

Thanks for adding colorFilters prop, it really helps to build white label applications, but unfortunately I can't set color to layer that has color as gradient. Please, add an ability to color this layers and also please provide an ability to set color in colorFilters with gradient. Thanks!

**Comment by felansu** [comment]
👍 Yeah! 👍 
I need that
