### ISSUE TITLE
Animation works differently on mobile than on the web (lottie preview)

### ISSUE THREAD

**Issue by roruva** [lottie-react-native/lottie-react-native#616]
### Description

I'm using a [file.json](https://assets5.lottiefiles.com/packages/lf20_5EK2Zu.json) on the LottieFiles (preview section) and the [animation](https://lottiefiles.com/share/5EK2Zu) works right, but when I try to use de same file  in `<LottieView />`, the animation works differently, part of the animation is rendered on the opposite side. I can't give detail on how the animation was built (I have no knowledge in that), but the designer explain me that he used `null layer` element  (is part of `Layer controller`)(After Effects) to rotate and to control the leaf (item that shows badly).

### Steps to Reproduce

1. Just use the component `<LottieView />` with the file.json

**Expected behavior:** The animation should work the same way as than on the web

**Actual behavior:**  Part of the animation is rendered on the opposite side.

### Versions
`npm version`
```js
{
  npm: '6.9.0',
  ares: '1.15.0',
  cldr: '33.1',
  http_parser: '2.8.0',
  icu: '62.1',
  modules: '64',
  napi: '3',
  nghttp2: '1.34.0',
  node: '10.15.3',
  openssl: '1.1.0j',
  tz: '2018e',
  unicode: '11.0',
  uv: '1.23.2',
  v8: '6.8.275.32-node.51',
  zlib: '1.2.11' 
}
```
`package.json`
```js
{
"lottie-ios": "3.1.3",
"lottie-react-native": "^3.3.1",
"react": "^16.9.0",
"react-native": "^0.61.5",
}
```

**Comment by corosteg** [comment]
This could be due to the version of body movin you are using.
I had the same problem I downloaded the JSON of a similar animation but with a more recent bodymovin.
It worked for me

**Comment by Dimasprog** [comment]
Any solutions?

**Comment by risingsunho** [comment]
save issue!

**Comment by arjunghimire** [comment]
Same issue

**Comment by emreharman** [comment]
I've got the same issue. color transitions works well but animation doesn't rotate. I've tried another sample json file from https://lottiefiles.com/ but still problem goes on. Anyone who handles this issue? Wyh doesn't animation rotate?
