### ISSUE TITLE
[iOS] Cycle in dependencies between targets 'DoubleConversion' and 'FBLazyVector'; building could produce unreliable results.

### ISSUE THREAD

**Issue by suraneti** [lottie-react-native/lottie-react-native#619]
### Description

An error occurred while running react-native run-ios.

### Steps to Reproduce

1. installing lttie-react-native following the instruction [RN => 0.60]
2. run react-native run-ios

**Expected behavior:** Run command successful

**Actual behavior:** An error occurred and I have to clear build-cache every time on Xcode to run successfully on next time.

### Versions

**Xcode: 11.0 (11A420a)**
**MacOS: 10.14.6**

I'm using yarn.

```javascript
"react-native": "^0.61.5",
"lottie-ios": "3.1.3",
"lottie-react-native": "^3.3.2",
```

**Comment by Sbarcenas** [comment]
Same :C

**Comment by Sbarcenas** [comment]
try it
close xCode
rm -rf ~/library/developer/xcode/deriveddata
rm -rf ~/.rncache
rm -rf node_modules && npm install && cd ios && rm -rf Pods && pod install && cd ..

**Comment by schrulnz** [comment]
Product -> 'Clean Build Folder' (cmd + Shift + K) in XCode and rebuilding worked for me. 

Removing the Pods + Podfile.lock  and pod install works as well, but is a bigger effort.

**Comment by Saad-Bashar** [comment]
I tried both solutions, still having the same error while building from the command line. Xcode can still build and run the project.
