### ISSUE TITLE
Weird rendering compared to web (lines and thickness)

### ISSUE THREAD

**Issue by dancherb** [lottie-react-native/lottie-react-native#629]
Animations show up with weird rendering with react-native-lottie, particularly when it comes to lines and thickness. This occurs on Android, both device and emulator. Image attached - this is a comparison with how the JSON renders on https://lottiefiles.com/web-player. 

react-native: 0.61.5
lottie-react-native: 3.3.2

Please message if you'd like a copy of the animation file :)

![lottie_comparison](https://user-images.githubusercontent.com/32280121/78612711-5f31dc80-78ad-11ea-9e8e-64d481dfac25.png)

**Comment by oktalk** [comment]
I'm seeing similar issues. Any suggestions on how to fix this?
