### ISSUE TITLE
color issue

### ISSUE THREAD

**Issue by jingfreeks** [lottie-react-native/lottie-react-native#631]
Hello, Guys

Got a problem on the color on the web and mobile out

I attached here the screenshots of the issue

this is the web version
<img width="486" alt="Screen Shot 2020-04-07 at 7 58 50 PM" src="https://user-images.githubusercontent.com/11815014/78666768-6b985280-790a-11ea-9b6e-973b3be77771.png">

this one from the lottiefiles.com
<img width="462" alt="Screen Shot 2020-04-07 at 8 02 04 PM" src="https://user-images.githubusercontent.com/11815014/78666953-b31ede80-790a-11ea-8266-673d95afbf58.png">

this one is the mobile version
<img width="363" alt="Screen Shot 2020-04-07 at 7 57 24 PM" src="https://user-images.githubusercontent.com/11815014/78666791-74892400-790a-11ea-8a1e-8488659c0a59.png">

**Comment by wellmonge** [comment]
@jingfreeks has any update on this?
