### ISSUE TITLE
Build Failed using RN 061.5

### ISSUE THREAD

**Issue by Monir-Shembesh** [lottie-react-native/lottie-react-native#633]
### Description

I tried Building the app but it always fails. the errors are as follows: 

Build targets lottie-ios:
     - compile AimationButton.swift
     - compile AnimationControl.swift
     - and all the other files as can be seen in this [picture](https://ibb.co/pwfHHMn)

**Solutions Already Tried:**

I literally tried every solution mentioned in this [thread](https://stackoverflow.com/questions/52536380/why-linker-link-static-libraries-with-errors-ios) but nothing worked

**Expected behavior:** [What you expected to happen]

Builds to succeed and Lottie library will be available to be used after

**Actual behavior:** [What actually happened]

Build fails

### Versions

Dep list: 

```
"dependencies": {
    "@react-native-community/art": "^1.2.0",
    "@react-native-community/async-storage": "^1.5.0",
    "@react-native-firebase/app": "6.2.0",
    "@react-native-firebase/auth": "^6.2.0",
    "@react-native-firebase/firestore": "^6.2.0",
    "axios": "^0.19.0",
    "formik": "^2.1.4",
    "i18n-js": "github:fnando/i18n-js#v3.0.1",
    "native-base": "^2.13.8",
    "react": "16.9.0",
    "react-native": "0.61.5",
    "react-native-app-intro-slider": "^3.0.0",
    "react-native-barcode-builder": "^2.0.0",
    "react-native-bootsplash": "^1.2.1",
    "react-native-circular-progress": "^1.3.6",
    "react-native-elements": "^1.2.7",
    "react-native-fast-image": "^6.0.1",
    "react-native-gesture-handler": "^1.5.3",
    "react-native-keyboard-aware-scroll-view": "^0.9.1",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-localize": "^1.1.4",
    "react-native-material-textfield": "^0.16.1",
    "react-native-modal": "^11.5.6",
    "react-native-numeric-input": "^1.8.3",
    "react-native-onesignal": "^3.6.5",
    "react-native-progress": "^4.0.3",
    "react-native-reanimated": "^1.4.0",
    "react-native-responsive-screen": "^1.2.2",
    "react-native-snap-carousel": "^3.8.0",
    "react-native-super-grid": "^3.1.2",
    "react-native-svg": "^12.0.3",
    "react-native-tab-view": "^2.13.0",
    "react-native-vector-icons": "^6.6.0",
    "react-native-webview": "^8.1.0",
    "react-navigation": "^3.13.0",
    "react-redux": "^7.1.0",
    "redux": "^4.0.1",
    "redux-logger": "^3.0.6",
    "redux-persist": "^5.10.0",
    "redux-thunk": "^2.3.0",
    "yup": "^0.28.1"
  },
```

You can get this information from executing `npm version`.

**Comment by ckOfor** [comment]
I am having this same issue any update on this @Monir-Shembesh?

**Comment by Monir-Shembesh** [comment]
> I am having this same issue any update on this @Monir-Shembesh?

Not really. I just didnt use it. @ckOfor

**Comment by lucianomlima** [comment]
> > I am having this same issue any update on this @Monir-Shembesh?
> 
> Not really. I just didnt use it. @ckOfor

This step should work: https://stackoverflow.com/a/56176956

**Comment by Monir-Shembesh** [comment]
@lucianomlima I have already tried this but still doesnt work. no luck here i guess

**Comment by prog-24** [comment]
I think I know what the issue is, your pods project might not have all the architectures listed as your actual target. Check the errors again, look for the very first warning from the target concerning pods. In my case, I could build but I could not archive. When I removed armv7 from my archs on my target, I could do both and that error went.
