### ISSUE TITLE
App simply crashes

### ISSUE THREAD

**Issue by karimcambridge** [lottie-react-native/lottie-react-native#635]
### Description

https://lottiefiles.com/18779-lightning-bolt

### Steps to Reproduce

<LottieView
								resizeMode='contain' 
								source={require('../assets/lottie/18779-lightning-bolt.json')}
								autoPlay={true}
							/>

**Expected behavior:** For the lottie view animation to show

**Actual behavior:** App crashes

### Versions

npm info using node@v13.7.0
{
  npm: '6.13.6',
  ares: '1.15.0',
  brotli: '1.0.7',
  cldr: '36.0',
  icu: '65.1',
  llhttp: '2.0.1',
  modules: '79',
  napi: '5',
  nghttp2: '1.40.0',
  node: '13.7.0',
  openssl: '1.1.1d',
  tz: '2019c',
  unicode: '12.1',
  uv: '1.34.1',
  v8: '7.9.317.25-node.28',
  zlib: '1.2.11'
}

 Expo CLI 3.18.4 environment info:
    System:
      OS: Windows 10 10.0.18363
    Binaries:
      Node: 13.7.0 - C:\Program Files\nodejs\node.EXE
      npm: 6.13.6 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ^37.0.7 => 37.0.7
      react: ^16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz => 0.61.4

**Comment by emanueldiego0** [comment]
+1

**Comment by CloudFol** [comment]
Are you testing on an Android? I experienced issues with JSON-files being too new Bodymovin format. If you import into Adobe After Effects and then export supporing old JSON format, it removed the crash in my end.

OBS: Remember this is Android. I haven't had any issues on iOS.

**Comment by karimcambridge** [comment]
Yes Android.

**Comment by CloudFol** [comment]
> Yes Android.

Then you have to either open it in After Effects and export it supporting older JSON versions or find another animation, which already use an earlier version of BodyMovin.

**Comment by yesIamFaded** [comment]
Had few issues with this too. For me the solution was to actually rebuild the app in Android Studio. 

After closing the Emulator and restarting AS it began to work for me.

**Comment by wdospinal** [comment]
I have got the same problem with the expo cli, the app crash without showing any error in the console.

I'm using this [lottie](https://lottiefiles.com/10052-soccer-field)

```
<View style={styles.loadinContainer}>
          <LottieView
            source={soccer}
            autoPlay
            loop
            style={{ width: 500, height: 500 }}
            resizeMode="cover"
          />
</View>
```

**Comment by emilioicai** [comment]
Could you try using the latest version (3.4.0)?

**Comment by tamago3keran** [comment]
I tried to render animation and crashed on Android 😢 
But it can render animation by old formatted JSON file :tada:

↓ checked setting of "Export old json format"

<img width="635" alt="Screen Shot 2020-05-24 at 20 28 14" src="https://user-images.githubusercontent.com/24249859/82753131-4e5a0d80-9dfe-11ea-9c7e-129d48d64817.png">

### environment

```
"expo": "37.0.3",
"lottie-ios": "3.1.3"
"lottie-react-native": "3.4.0"
"react": "16.9.0"
"react-native": "https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz" => 0.61.4
```

### Files
- [Link to crashed json file](https://assets9.lottiefiles.com/packages/lf20_FZA5AG.json)
- [Link to successful rendered json file](https://assets6.lottiefiles.com/packages/lf20_5Xmx1Q.json)
