### ISSUE TITLE
Animation working properly on web preview but not in iOS

### ISSUE THREAD

**Issue by msherman93** [lottie-react-native/lottie-react-native#640]
### Description

It's not animating, just showing an inverted image.

I am animating a spinning coin to act as a loader for an app. It's meant to spin in place. 

### Steps to Reproduce

1. [View the Lottie file]((https://lottiefiles.com/share/ta5G5K)
2. Preview on iOS device

**Expected behavior:** To animate in app.

**Actual behavior:** It did not animate and just showed an inverted image of the coin.

### Versions

bodymovin: 5.6.9
AfterEffects: 17.0.6

**Comment by pvanny1124** [comment]
something very similar is happening with my animation here: https://github.com/react-native-community/lottie-react-native/issues/643

**Comment by emilioicai** [comment]
Not all features in After effects are available in `lottie-react-native`. Can you check if you are using any of these? https://airbnb.io/lottie/#/supported-features

**Comment by MattPark** [comment]
We're having the same issue with a spinning / rotating object --
