### ISSUE TITLE
Lottie showing only parts of animation after updating RN to 62.2

### ISSUE THREAD

**Issue by joseguya** [lottie-react-native/lottie-react-native#647]
### Description

After updating React-Native to  0.62, Lottie shows only parts of one of the animations in my app, in both iOS and Android.

### Steps to Reproduce

1. Add animation to assets folder in both iOS and Android
2. Run animation

**Expected behavior:**
Animations plays fully
**Actual behavior:**
Animation not showing parts of the animation
### Versions

package.json:

`
"lottie-ios": "^3.1.3",
"lottie-react-native": "^3.3.2",
"react-native": "0.62.2",
`

[Link to json file](https://assets7.lottiefiles.com/packages/lf20_eoaQmb.json)

**Comment by tamago3keran** [comment]
@joseguya I tried rendering your animation on same environment.☺️

```
"lottie-ios": "^3.1.3"
"lottie-react-native": "^3.3.2"
"react-native": "0.62.2"
```

```js
import React from 'react';
import LottieView from 'lottie-react-native';

export default class App extends React.Component {
  render() {
    return <LottieView source={require('./animation.json')} autoPlay loop />;
  }
}
```

Are there some problems? Doesn't it render perfectly?

|iOS|Android|
|:--:|:--:|
|<img src="https://user-images.githubusercontent.com/24249859/82749255-e21de080-9de2-11ea-92bf-48166609e573.gif" width=200px>|<img src="https://user-images.githubusercontent.com/24249859/82749261-ea761b80-9de2-11ea-8414-b92e3f346a61.gif" width=200px>|

**Comment by computerjazz** [comment]
I'm also trying to track down an issue where some layers don't render.
fwiw i don't see the background text when i drop @joseguya 's json file into my project:

![lottie-bug](https://user-images.githubusercontent.com/6730148/92269236-a5a95880-ee98-11ea-9fe0-ba44a1da3ee2.gif)


```
     "react-native": "0.62.2",
    "lottie-ios": "3.1.8",
    "lottie-react-native": "^3.5.0",
```

**Comment by Yadro** [comment]
I have the same problem. Lottie shows only parts of animation in iOS. Android works fine. I've tried to downgrade libs to 
```
    "lottie-ios": "3.1.5",
    "lottie-react-native": "3.4.0",
```
But it didn't help.

**Comment by joseguya** [comment]
After months of staying in older versions, it finally worked with:

`
"lottie-ios": "^3.1.8",
"lottie-react-native": "^4.0.2"
`

**Comment by Yadro** [comment]
> "lottie-ios": "^3.1.8", "lottie-react-native": "^4.0.2"

Tried this version with no luck
