### ISSUE TITLE
Cannot find name 'LayoutChangeEvent' v^3.4.0

### ISSUE THREAD

**Issue by PZenha** [lottie-react-native/lottie-react-native#657]
### Description
Updated to latest version 3.4.0 and build failed with the following error. 
![Captura de ecrã 2020-06-03, às 17 54 33](https://user-images.githubusercontent.com/54964651/83669088-e3ac8d00-a5c8-11ea-8241-7dd9f515aa78.png)
![Captura de ecrã 2020-06-03, às 17 54 54](https://user-images.githubusercontent.com/54964651/83669118-f030e580-a5c8-11ea-9aec-ab6d6f050e20.png)

[Description of the bug]

Missing `import { ..., LayoutChangeEvent } from "react-native"`

### Steps to Reproduce

1. [First Step]
yarn upgrade lottie-react-native
2. [Second Step]
yarn build

**Expected behavior:** [What you expected to happen]

Build with sucess

**Actual behavior:** [What actually happened]

`Cannot find name 'LayoutChangeEvent'`

### Versions
` "lottie-react-native": "^3.4.0",
    "lottie-react-web": "^2.1.4",
    "react": "^16.12.0",
    "react-native": "^0.61.5",`

###
Importing LayoutChangeEvent fixes the problem

**Comment by mayconmesquita** [comment]
I'm getting this issue using **React Native** v0.63 and **lottie-react-native** v3.4.0.
