### ISSUE TITLE
Can't build in xcode 11.5, No issue with xcode 10.1

### ISSUE THREAD

**Issue by MaheshNewAge** [lottie-react-native/lottie-react-native#658]
### Description

I recently build my project with xcode 11.5 to upgrade to ios 13 sdk.

### Steps to Reproduce

1. yarn install lottie-react-native
2. yarn install lottie-ios
3. pod install
4. run the project . in xcode 11.5

**Expected behavior:** build normally

**Actual behavior:** got build error . including screenshot
![Screenshot 2020-06-08 at 10 54 19 AM](https://user-images.githubusercontent.com/31950468/83995505-3397a500-a977-11ea-8ea3-1741263a1e79.png)

### Versions
react native : 0.61.4
lottie-ios: 3.1.8
lottie-react-native : 3.4.0
xcode : 11.5

**Comment by AndreyPatseiko** [comment]
The same problem! Project failed in compilation step! 
Xcode Version 11.4.1 (11E503a)
"react-native": "0.62.2"
"lottie-ios": "3.1.8",
"lottie-react-native": "^3.5.0",
