### ISSUE TITLE
crash on launch on url

### ISSUE THREAD

**Issue by varunsdcet** [lottie-react-native/lottie-react-native#660]
![IMG_6021](https://user-images.githubusercontent.com/33832368/84387882-4cbb8280-ac11-11ea-8a2b-7ec454f9f6bd.jpg)
<LottieView style = {{width:200,height:200}} source={{uri:'http://139.59.76.223/varun/Crown_Animation.json'}}
 resizeMode='cover'
 />

**Comment by ilyapishchulin** [comment]
Same problem

**Comment by Edison-fe** [comment]
I also want to know how to solve this problem
