### ISSUE TITLE
Every .json animation from lottifiles.com crashes my app!

### ISSUE THREAD

**Issue by mix0000** [lottie-react-native/lottie-react-native#661]
### Description
Hi, I using _expo (~37.0.3)_, when download `.json` animation from [lottifiles](https://lottiefiles.com/) and try to open it, my app **doesn't open**, it's just **crushing**. 

### Versions

`"expo": "~37.0.3"`
`"react-native": "~0.61.5"`
`"lottie-react-native": "^3.4.0"`

### Code Example
```
<LottieView
  ref={animation}
  style={{
    width: '100%',
    height: 375,
  }}
  source={require('../assets/data34.json')}
/>
```

**Comment by ArthurDelbeke** [comment]
+1

**Comment by Mehulpunchh** [comment]
Same here,
app crashes with json's downloaded from lottifiles.com
dependencies-
"react-native": "0.59.10"
"lottie-react-native": "2.6.1"

running on android Emulator.

**Comment by varunraghu3112** [comment]
import React, { PureComponent } from 'react';
import { View, UIManager} from 'react-native'
import Animation from 'lottie-react-native';
import loaderAnim from '../../../assets/lottieAnimations/bookLoader'

export default class Loader extends PureComponent {

  componentWillMount() {
    UIManager.setLayoutAnimationEnabledExperimental && UIManager.setLayoutAnimationEnabledExperimental(true);
  }

  componentDidMount = () => {
    this.anim.play();
    
  }
  
  render() {
    return (
      <View style={{ flex: 1, alignItems:'center', alignSelf:'center', justifyContent:'center' }}>
        <Animation
          ref={animation => {
            this.anim = animation;
          }}
          style={{
            width:220,
            height:220 ,
            alignSelf: 'center'
          }}
          loop
          source={loaderAnim}
        />
      </View>
    )
  }
}

**Comment by Ceredavide** [comment]
Same issue here, on ios works fine, but in android the app crashes without give me any error.
I am using expo 37

**Comment by Ceredavide** [comment]
> Same issue here, on ios works fine, but in android the app crashes without give me any error.
> I am using expo 37

Ok I found the solution for my problem here : https://github.com/react-native-community/lottie-react-native/issues/617#issuecomment-619593970

**Comment by mix0000** [comment]
@varunraghu3112 No it's not help for me.

**Comment by emilioicai** [comment]
@mix0000 if you are using expo you are not using `"lottie-react-native": "^3.4.0"`. I would consider asking the expo maintainers to update to the latest version of `lottie-react-native` to prevent this kind of things from happening.

**Comment by anujjainme** [comment]
I noticed the lottie files above version 5.5.* are crashing for me with the keyframe issue for my lottie react native 3.5.0

**Comment by VictorioMolina** [comment]
I am using Expo 39, and lottie-react-native 3.5.0. On android, a lottie file with version 5.6.10 is crashing my app.

**Comment by Trojan1988th** [comment]
Issue still here.  Fatal error "keyframe issue".  Android

**Comment by Elliotbaz** [comment]
2024 February. This is still an issue.  This is just unbelievable

**Comment by OmarKhattab** [comment]
@Elliotbaz we can fork this repo and fix it

**Comment by mzdon** [comment]
If anyone is still experiencing this issue I may have found a workaround.

I have several Lottie `.json` files stored in an S3 bucket. If I provide an asset object containing a `uri:` property as the `source` prop of a `LottieView`, iOS app will usually crash. The issue looks like it might be that the native Lottie implementation is fetching the remote asset multiple times leading to memory issues.

If I fetch the `.json` file up front, parse it into an `AnimationObject` and pass the object to the `LottieView` instead of passing the asset object containing the uri, it seems to work just fine.

### Fetch hook impl (super simple)
```
export function useFetchedAnimationObject(uri: string, onError: (error: string) => void) {
    const [animation, setAnimation] = React.useState<AnimationObject | undefined>();
    React.useEffect(() => {
        // We are fetching this object explicitly to avoid multiple fetches
        // at the native layer in the Lottie library.
        async function fetchAnimation() {
            try {
                const response = await fetch(uri);
                if (!response.ok) {
                    throw new Error(`[${response.status}] ${response.statusText}`);
                }
                const json = (await response.json()) as AnimationObject;
                setAnimation(json);
            } catch (error: NotWorthIt) {
                onError(error?.message ?? String(error));
            }
        }

        fetchAnimation();
    }, [uri, onError]);

    return animation;
}
```

### Usage
```
const { uri } = getCalibrationAsset(side); // this returns an object like { uri: string }
const animationObject = useFetchedAnimationObject(uri, handleAnimationFailure);

...

return (
  ...
  {animationObject && (
    <ReanimatedLottieView
      animatedProps={animatedProps}
      progress={animationDriver}
      source={animationObject}
      onAnimationFailure={handleAnimationFailure}
    />
  )}
  ...
);
```

**Comment by faizansahib** [comment]
expo app crahs when use LottieView

**Comment by faizansahib** [comment]
In Samsung S25, LottieView just shows 1 frame
