### ISSUE TITLE
Absolutely positioned lottie-view, wrong animation position

### ISSUE THREAD

**Issue by ospfranco** [lottie-react-native/lottie-react-native#663]
### Description

Hey! I'm trying to create a simple animation using a world map and some absolutely positioned lottie views.

Basically I have a View with a absolutely positioned image and some absolutely positioned lottie views, the views have a size applied via the style prop, but they are not show in the current view because somehow the viewport (I think it is the view port) is not respecting the width/height attributes:

I added an orange background to show where the points "should" be:

![Screenshot 2020-06-15 at 15 45 31](https://user-images.githubusercontent.com/1634213/84664786-53067300-af1f-11ea-9441-183d89b2a487.JPG)

Code:
```javascript
<View
        style={{ height: 222, width: 320, overflow: 'hidden' }}
      >
        <Image
          source={images.WorldMap2}
          style={{ height: 320, width: 320 }}
          resizeMode='contain'
        />
        {dots.map((d, ii) => {
          return (
            <LottieView
              key={`map-tactical-dot-${d[0]}-${d[1]}-${ii}`}
              source={animations.mapDot}
              autoPlay
              style={{
                position: `absolute`,
                left: d[0],
                top: d[1],
                height: 10,
                width: 10,
                backgroundColor: 'orange'
              }}
              duration={6000}
            />
          )})}
      </View>
```
![Screenshot 2020-06-15 at 15 45 42](https://user-images.githubusercontent.com/1634213/84664789-539f0980-af1f-11ea-8c96-64044ea8cb8d.JPG)

Here I remove a fixed value so you can see the displacement of the actual "position" and where the lottie animation actually gets positioned:

```javascript
left: d[0] - 100,
top: d[1] - 100,
```

### versions
System:
    OS: macOS 10.15.5
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 614.24 MB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.2.0 - /usr/local/bin/node
    Yarn: 1.22.0 - ~/.volta/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 27, 28, 29
      Build Tools: 27.0.3, 28.0.3, 29.0.0
      System Images: android-28 | Google Play Intel x86 Atom, android-R | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_212 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: 0.62.2 => 0.62.2
  npmGlobalPackages:
    *react-native*: Not Found

Lottie:
"lottie-ios": "3.1.3",
"lottie-react-native": "^3.4.0"

**Comment by ospfranco** [comment]
If I only leave one lottie view inside my render loop, like this:

```javascript
{dots.map((d, ii) => {
          return (
            <LottieView
              key={`dot-${d[0]}-${d[1]}-${ii}`}
              source={animations.mapDot}
              autoPlay
              style={{
                position: `absolute`,
                height: 20,
                width: 20,
                left: 0 + ii * 40,
                top: 30 + ii * 40,
                backgroundColor: 'red'
              }}
              duration={6000}
            />
          )
```

I get this:

![Screenshot 2020-06-15 at 16 03 58](https://user-images.githubusercontent.com/1634213/84666816-d923b900-af21-11ea-803b-17b947665c35.JPG)

**Comment by ospfranco** [comment]
One more try, I've removed the loop and placed a single lottie view inside the container:

![Screenshot 2020-06-15 at 16 11 59](https://user-images.githubusercontent.com/1634213/84667673-f60cbc00-af22-11ea-8aa5-57f8c96ba8a7.JPG)

```javascript
<View
        style={{ height: 222, width: 320, overflow: 'hidden' }}
      >
        <Image
          source={images.WorldMap2}
          style={{ height: 320, width: 320 }}
          resizeMode='contain'
        />

        <LottieView
          source={animations.mapDot}
          style={{ height: 20, width: 20, position: 'absolute', top: 50, left: 50, backgroundColor: 'orange' }}
          autoPlay
          duration={6000}
        />
      </View>
```

**Comment by ospfranco** [comment]
Workaround for now is to place the lottie view inside of another view, and have the parent view absolutely positioned

**Comment by samslow** [comment]
Same to me

**Comment by samslow** [comment]
Same to me. and if you debug on Chrome Developer tools through pointer(cmd + shift + c). then they align thet position. so curiuse 🤔

**Comment by ujeon** [comment]
Do you have the latest information on this issue?
