### ISSUE TITLE
The maven plugin has been deprecated. This is scheduled to be removed in Gradle 7.0. Please use the maven-publish plugin instead.

### ISSUE THREAD

**Issue by heron2014** [lottie-react-native/lottie-react-native#668]
## Description
Deprecation warning:
The maven plugin has been deprecated. This is scheduled to be removed in Gradle 7.0. Please use the maven-publish plugin instead.

## Steps to Reproduce
./gradlew --warning-mode all

## Message
> Configure project :lottie-react-native
The maven plugin has been deprecated. This is scheduled to be removed in Gradle 7.0. Please use the maven-publish plugin instead.
        at gradle_maven_push_2flms8ezl2ddr02n0ay4w2si9.run(/Users/..../node_modules/lottie-react-native/src/android/gradle-maven-push.gradle:17)
        (Run with --stacktrace to get the full stack trace of this deprecation warning.)

## Versions
"lottie-react-native": "3.4.0",
"react": "16.13.1",
"react-native": "0.62.2"

Does anyone has this warning?

**Comment by Maddumage** [comment]
I got the same error when I'm going to get a release build. Any solutions?

**Comment by Sphinxs** [comment]
Update?

**Comment by uusa35** [comment]
same here , any updates ?

**Comment by fiznool** [comment]
FWIW this is the only third party dependency in one of my projects which is holding back the use of gradle 7, and hence java 16. ATM it means pinning to JDK 1.8 which (although suggested for use by the built-in React Native template) is unsupported and due for end-of-life.

Here's some further information on the changes that are necessary: https://docs.gradle.org/6.7/userguide/upgrading_version_5.html#legacy_publication_system_is_deprecated_and_replaced_with_the_publish_plugins

**Comment by anuragdadheech** [comment]
Same error, can't upgrade to gradle 7

**Comment by rosnaib11** [comment]
+1 got same issue when building assembleRelease

**Comment by QuintonC** [comment]
+1 same issue, can we get this resolved ASAP please?

**Comment by joshuapinter** [comment]
According to [this](https://discuss.gradle.org/t/mavendeployment-deprecated-with-gradle-6-3/36096), `MavenDeployment` was deprecated in Gradle 6.3 and removed entirely in Gradle 7. 

I just upgraded to Gradle 7, as Android Studio is now prompting Users to do this and my build fails with: 

```
node_modules/lottie-react-native/src/android/gradle-maven-push.gradle': 46: unable to resolve class MavenDeployment 
   @ line 46, column 26.
             beforeDeployment { MavenDeployment deployment -> signing.signPom(deployment) }
```

I added another Issue for this specifically [here](#794).

**Comment by felansu** [comment]
+1

**Comment by makahn64** [comment]
+1 Bitrise builds all fail now too.

**Comment by rgr14** [comment]
+1

**Comment by emilioicai** [comment]
Can you try updating to the latest version of `lottie-react-native`?

**Comment by eduardofinotti** [comment]
+1

**Comment by renie** [comment]
+1

**Comment by benkhlifafahmi** [comment]
+1

**Comment by anhtuank7c** [comment]
+1
