### ISSUE TITLE
LottieAnimationViewManager.java uses or overrides a deprecated API.

### ISSUE THREAD

**Issue by rubek-joshi** [lottie-react-native/lottie-react-native#669]
### Description

The package fails to compile in the latest react native version (i.e. 0.63.0).

### Steps to Reproduce

1. Create react native project in version 0.63.0
2. Add this package and compile.

**Expected behavior:** The app compiles and runs.

**Actual behavior:** Build fails with the error message: `LottieAnimationViewManager.java uses or overrides a deprecated API.`

### Versions
"react-native": "0.63.0",
"lottie-react-native": "^3.4.0",
"lottie-ios": "3.1.3",

**Comment by savefolla** [comment]
just updated to react-native 0.63.0, have the same issue

**Comment by Aung-Myint-Thein** [comment]
Is it on dev or release apk?

**Comment by savefolla** [comment]
release for me. also using `--no-jetifier` seems to make it work

**Comment by rubek-joshi** [comment]
dev for me, haven't tried it on release.

**Comment by floelm** [comment]
having the same issue when upgrading to latest RN

**Comment by MohammadShahbaziP** [comment]
same issue on dev

**Comment by vikil143** [comment]
same issue when upgrade RN version 63

**Comment by savefolla** [comment]
> > release for me. also using `--no-jetifier` seems to make it work
> 
> @savefolla where did you put this line?

`react-native run-android --no-jetifier`

**Comment by RicardoDolNL** [comment]
> release for me. also using `--no-jetifier` seems to make it work

Does not work for me.

My version:
_"lottie-ios": "3.1.8",
"lottie-react-native": "^3.5.0",
"react-native": "0.63.2",_

**Comment by yuriedmundo** [comment]
I have the same problem RN 0.63.2

**Comment by sudheepkr** [comment]
I have same issue .Any one resolved??
The issue I rectified in my project .I created RN 0.63.3 and i installed Lottie module  its working But my project have several npm  module . Then i noticed i have bottom tab npm ie  react-navigation/bottom-tabs its using react-native-screens npm .If i uninstall react-native-screens  the error will gone .

**Comment by sudheepkr** [comment]
Issue resolved Me.
You need to change :android->build.gradle **minSdkVersion** version . Mine was 16 i changed to 28
Its working .There is no build error now.

**Comment by marcelxsilva** [comment]
> Issue resolved Me.
> You need to change :android->build.gradle **minSdkVersion** version . Mine was 16 i changed to 28
> Its working .There is no build error now.
> https://user-images.githubusercontent.com/38225866/98339659-13f1cf00-2032-11eb-9382-a1fccc8fe404.jpeg

Thanks @sudheepkr, change `minSdkVersion` to `28` work for me!!

Versions dependencies:

```
    "react-native": "0.64.1",
    "lottie-react-native": "^5.1.4",

``
