### ISSUE TITLE
Cannot import Lottie in Typescript

### ISSUE THREAD

**Issue by kockok** [lottie-react-native/lottie-react-native#670]
### Description

package not resolving to `/node_modules` and thus `LottieView` component is not imported.

![Screenshot 2020-07-19 at 3 33 22 PM](https://user-images.githubusercontent.com/232541/87869943-6b622580-c9d6-11ea-9ed3-0549d7a3706f.png)

### Steps to Reproduce

1. `npm i --save lottie-react-native`
`npm i --save lottie-ios@3.1.3`
2. 
```
["allowSyntheticDefaultImports": true, 
    "esModuleInterop": true       
```
3. Paste the sample code:
```
import React from 'react';
import LottieView from 'lottie-react-native';

export default class WelcomeScreen extends React.PureComponent {
  render() {
    return <LottieView source={require('./logo.json')} autoPlay loop />;
  }
}
```

**Expected behavior:** Normally renders the animation

**Actual behavior:**

![Screenshot 2020-07-19 at 3 37 49 PM](https://user-images.githubusercontent.com/232541/87869935-61d8bd80-c9d6-11ea-8017-4f005da5f8c9.png)

### Versions

```
    "lottie-ios": "^3.1.3",
    "lottie-react-native": "^3.4.0",
    "react": "16.13.1",
    "react-native": "0.63.0",
```

**Comment by RayKay91** [comment]
did you manage to import it?
