### ISSUE TITLE
Support for React Native colorFilters

### ISSUE THREAD

**Issue by rossbulat** [lottie-react-native/lottie-react-native#671]
It appears that `colorFilters` do not work on React Native right now. Having the ability to easily change shape colours is essential for adoption (light and dark theming, active and inactive icons big use cases).

This has been discussed [here](https://stackoverflow.com/questions/61500619/how-do-i-use-colorfilter-with-react-native-lottie) with a messy workaround, but this is not scalable.

This is one of two issues preventing me from adopting Lottie in React Native.

**Comment by Noitidart** [comment]
I added a tool to that stackoverflow topic to help customize colors until `colorFilters` is fixed - https://colorize-react-native-lottie.netlify.app/

**Comment by michaelbayday** [comment]
@Noitidart  just wanted to say that this is really cool. they should actually feature your tool and it was nice you built a quick demo for it

**Comment by Noitidart** [comment]
Thank you @michaelbayday! :)

**Comment by RBrNx** [comment]
@Noitidart Genuinely great tool, very easy to use!

If it helps anyone I wrote a version of it that uses the [color package](https://www.npmjs.com/package/color) instead of `tinycolor2`

```js
import Color from 'color';
import set from 'lodash.set';

const colouriseLottie = (json, colorByPath) => {
  const nextJson = JSON.parse(JSON.stringify(json));

  Object.entries(colorByPath).forEach(([path, color]) => {
    // incase undefined/null/falsy is passed to color
    if (!color) return;
    const rgbValues = Color(color).object();
    const rFraction = rgbValues.r / 255;
    const gFraction = rgbValues.g / 255;
    const bFraction = rgbValues.b / 255;

    const pathParts = path.split('.');
    set(nextJson, [...pathParts, 0], rFraction);
    set(nextJson, [...pathParts, 1], gFraction);
    set(nextJson, [...pathParts, 2], bFraction);
  });

  return nextJson;
};

export default colouriseLottie;

```
-------------------------
Using it I was able to easily add theme support to my lottie animations 😄 

```js
const indicatorBackground = {
  light: '#1b1b1b',
  dark: '#a2a2a2',
};

const LoadingIndicator = ({ size, style }) => {
  const { currentTheme } = useCurrentTheme();

  const colorizedSource = useMemo(
    () =>
      colouriseLottie(LoadingAnimation, {
        // Shape Layer 1.Shape 1.Stroke 1
        'layers.1.shapes.0.it.1.c.k': indicatorBackground[currentTheme],
      }),
    [currentTheme],
  );

  return <LottieAnimation style={style} source={colorizedSource} size={size} autoPlay loop speed={0.75} />;
};
```

**Comment by Noitidart** [comment]
Thank you @RBrNx! :)

**Comment by Olalexy1** [comment]
> ```js
> colouriseLottie
> ```

Thanks for this fix. You saved me a lot of time

**Comment by Olalexy1** [comment]
> @Noitidart Genuinely great tool, very easy to use!
> 
> If it helps anyone I wrote a version of it that uses the [color package](https://www.npmjs.com/package/color) instead of `tinycolor2`
> 
> ```js
> import Color from 'color';
> import set from 'lodash.set';
> 
> const colouriseLottie = (json, colorByPath) => {
>   const nextJson = JSON.parse(JSON.stringify(json));
> 
>   Object.entries(colorByPath).forEach(([path, color]) => {
>     // incase undefined/null/falsy is passed to color
>     if (!color) return;
>     const rgbValues = Color(color).object();
>     const rFraction = rgbValues.r / 255;
>     const gFraction = rgbValues.g / 255;
>     const bFraction = rgbValues.b / 255;
> 
>     const pathParts = path.split('.');
>     set(nextJson, [...pathParts, 0], rFraction);
>     set(nextJson, [...pathParts, 1], gFraction);
>     set(nextJson, [...pathParts, 2], bFraction);
>   });
> 
>   return nextJson;
> };
> 
> export default colouriseLottie;
> ```
> 
> Using it I was able to easily add theme support to my lottie animations 😄
> 
> ```js
> const indicatorBackground = {
>   light: '#1b1b1b',
>   dark: '#a2a2a2',
> };
> 
> const LoadingIndicator = ({ size, style }) => {
>   const { currentTheme } = useCurrentTheme();
> 
>   const colorizedSource = useMemo(
>     () =>
>       colouriseLottie(LoadingAnimation, {
>         // Shape Layer 1.Shape 1.Stroke 1
>         'layers.1.shapes.0.it.1.c.k': indicatorBackground[currentTheme],
>       }),
>     [currentTheme],
>   );
> 
>   return <LottieAnimation style={style} source={colorizedSource} size={size} autoPlay loop speed={0.75} />;
> };
> ```

Thanks for this fix!

**Comment by Olalexy1** [comment]
> I added a tool to that stackoverflow topic to help customize colors until `colorFilters` is fixed - https://stackoverflow.com/questions/61500619/how-do-i-use-colorfilter-with-react-native-lottie#comment117312978_62790537
> 
> Open source if anyone would like to send a PR - https://github.com/Noitidart/Colorize-Lottie

Bless you for this amazing tool.

**Comment by Noitidart** [comment]
Thank you!

**Comment by ahmedam55** [comment]
> I added a tool to that stackoverflow topic to help customize colors until `colorFilters` is fixed - https://stackoverflow.com/questions/61500619/how-do-i-use-colorfilter-with-react-native-lottie#comment117312978_62790537
> 
> Open source if anyone would like to send a PR - https://github.com/Noitidart/Colorize-Lottie

What a great tool! Thanks a lot @Noitidart!
