### ISSUE TITLE
Animateless

### ISSUE THREAD

**Issue by AdeilsonESilva** [lottie-react-native/lottie-react-native#675]
### Description

Hello, I have the following animation done in AE: [https://lottiefiles.com/share/7F35uC](https://lottiefiles.com/share/7F35uC)
However, when importing into my project it stops and blinks at the end of the animation.
![photo5021921314809686158](https://user-images.githubusercontent.com/19808865/90248246-b40ed200-de0e-11ea-9e6d-d13c98c1dae4.jpg)

Any idea?

### Steps to Reproduce

1. Create an project
2. Install de package
3. Import animation

**Expected behavior:** Animated image

**Actual behavior:** Animateless

### Versions

{
  PicktowCustomer: '0.0.1',
  npm: '6.14.7',
  ares: '1.16.0',
  brotli: '1.0.7',
  cldr: '37.0',
  http_parser: '2.9.3',
  icu: '67.1',
  llhttp: '2.0.4',
  modules: '72',
  napi: '6',
  nghttp2: '1.41.0',
  node: '12.18.3',
  openssl: '1.1.1g',
  tz: '2019c',
  unicode: '13.0',
  uv: '1.38.0',
  v8: '7.8.279.23-node.39',
  zlib: '1.2.11'
}

**Comment by Adiiiii** [comment]
Hey @AdeilsonESilva , tried replicating the issue , but it turns out the playable animation is not even visible on my build.
whats the RN and Lottie version you are using ?


My RN app is using.
> {
> "react-native": "0.63.2",
> "lottie-react-native": "^3.5.0",
> }

**Comment by AdeilsonESilva** [comment]
> Hey @AdeilsonESilva , tried replicating the issue , but it turns out the playable animation is not even visible on my build.
> whats the RN and Lottie version you are using ?
> 
> My RN app is using.
> 
> > {
> > "react-native": "0.63.2",
> > "lottie-react-native": "^3.5.0",
> > }

Hey @Adiiiii my version
{
    "lottie-ios": "3.1.8",
    "lottie-react-native": "^3.5.0",
    "react-native": "0.61.5",
}

**Comment by AdeilsonESilva** [comment]
@Adiiiii I got another animation straight from the site and had the same problem.
https://lottiefiles.com/27587-test

**Comment by AdeilsonESilva** [comment]
@Adiiiii pls look my repo https://github.com/AdeilsonESilva/lottie-test same error....

**Comment by Chipzstar** [comment]
I too am also facing the same issue, I am using:
- react-native v0.62.2
- lottie-react-native: 3.5.0

running on android device/emulator, using a premade json animation file, animation refuses to play or show on the screen 😐
