### ISSUE TITLE
Release Lottie File on unmount

### ISSUE THREAD

**Issue by NicholasNations** [lottie-react-native/lottie-react-native#676]
I am running quite a few Lottie Animations in my app and every time it runs, the animation never releases. Is there a way to clear the local memory after running the animation? At least the current animation. My memory get's up to 2gbs pretty fast.  I am running animations all over the app and every time I unmount and come back, it adds the same animation into the memory. I start at 470 mbs, then I see an animation, i have 500 mbs, then I leave, it stays at 500 mbs, then I come back to the same animation page and it goes up to 530 mbs. Unmounting the component seems to make it stick in the internal memory. Any information as to why why the animation never releases and how to release it would be greatly appreciated. 

Here is a component that is never released from memory:
  <LottieView
            style={{height: '100%', width: '100%'}}
            source={source}
            ref={animation}
            enableMergePathsAndroidForKitKatAndAbove
            autoPlay
     />

**Comment by taneba** [comment]
I was facing the similar issue, and in my case it was solve by running `reset` when component unmounts.
I created a helper hook that can start animation on mount and reset on unmount:

```
export function useLottieAnim() {
  const animation = useRef<LottieView>(null)

  useEffect(() => {
    if (animation.current) {
      animation.current.play()
    }
    return () => {
      animation.current && animation.current.reset()
    }
  }, [])

  return animation
}

// usage
const animation = useLottieAnim()

<LottieView
 source={source}
 ref={animation}
/>
```

**Comment by wanderSX** [comment]
@NicholasNations  Did the solution above helped you, because it did not for me. Could it be because i have a dynamic source?

**Comment by jogoool** [comment]
same issue here, reset is not helping.

**Comment by nikitph** [comment]
This is a critical bug. The reset does help but this needs to be addressed natively

**Comment by longnc100500** [comment]
same issue

**Comment by keselme90** [comment]
@longnc100500 @nikitph Did you guys found a solution?

**Comment by nikitph** [comment]
`  useFocusEffect(
    useCallback(() => {
      if (animation.current) {
        animation.current.play();
      }
      return () => {
        animation.current && animation.current.reset();
      };
    }, []),
  );`

**Comment by nikitph** [comment]
this will help u get back the ram after the animation finishes and u nav out 
but this still needs to be addressed in terms of better ram use

**Comment by pSapien** [comment]
Not sure why this issue has been closed, it still persists. I have raised another issue for this
https://github.com/lottie-react-native/lottie-react-native/issues/1010

**Comment by matinzd** [comment]
Fixed by https://github.com/lottie-react-native/lottie-react-native/pull/1055.
