### ISSUE TITLE
Loop set to false but when animation end it goes to start

### ISSUE THREAD

**Issue by sclavijo93** [lottie-react-native/lottie-react-native#681]
### Description
I set the loop prop to false, but when the animation ends it goes to the first frame again. Is there a way to stay in the last frame when the animation ends?

**Comment by sclavijo93** [comment]
Hi @mirko1075 it seems to work right now, I'm using the following versions:
```
    "lottie-ios": "3.1.8",
    "lottie-react-native": "^4.0.2",
```

Maybe this snipped can help you, I'm not sure if it's the best way but it works 😅 

```jsx
import LottieView from 'lottie-react-native';
import React, { useCallback, useImperativeHandle, useRef } from 'react';

const Lottie = (
  { loop, onAnimationFinish, finalFrame, ...props },
  forwardRef: any,
) => {
  let lottieRef = useRef(null);
  useImperativeHandle(forwardRef, () => lottieRef.current, []);

  const handleAnimationEnd = useCallback(() => {
    if (!loop && finalFrame) {
      lottieRef.current.play(finalFrame, finalFrame);
    }
    if (typeof onAnimationFinish === 'function') {
      onAnimationFinish();
    }
  }, []);

  return (
    <LottieView
      ref={lottieRef}
      loop={loop}
      onAnimationFinish={handleAnimationEnd}
      {...props}
    />
  );
};

export default React.forwardRef(Lottie);

```

**Comment by c6z3h** [comment]
Not sure if anyone still needs advice for this, but what seemed to work for me was going into the `animation.json` file, and changing the ending frame from a decimal point to a whole number. In my case it was `40.000016292334` or `39.9600016276042` and I just changed them to `40`.

Got the inspiration from [this stackoverflow discussion](https://stackoverflow.com/questions/64040762/how-to-get-total-number-of-frames-available-in-the-lottie-animation). So basically find all instances of "op" and change them to whole numbers (if they're not already)
