### ISSUE TITLE
json from remote url is not working

### ISSUE THREAD

**Issue by bantyK** [lottie-react-native/lottie-react-native#682]
Adding the package.json and the component to repro the issue. It is working fine if I give the json in the asset folder. But not when the url for the json is provided.
     
    {
      "name": "LottieSamples",
      "version": "0.0.1",
      "private": true,
      "dependencies": {
        "@types/jest": "^26.0.13",
        "@types/node": "^14.6.4",
        "@types/react": "^16.9.49",
        "@types/react-dom": "^16.9.8",
        "lottie-react-native": "^3.5.0",
        "react": "16.13.1",
        "react-native": "0.63.2",
        "typescript": "^4.0.2"
    },
    "devDependencies": {
        "@babel/core": "^7.11.6",
        "@babel/runtime": "^7.11.2",
        "@react-native-community/eslint-config": "^2.0.0",
        "babel-jest": "^26.3.0",
        "eslint": "^7.8.1",
        "jest": "^26.4.2",
        "metro-react-native-babel-preset": "^0.63.0",
       "react-test-renderer": "16.13.1"
      },
    }

Component.tsx
    
    import React, {Component} from 'react';
    import {Text, TouchableOpacity, View} from 'react-native';
    import LottieView from 'lottie-react-native';
    
    export default class MyAnimComp extends Component {

    render() {
        return (
            <View
                style={{
                    flex: 1,
                    alignItems: 'center',
                    justifyContent: 'center',
                    backgroundColor: '#19BAE2',
                }}>
                <Text>Hello</Text>

                <LottieView
                    source={{uri: 'https://assets10.lottiefiles.com/datafiles/c56b08b89932c090a0948b53fd58427d/data.json'}}
                    autoPlay={true}
                    loop={true}
                />
            </View>
        );
    }
}
`

Error screen
![ex](https://user-images.githubusercontent.com/8079844/93309804-92e03d80-f821-11ea-8fd3-3a29fcb6ba68.png)

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** Animation should load

**Actual behavior:** Animation is not loading.

### Versions

You can get this information from executing `npm version`.

**Comment by jetBn** [comment]
can you slove it ?

**Comment by ahmedrowaihi** [comment]
same to me that upsets me a lot....... having troubles with passing URL for dynamically maping

**Comment by Rajan-Savaliya-spt** [comment]
not working..any soluion...

**Comment by Rajan-Savaliya-spt** [comment]
i find a solution ...
`            <LottieView
                source={YOUR_JSON_DATA}
                autoPlay={true}
                loop={true}
            />
`

**Comment by ahmedrowaihi** [comment]
I guys I have found a solution which is:
- store the LottieJson in a variable first after fetching it // let somejson = fetch("<jsonURL>")
- then render it with a condition like:
{!somejson ? null : <LottieView  source={somejson} autoPlay loop  /> }

and it will all work fine, you just need to fetch it first or cache it or store in a variable

**Comment by surajprasad13** [comment]
Same here
