### ISSUE TITLE
Module compiled with Swift 5.2.4 cannot be imported by the Swift 5.3 compiler

### ISSUE THREAD

**Issue by bouchja1** [lottie-react-native/lottie-react-native#683]
### Description

I have upgraded XCode version to 12.0 and suddenly it is not possible to build the project because there is an error shown:

AnimationViewManagerModule.swift:5:8: error: module compiled with Swift 5.2.4 cannot be imported by the Swift 5.3 compiler

### Steps to Reproduce

1. update your XCode version to 12.0
2. using lottie-react-native v3.5.0
3. react-native run-ios

**Expected behavior:** [What you expected to happen]

- the project is built correctly and my app is runnin

**Actual behavior:** [What actually happened]

/Users/janbouchner/cfhero/cfhero-react/node_modules/lottie-react-native/src/ios/LottieReactNative/AnimationViewManagerModule.swift:5:8: error: module compiled with Swift 5.2.4 cannot be imported by the Swift 5.3 compiler: /Users/janbouchner/cfhero/cfhero-react/ios/build/CFHero/Build/Products/Debug-iphonesimulator/lottie-ios/Lottie.swiftmodule/x86_64-apple-ios-simulator.swiftmodule
import Lottie
       ^

** BUILD FAILED **

The following build commands failed:
	CompileSwift normal x86_64 /Users/janbouchner/cfhero/cfhero-react/node_modules/lottie-react-native/src/ios/LottieReactNative/AnimationViewManagerModule.swift
	CompileSwift normal x86_64 /Users/janbouchner/cfhero/cfhero-react/node_modules/lottie-react-native/src/ios/LottieReactNative/ContainerView.swift
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(3 failures)

### Versions

- lottie-ios v3.1.8
- lottie-react-native v 3.5.0

**Comment by magrinj** [comment]
@bouchja1 Ok, I think I've found a way to build, I've done the following steps and it's working:

- Remove `Podfile.lock` in ios directory
- Remove `Pods` directory in ios directory
- Run `pod update` in ios directory
- Got to Xcode -> Preferences -> Locations
- Check that the command line tools user is Xcode 12.0.0
- Under `Derived Data:` you have a path with a small arrow, click on the arrow and delete `DerivedData` from directory
- Run Product -> Clean
- Try yo build your project again

Hope that's going to help !

**Comment by bouchja1** [comment]
> @bouchja1 Ok, I think I've found a way to build, I've done the following steps and it's working:
> 
> * Remove `Podfile.lock` in ios directory
> * Remove `Pods` directory in ios directory
> * Run `pod update` in ios directory
> * Got to Xcode -> Preferences -> Locations
> * Check that the command line tools used is Xcode 12.0.0
> * Under `Derived Data:` you have a path with a small arrow, click on the arrow and delete `DerivedData` from directory
> * Run Product -> Clean
> * Try yo build your project again
> 
> Hope that's going to help !

Thanks! This worked also for me. You probably know this but there is an alias to clear "Pods" directory. Instead of deleting the whole folder you can use the command:

`pod deintegrate`

And I am stopping to be a "smart" guy :D

**Comment by magrinj** [comment]
@bouchja1 Haha no problem, I know that command but I'm not using it quite often it's why I'm doing it in the old basic way ^^

**Comment by schumannd** [comment]
In case you build the app using the `xcodebuild` command and have a paramter -derivedDataPath, make sure to clear the files there.

**Comment by yabao-zy** [comment]
@bouchja1 thanks very much , beacusn help me

**Comment by dodody** [comment]
@magrinj thank you ㅠㅜㅠㅜ love you🥺
