### ISSUE TITLE
Background not appearing / hidden layers visible

### ISSUE THREAD

**Issue by lukehamilton** [lottie-react-native/lottie-react-native#687]
The background is not appearing in RN when I export with Lottie. I've spent a few hours and have made no progress.

Has anyone else encountered this? Or have any advice?

The layers that make the inside fluid should not be visible outside of the bottle. This seems to work in lottie web but not in react native.

![animation-example](https://user-images.githubusercontent.com/339341/94354453-32cf6f80-0049-11eb-81a5-dc059357d68c.gif)

**Comment by AliRehman7141** [comment]
Any update?

**Comment by matinzd** [comment]
Please test the JSON file with Lottie Files app. If it is not working there either, then you can reopen the issue here. 

https://lottiefiles.com/mobile

**Comment by allisonadam81** [comment]
I believe I am running into this same issue here. This is a newspaper, and the dark grey rectangles are supposed to appear over a grey newspaper background. But instead, there is no background --
![simulator_screenshot_5F134091-2B04-4A9B-BC7E-6DB9571331EC](https://user-images.githubusercontent.com/98195968/236345692-f046dddc-2ab5-4fc5-a186-ee00388ab94d.png)

Here is the lottie - https://iconscout.com/lottie/newspaper-6431337

I have the most up to date lottie-react-native 5.1.5 and lottie-ios 3.4.0. RN v .66.5.0. The lottie player on the website was working correctly and displays everything as expected. But in the app, it does not work and I can not figure out why.
