### ISSUE TITLE
iOS - Setting Speed prop to 0 causes onAnimationFinish callback to fire

### ISSUE THREAD

**Issue by NeilMcGuiness** [lottie-react-native/lottie-react-native#688]
### Description

DISCLAIMER: This bug report may actually be referencing two bugs, though one may be related to the other. If this is not helpful I am happy to file a second bug report for the other. 

#### Main Bug 

On iOS, when setting the Speed prop to 0 it will cause the onAnimationFinish callback to fire. However the animation does not jump to its last frame. 

#### Secondary Bug 

Also only on iOS, even when setting the Loop prop to false the animation loops

Neither of these problems occur on Android using the same code.

### Steps to Reproduce

Context: I am using the LottieView as the main return value of a Functional component called 'RaceRunner' and controlling the animation speed using a useState hook variable called 'runnerSpeed' (the animations are of running avatars as part of a racing game). The RaceRunner component subscribes to a sensor data Subject (observer pattern) which updates my Component with new data which will subsequently be used to set the 'runnerSpeed' state variable.

1. Load a JS Object of an animation with require() into a LottieView Component
2. Set the autoPlay prop to **true**, and the loop prop to **false**
3. Supply the speed prop with a state variable.
4. Allow the speed state variable to be 0 (either initialised as 0 or set to 0 later dynamically)

**Expected behavior:** [What you expected to happen]

As on Android, I expect the animation to simply stop, as if paused when the speed is set to 0, and not fire the onAnimationFinished callback.

With regards to the secondary looping bug, i expect the animation not to repeat when loop is set to false.

**Actual behavior:** [What actually happened]

When the speed prop is set to 0, the onAnimationFinish callback is called. Also when the animation actually does reach its end, the callback is not fired. (I imagine because it has already been fired before its real end) And when the animation reaches its end it simply returns to the start of the animation as if looping.

### Versions

"react": "16.9.0",
"react-native": "0.61.4",
"lottie-ios": "3.1.8",
"lottie-react-native": "^3.5.0",

**Comment by MFrat** [comment]
Any solution?
