### ISSUE TITLE
Android emulator animation not showing up

### ISSUE THREAD

**Issue by wilq32-pwitkowski** [lottie-react-native/lottie-react-native#690]
### Description
When trying to run simple animation on Android Emulator it only shows last frame of the animation. It does work fine on real Android device, or in iOS Simulator.

### Steps to Reproduce

package.json:

    "react-native": "^0.63.0",
    "lottie-ios": "^3.1.8",
    "lottie-react-native": "^3.5.0",

code:

    import LottieView from 'lottie-react-native'
    import animationCard from 'card.json'

    (...)
      <LottieView source={animationCard} autoPlay loop/>

**Expected behavior:** Animations runs and goes in loop on all devices

**Actual behavior:** Shows last frame of the animation, no animation is shown at all on Android Emulator. Same code works for iOS and real Android device.

### Versions

{
  rndify: '0.1.0',
  npm: '6.14.5',
  ares: '1.16.0',
  brotli: '1.0.7',
  cldr: '37.0',
  icu: '67.1',
  llhttp: '2.0.4',
  modules: '83',
  napi: '6',
  nghttp2: '1.40.0',
  node: '14.3.0',
  openssl: '1.1.1g',
  tz: '2019c',
  unicode: '13.0',
  uv: '1.37.0',
  v8: '8.1.307.31-node.33',
  zlib: '1.2.11'
}

**Comment by renanborgez** [comment]
precisely the same problem in Android and iOS

```
"lottie-ios": "^3.1.8",
 "lottie-react-native": "^3.5.0",
"react-native": "^0.63.3",
```

**Comment by GabrielBlink32** [comment]
Same problem in Android, only in iOS works.
`"lottie-react-native": "~3.1.8",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-39.0.4.tar.gz",`

**Comment by imcyee** [comment]
Calling it with ref, autoplay, loop does not work. Work in device.
But controlling it with `Animated` progress works for android emulator.
