### ISSUE TITLE
Animation stops when progress is changed mid animation

### ISSUE THREAD

**Issue by Jacobrc2018** [lottie-react-native/lottie-react-native#691]
### Description

I am trying to create a timer animation and when the app is closed to the background, the animation stops and I would like to resume it from where it should be. I am using AppState to update the progress, but when the progress changes, it stops the animation and is unable to be resumed/started.

### Steps to Reproduce

1. Play animation 
2. Change the progress of the animation while animating
3. Animation stops, using play/resume does not resume it.

**Expected behavior:** The animation to continue playing after the progress changed and finished it's duration

**Actual behavior:** Animation stops and does not resume

### Versions

You can get this information from executing `npm version`. react-native-lottie v3.5.0

**Comment by Jacobrc2018** [comment]
I'd love if this could get fixed or an option to continue the timing of the animation when the app is in the background, but I found a  way around this issue by getting the % of duration used so far then multiplying that by the total frames in my animation, then using play(%*totalFrames, totalFrames)

**Comment by TechySharnav** [comment]
Same here :(

**Comment by TechySharnav** [comment]
Nvm, got it working!! Used setInterval() in ComponentDidMount() to update the progress by adding (frameToStart*100/TotalFrames*100) each time in the state, after every (1/frameRateofAnimation) seconds, and adding 'progress={this.state.progress}' to LottieView.
