### ISSUE TITLE
while building the iOS project, I am getting error:

### ISSUE THREAD

**Issue by Pratibhabdl** [lottie-react-native/lottie-react-native#693]
### Description

[Description of the bug]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

You can get this information from executing `npm version`.

**Comment by Pratibhabdl** [comment]
Showing All Errors Only, Filtering for "error".
: Closure #1 (Foundation.Data?, __C.NSURLResponse?, Swift.Error?) -> () in static Lottie.Animation.loadedFrom(url: Foundation.URL, closure: (Lottie.Animation?) -> (), animationCache: Lottie.AnimationCacheProvider?) -> () in liblottie-ios.a(AnimationPublic.o)

: Closure #1 (Foundation.Data?, __C.NSURLResponse?, Swift.Error?) -> () in static Lottie.Animation.loadedFrom(url: Foundation.URL, closure: (Lottie.Animation?) -> (), animationCache: Lottie.AnimationCacheProvider?) -> () in liblottie-ios.a(AnimationPublic.o)

: Closure #1 (Foundation.Data?, __C.NSURLResponse?, Swift.Error?) -> () in static Lottie.Animation.loadedFrom(url: Foundation.URL, closure: (Lottie.Animation?) -> (), animationCache: Lottie.AnimationCacheProvider?) -> () in liblottie-ios.a(AnimationPublic.o)

: "Foundation._convertNSErrorToError(__C.NSError?) -> Swift.Error", referenced from:

: Closure #2 () -> () in closure #1 (Foundation.Data?, __C.NSURLResponse?, Swift.Error?) -> () in static Lottie.Animation.loadedFrom(url: Foundation.URL, closure: (Lottie.Animation?) -> (), animationCache: Lottie.AnimationCacheProvider?) -> () in liblottie-ios.a(AnimationPublic.o)

: Lottie.AnimationView.__allocating_init(url: Foundation.URL, imageProvider: Lottie.AnimationImageProvider?, closure: (Swift.Error?) -> (), animationCache: Lottie.AnimationCacheProvider?) -> Lottie.AnimationView in liblottie-ios.a(AnimationViewInitializers.o)

: Lottie.AnimationView.__allocating_init(url: Foundation.URL, imageProvider: Lottie.AnimationImageProvider?, closure: (Swift.Error?) -> (), animationCache: Lottie.AnimationCacheProvider?) -> Lottie.AnimationView in liblottie-ios.a(AnimationViewInitializers.o)

: Lottie.AnimationView.__allocating_init(url: Foundation.URL, imageProvider: Lottie.AnimationImageProvider?, closure: (Swift.Error?) -> (), animationCache: Lottie.AnimationCacheProvider?) -> Lottie.AnimationView in liblottie-ios.a(AnimationViewInitializers.o)

: Reabstraction thunk helper from @escaping @callee_guaranteed (@guaranteed Foundation.Data?, @guaranteed __C.NSURLResponse?, @guaranteed Swift.Error?) -> () to @escaping @callee_unowned @convention(block) (@unowned __C.NSData?, @unowned __C.NSURLResponse?, @unowned __C.NSError?) -> () in liblottie-ios.a(AnimationPublic.o)

: Closure #1 (Foundation.Data?, __C.NSURLResponse?, Swift.Error?) -> () in static Lottie.Animation.loadedFrom(url: Foundation.URL, closure: (Lottie.Animation?) -> (), animationCache: Lottie.AnimationCacheProvider?) -> () in liblottie-ios.a(AnimationPublic.o)

: Closure #1 (Foundation.Data?, __C.NSURLResponse?, Swift.Error?) -> () in static Lottie.Animation.loadedFrom(url: Foundation.URL, closure: (Lottie.Animation?) -> (), animationCache: Lottie.AnimationCacheProvider?) -> () in liblottie-ios.a(AnimationPublic.o)

: Closure #1 (Foundation.Data?, __C.NSURLResponse?, Swift.Error?) -> () in static Lottie.Animation.loadedFrom(url: Foundation.URL, closure: (Lottie.Animation?) -> (), animationCache: Lottie.AnimationCacheProvider?) -> () in liblottie-ios.a(AnimationPublic.o)

: Closure #1 (Foundation.Data?, __C.NSURLResponse?, Swift.Error?) -> () in static Lottie.Animation.loadedFrom(url: Foundation.URL, closure: (Lottie.Animation?) -> (), animationCache: Lottie.AnimationCacheProvider?) -> () in liblottie-ios.a(AnimationPublic.o)

: "Swift._StringGuts.foreignErrorCorrectedGrapheme(startingAt: Swift.Int, endingAt: Swift.Int) -> Swift.Character", referenced from:

: "static Swift.DecodingError.dataCorruptedError<A where A: Swift.KeyedDecodingContainerProtocol>(forKey: A.Key, in: A, debugDescription: Swift.String) -> Swift.DecodingError", referenced from:

: "type metadata accessor for Swift.DecodingError", referenced from:

: "protocol witness table for Swift.DecodingError : Swift.Error in Swift", referenced from:

Please help me with this. I am building iOS project for the first time and not able to figure out any thing

**Comment by danghung24031992** [comment]
same
