### ISSUE TITLE
Blank screen

### ISSUE THREAD

**Issue by marcibk** [lottie-react-native/lottie-react-native#696]
### Description

Blank screen of Lottie. Not error while installing on device/building with pods. Probably a bug with iOS 14?

### Steps to Reproduce
   
iOS 14 Real Device.
```
  <LottieView
                source={require('../../assets/logoAnimation.json')}
                autoPlay
                style={{ height: 250, width: 250 }}
                loop
              />
```

**Expected behavior:** 

Show the animation

**Actual behavior:** 

Blank screen (white)

### Versions

    "lottie-ios": "^3.1.8",
    "lottie-react-native": "^3.5.0",
    "react": "16.13.1",
    "react-native": "0.63.3",

iOS 14

You can get this information from executing `npm version`.

**Comment by Thomaswaldick** [comment]
I'm also having this issue still

**Comment by Thomaswaldick** [comment]
I was able to get my iOS animation working (Android is still stuck on animation's first frame). I was using an unsupported animation for iOS so that's why nothing showed up

**Comment by joshuapinter** [comment]
FYI, we went through the painstaking process of updating from 0.59.10 to 0.60.6 just to get this working and after a few days of upgrade hell, Lottie works perfectly now without any monkeying around.

**Comment by BeyoncesHomeboy** [comment]
We are on the latest version on react native and I'm having the same issues with only getting blank screen. It works in react but not react native. I

**Comment by zhian-ot** [comment]
I'm also with version of react-native (0.63.3) and have the same issue...

**Comment by erickcrus** [comment]
same here

**Comment by dylanclements** [comment]
Same issue here
