### ISSUE TITLE
Android does not accept child components within LottieView

### ISSUE THREAD

**Issue by mark-quinn** [lottie-react-native/lottie-react-native#702]
### Issue
LottieView only accepts child components on iOS but **not** on Android.

### STR
Wrap anything between a <_LottieView>_ component. On iOS you'll see the wrapped element as expected but on Android it'll flash an error `com.airbnb.lottie.LottieAnimationView cannot be cast to android.view.ViewGroup`.

### Versions
RN: 0.61.5
Lottie-react-native: ^3.3.2

This has been tested on the simulator and also a physical device and both failed.

**Comment by roshansingh21** [comment]
@mark-quinn were you able to do any workaround?

**Comment by Leo2018Wu** [comment]
> were you able to do any workaround?

you can use position on child component
