### ISSUE TITLE
Build fail in Xcode12.2

### ISSUE THREAD

**Issue by wcly** [lottie-react-native/lottie-react-native#703]
![image](https://user-images.githubusercontent.com/23275036/99325466-62fcf700-28b1-11eb-8820-8db8bafc28f4.png)

any solution？

**version:** 
- "lottie-ios": "3.1.9",
- "lottie-react-native": "^3.3.1"
- "react-native": "0.61.5"
- xcode: Version 12.2 (12B45b)

**Comment by RobPando** [comment]
I was running into huge problems with this library but I am also using the new Mac m1. So if you are on apples new silicon the only way it worked for me was to go to **Finder** > **Applications** > **Right click on Xcode** > **Select Get Info**  and you will need to check the box to **Open with Rosetta**. After that open the project again clean and build and it should succeed.

**Comment by xgenem** [comment]
Running in Rosetta didn't really solve the issue for me.

**Comment by frankely** [comment]
Any updates on this?

**Comment by EvertonFerreira96** [comment]
platform :ios, '12.0'

**Comment by huy-lv** [comment]
all the above suggestion doesn't work
