### ISSUE TITLE
Can't load animation from local path 

### ISSUE THREAD

**Issue by schonfeld** [lottie-react-native/lottie-react-native#704]
### Description

The rn lottie library only supports loading animations using a pre-bundled asset name, or a whole JSON blob. Using the `{ uri: path }` syntax isn't currently supported, and results in a RN error (since the library treats that syntax as-if we supplied an animation JSON blob).

PR to follow

**Comment by BeyoncesHomeboy** [comment]
wait, is the reason why I can not get Lottie files to run in my projects? I can't even get it to run in a sandbox. 
`source={require("../public/4565-heartbeat-medical.json")}`

**Comment by schonfeld** [comment]
This would be the reason. This project seems a bit unmaintained, considering the number of open pull requests...

**Comment by BeyoncesHomeboy** [comment]
Is there a way around it? Put it on CDN and link to it?

I spent 3 days trying to figure out why this wasn't working...so frustrated.

**Comment by patrickkempff** [comment]
> This would be the reason. This project seems a bit unmaintained, considering the number of open pull requests...

This is because of the work related to the  release of the next major version (4). See https://github.com/lottie-react-native/lottie-react-native/issues/727#issuecomment-772414088

**Comment by schonfeld** [comment]
@BeyoncesHomeboy you can apply this patch file using `patch-package` if you need an interim fix:

https://gist.github.com/schonfeld/39a5955a641899b315d35c693e5e111e
