### ISSUE TITLE
3.4.0 could not resolve 

### ISSUE THREAD

**Issue by NaudyDev** [lottie-react-native/lottie-react-native#709]
Could not resolve com.airbnb.android:lottie:3.4.0.

this is an issue i am getting when i integrate the library on react native application . and the problem is this version isn't in use in my project. i am currently using lottie:3.5.0 and lottie-ios:3.1.0

**Comment by Vasault** [comment]
having the same issue, fromm solving my ios issue, ended up screwing android too :(
