### ISSUE TITLE
null is not an object (evaluating 'safeGetViewManagerConfig('LottieAnimationView').Commands')

### ISSUE THREAD

**Issue by Bayramito** [lottie-react-native/lottie-react-native#712]
Hello,

I just installed the package, but getting this error.

![Adsız](https://user-images.githubusercontent.com/44513402/102343035-bb9fdc80-3fa2-11eb-8b77-9600e11763d1.png)

	"react-native": "0.63.4",
	"lottie-ios": "^3.1.8",
	"lottie-react-native": "^3.5.0",

I followed all the steps correctly and also tried to link it manually

**Comment by n4nirmal09** [comment]
Same issue here. using "npm i --save lottie-react-native"

**Comment by riamon-v** [comment]
yep, same here too

**Comment by tushar-singhal** [comment]
Follow these steps and you will be good

```
 IMPORTANT _

If you have issues linking your iOS project check out this StackOverflow thread on how to fix it.

If your app crashes on Android, means auto linking didn't work. You will need to make the following changes:

android/app/src/main/java/<AppName>/MainApplication.java

add import com.airbnb.android.react.lottie.LottiePackage; on the imports section
add packages.add(new LottiePackage()); in List<ReactPackage> getPackages();
android/app/build.gradle

add implementation project(':lottie-react-native') in the dependencies block

android/settings.gradle

add:

include ':lottie-react-native'
project(':lottie-react-native').projectDir = new File(rootProject.projectDir, '../node_modules/lottie-react-native/src/android')

```

**Comment by n4nirmal09** [comment]
@tushar-singhal, did that manual linking too. Didn't work for me. Restarted the metro bundler, still shows the same issue. Turns out it was inconsistent across devices. In my friends device it was working fine, but in my emulated device, it was not.

**Comment by tushar-singhal** [comment]
> @tushar-singhal, did that manual linking too. Didn't work for me. Restarted the metro bundler, still shows the same issue. Turns out it was inconsistent across devices. In my friends device it was working fine, but in my emulated device, it was not.

does not make sense, remove old stuff and restart adding lottie afresh just with npm and then above steps, do not run linking command

**Comment by n4nirmal09** [comment]
@tushar-singhal, Thanks. It is working after fresh install. 
I removed all packages and did a clean install and than installed 
npm i --save lottie-react-native@2.5.11
npm i --save lottie-ios@2.5.3

After that I manually linked using the info here 
https://github.com/lottie-react-native/lottie-react-native

Working fine now. Also tried importing custom AE anim json file, works like charm.

Thanks

**Comment by tushar-singhal** [comment]
> @tushar-singhal, Thanks. It is working after fresh install.
> I removed all packages and did a clean install and than installed
> npm i --save lottie-react-native@2.5.11
> npm i --save lottie-ios@2.5.3
> 
> After that I manually linked using the info here
> https://github.com/lottie-react-native/lottie-react-native
> 
> Working fine now. Also tried importing custom AE anim json file, works like charm.
> 
> Thanks

glad I could help! Cheers! Happy Lottie :)

**Comment by FaisalKhawaj** [comment]
I was also facing the same issue . What I simply did is , I just close the metro bundler and install the package again . and run command :  npx-react-native run-android. It worked .

**Comment by hrupesh** [comment]
After Installing we actually need to rebuild the android project. You can either do it with `react-native run-android` or manually build the project with Android Studio

**Comment by iamharisbutt** [comment]
> Follow these steps and you will be good
> 
> ```
>  IMPORTANT _
> 
> If you have issues linking your iOS project check out this StackOverflow thread on how to fix it.
> 
> If your app crashes on Android, means auto linking didn't work. You will need to make the following changes:
> 
> android/app/src/main/java/<AppName>/MainApplication.java
> 
> add import com.airbnb.android.react.lottie.LottiePackage; on the imports section
> add packages.add(new LottiePackage()); in List<ReactPackage> getPackages();
> android/app/build.gradle
> 
> add implementation project(':lottie-react-native') in the dependencies block
> 
> android/settings.gradle
> 
> add:
> 
> include ':lottie-react-native'
> project(':lottie-react-native').projectDir = new File(rootProject.projectDir, '../node_modules/lottie-react-native/src/android')
> ```

worked for me. Thanks

**Comment by Shazil1** [comment]
@tushar-singhal Anser Worked for me, thanks❤️

**Comment by alidavodii** [comment]
After Installing "npm i --save lottie-react-native"  please rebuild the android project. 
just do it ;)

**Comment by muneendraShuklaa** [comment]
restart the android studio and uninstall the previous build

**Comment by great-ian** [comment]
There is currently a conflict issue between packages such as lottie-react-native and lottie-ios. To resolve this, start by ensuring that you have the exact version of each package required. In my case, I was able to resolve the conflict by using "lottie-react-native@5.0.1 / lottie-ios@2.0.1".

After confirming the correct package versions, open Android Studio and follow the setup instructions outlined in the documentation found at https://github.com/lottie-react-native/lottie-react-native#ios-and-android.

Once you have completed the setup, rebuild your app via Android Studio to apply the changes.
