### ISSUE TITLE
Unable to loop seamlessly

### ISSUE THREAD

**Issue by jackharding** [lottie-react-native/lottie-react-native#715]
There seems to be some kind of easing applied to my looped animation, preventing it from looping seamlessly. I can loop how I want with the same JSON file in react-lottie as seen in [this video](https://user-images.githubusercontent.com/12549439/103630613-d4643800-4f39-11eb-8f8a-0706227fcf48.mov). Here's an [example snack](https://snack.expo.io/@jackharding/bossy-blueberries)

I also tried controlling the animation via `progress` with an `Animated.Value` but got similar results.

**Comment by akhan118** [comment]
Were you able to figure it out?

**Comment by DomantasMk** [comment]
When you tried controlling with `Animated.Value` did you set the ease to linear? Since I think it defaults to some kind of easing :). But from my POV it seems like it's the lottie animations fault, since looping works perfectly with only loop and autoplay true.
