### ISSUE TITLE
lottie-react-native closes when I run my application

### ISSUE THREAD

**Issue by AlienDev66** [lottie-react-native/lottie-react-native#716]
### **Bug in open my app with lottie-react-native and expo**

[Description of the bug]

### Steps to Reproduce

Every time I try to get the animation to run my app it stops and closes.

**Comment by t1gu1** [comment]
Yeah it happends to me only on Android. IOS works great.

https://docs.expo.io/versions/latest/sdk/lottie/#known-issues

> Importing Lottie 3 files causes the previewer to crash without a visible error, because Expo relies on lottie-react-native v2.

**Comment by jhsonmac** [comment]
I also had the same problem in react-native, I followed all the steps in the documentation and to my surprise the problem was the .json file.

Try using a different .json.

**Comment by t1gu1** [comment]
> I also had the same problem in react-native, I followed all the steps in the documentation and to my surprise the problem was the .json file.
> 
> Try using a different .json.

@jhsonmac, so you make it works?

What did you do with your .json?
How you generate it?

In my case the .json file are generated by After effect.

**Comment by jhsonmac** [comment]
@t1gu1 I still haven't managed to generate a file through afterEffect that works unfortunately.
I have tried it in different versions, but error persists. The only case I was able to use was not placing assets, just animated text. Test with animated text only without assets.

**Comment by albert-dias** [comment]
I'm having the same problem no matter what .json I use the app keeps crashing when I try to run Lottie
