### ISSUE TITLE
Lottie does not work on samsung android device

### ISSUE THREAD

**Issue by ujeon** [lottie-react-native/lottie-react-native#717]
### Description

[Description of the bug]

**Expected behavior:** [What you expected to happen]
I expected that Lottie animation work any kind of android devices.

**Actual behavior:** [What actually happened]
But does not work on some kind of android devices.

### Versions
react-native : 0.63.2
lottie-react-native : ^3.5.0
android version : 10
kernel version : 4.14.113-20034833

You can get this information from executing `npm version`.

**Comment by viv3kk** [comment]
Yes its not working on samsung device.

**Comment by KamilNatonek** [comment]
Yes, I confirm that.
In my case tested on:
- Samsung Galaxy s10
- Samsung Galaxy m21
