### ISSUE TITLE
TypeError: Attempted to assign to readonly property - Lottie crashes on start

### ISSUE THREAD

**Issue by Batuu13** [lottie-react-native/lottie-react-native#719]
### Description

I was using Lottie without a problem for a while but since 3-4 days it gives me error without any change. It crashes on start on a brand new android project as well after importing the Lottie.
It gives `TypeError: Attempted to assign to readonly property.`

### Steps to Reproduce

1. Start a new react-native project
2. Install the latest Lottie as on the documentation
3. add  `import LottieView from 'lottie-react-native';` to your App.js
4. Run react-native run-android

### Versions

```
"dependencies": {
    "lottie-ios": "^3.1.9",
    "lottie-react-native": "^3.5.0",
    "react": "16.13.1",
    "react-native": "0.63.4"
  },
  "devDependencies": {
    "@babel/core": "7.12.10",
    "@babel/runtime": "7.12.5",
    "@react-native-community/eslint-config": "1.1.0",
    "babel-jest": "25.5.1",
    "eslint": "6.8.0",
    "jest": "25.5.4",
    "metro-react-native-babel-preset": "0.59.0",
    "react-test-renderer": "16.13.1"
  },
```
Android 10 API 29

Also tried on actual device with a lot of linking/rerunning/cleaning the project/restarting everything combinations.

**Comment by developer-ghahremani** [comment]
Hi guys

**Comment by Batuu13** [comment]
I solved it. It is silly why it works but I was trying to debug the LottieView file in **lottie-react-native/lib/LottieView.js** just to see what breaks it. And this file was all one line so I made it parsed with prettier and actually without any change it worked.

**Comment by akmalelias** [comment]
Hi, I have encountered same problem. Actually, just need to reload your simulator/app & it will work just fine.

**Comment by muhsalfarizi** [comment]
I had the same problem but i don't know what the error was, i saw this method from youtube and i have followed it and had the same problem and tried to follow the video but couldn't solve the problem either

import React from "react";
import { View } from "react-native";
import LottieView from 'lottie-react-native'

export default class Splash extends React.Component{
    render(){
        return (
            <View>
                <LottieView 
                source={require('../Asset/Lottie/69069-white-hand.json')}
                loop={true}
                autoPlay={true}
                
                />
            </View>
        )
    }
}

**Comment by Twos22** [comment]
I have then same issue. Restarting expo helps to get rid of the error. But then the screen with the lottie file will crash the app. Any ideas?

**Comment by JohnyClash** [comment]
I'm having the same issue, restarting the expo app does not solve the problem.

**Comment by Twos22** [comment]
Any news?

**Comment by ryanstout** [comment]
Seeing the same problem a year later. @Twos22 any luck fixing it? I tried a few lottie json files (some online) and still got the same crash. Thanks!
