### ISSUE TITLE
Android app crashes on Bodymovin version 5.6.2

### ISSUE THREAD

**Issue by Gabsys** [lottie-react-native/lottie-react-native#720]
### Description

I have tried using lottie-react-native with Bodymovin version 5.4.2 and it works but app crashes when using JSON with Bodymovin version 5.6.2

### Steps to Reproduce

1) Install lottie-react-native as per the instruction
2) Use LottieView with source from a Bodymovin v5.6.2 JSON file

**Expected behavior:** 
App able to load the lottie json successfully

**Actual behavior:**
App Crashes

### Versions
Node v10.23.0
react-native v0.63.4
lottie-react-native v3.5.0
lottie-ios v3.1.8

**Comment by vinniimiranda** [comment]
Same thing here

**Comment by gshenar** [comment]
Hey, I'm running into this issue. Any fixes or ideas?
