### ISSUE TITLE
Bug: Building with build-tools v29.0.2

### ISSUE THREAD

**Issue by productdevbook** [lottie-react-native/lottie-react-native#722]
### Description

```
A problem occurred configuring project ':lottie-react-native'.
> Failed to install the following Android SDK packages as some licences have not been accepted.
     build-tools;29.0.2 Android SDK Build-Tools 29.0.2
     platforms;android-29 Android SDK Platform 29
  To build this project, accept the SDK license agreements and install the missing components using the Android Studio SDK Manager.
  Alternatively, to transfer the license agreements from one workstation to another, see http://d.android.com/r/studio-ui/export-licenses.html
``` 

### Steps to Reproduce
yarn android

### Versions

node - v14.15.3
react native - 0.64.0-rc.2
emulator - 30

**Comment by catarinaccmateus** [comment]
Hello @productfrontenddeveloper ,

I'm having the same issue. Did you find any solution for this?

Thanks!

**Comment by productfrontenddeveloper** [comment]
Hello @catarinaccmateus,

0.64-rc hermes problem.

For this, I have removed  lottie-react-native the project now. I will add it when updated. You can opt out of your project for now or use the 0.63 react native version.
