### ISSUE TITLE
podinstall broke: version mimatch?

### ISSUE THREAD

**Issue by ulrichsi-hrbl** [lottie-react-native/lottie-react-native#725]
[!] CocoaPods could not find compatible versions for pod "lottie-ios":
  In snapshot (Podfile.lock):
    lottie-ios (from `../node_modules/lottie-ios`)

  In Podfile:
    lottie-ios (from `../node_modules/lottie-ios`)

    lottie-react-native (from `../node_modules/lottie-react-native`) was resolved to 3.5.0, which depends on
      lottie-ios (~> 3.1.8)

Got the following this morning. possibly after the upgrade of lottie-ios to 3.2. 
Appcenter build crashes and my local build broke after running "pod update"

My package,json:
  "lottie-ios": "^3.1.9",
        "lottie-react-native": "^3.5.0",

My podfile.lock:
  - lottie-ios (3.1.9)
  - lottie-react-native (3.5.0):
    - lottie-ios (~> 3.1.8)
    - React

**Comment by liusjkob** [comment]
Try uninstall lottie-ios with NPM or YARN:
-> yarn remove lottie-ios  
or 
-> npm uninstall lottie-ios
then install pods:
-> npx pod-intall ios 
or
cd ios && pod intall

**Comment by ulrichsi-hrbl** [comment]
@liusjkob Thank you, perfect!

**Comment by stylder** [comment]
@liusjkob  es usted un crack!, Saludos!

**Comment by Manju-lab** [comment]
I got the same issue

Follow these steps, this worked for me

npm uninstall lottie-ios
npm install lottie-ios@3.1.8
npx pod-install

**Comment by eramudeep** [comment]
> I got the same issue
> 
> Follow these steps, this worked for me
> 
> npm uninstall lottie-ios npm install lottie-ios@3.1.8 npx pod-install

facing the same issue.
your solution not worked for me :(
