### ISSUE TITLE
Is project dead ?

### ISSUE THREAD

**Issue by meftunca** [lottie-react-native/lottie-react-native#727]
### Versions
"lottie-ios": "3.1.8",
"lottie-react-native": "^3.5.0",
"react-native":"0.64.0-rc.2",
npm 7.0.14

**Comment by emilioicai** [comment]
No, it's not dead, we are preparing version 4 which will prepare lottie react native to be used in several new platforms, which takes time to test.

**Comment by meftunca** [comment]
What do you think of your project version estimated release date?

**Comment by emilioicai** [comment]
I hope it is released within this month or beginning of next

**Comment by BeyoncesHomeboy** [comment]
Is this release going to fix not being able play loca files in react native? It's very glitchy for me that 1 in 10x works. Background of the json file not rendering correctly....not being able to play the animation only in specific frames

**Comment by tobiaseisenschenk** [comment]
@emilioicai will version 4 include support for web as well?
I currently work on a cross-platform project and one issue I see is the slightly varying API between lottie-react-native, lottie-react and react-lottie ;)

**Comment by emilioicai** [comment]
@tobiaseisenschenk unfortunately no :/ We would need someone who has a good knowledge on react-native-web to send a PR for integrating lottie in it first.

**Comment by mariomurrent-softwaresolutions** [comment]
@emilioicai Will lottiefiles v3 also be supported?

**Comment by emilioicai** [comment]
Probably not right in the next version but a future patch should resolve it

**Comment by mariomurrent-softwaresolutions** [comment]
Alright - because not it is kind of a trial and error to find the correct files which are working.
Or can I somehow distinguish between v2/v3 files?

**Comment by emilioicai** [comment]
I'm afraid it's not a lottiefiles version issue but a problem with certain features which are not yet supported on lottie-react-native so you won't be able to see which ones will fail right away

**Comment by mariomurrent-softwaresolutions** [comment]
Alright, I see. Thank your for the detailed explanation

**Comment by emilioicai** [comment]
v4.0.0 is just released. It contains three large changes:

- Fix react-native 0.64 compatibility
- Windows support [C#]
- macOS Support (based on react-native-windows)

So I would really appreciate if you guys could help me testing it and creating any issues you might find.
