### ISSUE TITLE
Error in Latest versions (3.1.8)

### ISSUE THREAD

**Issue by nixstory** [lottie-react-native/lottie-react-native#729]
### Description
[!] CocoaPods could not find compatible versions for pod "lottie-ios":
  In snapshot (Podfile.lock):
    lottie-ios (from `../node_modules/lottie-ios`)

  In Podfile:
    lottie-ios (from `../node_modules/lottie-ios`)

    lottie-react-native (from `../node_modules/lottie-react-native`) was resolved to 3.5.0, which depends on
      lottie-ios (~> 3.1.8)
##[error]The process '/usr/local/lib/ruby/gems/2.7.0/bin/pod' failed with exit code 1
##[error]The 'pod' command failed with error: The process '/usr/local/lib/ruby/gems/2.7.0/bin/pod' failed with exit code 1
##[section]Finishing: Pod install
##[section]Starting: Xcode build (signed)

**Comment by nixstory** [comment]
package.json
    "lottie-ios": "^3.1.8",
    "lottie-react-native": "^3.5.0",

**Comment by nixstory** [comment]
it was fixed after macbook restart.

**Comment by MrXyfir** [comment]
Anyone else have a solution for this? I've had this issue for a couple weeks now and can't upgrade. Restarts don't do anything.

**Comment by OlegPanfyorov** [comment]
Same issue. Restart not help

**Comment by MrXyfir** [comment]
```
npm uninstall lottie-ios
npm install lottie-ios@3.1.8
npx pod-install
```

That's what worked for me.

**Comment by notjulian** [comment]
> ```
> npm uninstall lottie-ios
> npm install lottie-ios@3.1.8
> npx pod-install
> ```
> 
> That's what worked for me.

also this works:

```
npm uninstall lottie-ios
npm install lottie-ios@3.1.9
npx pod-install
```

**Comment by cam-shaw** [comment]
@emilioicai I still have this issue with the latest lottie for RN (4.0.2) and lottie-ios 3.2.0. 
Reverting to lotties-ios@3.1.9 solves the issue.

**Comment by emilioicai** [comment]
@cam-shaw peer dependency is set to 3.1.8, it looks 3.1.9 would also be ok but I'm not sure how you ended up with lottie-ios 3.2.0. Any idea?

**Comment by cam-shaw** [comment]
I apologise, it would be because of my mistake. I attempted to update lottie-ios to 3.2.0 after updating lottie-react-native, before reading the readme that states we should install 3.1.8.

**Comment by artdevgame** [comment]
Hi @emilioicai 👋 
Is support for the most recent version of `lottie-ios` (currently `3.2.2`) on your roadmap?
Kind of an extension to @cam-shaw's question rather than starting a new ticket.

**Comment by emilioicai** [comment]
@artdevgame it is the next priority, yes. Actually, if you need it right now you can try just updating the dependency manually on a fork. I tried it myself and seems to be working (almost) out of the box but I would like to settle version 4.0.2 before preparing another minor update.

**Comment by ghasemikasra39** [comment]
```bash
[!] CocoaPods could not find compatible versions for pod "lottie-ios":
  In Podfile:
    lottie-ios (from `../node_modules/lottie-ios`)

    lottie-react-native (from `../node_modules/lottie-react-native`) was resolved to 4.0.2, which depends on
      lottie-ios (~> 3.1.8)
```

```
    "lottie-ios": "^3.2.3",
    "lottie-react-native": "^4.0.0",
    "react-native": "0.64.1",
```

**Comment by pvshum** [comment]
@ghasemikasra39 bumping `lottie-react-native` version to `^4.0.3` solved it for me.

**Comment by nriccar** [comment]
any news? nothing works

**Comment by emilioicai** [comment]
@nriccar which version of React native are you using?

**Comment by nriccar** [comment]
Thanks for the quick response. My RN version is 0.64.2

**Comment by emilioicai** [comment]
Try installing lottie-react-native 4.0.3, lottie-ios 3.2.3, remove Podfile folder and Podfile lock, and run pod install once again

**Comment by ontckr** [comment]
@emilioicai My RN version is 0.61.5

**Comment by ontckr** [comment]
@emilioicai  My RN version is 0.61.5

"lottie-ios": "^3.1.6"
"lottie-react-native": "^3.3.2"

I can't upgrade my RN version and when I upgrade these lottie dependencies it says, 

" Specs satisfying the `lottie-react-native (from `../node_modules/lottie-react-native`)` dependency were found, but they required a higher minimum deployment target. "

**Comment by timothytripp** [comment]
> @emilioicai unfortunately that did not work, getting this error still:
> 
> ```
> [!] CocoaPods could not find compatible versions for pod "lottie-react-native":
>   In Podfile:
>     lottie-react-native (from `../node_modules/lottie-react-native`)
> 
> Specs satisfying the `lottie-react-native (from `../node_modules/lottie-react-native`)` dependency were found, but they required a higher minimum deployment target.
> ```
> 
> I'm on: "lottie-ios": "3.2.3", "lottie-react-native": "4.1.3", "react-native": "0.64.1",

Try this:
npm install lottie-react-native@4.0.3
npm install lottie-ios@3.2.3

**Comment by ZohaibAhmad786** [comment]
@timothytripp you saved my time thanks it work

**Comment by mostasim** [comment]
> > @emilioicai unfortunately that did not work, getting this error still:
> > ```
> > [!] CocoaPods could not find compatible versions for pod "lottie-react-native":
> >   In Podfile:
> >     lottie-react-native (from `../node_modules/lottie-react-native`)
> > 
> > Specs satisfying the `lottie-react-native (from `../node_modules/lottie-react-native`)` dependency were found, but they required a higher minimum deployment target.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I'm on: "lottie-ios": "3.2.3", "lottie-react-native": "4.1.3", "react-native": "0.64.1",
> 
> Try this: npm install lottie-react-native@4.0.3 npm install lottie-ios@3.2.3

it's worked for me, many Thanks

**Comment by Abdulrauf-vhora** [comment]
> ```
> npm uninstall lottie-ios
> npm install lottie-ios@3.1.8
> npx pod-install
> ```
> 
> That's what worked for me.

**Comment by VhoraAbdulrauf** [comment]
> ```

1.  npm uninstall lottie-ios or yarn remove  lottie-ios
2.  npx pod-install  or cd ios && pod install // do that after remove lottie-ios
3.  npm install lottie-ios@3.1.8 || yarn add  lottie-ios@x.x.x // where x.x.x = specific version
4.  npx pod-install  || cd ios && pod install 

> ```
> 
> That's what worked for me.

**Comment by VhoraAbdulrauf** [comment]
> > ```
> > npm uninstall lottie-ios
> > npm install lottie-ios@3.1.8
> > npx pod-install
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > That's what worked for me.
> 
> also this works:
> 
> ```
> npm uninstall lottie-ios
> npm install lottie-ios@3.1.9
> npx pod-install
> ```

 1. npm uninstall lottie-ios or yarn remove  lottie-ios
 2. npx pod-install  or cd ios && pod install // do that after remove lottie-ios
 3. npm install lottie-ios@3.1.8 || yarn add  [lottie-ios@x.x.x](mailto:lottie-ios@x.x.x) // where x.x.x = specific version
 4. npx pod-install  || cd ios && pod install

 This what worked for me.

**Comment by VivekGoplan-Vivek** [comment]
Don't update the lottie version Instead of that try this

**Step 1:**
`pod 'lottie-ios'` in Pod file. 

**Step 2:**
  do `pod install`

This is worked for me
