### ISSUE TITLE
onAnimationFinish triggered before animation fully executed

### ISSUE THREAD

**Issue by ashton-hoss** [lottie-react-native/lottie-react-native#731]
### Description

In my code I render a lottie with onAnimationFinish prop. The function in the onAnimationFinish changes the showLottie state to false so lottie goes away after its shown once. 
The issue I am experiencing is that the lottie animation goes away very fast and before its completed.

``` if (this.state.showLottie === true) {
        return (
          <SafeAreaView style={styles.container}>
            <LottieView
              source={require('../../../../../assets/lottie/XX.json')}
              autoPlay={true}
              loop={false}
              speed={1}
              autoSize={false}
              style={{
                width: 150,
                height: 150,
              }}
              imageAssetsFolder={'../../../../../assets/lottie/XX.json'}
              onAnimationFinish={ this.changeShowLottie}
            />
          </SafeAreaView>
        );

and my change state function is as below

changeShowLottie= () => {
     this.setState((state) => {
       return {
         showLottie : false,
       };
    });
  };



[Description of the bug]

### Steps to Reproduce

1. state to show is true
2. lottie is rendered
3. only a portion of animation is shown because the onAnimationFinish function is called which changes the state to show to false

**Expected behavior:** 
The animation completes before the function in onAnimationFinish is triggered

**Actual behavior:** 
The function assigned in onAnimationFinish is triggered before animation is fully shown. ex. animation is 3 sec and the function is called prior to that and only less than a sec of the animation is shown

### Versions
 "expo": "~40.0.0",
"lottie-react-native": "~2.6.1",

**Comment by AxelHgt** [comment]
Hi !
Same issue here, on ios only.

**Comment by Liip3Lim4** [comment]
Same here!

**Comment by sarazeaiter1** [comment]
same here

**Comment by Yurii456** [comment]
Temp solution: onAnimationFinish={(isPlaying) => console.log(isPlaying))

**Comment by Yurii456** [comment]
You can use isCancelled prop. onAnimationFinish={this.changeShowLottie}
changeShowLottie= (isCancelled) => {
  if (!isCancelled) {
     this.setState((state) => {
       return {
         showLottie : false,
       };
    });
  }
  };

**Comment by artvichi** [comment]
up, doesn't work as expected

**Comment by okevino47** [comment]
Hi, i have the same problem here, i have a lottie animation during my app onboarding (during new account creation), the animation work well. but if i disconnect from this new account and create a new one which means, going again on the screen with the lottie animation, this time the callback i setted up in the prop onAnimationFinish is triggered just after the animation started.

I guess that the animation could have a property / state which define if the animation is finish and that state can not being reset after the animation finished maybe.

**Comment by pasteancalin** [comment]
This reproduces in 5.1.4 with react-native 0.64.4, iOS only. @Yurii456 fix works

**Comment by Isra1610** [comment]
This works for me 

const onPressLottie = () => {
        if (!disableAnimation) {
            setIsHide(false)
            Animated.timing(animationProgress.current, {
                toValue,
                duration: duration || 5000,
                easing: animationType || Easing.linear,
                useNativeDriver: useNativeDriver ?? true
            }).start();
            hideLottie()
        }
    }

    const hideLottie = () => {
        setTimeout(() => setIsHide(true), 4500)
    }

return (
//--- code ---//
      {!isHide &&
                <Lottie
                    progress={animationProgress.current}
                    source={animationGif}
                />
            }
//--- code ---//
)

**Comment by sandeep194920** [comment]
Make sure to add  `loop={false}`  to ` <LottieView` if @Yurii456[ solution needs to work that is posted above](https://github.com/lottie-react-native/lottie-react-native/issues/731#issuecomment-857540915).

**Comment by ericksprengel** [comment]
⚠️ Add `key` prop to each `<LottieView />` if you have more animations

BEFORE - `onAnimationFinish` was triggered 2 times when I rendered the `<LottieView />`. Logs:
```log
10:02:20 - Render animation
10:02:20 - onAnimationFinish
10:02:20 - onAnimationLoaded
10:02:47 - onAnimationFinish
```

AFTER - `onAnimationFinish` triggered 1 time:
```log
10:16:31 - Render animation
10:16:32 - onAnimationFinish
```

I had 2 `<LottieView />`.
To fix it I add `key` to each animation.
```
const MyComponent = ({state, onApprovedDone}: CardReaderProps) => {
    if (state === 'loading') {
        return (
            <LottieView
                key={'loading'}   // <== SOLUTION
                source={require('./lottie/loading.json')}
                style={styles.loading}
                autoPlay
                loop
            />
        );
    }
    if (state === 'approved') {
        return (
            <LottieView
                key={'approved'} // <== SOLUTION
                source={require('./lottie/approved.json')}
                style={styles.approved}
                autoPlay
                loop={false}
                onAnimationLoaded={() => {
                    console.log('onAnimationLoaded')
                }}
                onAnimationFinish={() => {
                    console.log('onAnimationFinish')
                }}
            />
        );
    }
    return (
        <Text>Denied</Text>
    );
};
```

**Comment by tunhnt2** [comment]
> Just do it:
> 
> ```
> <LottieView
>         autoPlay
>         style={{
>           width: 200,
>           height: 200,
>         }}
>         source={require("../../assets/lottie-exe.json")}
>         loop={false}
>         useNativeLooping={true}
>         onAnimationFinish={(isCanceled) => {
>           if (!isCanceled) {
>             navigation.replace("SelectCompany");
>           }
>         }}
>     />
> ```

thank you
