### ISSUE TITLE
if list is long , get large laggings, please anyone has solutions ?

### ISSUE THREAD

**Issue by yzhangdegit** [lottie-react-native/lottie-react-native#741]

**Comment by ducdh-fabbi** [comment]
You should check RAM when you use animation, if it has large size, you must to change to another one.

**Comment by shoonne** [comment]
I have the same problem. I am conditionally rendering views where each has its own lottie animations. 
When trying to display the views, the whole app freezes for a second or two and then renders the views. When I inspect the performance monitor, i notice the UI tab drops to 0. Please help!

**Comment by Brumor** [comment]
@shoonne I have the same problem, I sincerely hope it is related with https://github.com/lottie-react-native/lottie-react-native/issues/769 which would be an easy fix, but at the same time I tried applying the fix that was made on lottie-ios locally and it did not change anything 🤔

**Comment by jenipharachel** [comment]
@shoonne What did you do to fix your issue? Did find any solutions that will help?
