### ISSUE TITLE
Android cannot set text programmatically

### ISSUE THREAD

**Issue by Taylor123** [lottie-react-native/lottie-react-native#748]
### Description
On iOS I'm able to set the text of a layer during run time by modifying the json object directly. This doesn't work properly with Android. Most of the time the text will end up blank.

### Steps to Reproduce

1. Overwrite text layer with something along the lines of `Anim.layers[1].t.d.k[0].s.t = 'new text'`
2. Run animation on android device

**Expected behavior:**
Lottie animation on Android to show 'new text'

**Actual behavior:**
Animation will usually contain no text

### Versions
`react-native`: `0.63.3`
`lottie-react-native`: `3.5.0`
`lottie-ios`: `3.1.8`

**Comment by mashrukh-islam** [comment]
@Taylor123 how are you changing the text during run time on iOS?

**Comment by Taylor123** [comment]
overwriting the specific layer with new text during render `Anim.layers[1].t.d.k[0].s.t = 'new text'`
