### ISSUE TITLE
Lottie json files crash on android emulator

### ISSUE THREAD

**Issue by Ozzi48** [lottie-react-native/lottie-react-native#749]
When I use lottie json animations, which have BodyMovin version newer then 4.5.7, it crashes on android devices. As I understand to use animation, I should convert json version to 4.5.7. Maybe someone can help me and convert this animation to older version of BodyMovin?   Animation json file -->  [https://lottiefiles.com/share/mvkb4w79](url)

**Comment by Dimasprog** [comment]
I reviewed my json `lottie` file and i realized that i have unrecognized `ios` fonts for `android system`. So i removed all fonts from my `lottie`. If you use fonts in `lottie`, be sure to use fonts friendly for both `platforms!`
