### ISSUE TITLE
iOS Lottie

### ISSUE THREAD

**Issue by teamzz111** [lottie-react-native/lottie-react-native#750]
### Description

Error with Hermes for iOS

### Steps to Reproduce

1. Use React Native 0.64
2.  Install lottie 
3. Enable hermes for ios

Could not build Objective-C module 'React'
<img width="1143" alt="Captura de Pantalla 2021-04-02 a la(s) 12 59 16 a  m" src="https://user-images.githubusercontent.com/37392536/113385900-a763cd80-934e-11eb-8e06-0ae8820c9e89.png">

### Versions

```
{
  chamba: '1.0.3',
  npm: '6.14.10',
  ares: '1.16.1',
  brotli: '1.0.9',
  cldr: '37.0',
  icu: '67.1',
  llhttp: '2.1.3',
  modules: '83',
  napi: '7',
  nghttp2: '1.41.0',
  node: '14.15.4',
  openssl: '1.1.1i',
  tz: '2020a',
  unicode: '13.0',
  uv: '1.40.0',
  v8: '8.4.371.19-node.17',
  zlib: '1.2.11'
}
```

**Comment by meehol** [comment]
@teamzz111 try this for now https://github.com/lottie-react-native/lottie-react-native/issues/708#issuecomment-775175081

**Comment by emilioicai** [comment]
v4.0.0 is just released. It contains three large changes:

- Fix react-native 0.64 compatibility
- Windows support [C#]
- macOS Support (based on react-native-windows)

So I would really appreciate if you guys could help me testing it and creating any issues you might find.

**Comment by dmackinn** [comment]
@emilioicai thank you for the package update! Do you have plans for updating the lottie-ios package dependency to 3.2.2?

**Comment by emilioicai** [comment]
@dmackinn that should be the next minor version update after we are done with any patches we need for the changes introduced in 4.0.0

**Comment by ali-digizonelabs** [comment]
@emilioicai When I build My app from Xcode its build successfully and also successfully run on simulator. When I use app centre and try to build app from app centre it giving me issue in lottie-Ios.
1. Use React Native 0.64
2. Install lottie
3. Enable hermes for ios

 "lottie-ios": "^3.1.8",
 "lottie-react-native": "^4.0.2",

<img width="1005" alt="Screenshot 2021-05-04 at 15 38 18" src="https://user-images.githubusercontent.com/80245298/116991958-c4454500-acee-11eb-9078-bf880622d04d.png">
