### ISSUE TITLE
There's no way of knowing if an animation is playing [Feature Request]

### ISSUE THREAD

**Issue by Ibrahimrahhal** [lottie-react-native/lottie-react-native#752]
I have a scenario where I want to check if the animation is playing or not & I can't find any attribute in the AnimatedLottieView Ref that will give that info

**Comment by Ibrahimrahhal** [comment]
doing an activity

**Comment by Ibrahimrahhal** [comment]
doing an activity

**Comment by JoeDareZone** [comment]
doing an activity
