### ISSUE TITLE
Lottie not building  crash in xcode 12.4 simulator

### ISSUE THREAD

**Issue by Bilal112** [lottie-react-native/lottie-react-native#753]
<img width="911" alt="Screenshot 2021-04-12 at 1 10 58 AM" src="https://user-images.githubusercontent.com/23139110/114319685-ed2d4c80-9b2b-11eb-89df-ae182b94842b.png">

**Comment by Bilal112** [comment]
@emilioicai

**Comment by emilioicai** [comment]
@Bilal112 check out this issue: https://github.com/lottie-react-native/lottie-react-native/issues/513 there are several fixes for this problem
