### ISSUE TITLE
Animation bugs on iOS

### ISSUE THREAD

**Issue by franzapiola** [lottie-react-native/lottie-react-native#754]
### Description
I'm using an animation json file on my React Native project. This animation works fine on Android, however on iOS it seems to bug out at a certain frame. I checked if my lottie-react-native installation had a problem somehow, by replacing this animation with many other animations I took from the internet. These animations worked fine, so I assume my installation is fine. I also tried installing different versions of lottie-react-native but it made no difference.

### Steps to Reproduce

1. Play the animation **on iOS**, anywhere on the app

**Expected behavior:** The animation plays normally, [like it does on Android](https://vimeo.com/536543368) 

**Actual behavior:** The animation[ bugs out at a certain frame](https://vimeo.com/536544872). Here is [another video in slow motion](https://vimeo.com/536545897), in case that's useful.

### Versions
react: 16.31.1
react-native: 0.63.2
lottie-react-native: 3.5.0

**Comment by ilya-work** [comment]
i have same problem, android work great, but ios animatio doesnt correct render, help please

**Comment by jetaix** [comment]
Same issue, some animation's layers seems doesn't render on iOS, it works fine on https://lottiefiles.com/preview !

**Comment by mengnans** [comment]
Same thing here, any updates or potential workarounds?

**Comment by franzapiola** [comment]
No updates so far, this problem still persists :(

**Comment by jonxssc** [comment]
+1 Problem is still there
