### ISSUE TITLE
error: Abort trap: 6 (in target 'lottie-react-native' from project 'Pods')

### ISSUE THREAD

**Issue by firasskarboul** [lottie-react-native/lottie-react-native#755]
### Description

I installed Lottie on my React Native `RN 0.64` Project using:

```
npm i --save lottie-react-native
npm i --save lottie-ios@3.1.8
```

and after building the project on `Xcode 12.5 beta 3` I had this error:

`error: Abort trap: 6 (in target 'lottie-react-native' from project 'Pods')`

**PS:** The build on `Android Studio` worked well.

### Versions

npm: '7.9.0',
node: '14.16.1',
v8: '8.4.371.19-node.18',
uv: '1.40.0',  
zlib: '1.2.11',
brotli: '1.0.9',
ares: '1.16.1',
modules: '83',
nghttp2: '1.41.0',
napi: '7',
llhttp: '2.1.3',
openssl: '1.1.1k',
cldr: '37.0',
icu: '67.1',
tz: '2020a',
unicode: '13.0'

**Comment by nobbyclark** [comment]
I am also getting this error after installing and running my RN app with Xcode 12.5 beta 3. We're using  `RN: 0.63.3` and `Lottie: 3.4.0`

**Comment by cam-shaw** [comment]
@firasskarboul Hey hey, you've left a comment on the other thread with this issue (see: https://github.com/lottie-react-native/lottie-react-native/issues/734). It could be good to keep the issue consolidated.

Have you give the fix a go that's in the other thread? https://github.com/lottie-react-native/lottie-react-native/issues/734#issuecomment-792771010

In the "fix" thread, you can find this comment here where someone has had their PR merged to address the issue https://github.com/lottie-react-native/lottie-react-native/issues/708#issuecomment-775175081 . 

@emilioicai has said the next release will contain the fix, but due to the size of the release it's going to take a while to make sure it's okay. An ETA would be nice as iOS 14.5 will drop next week and will require Xcode 12.5.

**Comment by ashishPSAG** [comment]
> I am also getting this error after installing and running my RN app with Xcode 12.5 beta 3. We're using `RN: 0.63.3` and `Lottie: 3.4.0`

how you solve it

**Comment by JuanpaG94** [comment]
iOS 14.5 will be dropped next tuesday along with Xcode 12.5, we need at least a hotfix for that. Thank you collaborators for your work in advance.

**Comment by R8Manzo** [comment]
We really need this update, any news about the progress?

**Comment by dwesty17** [comment]
I'm seeing this as well. Xcode 12.5 / react-native 0.63.4 / lottie-react-native: 3.5.0. Any updates? Like @R8Manzo we need an update quickly on this one.

**Comment by lucasjohnston** [comment]
Same issue here. iOS 14.5 and Xcode 12.5 are released now, is there any update on this?

**Comment by emilioicai** [comment]
v4.0.0 is just released. It contains three large changes:

- Fix react-native 0.64 compatibility
- Windows support [C#]
- macOS Support (based on react-native-windows)

So I would really appreciate if you guys could help me testing it and creating any issues you might find.

**Comment by chreck** [comment]
If you want to use 3.5.0 use the patch I found here https://github.com/lottie-react-native/lottie-react-native/issues/708#issuecomment-775175081

**Comment by rjuevesano** [comment]
> If you want to use 3.5.0 use the patch I found here [#708 (comment)](https://github.com/lottie-react-native/lottie-react-native/issues/708#issuecomment-775175081)

it works! thanks :)

**Comment by andrespaggy** [comment]
This morning, after upgrading to XCode 12.5, I received this error too.
I already had lottie-react-native installed, but the following worked for me.

My solution was to run `yarn add lottie-react-native`

**Comment by shamilovtim** [comment]
Thank you for the fix! FYI you might want to do a Github release to update the sidebar / releases / tags section

**Comment by emilioicai** [comment]
@shamilovtim thanks for the heads up, version created

**Comment by nthegedus** [comment]
I'm faced the same issue, but when I upgrade the Xcode and lottie-react-native, Android stop working. 
On Android I got this problem https://github.com/lottie-react-native/lottie-react-native/issues/763
