### ISSUE TITLE
react-native-safe-modules issues after last release 4.0.1

### ISSUE THREAD

**Issue by alimek** [lottie-react-native/lottie-react-native#760]
### Description

Looks like last version of `react-native-safe-modules` has broken `package.json` and app is throwing error after upadting to `lottie-react-native:4.0.1`

https://github.com/emilioicai/react-native-safe-modules/issues/7

### Steps to Reproduce

1.  `yarn add lottie-react-native`
2. yarn start
3. when try to use Lottie in any screen, its producing error.

Error: While trying to resolve module `react-native-safe-modules` from file `xxx/node_modules/lottie-react-native/lib/LottieView.js`, the package `xxx/node_modules/react-native-safe-modules/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`xxx/node_modules/react-native-safe-modules/lib/index.js`. Indeed, none of these files exist:

Solution for now: use `4.0.0` version not `4.0.1` until `react-native-safe-modules` is fixed.

**Comment by emilioicai** [comment]
Yup, I just released a new version of react-native-safe-modules (1.0.3) to fix this and another version of lottie-react-native (4.0.2) with the dependency updated. Can you try again?

**Comment by alimek** [comment]
it works now, thanks for fast update :+1:
