### ISSUE TITLE
Stroke effect is not working

### ISSUE THREAD

**Issue by Liip3Lim4** [lottie-react-native/lottie-react-native#761]
Hi, i'm new in Lottie/After Effects so i don't know if is my mistake or bug/library limitation. I made a animation one logo with two animations, one to move a pen and other to show a letter simulating writing. When i export using bodymovin, in lottiefiles works absolutely fine but when i show in react native project only the pen movement works, the effect on letter that i made using stroke not work.

My Animation
https://lottiefiles.com/share/woltdzbn

**Comment by emilioicai** [comment]
Hey, yeah, some Afrer Effects features are not supported by lottie. Here's the full list: https://github.com/airbnb/lottie/blob/master/supported-features.md

**Comment by Liip3Lim4** [comment]
Correct me if I'm wrong but this effect is using Strokes and according to your link, strokes are completely supported.
