### ISSUE TITLE
Loading animation from JSON link fails

### ISSUE THREAD

**Issue by thechaudharysab** [lottie-react-native/lottie-react-native#762]
### Description

If I store the file locally this works fine
```
<LottieView style={styles.container} source={require('../Assets/Animations/city.json')} autoPlay loop />
```

But if I try to add it using the URL:

```
<LottieView style={styles.container} source={{ uri: 'https://assets3.lottiefiles.com/packages/lf20_0apkn3k1.json' }} autoPlay loop />
```

I get errors like:

```
Error: Exception in HostFunction: Malformed calls from JS: field sizes are different.

[[47,64,64,64,64,64,64,64,49,24,50],[0,3,3,3,3,3,3,0,1,5,10],[[251,0,1619628650647,false],["didSendNetworkData"],["didReceiveNetworkResponse"],["didReceiveNetworkData"],["didReceiveNetworkIncrementalData"],["didReceiveNetworkDataProgress"],["didCompleteNetworkResponse"],[{"withCredentials":true,"incrementalUpdates":false,"headers":{"content-type":"application/json","accept":"application/json"},"data":{"trackingName":"unknown"},"url":"https://assets3.lottiefiles.com/packages/lf20_0apkn3k1.json","responseType":"blob","timeout":0,"method":"GET"},5913],["{\"type\":\"log\",\"level\":\"log\",\"data\":[\"{\\\"_U\\\": 0, \\\"_V\\\": 0, \\\"_W\\\": null, \\\"_X\\\": null}\"]}",1],[141,1939]],2949]
```

and also this

```
Invariant Violation: [2095,"LottieAnimationView",131,{"loop":true,"progress":0,"speed":1,"resizeMode":"contain","sourceJson":"{\"uri\":\"https://assets3.lottiefiles.com/packages/lf20_0apkn3k1.json\"}","onAnimationFinish":true,"onLayout":true,"aspectRatio":"<<NaN>>","width":390,"height":"100%"}] is not usable as a native method argument
```

Then I tried doing it like this:

```
    async function getLottieJSON() {

        return fetch("https://assets3.lottiefiles.com/packages/lf20_0apkn3k1.json", {
            headers: {
                'Accept': 'application/json',
                'Content-Type': 'application/json',
            }
        })
            .then((response) => response.json())
            .then((json) => {
                return json;
            })
            .catch((error) => {
                return (error)
            });
    }

    let somejson = getLottieJSON()

    console.log(somejson)
```

The `console.log` prints:
```
{"_U": 0, "_V": 0, "_W": null, "_X": null}
```

### Steps to Reproduce

1. Install Lottie files package
2. Make a bridging header for iOS
3. Use the code given in the description

**Expected behavior:** It should take a few seconds and load the animation from the `.json` URL 

**Actual behavior:** There are multiple errors explained in the description.

### Versions

npm: '7.11.1',
node: '15.13.0',

**Comment by baronha** [comment]
Have you solved it yet? I also got the same error :(

**Comment by baronha** [comment]
I solve it. You must have to use fetch  or axios to decode JSON data.
Ex(axios): 
``` 
axios
      .get("YOUR_LOTTIE_URL")
      .then((json) => {
        resolve(json.data);
      })
```

**Comment by thechaudharysab** [comment]
@baronha I tried the way you have mentioned as well, I did:

```
                                    axios.get("https://assets3.lottiefiles.com/packages/lf20_0apkn3k1.json").then((json) =>                                        
                                        <LottieView style={styles.container} source={json.data} autoPlay loop />
                                    )
```

But I got an error like:

> Error: Objects are not valid as a React child (found: object with keys {_U, _V, _W, _X}). If you meant to render a collection of children, use an array instead.

How did you do it? Can you share the full code event the URL if possible... as the URL I've mentioned is the one I'm taking directly from Lottie you can use the URL I've used and try?

**Comment by baronha** [comment]
> @baronha I tried the way you have mentioned as well, I did:
> 
> ```
>                                     axios.get("https://assets3.lottiefiles.com/packages/lf20_0apkn3k1.json").then((json) =>                                        
>                                         <LottieView style={styles.container} source={json.data} autoPlay loop />
>                                     )
> ```
> 
> But I got an error like:
> 
> > Error: Objects are not valid as a React child (found: object with keys {_U, _V, _W, _X}). If you meant to render a collection of children, use an array instead.
> 
> How did you do it? Can you share the full code event the URL if possible... as the URL I've mentioned is the one I'm taking directly from Lottie you can use the URL I've used and try?

My Code: 
```
export const getSticker = (uri: String, callback: Function) => {
  if (!uri.match('https://')) uri = STICKER_URL + uri;
  return new Promise((resolve, reject) => {
    axios
      .get(uri)
      .then((json) => {
        resolve(json.data);
      })
      .catch((e) => {
        reject(e);
      })
      .finally(() => {
        callback && callback();
      });
  });
};
```

**Comment by thechaudharysab** [comment]
> > @baronha I tried the way you have mentioned as well, I did:
> > ```
> >                                     axios.get("https://assets3.lottiefiles.com/packages/lf20_0apkn3k1.json").then((json) =>                                        
> >                                         <LottieView style={styles.container} source={json.data} autoPlay loop />
> >                                     )
> > ```
> > 
> > 
> > But I got an error like:
> > > Error: Objects are not valid as a React child (found: object with keys {_U, _V, _W, _X}). If you meant to render a collection of children, use an array instead.
> > 
> > 
> > How did you do it? Can you share the full code event the URL if possible... as the URL I've mentioned is the one I'm taking directly from Lottie you can use the URL I've used and try?
> 
> My Code:
> 
> ```
> export const getSticker = (uri: String, callback: Function) => {
>   if (!uri.match('https://')) uri = STICKER_URL + uri;
>   return new Promise((resolve, reject) => {
>     axios
>       .get(uri)
>       .then((json) => {
>         resolve(json.data);
>       })
>       .catch((e) => {
>         reject(e);
>       })
>       .finally(() => {
>         callback && callback();
>       });
>   });
> };
> ```
> 
> Hope to help you

I think you are using TypeScript. As I'm using the functional approach in Javascript so I created this function:

```
    function getSticker(uri) {
        return new Promise((resolve, reject) => {
            axios
                .get(uri)
                .then((json) => {
                    resolve(json.data);
                })
                .catch((e) => {
                    reject(e);
                })
        });
    };
```

Then to use it I did

```
                            <LottieView style={styles.container} source={getSticker("https://assets3.lottiefiles.com/packages/lf20_0apkn3k1.json")} autoplay loop />

```

But I'm still getting the error:

> Invariant Violation: [4963,"LottieAnimationView",1,{"loop":true,"progress":0,"speed":1,"enableMergePathsAndroidForKitKatAndAbove":false,"cacheComposition":true,"resizeMode":"contain","sourceJson":"{\"_U\":0,\"_V\":0,\"_W\":null,\"_X\":null}","onLayout":true,"aspectRatio":"<<NaN>>","width":392.72727272727275,"height":400}] is not usable as a native method argument

**Comment by baronha** [comment]
I used a state to display Lottie
```
const renderJson = useCallback(() => {
    return jsonData !== null ? (
      <Lottie
        {...props}
        style={[
          {
            width: size,
            height: size,
          },
          props.style,
        ]}
        source={jsonData}
      />
    ) : null;
  }, [jsonData]);
```

**Comment by klandell** [comment]
I'm getting this error too.  The solutions here don't really solve the problem, but are instead workarounds to use an `AnimationObject` as the source instead of `{ uri: string }`.  Fetching the JSON will work short term, but is a really ugly solution.

**Comment by SamRichards** [comment]
The solution above does work, but as @klandell said, that's doesn't solve the problem, that's a workaround.

The URI source does not work, it throws an error. This needs to be looked at.
