### ISSUE TITLE
Error while updating property 'cacheComposition' of a view managed by: LottieAnimationView

### ISSUE THREAD

**Issue by nthegedus** [lottie-react-native/lottie-react-native#763]
Error while updating property 'cacheComposition' of a view managed by: LottieAnimationView

![LottieError](https://user-images.githubusercontent.com/1063383/116567842-5f4cb200-a8de-11eb-8e4b-db0ce4fd2538.png)

This error started after upgrade my env

"react": "17.0.1",
"react-native": "0.64.0",
"lottie-ios": "^3.1.8",
"lottie-react-native": "4.0.2",

### Steps to Reproduce

Just use LottieView as usual

```
<LottieView
  autoPlay
  resizeMode='cover'
  source={require('../animations/splash.json')}
  loop={false}
  cacheComposition={false}
/>
```

Tried using 
`cacheComposition={false}` and `cacheComposition={true}`, but got the same error

On iOS still works as well, but on android i'm facing this error

Does anyone have an idea what about it?

**Comment by nthegedus** [comment]
I'm debugging and is possible to see that `cacheComposition` is looks right, but `setCacheComposition` has a problem

<img width="1342" alt="debug1" src="https://user-images.githubusercontent.com/1063383/116607346-3fca7f00-a908-11eb-90f1-cb6d9009190a.png">

Continuing the process will give the exception

<img width="1418" alt="debug2" src="https://user-images.githubusercontent.com/1063383/116606594-57edce80-a907-11eb-8fcb-812e4c253bcd.png">

**Comment by stevehollaar** [comment]
I was able to bypass this error by reverting the changes from https://github.com/lottie-react-native/lottie-react-native/pull/747, using [patch-package](https://github.com/ds300/patch-package).
I'm on:
```
"react-native": "0.63.4",
"lottie-react-native": "4.0.2",
```
FYI @emilioicai & @tarasvakulka

**Comment by nthegedus** [comment]
I'm still stuck by this issue.
If I use 
```
"lottie-ios": "3.1.8",
"lottie-react-native": "4.0.2",
```
I'm able to build with Xcode 12.5, but android got the `cacheComposition` error. But if I use `"lottie-react-native": "3.5.0"`, the build works on Android and fail with this error `Command failed due to signal: Abort trap: 6` on iOS, and I have to use 12.4

**Comment by finik-htec** [comment]
Het @nthegedus, not sure if you solved this problem,but I encountered this issue while updating RN, and i forgot i had resolution strategy to force to different version in app/build.gradle
`configurations.all {
        resolutionStrategy {
            force "com.airbnb.android:lottie:2.5.5"
        }
    }`
As soon i removed that, it started working

**Comment by nthegedus** [comment]
Thanks @finik-htec 
Worked very well removing this resolution strategy
I think this issue might be closed with your solution
