### ISSUE TITLE
Unable to determine Swift version for the following pods

### ISSUE THREAD

**Issue by Vednus** [lottie-react-native/lottie-react-native#764]
I'm getting 
```
[!] Unable to determine Swift version for the following pods:

- lottie-react-native
```

When upgrading to version 4.0.2 and reinstalling everything. Anyone else seeing this?

**Comment by thechaudharysab** [comment]
Not sure if this is the solution but try the following:

1. If you haven't already do `npx pod-install` or `cd ios && pod install && cd ..` after you have installed the package.
2. Open the iOS project in XCode and add a blank `SwiftFile` to create a bridging header.

**Comment by hakansaglam29** [comment]
I'm also getting

DESERIALIZATION FAILURE (please include this section in any bug report) ***
could not deserialize type for 'ContainerView': top-level value not found
Cross-reference to module 'lottie_react_native'

**Comment by Vednus** [comment]
@thechaudharysab that did the trick. Thanks!
