### ISSUE TITLE
Can you bump the lottie-ios version from 3.1.8 to 3.2.2?

### ISSUE THREAD

**Issue by pepasibble** [lottie-react-native/lottie-react-native#769]
It looks like upstream shipped a performance improvement in 3.2.2.  https://github.com/airbnb/lottie-ios/commit/bd5bcef4e964d71dd02c51038baa430f02743c14

**Comment by shoonne** [comment]
Having the same problem

**Comment by IsmaelMiber** [comment]
+1

**Comment by smfeest** [comment]
This appears to have been resolved in v4.0.3 (via 34ed4ea1cdf8ce9eac9606eb5a3858577738ca91)
