### ISSUE TITLE
Animation not showing on iPhone 8 iOS 14.4 simulator

### ISSUE THREAD

**Issue by truongemily** [lottie-react-native/lottie-react-native#774]
Lottie animation is not showing specifically on iPhone 8 iOS 14.4 simulator, however, is showing on all other iPhone and iOS versions of the simulator.

**Steps to reproduce**

The usual Lottie View.

```
import LottieView from 'lottie-react-native';

   <LottieView
      source={require('./busy-loader.json')}
      autoPlay={true}
      loop={true}
    />
```

**Expected behavior**
Animation to show on all iPhone and iOS simulator versions.

**Actual behavior**
Blank screen for only iPhone 8 iOS 14.4 simulator.

**Comment by NisargTailor** [comment]
I am also facing the same issue my file working in Lottie player but not working in code. did you find any solution ?

**Comment by clockelliptic** [comment]
I'm experiencing this issue on iPhone 8 simulator.

Works fine on other iPhones.
