### ISSUE TITLE
Large json file not work in LottieView

### ISSUE THREAD

**Issue by NisargTailor** [lottie-react-native/lottie-react-native#775]
I am using a large JSON file that works on the Lottie player and checks the demo in the Lottie JSON editor. everything works fine over there but when I put that JSON in the react-native program it's not working. I have to use a sequential png file that creates my animation.

I also download a similar kind of file from lottilefile.com and it's running perfectly.
**I attach my JSON file below. I don't have any idea why it's not working.**
[animation.txt](https://github.com/lottie-react-native/lottie-react-native/files/6551330/animation.txt)

working on the react-native lottileView

Animation works on the Lottie JSON editor perfectly but not working on the react-native lottileView

 react-native: 0.64.1 => 0.64.1 

```
npm i --save Lottie-react-native
npm i --save lottie-ios@3.1.8
```

```
    OS: macOS 11.3.1
    CPU: (6) x64 Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz
    Memory: 102.33 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.13 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 12.5/12E262 - /usr/bin/xcodebuild
  Languages:
    Java: javac 15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.1 => 0.64.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by glorio-loopstudio** [comment]
Any help with this??? I have the same issue

**Comment by saurabhkanswal** [comment]
@NisargTailor @glorio-loopstudio guys any update on this ?
