### ISSUE TITLE
Crashing with React Native for macOS

### ISSUE THREAD

**Issue by brianangulo** [lottie-react-native/lottie-react-native#776]
### Description
First was encountering the following issue: https://github.com/brianangulo/scrappiefe/issues/1 where I could not run pod install but I fixed that by creating a new file with Xcode. Now every time I attempt to use LottieFiles within the project it crashes and gives me a very long log with the below error at the end. Is Lottie not compatible with React native windows+macOs?

>  ** BUILD FAILED **
> 
> The following build commands failed:
>         Ld /Users/brian/Library/Developer/Xcode/DerivedData/scrappie-egaqnyeqrbrgakedpnvutjlgbnmk/Build/Products/Debug/scrappie.app/Contents/MacOS/scrappie normal
> (1 failure)
> 

### Steps to Reproduce

1. yarn add or npm install Lottie into a react-native for macOS application
2. Run pod install on macOS folder (may need to create new file with xcode to complete)
3. Command `npx react-native run-macos`
4. Watch it fail to build 😏 

**Expected behavior:** Ideally app should build and load normally using metro server and Lottie animations would show

**Actual behavior:** App fails to build

### Versions
`{
  scrappiefe: '0.0.1',
  npm: '6.14.8',
  ares: '1.16.0',
  brotli: '1.0.7',
  cldr: '37.0',
  icu: '67.1',
  llhttp: '2.0.4',
  modules: '83',
  napi: '6',
  nghttp2: '1.41.0',
  node: '14.9.0',
  openssl: '1.1.1g',
  tz: '2020a',
  unicode: '13.0',
  uv: '1.39.0',
  v8: '8.4.371.19-node.13',
  zlib: '1.2.11'
}`

Also my pk.json dependencies just in case 👍 

` "dependencies": {
    "@react-native-community/masked-view": "^0.1.11",
    "@react-navigation/drawer": "^5.12.5",
    "@react-navigation/native": "^5.9.4",
    "@react-navigation/stack": "^5.14.5",
    "lottie-ios": "3.1.8",
    "lottie-react-native": "^4.0.2",
    "react": "16.13.1",
    "react-native": "0.63.4",
    "react-native-elements": "^3.4.1",
    "react-native-gesture-handler": "^1.10.3",
    "react-native-macos": "^0.63.0-0",
    "react-native-reanimated": "^2.2.0",
    "react-native-safe-area-context": "^3.2.0",
    "react-native-screens": "^3.3.0"
  },
  "devDependencies": {
    "@babel/core": "^7.8.4",
    "@babel/runtime": "^7.8.4",
    "@react-native-community/eslint-config": "^1.1.0",
    "babel-jest": "^25.1.0",
    "eslint": "^6.5.1",
    "jest": "^25.1.0",
    "metro-react-native-babel-preset": "^0.59.0",
    "react-test-renderer": "16.13.1"
  },`

**Comment by m-w-d-d** [comment]
Also having this issue.

**Comment by irajeshverma2020** [comment]
Any update on this issue, Did we resolve this.
Please share.
