### ISSUE TITLE
iOS build fails

### ISSUE THREAD

**Issue by SumitSingh-3** [lottie-react-native/lottie-react-native#778]
I tried many solution like 
https://stackoverflow.com/a/56176956
https://stackoverflow.com/a/53101587

But i can't resolve this issue please help 

ld: warning: Could not find or use auto-linked library 'swiftFoundation'
ld: warning: Could not find or use auto-linked library 'swiftMetal'
ld: warning: Could not find or use auto-linked library 'swiftCoreFoundation'
ld: warning: Could not find or use auto-linked library 'swiftObjectiveC'
ld: warning: Could not find or use auto-linked library 'swiftDispatch'
ld: warning: Could not find or use auto-linked library 'swiftSwiftOnoneSupport'
ld: warning: Could not find or use auto-linked library 'swiftCore'
ld: warning: Could not find or use auto-linked library 'swiftQuartzCore'
ld: warning: Could not find or use auto-linked library 'swiftCoreGraphics'
ld: warning: Could not find or use auto-linked library 'swiftDarwin'
ld: warning: Could not find or use auto-linked library 'swiftUIKit'
ld: warning: Could not find or use auto-linked library 'swiftCoreImage'

**Comment by ngxhuyhoang** [comment]
Same

**Comment by m-w-d-d** [comment]
Also getting this!
