### ISSUE TITLE
Error iOS lottie-react-native rn v0.64.1

### ISSUE THREAD

**Issue by AgustinNG** [lottie-react-native/lottie-react-native#779]
### Description

Error running app on iOS after installing lottie-react-native ^4.0.2 and lottie-ios 3.1.8

ERROR:
`error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening apptest.xcworkspace.`

### Steps to Reproduce
1. npx react-native init apptest
2. cd apptest
3. yarn add lottie-react-native
4. yarn add lottie-ios@3.1.8
5. cd ios
6. pod install
7. cd ..
8. yarn ios

### Versions
```
"lottie-ios": "3.1.8",
"lottie-react-native": "^4.0.2",
"react": "17.0.1",
"react-native": "0.64.1"
```

**Comment by myckhel** [comment]
try installing from the master branch

`yarn add https://github.com/lottie-react-native/lottie-react-native`

This library keeps frustrating people's lives.

The maintainer should add another maintainer since dev is too slow on this library.

and please release the master branch @emilioicai

**Comment by Lucifer24a** [comment]
first answer is my solution : "https://stackoverflow.com/questions/52536380/why-linker-link-static-libraries-with-errors-ios/56176956#56176956"
