### ISSUE TITLE
ios not showing lottie

### ISSUE THREAD

**Issue by YangJongBin** [lottie-react-native/lottie-react-native#780]
'lottie' does not work in the following circumstances.
react-native : 0.64.1
lottie-ios: 3.1.8
lottie-react-native: 4.0.1 (?)
or 
lottie-react-native: "http://github.com/lottie-react-native-native/lottie-react-nativve

It just shows me a blank screen. If you give bacgkround color to 'LottieView', the area is displayed.

how can i do?

**Comment by fiznool** [comment]
https://github.com/lottie-react-native/lottie-react-native/issues/581#issuecomment-823151146
