### ISSUE TITLE
The following Swift pods cannot yet be integrated as static libraries:

### ISSUE THREAD

**Issue by juliscotto** [lottie-react-native/lottie-react-native#784]
Hi! Im having this problem. Did yarn add lottie-react-native and yarn add lottie-ios@3.1.8 but when I do pod install i get this error:

Installing lottie-ios 3.1.9 (was 3.2.3)
Installing lottie-react-native 4.0.2 (was 1.1.1-beta1)
[!] The following Swift pods cannot yet be integrated as static libraries:

The Swift pod `lottie-react-native` depends upon `React-Core`, which does not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.

Im using "react-native": "^0.62.2". Thanks!

**Comment by Chase-Bullock** [comment]
Also experiencing this issue

**Comment by deeepanshu** [comment]
+1

**Comment by joe-goodall-ticketmaster** [comment]
Same issue

<img width="600" alt="Screenshot 2021-06-23 at 21 18 47" src="https://user-images.githubusercontent.com/65718433/123162568-abdce580-d468-11eb-83d7-70d6c3e40a65.png">

**Comment by Sephaq** [comment]
Cocoapods version 1.9+ allows linking of Swift static libraries., use the following command:

`use_frameworks! :linkage => :static`

**Comment by jaonystudio** [comment]
@Sephaq Thank man, you save my day!!

**Comment by harshit-codes-bit** [comment]
@Sephaq  Tried many things, but this worked, thanks

**Comment by VoHoangThien** [comment]
> Cocoapods version 1.9+ allows linking of Swift static libraries, add the following command to your Podfile:
> 
> `use_frameworks! :linkage => :static`


> Cocoapods version 1.9+ allows linking of Swift static libraries, add the following command to your Podfile:
> 
> `use_frameworks! :linkage => :static`

this work for me! thanks.

**Comment by VoHoangThien** [comment]
> Cocoapods version 1.9+ allows linking of Swift static libraries, add the following command to your Podfile:
> 
> `use_frameworks! :linkage => :static`

this worked, thanks.

**Comment by ildaneta** [comment]
> Cocoapods version 1.9+ allows linking of Swift static libraries, add the following command to your Podfile:
> 
> `use_frameworks! :linkage => :static`

Thanks!
You save my day rs!

**Comment by Khachik98** [comment]
You may not need to use use_frameworks! or use_modular_headers! because it's getting conflict with use_flipper

You can add the following without using them:

  

> pod 'Firebase', :modular_headers => true
  pod 'FirebaseCoreInternal', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true
  #....add any library need headers

**Don't say thank you**

**Comment by PSSubramanya** [comment]
> Cocoapods version 1.9+ allows linking of Swift static libraries, add the following command to your Podfile:
> 
> `use_frameworks! :linkage => :static`

You saved so much of my time sir, thankyou so much.

**Comment by atseven** [comment]
> Cocoapods version 1.9+ allows linking of Swift static libraries, add the following command to your Podfile:
> 
> `use_frameworks! :linkage => :static`

Please can u tell me exactly where to paste that?

**Comment by serkanurganci** [comment]
> Cocoapods version 1.9+ allows linking of Swift static libraries, add the following command to your Podfile:
> 
> `use_frameworks! :linkage => :static`

this worked, thank you

**Comment by Yeonbin** [comment]
where can I write that? I don't know where should I write..

**Comment by 4ZR41L** [comment]
> Cocoapods version 1.9+ allows linking of Swift static libraries, add the following command to your Podfile:
> 
> `use_frameworks! :linkage => :static`

thank you bro. this worked for me

**Comment by BlueSkyTechnology** [comment]
> You may not need to use use_frameworks! or use_modular_headers! because it's getting conflict with use_flipper
> 
> You can add the following without using them:
> 
> > pod 'Firebase', :modular_headers => true
> > pod 'FirebaseCoreInternal', :modular_headers => true
> > pod 'GoogleUtilities', :modular_headers => true
> > #....add any library need headers
> 
> **Don't say thank you**

Life Saver

**Comment by ismaila-turner** [comment]
[!] The following Swift pods cannot yet be integrated as static libraries:

The Swift pod `FirebaseCoreInternal` depends upon `GoogleUtilities`, which does not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.

**Comment by kouamegerard** [comment]
I have the same error with expo eas build, how fix them

**Comment by MaryamKhan05** [comment]
> I have the same error with expo eas build, how fix them

I am experiencing the same issue. Have you found a solution yet?

**Comment by agrawalshanu708** [comment]
@Sephaq bro thanks, but that pods errors is resolved but, after updating pods ..it gets failed while rebuilding the ios app...
<img width="1508" alt="image" src="https://github.com/lottie-react-native/lottie-react-native/assets/95335996/dc9d5924-9f34-4ced-bf3c-a9311491b707">

**Comment by nuwanmalintha** [comment]
> Cocoapods version 1.9+ allows linking of Swift static libraries, add the following command to your Podfile:
> 
> `use_frameworks! :linkage => :static`

you saved my two days sleep. thank you

**Comment by JigarBilGit** [comment]
I am trying to create my own custom pod & for that required some other pods. So have added those pods as .podspec file but after that when try to publish my pods then getting below error.

    - ERROR | [iOS] unknown: Encountered an unknown error (The following Swift pods cannot yet be integrated as static libraries:

The Swift pod `xxxxxxxxxxx` depends upon `SDWebImage`, `SVProgressHUD`, and `AZSClient`, which do not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.) during validation.

  s.dependency 'Alamofire'
   s.dependency 'SDWebImage'
  s.dependency 'SVProgressHUD'
  s.dependency 'ReachabilitySwift'
  s.dependency 'AZSClient'

Have tried the solution provided above but getting any result.
