### ISSUE TITLE
Build failed MergeSwiftModule normal x86_64 

### ISSUE THREAD

**Issue by grantspilsbury** [lottie-react-native/lottie-react-native#785]
### Description
I am trying to start up a react native ios app from terminal with:
`npx react-native run-ios --configuration Debug --scheme Development` 

I then get the error:
** BUILD FAILED **
The following build commands failed:
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
	MergeSwiftModule normal x86_64 /Users/Library/Developer/Xcode/DerivedData/frnjcdnxmbqgcnhkwpisddivymns/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/lottie-react-native.build/Objects-normal/x86_64/lottie_react_native.swiftmodule
(2 failures) 

I expect the Xcode simulator to startup and run the ios app but the build fails.

npm: '6.14.11',
ares: '1.16.1',
brotli: '1.0.9',
cldr: '37.0',
icu: '67.1',
llhttp: '2.1.3',
modules: '83',
napi: '7',
nghttp2: '1.41.0',
node: '14.16.0',
openssl: '1.1.1j',
tz: '2020a',
unicode: '13.0',
uv: '1.40.0',
v8: '8.4.371.19-node.18',
zlib: '1.2.11'

lottie-ios: '3.1.8',
lottie-react-native: '3.5.0'

react-native: '0.64.2'

Xcode: '12.5'

Macbook pro 2019 2.3Ghz 8-Core Intel Core i9
macOS Big Sur v11.4

**Comment by rafael-soufer-Endava** [comment]
same here

**Comment by MohitSkycap** [comment]
"lottie-ios": "3.1.8",
 "lottie-react-native": "^4.0.2",
 
 I've upgrade lottie as well. Its worked for me

**Comment by hadimoha** [comment]
@MohitSkycap this worked perfectly, thanks a lot. A question I have about this before updating the versions,  I was able to build using xcode without any errors but it only failed when running it from the terminal. Any ideas why?

**Comment by MohitDhingra0786** [comment]
@hadimoha In my case,  same problem with release build as well. After update it works perfect.
