### ISSUE TITLE
Error when try --configuration Release (iOS)

### ISSUE THREAD

**Issue by Girum** [lottie-react-native/lottie-react-native#786]
Hi. I'm trying to build the RN app with lottie, in iOS in Release mode. I'm using a M1 Macbook Pro...

When I run the command `npx react-native run-ios --configuration Release` , I got an error:

` (maybe you meant: __swift_FORCE_LOAD_$_swiftDarwin_$_lottie_react_native, __swift_FORCE_LOAD_$_swiftDarwin_$_Lottie , __swift_FORCE_LOAD_$_swiftDarwin_$_YogaKit , __swift_FORCE_LOAD_$_swiftDarwin_$_APPNAME)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

The APPNAME is just to hide the project (because I cant share the name...

How can I procced?

**Comment by pkhien95** [comment]
I have the same error, tried bridging header file but it doesn't help. Did you find out a solution?

**Comment by Girum** [comment]
I dont remenber how fiz, but, you can try to add in build phases the excluded architectures (both in Debug and Release) the arm64.
