### ISSUE TITLE
run error on xcode(12.5.1)

### ISSUE THREAD

**Issue by iOScodeYF** [lottie-react-native/lottie-react-native#787]
### Description

1.	Apple Swift version 5.4.2 (swiftlang-1205.0.28.2 clang-1205.0.19.57)
2.	While evaluating request ASTLoweringRequest(Lowering AST to SIL for module lottie_react_native)
0  swift-frontend           0x000000010f23bf85 llvm::sys::PrintStackTrace(llvm::raw_ostream&) + 37
1  swift-frontend           0x000000010f23af78 llvm::sys::RunSignalHandlers() + 248
2  swift-frontend           0x000000010f23c546 SignalHandler(int) + 262
3  libsystem_platform.dylib 0x00007fff20542d7d _sigtramp + 29
4  libdyld.dylib            0x00007fff20517d08 _dyld_fast_stub_entry(void*, long) + 65
5  libsystem_c.dylib        0x00007fff20452411 abort + 120
6  swift-frontend           0x000000010afa9aa4 swift::ModuleFileSharedCore::fatal(llvm::Error) + 100
7  swift-frontend           0x000000010af2f0a8 swift::ModuleFile::fatal(llvm::Error) + 2600
8  swift-frontend           0x000000010af92f44 swift::SILDeserializer::readVTable(llvm::PointerEmbeddedInt<unsigned int, 31>) + 2532
9  swift-frontend           0x000000010b01790b swift::SILDeserializer::getAll(bool) + 107
10 swift-frontend           0x000000010a8f7b03 swift::ASTLoweringRequest::evaluate(swift::Evaluator&, swift::ASTLoweringDescriptor) const + 10899
11 swift-frontend           0x000000010aa03c7d swift::SimpleRequest<swift::ASTLoweringRequest, std::__1::unique_ptr<swift::SILModule, std::__1::default_delete<swift::SILModule> > (swift::ASTLoweringDescriptor), (swift::RequestFlags)9>::evaluateRequest(swift::ASTLoweringRequest const&, swift::Evaluator&) + 205
12 swift-frontend           0x000000010a8fbc1c llvm::Expected<swift::ASTLoweringRequest::OutputType> swift::Evaluator::getResultUncached<swift::ASTLoweringRequest>(swift::ASTLoweringRequest const&) + 780
13 swift-frontend           0x000000010a8f84af swift::performASTLowering(swift::ModuleDecl*, swift::Lowering::TypeConverter&, swift::SILOptions const&) + 143
14 swift-frontend           0x000000010a45b74e swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*) + 7166
15 swift-frontend           0x000000010a3dd362 main + 1266
16 libdyld.dylib            0x00007fff20518f5d start + 1
error: Abort trap: 6 (in target 'lottie-react-native' from project 'Pods')

**Comment by github984527** [comment]
me too

**Comment by ramkgunturu** [comment]
I am also getting the same issue.Can. you fix this issue please

**Comment by Desintegrator** [comment]
same. please help

**Comment by MohitSkycap** [comment]
Update the lottie package to

 "lottie-ios": "3.1.8",
 "lottie-react-native": "^4.0.2",
 
 Worked for me

**Comment by ontckr** [comment]
@MohitSkycap what is your RN version?
