### ISSUE TITLE
Lottie Animation does not play again on Android after reset()

### ISSUE THREAD

**Issue by RRaideRR** [lottie-react-native/lottie-react-native#789]
I am using Expo and React Native and I want to display a Lottie animation. On iOS this works like a charm - on Android the animation will play once and then it will not play again. It seems that reset() somehow behaves strange. You can also have a look at the corresponding [Expo snack](https://snack.expo.io/@raider/lottie-).

```
import { Button, View } from 'react-native';
import React, { useRef } from 'react';
import LottieView from 'lottie-react-native';

import likeAnimation from './assets/animation.json';

export default function App() {
  const animation = useRef(null);

  const onPress = () => {
    animation.current.play();
  };

  const onAnimationFinish = () => {
    animation.current.reset();
  }

  return (
    <View style={{ paddingTop: 200, backgroundColor: '#dddddd', flex: 1 }}>
      <LottieView
        loop={false}
        speed={1.5}
        autoSize
        ref={animation}
        source={likeAnimation}
        onAnimationFinish={onAnimationFinish}
      />
      <Button onPress={onPress} title="Click me!" />

    </View>
  );
}
```

**Comment by gohilmukund** [comment]
I am facing the same issue. I got a console of animation reference in onAnimationFinish and I found that it is stuck in infinite loop.

**Comment by RRaideRR** [comment]
Have you come up with a solution @gohilmukund ?

**Comment by Andre-at-LaCapitale** [comment]
Same issue, the animation re-play just fine on iOS but refuse to replay on Android:
- on Android the animation will play once and then it will not play again

Here our versions:
```json
    "lottie-react-native": "5.0.1",
    "react": "17.0.2",
    "react-native": "0.67.2",
```

The only workaround I found was to force a re-render of the `<LottieView ...>` component

**Comment by darkrideroffate** [comment]
this issue still exists

**Comment by comontes** [comment]
expo 46 and "lottie-react-native": "5.1.4" and still have this issue

**Comment by comontes** [comment]
> I am facing the same issue. I got a console of animation reference in onAnimationFinish and I found that it is stuck in infinite loop.

I checked the same thing, onAnimationFinish is not getting called, works on iOS but not on Android

**Comment by RRaideRR** [comment]
Hey,

I just updated my [initial snack and it seems to work now](https://snack.expo.dev/@raider/lottie-?platform=android).

**Comment by gitteraz** [comment]
This Workaround worked for me

```
const onAnimationFinish = useCallback((shouldSkip) => {
    if (!shouldSkip) animation?.current?.reset();
  }, []);
```
