### ISSUE TITLE
The effect of resizeMode='contain' in Android is not equal to iOS

### ISSUE THREAD

**Issue by jcdhlzq** [lottie-react-native/lottie-react-native#792]
when the property `resizeMode`  is set to `contain`, the image type  is set to CENTER_INSIDE in Android, but it is set to `scaleAspectFit`, which may cause the different.

Is it better to set the image type `FIT_CENTER` rather than `CENTER_INSIDE` in Android ?

**Comment by rishabh876** [comment]
+1 @jcdhlzq 
It should be FIT_CENTER instead of CENTER_INSIDE.

is there a work around to this?
