### ISSUE TITLE
Gradle 7: `unable to resolve class MavenDeployment`

### ISSUE THREAD

**Issue by joshuapinter** [lottie-react-native/lottie-react-native#794]
### Description

Just upgraded to Gradle Plugin 7.0.0 and Gradle 7.0.2 via Android Studio's prompt and now running into this error on build:

```
node_modules/lottie-react-native/src/android/gradle-maven-push.gradle': 46: unable to resolve class MavenDeployment 
   @ line 46, column 26.
             beforeDeployment { MavenDeployment deployment -> signing.signPom(deployment) }
```

It [appears](https://discuss.gradle.org/t/mavendeployment-deprecated-with-gradle-6-3/36096) that `MavenDeployment` was deprecated in Gradle 6.3 and removed entirely in Gradle 7 so a new deployment config needs to be used.

### Steps to Reproduce

1. Upgrade to Gradle 7.
2. Try to build latest `lottie-react-native`.

**Expected behavior:** Builds fine.

**Actual behavior:** `unable to resolve class MavenDeployment`

### Versions

`"lottie-react-native": "4.0.3"`
`gradle` 7.0.2
`gradle plugin` 7.0.0

**Comment by punndcoder28** [comment]
Hi @joshuapinter , same issue here, are the devs at Lottie working on removing maven or is there any temporary work around for this?

**Comment by andresesfm** [comment]
I split the migration into 3 PRs the last one depending on the previous two:
https://github.com/lottie-react-native/lottie-react-native/pull/797
https://github.com/lottie-react-native/lottie-react-native/pull/798
https://github.com/lottie-react-native/lottie-react-native/pull/799

For testing purposes (or temporary workaround please use: https://github.com/andresesfm/lottie-react-native/tree/gradle_7_full_migration) that includes the three PRs merged into one branch

**Comment by kklopfenstein** [comment]
Thanks for fixing this! Will a new release be created soon with these fixes?

**Comment by emilioicai** [comment]
Yes, the corresponding pull request has been already merged and we will release a new version as soon as possible.

**Comment by becle** [comment]
when this fix will be released??

**Comment by almahealth** [comment]
Any updates about when this is gonna be released?

**Comment by emilioicai** [comment]
We are planning a new release before end of next week if everything goes OK.

**Comment by dongdyang** [comment]
looking forward to it! Nice to have a new release soon! Thanks a lot @emilioicai

**Comment by RoderickMastrolinardo** [comment]
hi any update on the release?

**Comment by zienna** [comment]
@emilioicai has everything gone OK with the release?

**Comment by Gavsum** [comment]
Also having issues with this :(

**Comment by emilioicai** [comment]
I'm having issues with the release, apparently master needs some fixing but I'm working on it and should be ready within the week. Sorry for the delay guys.

**Comment by sharifhh** [comment]
Any updates here? can we have this patch in a separate release please? it is blocking us from using the latest gradle for android

**Comment by mayconline** [comment]
same issue =/

**Comment by zienna** [comment]
@emilioicai any update?

**Comment by rachitmishra** [comment]
hello! hope you doing well! is there any update on the release? `apparently master needs some fixing` we can help here if anything required.

**Comment by emilioicai** [comment]
@zienna @mayconline @rachitmishra @Gavsum @RoderickMastrolinardo @dongdyang 

Version v4.1.0 has been released with the migration for lottie-android and Gradle. In my experience, it might raise some build issues so please, give it a try and let me know if it worked for you, I'll work on a patch if needed.

**Comment by rachitmishra** [comment]
thank you for all the good work @emilioicai 🙌🏼

**Comment by joshuapinter** [comment]
Great work @emilioicai, so far so good! 🚀

**Comment by zienna** [comment]
Thank you @emilioicai !!
