### ISSUE TITLE
The Swift pod `lottie-react-native` depends upon `React-Core`, which does not define modules.

### ISSUE THREAD

**Issue by hpelitebook745G2** [lottie-react-native/lottie-react-native#807]
### Description

Just recently, I got error in compiling Android without touching anything in my package.json. I found [this](https://github.com/lottie-react-native/lottie-react-native/issues/794) thread and now I got new error in iOS:

The Swift pod `lottie-react-native` depends upon `React-Core`, which does not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.

Since I can't specify `:modular_headers => true` for `lottie-react-native` because of the Autolinking, I can't see it in my Podfile, which leaves me to put `use_modular_headers!` at the top of my Podfile. Is this the correct way? If not, can anyone suggest the correct way to fix this?

### Steps to Reproduce
Basically I just upgraded to latest versions:
1. yarn add lottie-react-native from `3.5.0` to `4.1.3`
2. yarn add lottie-ios from `3.1.8` to `3.2.3`
3. pod install

**Expected behavior:** To compile Android and iOS successfully.

**Actual behavior:** After step 3, I got the pod install error.

### Versions
    "lottie-ios": "3.2.3",
    "lottie-react-native": "^4.1.3",
    "react-native": "0.63.2",

Here's my Podfile:
    
    require_relative '../node_modules/react-native/scripts/react_native_pods'
    require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

    platform :ios, '10.0'

    abstract_target 'TestApp' do
      config = use_native_modules!
      use_react_native!(:path => config["reactNativePath"])

      permissions_path = '../node_modules/react-native-permissions/ios'
      pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
      pod 'react-native-config', :path => '../node_modules/react-native-config'
      pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'
      pod 'RNFBAnalytics', :path => '../node_modules/@react-native-firebase/analytics'
      pod 'GoogleIDFASupport', '~> 3.14.0'

      target 'TestApp Production' do
        #Production-specific pods    
      end

      target 'TestApp Dev' do
        #Development-specific pods
      end

      target 'TestApp SIT' do
        #SIT-specific pods
      end

      target 'TestApp UAT' do
        #UAT-specific pods
      end

      # Enables Flipper.
      #
      # Note that if you have use_frameworks! enabled, Flipper will not work and
      # you should disable these next few lines.
      # use_flipper!
      use_flipper!({ 'Flipper-Folly' => '2.5.3', 'Flipper' => '0.87.0', 'Flipper-RSocket' => '1.3.1' })
      post_install do |installer|
        flipper_post_install(installer)
      end
    end

**Comment by matinzd** [comment]
Please try upgrading to the latest version `lottie-react-native:5.1.4` and `lottie-ios:3.4.0` and let us know if the issue still exists.
