### ISSUE TITLE
The Swift pod `lottie-react-native` depends upon `React-Core`, which does not define modules. -> Getting pod error after upgrading lottie-ios to version 3.2.3

### ISSUE THREAD

**Issue by hpelitebook745G2** [lottie-react-native/lottie-react-native#808]
### Description

Just recently, I got error in compiling Android without touching anything in my package.json. I found [this](https://github.com/lottie-react-native/lottie-react-native/issues/794) thread and now I got new error in iOS:

    [!] The following Swift pods cannot yet be integrated as static libraries:

    The Swift pod `lottie-react-native` depends upon `React-Core`, which does not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.

Since I can't specify `:modular_headers => true` for `lottie-react-native` because of the Autolinking, I can't see it in my Podfile, which leaves me to put `use_modular_headers!` at the top of my Podfile. Is this the correct way? If not, can anyone suggest the correct way to fix this?

If I run `pod deintegrate` and delete `Podfile.lock`, I get new error:
    
    [!] CocoaPods could not find compatible versions for pod "lottie-react-native":
      In Podfile:
        lottie-react-native (from `../node_modules/lottie-react-native`)

    Specs satisfying the `lottie-react-native (from `../node_modules/lottie-react-native`)` dependency were found, but they required a higher minimum deployment target.

Is really necessary for me to update my Podfile from `platform :ios, '10.0'` to `platform :ios, '11.0'`?

And even when I update all these things in my Podfile, now I get another compilation error in my Xcode under `Folly` module:
    
    Import of module 'glog.glog.log_severity' appears within namespace 'google'

Please advise... It will greatly be appreciated.

### Steps to Reproduce
Basically I just upgraded to latest versions:
1. yarn add lottie-react-native from `3.5.0` to `4.1.3`
2. yarn add lottie-ios from `3.1.8` to `3.2.3`
3. pod install

**Expected behavior:** To compile Android and iOS successfully.

**Actual behavior:** After step 3, I got the pod install error.

### Versions
    "lottie-ios": "3.2.3",
    "lottie-react-native": "^4.1.3",
    "react-native": "0.63.2",

Here's my Podfile:
    
    require_relative '../node_modules/react-native/scripts/react_native_pods'
    require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

    platform :ios, '10.0'

    abstract_target 'TestApp' do
      config = use_native_modules!
      use_react_native!(:path => config["reactNativePath"])

      permissions_path = '../node_modules/react-native-permissions/ios'
      pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
      pod 'react-native-config', :path => '../node_modules/react-native-config'
      pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'
      pod 'RNFBAnalytics', :path => '../node_modules/@react-native-firebase/analytics'
      pod 'GoogleIDFASupport', '~> 3.14.0'

      target 'TestApp Production' do
        #Production-specific pods    
      end

      target 'TestApp Dev' do
        #Development-specific pods
      end

      target 'TestApp SIT' do
        #SIT-specific pods
      end

      target 'TestApp UAT' do
        #UAT-specific pods
      end

      # Enables Flipper.
      #
      # Note that if you have use_frameworks! enabled, Flipper will not work and
      # you should disable these next few lines.
      # use_flipper!
      use_flipper!({ 'Flipper-Folly' => '2.5.3', 'Flipper' => '0.87.0', 'Flipper-RSocket' => '1.3.1' })
      post_install do |installer|
        flipper_post_install(installer)
      end
    end

**Comment by jaonystudio** [comment]
Use static lib
 use_frameworks! :linkage => :static

**Comment by matinzd** [comment]
Please try enabling swift on your project by creating an objective-c bridging header. 
https://stackoverflow.com/a/56176956

**Comment by zyestin** [comment]
RN: 0.61, 
Autolinking
I fix the error by use `pod 'React-Core', :path => '../node_modules/react-native/', :modular_headers => true`
