### ISSUE TITLE
Bad animation quality on Android

### ISSUE THREAD

**Issue by Gentlee** [lottie-react-native/lottie-react-native#809]
### Description

On android quality of animation is very bad.

### Steps to Reproduce

Just use this lottie and compare both platforms:
[bottle-vibe.json.zip](https://github.com/lottie-react-native/lottie-react-native/files/7306312/bottle-vibe.json.zip)

**Expected behavior:**

They should be eqaully good.

**Actual behavior:**

On android it looks pretty bad. Screenshot from emulator but on devices it is the same.

![Screenshot 2021-10-07 at 22 11 08](https://user-images.githubusercontent.com/2361140/136447589-758eb981-a31d-40ee-99b7-9a9c7e5a8ed4.png)

### Versions

lottie-react-native 4.1.3

{
  npm: '6.14.15',
  ares: '1.17.2',
  brotli: '1.0.9',
  cldr: '39.0',
  icu: '69.1',
  llhttp: '2.1.3',
  modules: '83',
  napi: '8',
  nghttp2: '1.42.0',
  node: '14.17.6',
  openssl: '1.1.1l',
  tz: '2021a',
  unicode: '13.0',
  uv: '1.41.0',
  v8: '8.4.371.23-node.76',
  zlib: '1.2.11'
}

**Comment by edreyyo** [comment]
Did you find a solution, @Gentlee? I'm having the same issue but on iOS instead of Android.

**Comment by kentakang** [comment]
@edreyyo I think your case, is this case. https://github.com/airbnb/lottie-ios/issues/1467

**Comment by edreyyo** [comment]
Thanks, @kentakang. This is actually the issue I recently added to their tracker.

**Comment by emilioicai** [comment]
closing this one in favor of airbnb/lottie-ios#1467
