### ISSUE TITLE
[Android] Cannot include downloaded images in animation

### ISSUE THREAD

**Issue by curiousdustin** [lottie-react-native/lottie-react-native#811]
### Description

I need to be able to include a downloaded image in an animation.

On iOS, I can accomplish this by using `react-native-fs` to save the image to `RNFS.MainBundlePath` and then modify the JSON animation file to reference the new filename instead of the one that was exported from After Effects.

I cannot determine a way to accomplish this on Android. Lottie is looking for files in the `main/assets` directory, but I don't know of a way to store downloaded files here.

The Lottie docs discuss using `setImageAssetDelegate` to provide an alternate way of finding the assets, however, I do not see a way to implement this with `lottie-react-native`.

Is there a way to accomplish this with `lottie-react-native`?

**Comment by bolan9999** [comment]
> ```js
> image-data
> ```
`image-data` field does not exist in my `data.json` file.  My  json file looks like below:
```
{
  "v": "5.6.6",
  "fr": 30,
  "ip": 0,
  "op": 49,
  "w": 1280,
  "h": 720,
  "nm": "2",
  "ddd": 0,
  "assets": [
    {
      "id": "imgSeq_0",
      "w": 1280,
      "h": 720,
      "t": "seq",
      "u": "images/",
      "p": "seq_0_0.jpg",
      "e": 0
    },
...
],
layers:[...],
markers:[]
```

How can I fix it?
