### ISSUE TITLE
How to locate /images/ for the animation

### ISSUE THREAD

**Issue by taitran2512** [lottie-react-native/lottie-react-native#816]
### Description
How cant I use the local image in JSON file like react-lottie

I'm using this code for the web with react-lottie it work, but on react native it not work and crash app
It's can only use assets image from folder assets of android and ios

How can I use image from outside native folder and image from url server in `p`

Thanks

```javascript
import img_0 from './images/img_0.png'
export default {
  v: '5.2.1',
  fr: 25,
  ip: 1,
  op: 74,
  w: 500,
  h: 500,
  nm: 'pulseloop',
  ddd: 0,
  assets: [
    { id: 'image_0', w: 701, h: 632, u: '', p: img_0, e: 0 },
    {
      id: 'comp_0',
      layers: [
        {
          ddd: 0,
          ind: 1,
          ty: 2,
          nm: img_0,
          cl: 'png',
          refId: 'image_0',
....
```

### Versions
react -native: 0.64
"lottie-ios": "^3.2.3",
"lottie-react-native": "^4.1.3",

**Comment by chenweigh** [comment]
The same as me.
How to fix it ?

**Comment by rayliao** [comment]
Maybe convert image to base64 format ?

**Comment by AlexR0v** [comment]
if you use expo, then such animations will not work, if you have made an eject expo or do not use expo, then here is the solution - https://github.com/lottie-react-native/lottie-react-native/blob/master/docs/api.md#using-animations-with-assets

**Comment by iway1** [comment]
so the solution is to convert images to base64 pngs and then move them into the json file?
