### ISSUE TITLE
Support dotLottie file format

### ISSUE THREAD

**Issue by jetaix** [lottie-react-native/lottie-react-native#818]
Do you plan the support the `.lottie` format ?

https://dotlottie.io/resources/json-to-dotLottie/

**Comment by emilioicai** [comment]
Eventually we'll do but it's not a high priority for the time being

**Comment by jonsherrard** [comment]
For the moment I guess the move is to.... compile to dotLottie for web (where size really matters), and leave as JSON for RN - and have two files?

**Comment by roryabraham** [comment]
Would love this feature!

**Comment by roryabraham** [comment]
Since both lottie-ios and lottie-android now support `.lottie` files, maybe now is a good time to reopen this?

- https://github.com/airbnb/lottie-ios/pull/1785
- https://github.com/airbnb/lottie-android/pull/1660

**Comment by viv3kk** [comment]
We should consider to reopen this

**Comment by ranaavneet** [comment]
+1

**Comment by clementinoux** [comment]
+1 💕
