### ISSUE TITLE
In ios only  show lottie if i change the lottie json and save

### ISSUE THREAD

**Issue by Davi9130** [lottie-react-native/lottie-react-native#823]
### Description

The animation dont play until change the animation fila and save 

##

Pice of the code 

import React from 'react';
import { Lottie, ContainerLottie } from './Animation.styles';
import Error from '~/assets/animations/error.json';
import Intro from '~/assets/animations/intro.json';
import Loading from '~/assets/animations/loading.json';
import Scheduled from '~/assets/animations/scheduled.json';
import Success from '~/assets/animations/success.json';

const- -Animation: React.FC-<-AnimationProps> = (props) => (
  -<C. ontainerLottie.   >
    {props.type === 'error' && <Lottie source={Error} autoPlay loop={false} />}
    {props.type === 'intro' && <Lottie source={Intro} autoPlay loop={false} />}
    {props.type === 'loading' && (
     - <Lottie source={Loading} autoPlay loop={false} />
    )}
    {props.type === 'scheduled' && (
      <Lottie source={Scheduled} autoPlay loop={false} />
    )}
    {props.type === 'success' && (
      <L. ott. ie source={Success} autoPlay loop={false} />
    )}
  -<.    /ContainerLottie>
);

##

RN 0.66.1

Lottie 5.0.1

**Comment by elie-chaaban** [comment]
hello,

did you figure it out? same issue here

**Comment by Davi9130** [comment]
> hello,
> 
> did you figure it out? same issue here

i made a downgrade for the version 4.1.3

**Comment by elie-chaaban** [comment]
I tried the same but it didnt work also expo gave me a message that it is not compatible

**Comment by matinzd** [comment]
Hi, 
The code you are sharing does not have enough information and it really depends on the animations you are using. 
Attach the json file you are trying to load or if you are not facing the issue anymore let us know. 
This is not a valid issue and the description does not provide anything.

**Comment by Abdoulrasheed** [comment]
This is still an issue,

The animation doesn't work until I manually change the source prop value and save.

here's my Lottie file: https://github.com/Abdoulrasheed/dscmautech/blob/master/successII.json

**Comment by jacksonHendric** [comment]
Still facing this exact same issue
