### ISSUE TITLE
animation reset to first frame when app resume from background

### ISSUE THREAD

**Issue by sbin1211** [lottie-react-native/lottie-react-native#825]
### Description

at ios, after animation finished, when app goto background then resume, the animation reset to first frame not end of frame. 
this issue accure at 5.0.0, 5.0.1, it's ok before 5.0.0 

### Steps to Reproduce

https://user-images.githubusercontent.com/22540308/145149332-3ff9113d-c39a-4d73-8f58-58ea9c779c83.mp4

**Expected behavior:** 
animation should stay at last of frame.

**Actual behavior:** 
animation reset to first frame.

### Versions
lottie-react-native@5.0.1
react-native@0.66
system

**Comment by sbin1211** [comment]
@emilioicai could you have a look. thanks.

**Comment by nathanlevitt** [comment]
This is happening to mine as well, along with looped animations causing the frame to freeze when app resumes from background.

**Comment by kieranoreilly** [comment]
Having same issue :')

**Comment by kyang6** [comment]
Same here, any insights?

**Comment by kyang6** [comment]
https://github.com/lottie-react-native/lottie-react-native/issues/412 I think related to this issue from a while back

**Comment by Livijn** [comment]
I have the same problem. My workaround looks like this:

```js
  useEffect(() => {
    AppState.addEventListener('change', handleAppStateChange);

    return () => {
      AppState.removeEventListener('change', handleAppStateChange);
    };
  }, []);

  function handleAppStateChange(nextAppState: AppStateStatus) {
    if (nextAppState === 'active') {
      lottieRef.current!.play(75, 75);
    }
  }
```

**Comment by cam-shaw** [comment]
Happening for us on iOS, 5.0.1

**Comment by branoholy** [comment]
I had the same issue and the workaround from @Livijn didn't solve it completely. The animation blinked from the first frame to the last frame. Specifying the property `progress={1}` helped in my case. Fortunately, `autoPlay` still works as expected. I use these properties.

```tsx
<LottieView
  source={require('...')}
  autoPlay
  progress={1}
  loop={false}
/>
```

**Comment by Livijn** [comment]
@branoholy Actually, it seems that setting `progress={1}` worked. 😮

**Comment by MiteshKalal7** [comment]
@Livijn  Thanks
```  
const lottieRef = useRef();

useEffect(() => {
    const sub = AppState.addEventListener("change", handleAppStateChange);

    return () => sub.remove();
  }, []);

  const handleAppStateChange = (nextAppState) => {
    if (nextAppState === "active" && lottieRef.current) {
      lottieRef.current.play();
    }
  };
  
   <LottieView
          ref={lottieRef}
          source={require("./../assets/json/update1.json")}
          autoPlay
          loop
     />
```

**Comment by ronaldcurtis** [comment]
Commenting to keep this open, as it is still occurring.

**Comment by nikitph** [comment]
Still happening

**Comment by nikitph** [comment]
> const lottieRef = useRef();

this worked for me

**Comment by nikitph** [comment]
> I have the same problem. My workaround looks like this:
> 
> ```js
>   useEffect(() => {
>     AppState.addEventListener('change', handleAppStateChange);
> 
>     return () => {
>       AppState.removeEventListener('change', handleAppStateChange);
>     };
>   }, []);
> 
>   function handleAppStateChange(nextAppState: AppStateStatus) {
>     if (nextAppState === 'active') {
>       lottieRef.current!.play(75, 75);
>     }
>   }
> ```

this is working

**Comment by laffed** [comment]
Bump

**Comment by vishal-nykaa** [comment]
I am facing same issue in android whenever the animation is not visible it doesn't gets completed, i want to get my animation running in background and unable to find any solution for this in Android, can some one please help

**Comment by as4** [comment]
bump

**Comment by FlushNorris** [comment]
bump

**Comment by FlushNorris** [comment]
Should be possible to set animationView.backgroundBehavior = .pauseAndRestore on lottie-ios via swift, must be possible via react-native as well?!
https://github.com/airbnb/lottie-ios/issues/1332

**Comment by matinzd** [comment]
We do have that if you have tried the latest version. @FlushNorris 

https://github.com/lottie-react-native/lottie-react-native/blob/master/packages/core/ios/LottieReactNative/ContainerView.swift#L211

**Comment by as4** [comment]
It's not fixed in 5.1.4 (the latest version at the moment). Our animations reset when the app goes to background.

**Comment by matinzd** [comment]
Fixed in https://github.com/lottie-react-native/lottie-react-native/pull/980.

**Comment by lpatrun** [comment]
@matinzd when will you make the new version?

**Comment by matinzd** [comment]
> @matinzd when will you make the new version?

Waiting for @emilioicai to approve release script PR. 
The new release will be under rc tag. Should be out soon.

**Comment by matinzd** [comment]
Changes are not on the stable branch. Please test it on `@next` and let us know. @eljubec
