### ISSUE TITLE
Release-iphoneos/lottie-react-native/lottie_react_native.modulemap' not found on RN66

### ISSUE THREAD

**Issue by enigmablue** [lottie-react-native/lottie-react-native#826]
### Description

Getting a modulemap not found when trying to create an archive on my xcode.

fatal error: module map file '/Users/x/Library/Developer/Xcode/DerivedData/x-diljyhjtrreqpwewtjkzwxtjcgjs/Build/Intermediates.noindex/ArchiveIntermediates/soqqle/BuildProductsPath/Release-iphoneos/lottie-react-native/lottie_react_native.modulemap' not found

I can see that the pod has this modulemap set. But how do i find this folder? When is it generated?

How to fix this issue?

Thanks!

![image](https://user-images.githubusercontent.com/35584085/145668948-a5790166-2124-4f33-ab99-d95a527ff4fc.png)

### Steps to Reproduce

Try to do an archive on xcode

**Expected behavior:** [What you expected to happen]

Archive completed

**Actual behavior:** [What actually happened]

Does not complete. Error

fatal error: module map file '/Users/x/Library/Developer/Xcode/DerivedData/x-diljyhjtrreqpwewtjkzwxtjcgjs/Build/Intermediates.noindex/ArchiveIntermediates/soqqle/BuildProductsPath/Release-iphoneos/lottie-react-native/lottie_react_native.modulemap' not found

### Versions

    "lottie-ios": "^3.2.3",
    "lottie-react-native": "^5.0.1",
    "react-native": "0.66.3",
     "react": "^17.0.1",

You can get this information from executing `npm version`.

**Comment by enigmablue** [comment]
fixed it by setting arm64 to excluded architecture for ios simulator. Somehow??

![image](https://user-images.githubusercontent.com/35584085/145718995-4afca861-5def-46f5-9da8-8410859580da.png)

**Comment by Barney4242** [comment]
I have the same error with added arm64 to excluded architecture for ios simulator. Failed to archive but works on simulator.
