### ISSUE TITLE
Lottie glitch with Rubberhose - subframe interpolation

### ISSUE THREAD

**Issue by Charles-Froment** [lottie-react-native/lottie-react-native#831]
### Description

When exporting to Lottie with rubberhose animation, I got some glitch.
This is the same bug as this two tickets (Lottie web) :

[issue 1](https://github.com/airbnb/lottie-web/issues/2334)
or 
[issue 2](https://github.com/airbnb/lottie-web/issues/597)

This problem seems solved by using 

    anim.setSubframe(false)

There is no method available in the react native Lottie library as described.

There is a quote of the answer found for the Lottie web library : 
> usually those glitches are due to subframe interpolation, if the developer calls anim.setSubframe(false) , they will probably get fixed

I spent time to work around but I didn't solved the problem. 
I re-do the animation a lot of time but nothing change.

### Steps to Reproduce

**Expected behavior:** [What you expected to happen]

No glitch inside my animation

**Actual behavior:** [What actually happened]

Glitch are there in the web browser preview
and inside the react native app.
Bodymovin animation preview is ok.

### Versions
    lottie-ios: 3.2.3
    lottie-react-native: ^5.0.1
    react-native": 0.65.1

After effect Rubberhose v2.09 and last version of after effect CC

**Comment by scattar** [comment]
I'm having the same issue and even have the shape layer/hose vanish when previewing on my desktop within the lottie preview app. Any resolution here?

**Comment by emilioicai** [comment]
Not all After Effects features are supported by Lottie. If you notice there are some layers or animations missing check [this list](https://github.com/airbnb/lottie/blob/master/supported-features.md) to ensure they are supported.
