### ISSUE TITLE
Lottie animation doesn't play after Expo upgrade.

### ISSUE THREAD

**Issue by andrey-grach** [lottie-react-native/lottie-react-native#832]
### Description

I'm using React Native with Expo. Today I upgraded expo from version 42.0.0 to version 44.0.0(last), and I noticed that my lottie animations doesn't play on iOS and Android. However if I change speed from current to another animation starts to work as expected. autoPlay param set to true.

### Steps to Reproduce

1. Use expo version ^44.0.0
2. Use lottie-react-native version 5.0.1 
3. Use this code:   
 ```
<LottieView
                       loop={true}
                       speed={1}
                       style={{height: hp('35%'), alignSelf: 'center'}}
                       autoPlay={true}
                       source={require('./../../../assets/lottie/noPlacesInProfile.json')}
                       renderMode={"SOFTWARE"}
          />
```

**Expected behavior:** Animation plays

**Actual behavior:** Animation doesn't play until I change speed param.

### Versions
{
  npm: '6.14.13',
  ares: '1.17.1',
  brotli: '1.0.9',
  cldr: '38.1',
  icu: '68.2',
  llhttp: '2.1.3',
  modules: '83',
  napi: '8',
  nghttp2: '1.42.0',
  node: '14.17.0',
  openssl: '1.1.1k',
  tz: '2020d',
  unicode: '13.0',
  uv: '1.41.0',
  v8: '8.4.371.23-node.63',
  zlib: '1.2.11'
  expo version ^44.0.0
  lottie-react-native version 5.0.1 
}

**Comment by bakerj417** [comment]
I am experiencing this too. autoPlay doesn't start the lottie animation anymore.

Temp workaround: I have found that works now is to attach a ref and run a `.reset()` then `.play()` in a use effect on mount.

hope that helps till we get a fix.

**Comment by bakerj417** [comment]
We are also experiencing this issue. `autoPlay` property no longer starts the animation. We also upgraded from 42 -> 44 sdk.

**Temp Workaround:**
```javascript
const lottieRef = useRef<AnimatedLottieView|null>(null);

useEffect(() => {
  if (lottieRef.current) {
    setTimeout(() => {
      lottieRef.current?.reset();
      lottieRef.current?.play();
    }, 100);
  }
}, [lottieRef.current]);

...

<LottieView
    ref={lottieRef}
    loop={true}
    speed={1}
    style={{height: hp('35%'), alignSelf: 'center'}}
    source={require('./../../../assets/lottie/noPlacesInProfile.json')}
    renderMode={"SOFTWARE"}
/>
```

Hope this helps and looking forward to a fix.

**Comment by anija** [comment]
Same problem upgrading react-native without expo.

react: 17.0.2
react-native: 0.66.4
lottie-react-native: 5.0.1
lottie-ios: 3.2.3

Workaround by @bakerj417 works fine.

**Comment by delgiudices** [comment]
Also experiencing this issue

**Comment by LinusU** [comment]
Ref values shouldn't be used as dependencies to `useState` as changing the `useRef` current value won't trigger an update.

We are using this workaround currently:

```typescript
const lottieRef = useCallback((node: LottieView | null | undefined) => node?.play(), [])

// ...

<LottieView
    ref={lottieRef}
    // ...
/>
```

**Comment by LinusU** [comment]
Hmm, interesting. If I create a completely new Expo app the `autoPlay` work as intended 🤔 

1. `npx expo-cli@latest init .`
2. `npx expo-cli@latest add lottie-react-native`
3. Add a Lottie animation to `assets` folder, e.g. `countdown_10.json`
4. Replace `app.js` with:
    ```js
    import { StatusBar } from 'expo-status-bar';
    import LottieView from 'lottie-react-native';
    import { StyleSheet, View } from 'react-native';

    export default function App() {
      return (
        <View style={styles.container}>
          <StatusBar style="auto" />

          <LottieView
            autoPlay
            loop
            style={{ width: 200, height: 200 }}
            source={require('./assets/countdown_10.json')}
          />
        </View>
      );
    }

    const styles = StyleSheet.create({
      container: {
        flex: 1,
        backgroundColor: '#666',
        alignItems: 'center',
        justifyContent: 'center',
      },
    });
    ```
5. `npx expo-cli@latest start`
6. Scan QR on phone and test out

**Comment by jerearaujo03** [comment]
In my case isn't working either without expo, my workaround:

```
const lottieRef = useRef(null)

...

useEffect(() => {
    if (pending) lottieRef.current?.play()
    else lottieRef.current?.reset()
}, [pending])

..,.

<LottieView
        ref={lottieRef}
        ...
/>
```

**Comment by salmanExpo** [comment]
componentDidMount() {
	setTimeout(() => {
		this.animation.play();
	}, 100)
}


i think auto play is broken even if i call this.animation.play() in componentDidMount will not work but if i give it some time it will work

**Comment by jamesharding** [comment]
> In my case isn't working either without expo, my workaround:
> 
> ```
> const lottieRef = useRef(null)
> 
> ...
> 
> useEffect(() => {
>     if (pending) lottieRef.current?.play()
>     else lottieRef.current?.reset()
> }, [pending])
> 
> ..,.
> 
> <LottieView
>     ref={lottieRef}
>     ...
> />
> ```

What did you use for the pending variable?

**Comment by jerearaujo03** [comment]
It's a component prop, but could be an state if you want

**Comment by andrey-grach** [comment]
> ```js
> <LottieView
>     ref={lottieRef}
>     loop={true}
>     speed={1}
>     style={{height: hp('35%'), alignSelf: 'center'}}
>     source={require('./../../../assets/lottie/noPlacesInProfile.json')}
>     renderMode={"SOFTWARE"}
> />
> ```

Don't know what has happend. Now even this solution doesn't work...

**Comment by andrey-grach** [comment]
> We are also experiencing this issue. `autoPlay` property no longer starts the animation. We also upgraded from 42 -> 44 sdk.
> 
> **Temp Workaround:**
> 
> ```js
> const lottieRef = useRef<AnimatedLottieView|null>(null);
> 
> useEffect(() => {
>   if (lottieRef.current) {
>     setTimeout(() => {
>       lottieRef.current?.reset();
>       lottieRef.current?.play();
>     }, 100);
>   }
> }, [lottieRef.current]);
> 
> ...
> 
> <LottieView
>     ref={lottieRef}
>     loop={true}
>     speed={1}
>     style={{height: hp('35%'), alignSelf: 'center'}}
>     source={require('./../../../assets/lottie/noPlacesInProfile.json')}
>     renderMode={"SOFTWARE"}
> />
> ```
> 
> Hope this helps and looking forward to a fix.

Don't know what has happend. Even this workaround stopped working...

**Comment by andrey-grach** [comment]
@emilioicai we defenetly need your help.

**Comment by taneba** [comment]
I faced the same issue and I found a workaround that should work.
The thing is ref is passed after first rendering, so we should call ref.current 1 tick later.

```tsx
const lottieRef = useRef<AnimatedLottieView>(null);

useEffect(() => {
    setTimeout(() => {
      if (lottieRef.current) {
        lottieRef.current.play();
       }
    }, 1);
}, []);

...

<LottieView
    ref={lottieRef}
   ...
/>
```

**Comment by mayfairr** [comment]
Still Experiencing above, @taneba's workaround doesn't work for me. 

For some reason, changing the speed causes the animation to play. So, I created a useEffect hook that changes a state from 0.9 to 1 when the component loads: 

```
const lottieRef = React.useRef<LottieView | null>(null);
 const [lottieSpeed, setLottieSpeed] = React.useState();

React.useEffect(() => {
  setLottieSpeed(0.9);

  if (lottieRef.current) {
    setTimeout(() => {
      setLottieSpeed(1);
    }, 100);
  }
}, [lottieRef.current]);

**Comment by andrey-grach** [comment]
> Still Experiencing above, @taneba's workaround doesn't work for me.
> 
> For some reason, changing the speed causes the animation to play. So, I created a useEffect hook that changes a state from 0.9 to 1 when the component loads:
> 
> ```
> const lottieRef = React.useRef<LottieView | null>(null);
>  const [lottieSpeed, setLottieSpeed] = React.useState();
> 
> React.useEffect(() => {
>   setLottieSpeed(0.9);
> 
>   if (lottieRef.current) {
>     setTimeout(() => {
>       setLottieSpeed(1);
>     }, 100);
>   }
> }, [lottieRef.current]);
> ```
Actually animation starts working not because you change the speed but because you reload component. Good solution.

**Comment by Jorundur** [comment]
Just wanted to chip in that I'm having the same issue and some of the solutions above were working inconsistently for me but this is consistently working for me as a workaround, the animations are always playing now:

```ts
import React from 'react';

import LottieView from 'lottie-react-native';

const LottieAnimation = () => {
  const lottieRef = React.useRef<LottieView | null>(null);

  React.useEffect(() => {
    if (lottieRef.current) {
      lottieRef.current.play();
    }
  }, [lottieRef.current]);

  return <LottieView ref={lottieRef} source={require('../../assets/my_asset.json')} />;
};

export default LottieAnimation;
```

**Comment by emilioicai** [comment]
I'm not able to reproduce this issue from a newly created expo app. I've got the feeling that the problem may lay on how some screens are mounted on an expo app (maybe react-navigation?). Could anybody share a repo in which I can reproduce this issue?

**Comment by emilioicai** [comment]
@kieuquang1110tt Can you share a repo with me where autoplay is failing? I couldn't reproduce it at all

**Comment by emilioicai** [comment]
I would need to get access to a repo in which this is happening as I couldn't reproduce in any of my tests.

@tarasvakulka not required but recommended. Previous versions may or may not work

**Comment by tarasvakulka** [comment]
> I would need to get access to a repo in which this is happening as I couldn't reproduce in any of my tests.
> 
> @tarasvakulka not required but recommended. Previous versions may or may not work

@emilioicai Repo with reproducible demo app -> https://github.com/tarasvakulka/lottie-example-app
There are two ways to reproduce:
1. Just move app to background and open from background again - animation does not autoplay. For comparing,  on "lottie-react-native": "4.1.3" this bug doesn't appear.
2. Build release .ipa and open it on IPhone 12 Pro Max IOS 15.5, immediately after app launch you can see that autoplay doesn't work, because animation doesn't play (I also tested on IPhone X and this way doesn't work for it, only first one with move to background and reopen).

**Comment by tarasvakulka** [comment]
@emilioicai Did my repo with example help you to reproduce the bug ? Or may be would be better to create new issue for that ?

**Comment by GabrielDierks** [comment]
For me autoPlay is working perfectly fine one Expo 45. But all the methods on the ref are not working. Only with the   `setLottieSpeed(0.9);` fix I got it to work on iOS but not android.

    "lottie-ios": "3.2.3",
    "lottie-react-native": "^5.1.3",
    "react-native": "0.68.2",
    "expo": "^45.0.0",

**Comment by hristowwe** [comment]
> ```ts
> import React from 'react';
> 
> import LottieView from 'lottie-react-native';
> ```

**Many attempts so far, this works great Good job!!**🥳🥳🥳

**Comment by delboy1978uk** [comment]
None of the above workarounds worked for me, but this mish-mash combining answers from @jerearaujo03  and @salmanExpo  did.
```
    // temp lottie fix begin
    // @see https://github.com/lottie-react-native/lottie-react-native/issues/832
    const lottieRef = useRef(null);
    useEffect(() => {
        lottieRef.current?.reset();
        setTimeout(() => {
            lottieRef.current?.play();
        }, 100)

    }, []);
    // fix end
```

**Comment by d-rumal** [comment]
My workaround:

```javascript
    const anim = useRef(null);

    useEffect(() => {
        setTimeout(() => {
            anim.current.play();
        }, 0)
    }, [])
```
Just calling setTimeout function takes enough time as @taneba said.

**Comment by delboy1978uk** [comment]
Ah, nice, I'll try that later @d-rumal, thanks!

**Comment by federicogomezcactus** [comment]
None of the workarounds here have worked for me, I'm on Expo SDK 45

**Comment by delboy1978uk** [comment]
Try my fix, but set the timeout to 0, no delay was actually required. BTW i'm on Expo SDK 46

**Comment by Amaru333** [comment]
How can I use the workaround with setTimeout and refs if I'm looping through multiple animations using map function and displaying all of them?

**Comment by ianfelix** [comment]
I'm still have the same issue. autoPlay doesn't work 
I'm using:
"expo": "^47.0.0",
"lottie-react-native": "5.1.4",

**Comment by Major-Usama** [comment]
import React, { useState, useRef,useEffect } from "react";
import { StyleSheet, View, Text, TouchableOpacity,Animated,Easing } from "react-native";
import Swiper from "react-native-swiper";
import ImageModal from "react-native-image-modal";
import { RFValue } from "react-native-responsive-fontsize";
import Button from "../../components/Common/Button";


import LottieView from 'lottie-react-native';
const OnboardingScreen = ({navigation}) => {
  const [currentIndex, setCurrentIndex] = useState(0);
  const progress = useRef(new Animated.Value(0)).current;
  const progress2 = useRef(new Animated.Value(1)).current;

  // // const animationRef = useRef(null)
   const lottieRef = useRef(null);

  const swiperRef = useRef(null);

  const handleNext = () => {
    if (currentIndex < 3) {
      swiperRef.current.scrollBy(1);
    }
  };

  const handleGetStarted = () => {
    navigation.navigate('SignupScreen')
  };

  const renderNextButton = () => {
    if (currentIndex < 3) {
      return (
        <View>
          <Button onPress={handleNext} title="Next" />
          <TouchableOpacity
          onPress={()=>navigation.navigate('SignupScreen')}
          >
            <Text style={styles.skipText}>Skip</Text>
          </TouchableOpacity>
        </View>
      );
    } else {
      return <Button onPress={handleGetStarted} title="Get Started" />;
    }
  };

  const handleLikeAnimation = () => {
    Animated.loop(
      Animated.timing(progress, {
        toValue: 1,
        duration: 3000,
        easing: Easing.linear,
        useNativeDriver: true,
      })
    ).start();
  };
  
  useEffect(() => {
    handleLikeAnimation();
  }, []);

  const handleLikeAnimation2 = () => {
    Animated.loop(
      Animated.timing(progress2, {
        toValue: 1,
        duration: 3000,
        easing: Easing.linear,
        useNativeDriver: true,
      })
    ).start();
  };
  
  useEffect(() => {
    handleLikeAnimation2();
  }, []);

  return (
    <View style={styles.container}>
      <Swiper
        ref={swiperRef}
        loop={false}
        showsPagination={false}
        onIndexChanged={(index) => setCurrentIndex(index)}
      >
        {/* First onboarding screen */}
        <View style={styles.slide}>
          <View style={styles.gifContainer}>
  
      <LottieView
          progress={progress}
          source={require('../../assets/images/finance.json')}
          autoPlay={true}
          loop={true}
          style={{width:300,height:300}}
        
        />
    

 
            
        
          </View>

          <View style={styles.pagination}>
            {[0, 1, 2, 3].map((index) => (
              <View
                key={index}
                style={[
                  styles.dot,
                  currentIndex === index ? styles.activeDot : null,
                ]}
              />
            ))}
          </View>

          <Text style={styles.title}>All your accounts in one app</Text>
          <Text style={styles.desc}>
            See all your bank accounts and{"\n"}
            digital wallets without having to{"\n"}
            switch to other apps.
          </Text>
        </View>

        {/* Second onboarding screen */}
        <View style={styles.slide}>
          <View style={styles.gifContainer}>
          <LottieView
          progress={progress}
          source={require('../../assets/images/payment.json')}
          autoPlay={true}
          loop={true}
          style={{
            width: RFValue(300),
            height:RFValue(300),
          }}
        />
          </View>

          <View style={styles.pagination}>
            {[0, 1, 2, 3].map((index) => (
              <View
                key={index}
                style={[
                  styles.dot,
                  currentIndex === index ? styles.activeDot : null,
                ]}
              />
            ))}
          </View>

          <Text style={styles.title}>Send money or payments instantly </Text>
          <Text style={styles.desc}>
            Make payments fast and easy{"\n"}
            using a single point to initiate{"\n"}
            all transactions.
          </Text>
        </View>

        {/* Third onboarding screen */}
        <View style={styles.slide}>
          <View style={styles.gifContainer}>
            <ImageModal
              disabled
              imageBackgroundColor="#fff"
              style={{
                width: 300,
                height: 300,
                alignSelf: "center",
                backgroundColor: "red",
                marginTop: 25,
              }}
              // source={require('../../assets/images/test.gif')}
            />
          </View>

          <View style={styles.pagination}>
            {[0, 1, 2, 3].map((index) => (
              <View
                key={index}
                style={[
                  styles.dot,
                  currentIndex === index ? styles.activeDot : null,
                ]}
              />
            ))}
          </View>

          <Text style={styles.title}>See expenses and income </Text>
          <Text style={styles.desc}>
            Every spending counts. Get statements{"\n"}
            of your accounts and wallets within{"\n"}
            the app.
          </Text>
        </View>

        {/* Fourth onboarding screen */}
        <View style={styles.slide}>
          <View style={styles.gifContainer}>
            <ImageModal
              disabled
              imageBackgroundColor="#fff"
              style={{
                width: 300,
                height: 300,
                alignSelf: "center",
                backgroundColor: "red",
                marginTop: 25,
              }}
              // source={require('../../assets/images/test.gif')}
            />
          </View>

          <View style={styles.pagination}>
            {[0, 1, 2, 3].map((index) => (
              <View
                key={index}
                style={[
                  styles.dot,
                  currentIndex === index ? styles.activeDot : null,
                ]}
              />
            ))}
          </View>

          <Text style={styles.title}>Set your budget and track it</Text>
          <Text style={styles.desc}>
            Set your financial goals and reach{"\n"}
            them with a simple and intuitive{"\n"}
            budgeting tool.
          </Text>
        </View>
      </Swiper>

      <View style={styles.bottomContainer}>{renderNextButton()}</View>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
  },
  gifContainer: {
    alignSelf: "center",
  },
  slide: {
    flex: 1,
    // justifyContent: 'center',
    // alignItems: 'center',
  },

  pagination: {
    flexDirection: "row",
    justifyContent: "center",
    marginTop: RFValue(30),
  },
  dot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#AAA",
    marginHorizontal: 4,
  },
  activeDot: {
    backgroundColor: "#000",
  },
  bottomContainer: {
    paddingHorizontal: 16,
    paddingBottom: 50,
    alignItems: "center",
  },
  nextButton: {
    backgroundColor: "#000",
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 24,
  },
  buttonText: {
    color: "#FFF",
    fontSize: 16,
    fontWeight: "bold",
  },
  skipText: {
    fontSize: RFValue(13),
    color: "#65666B",
    fontFamily: "SemiBold",
    marginTop: 24,
    textAlign: "center",
  },
  title: {
    fontSize: RFValue(14),
    color: "#181818",
    fontFamily: "SemiBold",
    textAlign: "center",
    marginTop: RFValue(16),
  },
  desc: {
    fontSize: RFValue(14),
    color: "#65666B",
    fontFamily: "Regular",
    textAlign: "center",
    marginTop: RFValue(11),
    lineHeight: 24,
  },
});

export default OnboardingScreen;

**Comment by Major-Usama** [comment]
I was facing the same issue on IOS side , it was working properly on Android

Here are the steps that I take to solve
 
 
 Do Import Animated and easing on top
 import {,Animated,Easing } from 'react-native
 import LottieView from 'lottie-react-native';

  const progress = useRef(new Animated.Value(0)).current; (Before Return Statement)
    (before Return)
    const handleLikeAnimation = () => {
    Animated.loop(
      Animated.timing(progress, {
        toValue: 1,
        duration: 3000,
        easing: Easing.linear,
        useNativeDriver: true,
      })
    ).start();
  };
  
  After Retrun (Our lottie code)
     <LottieView
          progress={progress}
          source={require('../../assets/images/finance.json')}
          autoPlay={true}
          loop={true}
          style={{width:300,height:300}}
        
        />
        
        Hopefully this works :)

**Comment by hamdidamar** [comment]
For me just install lottie again with npx expo and it works for expo 48. ` npx expo install lottie-react-native`.

**Comment by ustuncem** [comment]
This shouldn't be closed. Still happening with Expo 52 and React Native 0.76.3
