### ISSUE TITLE
Animation components cut-off (using expo)

### ISSUE THREAD

**Issue by bbenson09** [lottie-react-native/lottie-react-native#833]
### Description

Some portions of the animation are not appearing when rendering using LottieView.

**Expected behavior:** 

https://media.giphy.com/media/BF8e3IZV9cC3kXPXYg/giphy.gif

**Actual behavior:** [What actually happened]

https://media.giphy.com/media/C51KYEgJXAC6ke4Ado/giphy.gif

As you can see, some of the components of the animation are cut-off.

### Versions

lottie-react-native: 4.0.3
lottie-ios: 3.2.3
expo: 43.0.3

**Comment by Pashevka** [comment]
Have same issue +1

**Comment by emilioicai** [comment]
Not all After Effects features are supported by Lottie. If you notice there are some layers or animations missing check [this list](https://github.com/airbnb/lottie/blob/master/supported-features.md) to ensure they are supported.
