### ISSUE TITLE
How to use dynamic URLs (Image asset inside JSON file)

### ISSUE THREAD

**Issue by varunraghu3112** [lottie-react-native/lottie-react-native#843]
I want to pass dynamic URLs as a asset to a Lottie JSON file is there any way to achieve that ?

**Comment by emilioicai** [comment]
This is now possible since version 5.1.0

**Comment by carolxs** [comment]
Is this really the same as [856](https://github.com/lottie-react-native/lottie-react-native/pull/856)? It asks about url for assets not for lottie file. I'm looking for a solution for that...

**Comment by brianjd** [comment]
Are asset/image urls supported?

**Comment by pfcodes** [comment]
@varunraghu3112 @brianjd did you guys ever figure out a workaround to this? 

i'm thinking about hardcoding a path in the Lottie file and overwriting that file before running the Lottie animation each time

**Comment by brianjd** [comment]
@pfcodes I came to the same (possible) solution as you.  I just haven't tested yet.  That feature was de-prioritized in my application.
