### ISSUE TITLE
Lottie file from Synfig Studio doesn't show

### ISSUE THREAD

**Issue by jalinegm** [lottie-react-native/lottie-react-native#846]
I have created an animation on Synfig Studio 1.4.2 and exported it in Lottie format. On web view it works, but it doesn't show up on LottieView from React Native (Android). Other files from the Lottie library work normally.
Any suggestions?

Animations:
https://assets3.lottiefiles.com/packages/lf20_3g6yjawd.json
https://assets3.lottiefiles.com/packages/lf20_brfsvwyt.json

    "react-native": "0.63.4",
    "react": "16.13.1",
    "lottie-react-native": "^4.0.3",

Thanks.

**Comment by imamabdulazis** [comment]
can you describe how you are using the Lottie file, that file is from remote or local,
because Lottie file can't use URL like image, you must convert the response from Lottie URL to string, then pass to source **LottieView source={response URL lottie}**

```js
const response=axios.get('https://assets3.lottiefiles.com/packages/lf20_3g6yjawd.json');

return (
....
{response&&LotieView source={response.data}}

....
)
```

**Comment by matinzd** [comment]
Not all features of Lottie are supported on Android and iOS. For more information please refer to this document.

https://lottiefiles.com/supported-features
