### ISSUE TITLE
colorFilters not working when updated expo to 44

### ISSUE THREAD

**Issue by cwnicoletti** [lottie-react-native/lottie-react-native#849]
### Description

I'm getting this error when trying to adjust the `colorFilters` prop in my `LottieView` component:

![image0(19)](https://user-images.githubusercontent.com/56566033/155903965-8d6f1980-2821-4ca4-a539-34928285325a.png)

### Steps to Reproduce

1. Update to expo 44 from 43
2. add a color filter to `LottieView` component
3. observe error

**Expected behavior:** 

Should work as it was previously, applying a different color to the lottie animation.

**Actual behavior:** 

Getting the error: "JSON value '#434AA8' of type NSString cannot be converted to a UIColor. Did you forget to call processColor() on the JS side?"

### Versions

{
  npm: '8.5.1',
  node: '16.14.0',
  v8: '9.4.146.24-node.20',
  uv: '1.43.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.18.1',
  modules: '93',
  nghttp2: '1.45.1',
  napi: '8',
  llhttp: '6.0.4',
  openssl: '1.1.1m+quic',
  cldr: '40.0',
  icu: '70.1',
  tz: '2021a3',
  unicode: '14.0',
  ngtcp2: '0.1.0-DEV',
  nghttp3: '0.1.0-DEV'
}

### Extra info
```

<LottieView
  ref={lottieRef}
  source={require("../../../assets/lottie_anims/52058-check.json")}
  autoPlay={false}
  loop={false}
  colorFilters={[
    {
      keypath: "circle - bg",
      color: "#434AA8",
    },
    {
      keypath: "circle - stroke",
      color: "#434AA8",
    },
  ]}
  style={{ height: 80 }}
/>
```

Also, it works fine when I remove the colorFilters prop completely. Annd I'm running v4.1.3.

**Comment by cwnicoletti** [comment]
Never mind, realized it's being discussed here: #671

**Comment by cwnicoletti** [comment]
Nevermind my nevermind, that was a different problem. This problem still exists when using colorFilters prop in expo 44

**Comment by emilioicai** [comment]
I don't see anything wrong on your code. Maybe it's a version specific issue? did you try updating?
