### ISSUE TITLE
Apk crash - RN 66.0

### ISSUE THREAD

**Issue by mustafauyysl** [lottie-react-native/lottie-react-native#853]
Hi, I used lottie-react-native with RN project. Lottie works Android and IOS on debug mode but when ı genereate apk, apk doesnt open. When i click apk, it suddenly shuts down.

Versions: 

```
"react-native": "^0.66.0",
"lottie-ios": "3.2.3",
"lottie-react-native": "^5.0.1",
```

By the way lottie(4.0.3) was working with RN 0.64.2

**Comment by matinzd** [comment]
Please provide more information or send us a link to a sample repo so we can reproduce the issue. We could not reproduce the issue with the example app. 
You can reopen the issue when you have more information.
