### ISSUE TITLE
[Fabric][React Native 0.68] Support the new architecture

### ISSUE THREAD

**Issue by Alaa-Ben** [lottie-react-native/lottie-react-native#861]
### Description

Hi !
Lottie doesn't currently support the new Fabric architecture. Are there any plans to ?

**Comment by emilioicai** [comment]
We will, but there are some major versions which need to be released in the meantime.

**Comment by AlexanderEggers** [comment]
@emilioicai I would keen to pick up the work for that. Let me know what you think 😃

**Comment by emilioicai** [comment]
Hey @AlexanderEggers that would be great! Let me know if I can support you in any way.

**Comment by capezzbr** [comment]
Hey @AlexanderEggers and @emilioicai any update on supporting the new architecture? 🙏

**Comment by AlexanderEggers** [comment]
@capezzbr I started with the work for that. I hope to have a PR up by the end of this month.

**Comment by chenop** [comment]
@AlexanderEggers does that means react-native-lottie does not work on RN 0.68?

**Comment by AlexanderEggers** [comment]
@chenop No, react-native-lottie should work fine with any newer RN version (tested on 0.68 and 0.69 and no issues so far). But you won't be able to actually enable the new architecture.

**Comment by EmreDereli** [comment]
Hey @AlexanderEggers any update about supporting new architecture?

**Comment by AlexanderEggers** [comment]
@EmreDereli The relevant integration is currently stuck because of an issue with the new arch: https://github.com/facebook/react-native/issues/34372 I hope we will be able to resolve that problem soon.

**Comment by AlexanderEggers** [comment]
@alfonsocj yes I already started with that a little bit but not much progress yet. The underlying new architecture issues are keeping me from progressing at the moment.

**Comment by alfonsocj** [comment]
Is there a specific new arch issue on iOS or is it same issue you mentioned above (https://github.com/facebook/react-native/issues/34372)?.

**Comment by AlexanderEggers** [comment]
@alfonsocj It would be unproductive to start working on the new arch for ios unless we get the android setup correct. That setup is still blocked by the mentioned issue.

**Comment by AlexanderEggers** [comment]
I finally managed to get the lib working with fabric (working for both platforms). We will do some internal testing to verify that the most of the basic props are working but a release should happen soon. 🎉 If anyone wants to help the testing effort, feel free to checkout https://github.com/lottie-react-native/lottie-react-native/issues/931.
