### ISSUE TITLE
RotateY doesn't work in react native

### ISSUE THREAD

**Issue by emreharman** [lottie-react-native/lottie-react-native#862]
### Description

I've an lottie animation file as json. It works smoothly in web but when I try to use it in react native animation doesn't rotate on Y axis (both ios and android). I've tried different json files from lottiefiles (ex: https://assets1.lottiefiles.com/packages/lf20_yyq5vq8q.json) it still doesn't rotate. I can't get if I miss something.

### Steps to Reproduce

1. [First Step]
    - I've installed lottie-ios (3.2.3) and lottie-react-native (5.0.1)
2. [Second Step]
    - I've imported LottieView and my json file as the document.
    - ```
            import LottieView from 'lottie-react-native'
            import loading from './src/assets/lottie-v2.json'        
          <LottieView
                  style={{
                     width: 100,
                     height: 100,
                  }}
                  source={loading}
                  autoPlay
                  loop
                 speed={1}
          />
```

**Expected behavior:** My animation should work smoothly as web version.

**Actual behavior:** Animation doesn't rotate on Y axis

### Versions

npm : 8.5.1
node: 17.6.0
react: 17.0.2
react-native: 0.68.0
lottie-ios: 3.2.3
lottie-react-native: 5.0.1

**Comment by suomimammutti** [comment]
We are having the same issue as other animations work but rotation does not. They work with the 'lottie-web' on a webpage but not with 'lottie-react-native' on mobile devices. 

Like this example: https://lottiefiles.com/71201-flip-love-coin

The rotation does not work and there is also some masking/layer issue with the coin shine effect.

**Comment by emreharman** [comment]
The problem still goes on for me. I have rotated it manually with Animated API but it doesn't work properly like timing etc.

**Comment by matinzd** [comment]
It seems the JSON you provided is using some unsupported features in lottie which is not available on iOS or Android.
For testing your lottie file, you can install Lottie Files app from App store and scan the QR code. If that is not working properly in Lottie Files app, for sure it will not work in react native as well.
