### ISSUE TITLE
ViewPropTypes 

### ISSUE THREAD

**Issue by imthiyazmuhammed** [lottie-react-native/lottie-react-native#868]
### Description

**ViewPropTypes** is deprecated in latest react native and it is asking it to import from the deprecated registry

### Steps to Reproduce

1:When Calling LottieView

**Expected behavior:** [What you expected to happen]

no warnings should be occurring

**Actual behavior:** [What actually happened]

shows warning "ViewPropTypes will be removed from React Native. Migrate to ViewPropTypes exported from 'deprecated-react-native-prop-types'." whenever the component is called

### Versions

5.0.1

**Comment by emilioicai** [comment]
We already have merged a fix for this. Should be released on 5.0.2

**Comment by imthiyazmuhammed** [comment]
Thanks.

**Comment by Sydney-o9** [comment]
Hi Team, any ideas when 5.0.2 will be released?

**Comment by emilioicai** [comment]
should be fine now

**Comment by Sydney-o9** [comment]
@emilioicai ok - just tested the new release you put out [v5.1.1](https://github.com/lottie-react-native/lottie-react-native/releases/tag/v5.1.1), all warnings are gone. Thank you for taking the extra time to put this release out.

**Comment by imthiyazmuhammed** [comment]
Thanks
