### ISSUE TITLE
[ANDROID] - A problem occurred configuring project ':lottie-react-native'

### ISSUE THREAD

**Issue by jokerhp6789** [lottie-react-native/lottie-react-native#869]
### Description

* What went wrong:
A problem occurred configuring project ':lottie-react-native'.
> SDK location not found. Define location with an ANDROID_SDK_ROOT environment variable or by setting the sdk.dir path in your project's local properties file at '.../android/local.properties'.

Everything is working fine on iOS , but on Android I got stuck at this error. 
I tried to create local.properties file and add the path but still doesn't work 
Any help is appreciate ! 

### Steps to Reproduce

1.yarn  add  lottie-react-native
2. cd android
3. ./gradlew clean

### Versions

 "lottie-ios": "3.2.3",
 "lottie-react-native": "5.0.1",
 "react-native": "0.65.1",

**Comment by emilioicai** [comment]
does it work if you do:

`$ export ANDROID_SDK_ROOT="/Users/$USER/Library/Android/sdk" && yarn android`

?

**Comment by jokerhp6789** [comment]
> export ANDROID_SDK_ROOT="/Users/$USER/Library/Android/sdk"

I add this and still got the same errors .
I tried to create the local.properties file again and add the path , and now it works 
Dont understand why 
Anyway thank you for your help . Wish you have good day today :)
