### ISSUE TITLE
Android compilation issue

### ISSUE THREAD

**Issue by bgrgit** [lottie-react-native/lottie-react-native#875]
error: local variable js is accessed from within inner class; needs to be declared final
                  getOrCreatePropertyManager(finalView).setAnimationJson(js);
                                                                         ^

### Versions

You can get this information from executing `5.1.2`.

**Comment by PiotrNap** [comment]
@bgrgit i had the same problem, check this issue. You have to downgrade the packagee to 5.0.1
https://github.com/lottie-react-native/lottie-react-native/issues/873

**Comment by bgrgit** [comment]
@PiotrNap I had an issue with 5.0.1 and I upgraded to 5.1.2. Still issue exists.
<img width="987" alt="Screenshot 2022-05-16 at 7 23 36 PM" src="https://user-images.githubusercontent.com/31758716/168608642-c58b4f81-65d4-4840-a780-a866a120d304.png">

**Comment by bgrgit** [comment]
<img width="908" alt="Screenshot 2022-05-16 at 8 03 56 PM" src="https://user-images.githubusercontent.com/31758716/168617343-1508ae7d-cfb6-435c-b067-724ebcb65646.png">
@emilioicai Please see the above one. I opened this file through error reported in termainal

**Comment by emilioicai** [comment]
yeah, that's an old version of the file, version 5.1.2 has those lines corrected. Could you remove and re-generate your node_modules? Maybe there's some caching preventing you to fetch the latest version

**Comment by emilioicai** [comment]
Sorry guys, this is actually an error I made at merging, I just uploaded v5.1.3 to get this fixed. Could you give it a try?

**Comment by emilioicai** [comment]
It shouldn't take long. You can force it by running `npm i --save lottie-ios@5.1.3`

**Comment by SanthoshDhandapani** [comment]
> npm i --save lottie-ios@5.1.3

npm i --save-dev lottie-react-native@5.1.3 right? not the lottie-ios.

**Comment by bgrgit** [comment]
Yeah it's working @emilioicai . Thanks
