### ISSUE TITLE
OnAnimationFinish Runs before animation finishes android

### ISSUE THREAD

**Issue by JakeOrel** [lottie-react-native/lottie-react-native#876]
### Description

During my apps splash screen we have an animation that plays, on animation finish it kicks off some initializing code before moving to sign in. After switching to minCompileSDK : 31 the on animation callback runs before the animation finishes resulting in more errors
### Steps to Reproduce

1. start app
2. during splash play animation (set to autoplay, loop false)
3. Animation repeats over and over at random times 

**Expected behavior:** animation finishes, onanimationfinish callback runs 

**Actual behavior:** onanimationfinish callback running at random times during animation (only occurs on android)

### Versions

 npm: '8.1.3',
  node: '12.21.0',
    "react": "17.0.1",
    "react-native": "0.64.2",
    "lottie-react-native": "^4.1.3",
 buildToolsVersion = "31.0.0"
        minSdkVersion = 21
        compileSdkVersion = 31
        targetSdkVersion = 31

### Code Snippet
```
    <LottieView
          autoPlay
          loop={false}
          source={animations.splash}
          imageAssetsFolder={'lottie/SplashAnimation/splash.json'}
          onAnimationFinish={() => {
            console.log('animation Finished');
            handleAnimFinish();
          }}
        />
```

**Comment by Michota** [comment]
same issue here!
