### ISSUE TITLE
Animations not always playing on IOS inside of Modal with presentation style "formSheet"

### ISSUE THREAD

**Issue by lpzimmermann** [lottie-react-native/lottie-react-native#879]
### Description
Hey there!

We're trying to implement a new button with a spinner, as lottie animation inside, when "busy".
We have experience with Lottie from our React stack and so far everything worked like a charm with your RN library.

I've noticed some weird behaviour in RN Modals, when using them in type "formSheet" on IOS.
When the component is rendered directly with the modal, they start autoplaying without problems.
However, if I conditionally render them (`{isLoading && <AnimatedLottieView ... />}`), they tend not to play on IOS.

On Android they play upon re-render after a state change, on IOS 15.4 they just display the first frame and won't start animation.

Everywhere else in the app, they work without any problems. The described behaviour also happens with all other lottie animations we use in the app, as soon as placed inside a modal with this attribute.

### Steps to Reproduce

```js
 <Modal
      visible={isVisible}
      animationType="slide"
      supportedOrientations={['portrait', 'landscape']}
      presentationStyle="formSheet"
      onRequestClose={goBack}>
...
{isLoading &&
   <AnimatedLottieView
          source={require('../../../../resources/lottie/loading_button.json')}
          autoPlay
          autoSize
          loop
    />
}
...
</Modal>
```
 
1. As described above, we use a modal view with the type "formSheet"
2. If the initial state of ìsLoading`is `true`, the animation on IOS works upon the first render but not after updating this state multiple times. 
3. If the initialState of `isLoading` is `false, thus not rendered initially, it will also only show the first frame upon state change on IOS, still works on Android though.
4. If I set the presentationStyle to any other (e.g. 'fullscreen') it works as intended

**Expected behavior:**
The lottie animation should also play in modals with presentationType 'formSheet' upon state change
This gif here shows how it works if the modal around is in fullscreen, or the app is deployed to an Android device:
![modal_fullscreen](https://user-images.githubusercontent.com/28627408/169253974-b55c4943-3f75-458c-9ef5-03fc75136400.gif)

**Actual behavior:**
In this gif you can see that the animation doesn't show, run on IOS and after a state change.
![modal_formSheet](https://user-images.githubusercontent.com/28627408/169253968-ca3ac6ba-98b8-4e7a-8e04-c59555bb1f7d.gif)

As described above the animation works upon the initial render but not after a state change. You can see this behaviour in this gif here:
![modal_state_change](https://user-images.githubusercontent.com/28627408/169254594-f295f026-5c98-4bd3-80e2-e7ff1054595f.gif)

### Versions
lottie-react-native: 5.1.3
react-native: 0.66.2
IOS: 15.4

Thank you very much for looking into this, let me know if you found something!

Cheers
Lucien

**Comment by Charmix** [comment]
The same issue

**Comment by jonathanj** [comment]
This doesn't seem to be fixed by #986. The [workarounds](https://github.com/lottie-react-native/lottie-react-native/issues/870#issuecomment-1114649517) don't work for me either.

**Comment by TheRogue76** [comment]
Heya.
I'm going through the repo trying to fix as many issues as i can. I'll take a look at this next weekend to see if it is still happening with V6. We did update our API surface to bring it more in line with other normal React Native views, but i'll check this regardless. If there is still any interest and anyone still has a use case, let me know

**Comment by TheRogue76** [comment]
Testing on the latest version of lottie the issue seems resolved:
<img width="1728" alt="Screenshot 2024-02-11 at 10 29 30" src="https://github.com/lottie-react-native/lottie-react-native/assets/40071952/c2fa820f-dcdc-4862-b973-b73bdfe4548f">
We did have a couple of PRs regarding the autoPlay prop since 5.1.3. I will close this, but if anyone is still running into this issue, feel free to open a new issue with details and we can take it from there.
