### ISSUE TITLE
textFilters does not work 

### ISSUE THREAD

**Issue by M1chaelChen** [lottie-react-native/lottie-react-native#880]
### Description
The `textFiltersIOS` and `textFiltersAndroid` doesn't replace text.

### Steps to Reproduce

1. Download this lottie file in the zip [lottie_text_01.json.zip](https://github.com/lottie-react-native/lottie-react-native/files/8732917/lottie_text_01.json.zip)
2. Create a Lottie component with textFilters like this
```
<LottieView
  autoPlay
  loop
  source={lottieText}
  style={{ width: 200, height: 300 }}
  textFiltersIOS={[{ keypath: 'welcome_to_lottie', text: 'Welcome' }]}
  textFiltersAndroid={[{ find: 'Welcome to Lottie', replace: 'Welcome' }]}
/>
```

**Expected behavior:** Text are replaced

**Actual behavior:** Text not replaced

### Versions
`"lottie-react-native": "^5.1.3"`

**Comment by suwu150** [comment]
any update? @M1chaelChen

**Comment by ravi-khinchi** [comment]
hey guys, 
on `lottie-react-native: 6.6.0` `textFiltersIOS` is not replacing the text, did anyone faced it ??
I'm on RN `0.72.5`
