### ISSUE TITLE
Failed in detox test

### ISSUE THREAD

**Issue by bgrgit** [lottie-react-native/lottie-react-native#881]
Task :lottie-react-native:mergeExtDexDebugAndroidTest
D8: Invoke-customs are only supported starting with Android O (--min-api 26)

> Task :lottie-react-native:mergeExtDexDebugAndroidTest FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':lottie-react-native:mergeExtDexDebugAndroidTest'.
> Could not resolve all files for configuration ':lottie-react-native:debugAndroidTestRuntimeClasspath'.
   > Failed to transform lottie-5.1.1.aar (com.airbnb.android:lottie:5.1.1) to match attributes {artifactType=android-dex, dexing-enable-desugaring=false, dexing-incremental-transform=false, dexing-is-debuggable=true, dexing-min-sdk=23, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for DexingNoClasspathTransform: /Users/brittognanaraj/.gradle/caches/transforms-3/f519b0162e11af4b9315487771b22b94/transformed/jetified-lottie-5.1.1-runtime.jar.
         > Error while dexing.
           The dependency contains Java 8 bytecode. Please enable desugaring by adding the following to build.gradle
           android {
               compileOptions {
                   sourceCompatibility 1.8
                   targetCompatibility 1.8
               }
           }
           See https://developer.android.com/studio/write/java8-support.html for details. Alternatively, increase the minSdkVersion to 26 or above.

Please help me to fix this

**Comment by matinzd** [comment]
You need to increase minSdk version in your `build.gradle`.

**Comment by bgrgit** [comment]
@matinzd This we need to fix in lottie build.gradle. I already have this config change in my Build.Gradle.

After I added the snippet in lottie build.gradle issues gone
