### ISSUE TITLE
ViewPropTypes will be removed from React Native

### ISSUE THREAD

**Issue by stesvis** [lottie-react-native/lottie-react-native#887]
### Description

After upgrading EXPO and react-native to v`45.0.4` and v`0.68.2` I started getting these warnings in the console:

> ViewPropTypes will be removed from React Native. Migrate to ViewPropTypes exported from 'deprecated-react-native-prop-types'.
> ...
> at node_modules\lottie-react-native\lib\LottieView.js:1:4462 in ViewStyleExceptBorderPropType

I have **lottie-react-native** v`5.0.1` installed.

### Steps to Reproduce
Just add a `<LottieView />` to your screen and you'll get the warnings:

```
<LottieView
        autoPlay
        loop
        source={require("../../assets/animations/loader.json")}
        style={styles.indicator}
      />
```

**Expected behavior:** [What you expected to happen]
No warnings

**Actual behavior:** [What actually happened]
> ViewPropTypes will be removed from React Native. Migrate to ViewPropTypes exported from 'deprecated-react-native-prop-types'.
> ...
> at node_modules\lottie-react-native\lib\LottieView.js:1:4462 in ViewStyleExceptBorderPropType

### Versions

```
{
  'live-dispatch-mobile': '1.0.0',
  npm: '8.8.0',
  node: '16.15.0',
  v8: '9.4.146.24-node.20',
  uv: '1.43.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.18.1',
  modules: '93',
  nghttp2: '1.47.0',
  napi: '8',
  llhttp: '6.0.4',
  openssl: '1.1.1n+quic',
  cldr: '40.0',
  icu: '70.1',
  tz: '2021a3',
  unicode: '14.0',
  ngtcp2: '0.1.0-DEV',
  nghttp3: '0.1.0-DEV'
}
```

**Comment by dlorddoyle-vhs** [comment]
Same!

**Comment by driannaude** [comment]
It appears using `expo install lottie-react-native` actually installs `5.0.1` currently. [This is fixed as of `5.1.3`](https://github.com/lottie-react-native/lottie-react-native/issues/868), and updating to `5.1.3` using `npm` resolved this for me with no obvious side effects as of writing this.

I'd tread carefully however and look out for unintentional side effects until compatibility can be 100% confirmed.

**Comment by dennis-gonzales** [comment]
> It appears using `expo install lottie-react-native` actually installs `5.0.1` currently. [This is fixed as of `5.1.3`](https://github.com/lottie-react-native/lottie-react-native/issues/868), and updating to `5.1.3` using `npm` resolved this for me with no obvious side effects as of writing this.
> 
> I'd tread carefully however and look out for unintentional side effects until compatibility can be 100% confirmed.

Hoping expo team updates us with new version of lottie-react-native to fix the issue once and for all

**Comment by eskoka** [comment]
Has there been any updates on this?

**Comment by dennis-gonzales** [comment]
> Has there been any updates on this?

The expo team graced us already the sdk version 46 which addressed this issue.
I recommend upgrading to remove the warning.

**Comment by hochungwong** [comment]
I've created a patch for version 5.0.1 in case expo doesn't have the fixed version supported

```
diff --git a/node_modules/lottie-react-native/src/js/LottieView.js b/node_modules/lottie-react-native/src/js/LottieView.js
index e3c076d..38337ab 100644
--- a/node_modules/lottie-react-native/src/js/LottieView.js
+++ b/node_modules/lottie-react-native/src/js/LottieView.js
@@ -6,12 +6,12 @@ import {
   View,
   Platform,
   StyleSheet,
-  ViewPropTypes,
   requireNativeComponent,
   NativeModules,
   processColor,
 } from 'react-native';
 import SafeModule from 'react-native-safe-modules';
+import { ViewPropTypes } from 'deprecated-react-native-prop-types';
 import PropTypes from 'prop-types';
 
 const getNativeLottieViewForDesktop = () => {
```

**Comment by gasparnd** [comment]
@dennis-gonzales I updated to expo sdk 46 but i have the same problem. Previously this didn't happen, it started when i updated expo

**Comment by dennis-gonzales** [comment]
@gasparnd are you able to provide us your package json file?

**Comment by gasparnd** [comment]
Sure @dennis-gonzales, i hope resolve this issue

`{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject",
    "postinstall": "patch-package"
  },
  "dependencies": {
    "@codler/react-native-keyboard-aware-scroll-view": "^1.0.1",
    "@expo/config-plugins": "^5.0.0",
    "@pachun/rn-pdf-reader-js": "^0.5.0",
    "@react-native-async-storage/async-storage": "~1.17.3",
    "@react-native-community/datetimepicker": "6.2.0",
    "@react-native-masked-view/masked-view": "0.2.7",
    "@react-navigation/bottom-tabs": "^5.11.1",
    "@react-navigation/native": "^5.8.9",
    "@react-navigation/stack": "^5.12.6",
    "axios": "^0.19.1",
    "buffer": "^6.0.3",
    "expo": "~46.0.7",
    "expo-av": "~12.0.4",
    "expo-camera": "~12.3.0",
    "expo-constants": "~13.2.3",
    "expo-contacts": "~10.3.0",
    "expo-dev-client": "~1.2.1",
    "expo-document-picker": "~10.3.0",
    "expo-file-system": "~14.1.0",
    "expo-font": "~10.2.0",
    "expo-image-manipulator": "~10.4.0",
    "expo-image-picker": "~13.3.1",
    "expo-media-library": "~14.2.0",
    "expo-notifications": "~0.16.1",
    "expo-secure-store": "~11.3.0",
    "expo-updates": "~0.14.4",
    "firebase": "^9.6.7",
    "formik": "^2.1.7",
    "ignore-warnings": "^0.2.1",
    "lottie-react-native": "5.1.3",
    "native-base": "^3.4.12",
    "patch-package": "^6.4.7",
    "pdf-to-base64": "^1.0.3",
    "react": "18.0.0",
    "react-dom": "18.0.0",
    "react-easy-state": "^6.1.3",
    "react-native": "0.69.4",
    "react-native-gesture-handler": "~2.5.0",
    "react-native-page-control": "^1.1.1",
    "react-native-reanimated": "^2.9.1",
    "react-native-redash": "^15.11.0",
    "react-native-safe-area-context": "4.3.1",
    "react-native-screens": "~3.15.0",
    "react-native-svg": "12.3.0",
    "react-native-web": "~0.18.7",
    "react-native-webview": "11.23.0",
    "rn-pdf-reader-js": "^4.1.1",
    "shorthash": "^0.0.2",
    "yup": "^0.29.3"
  },
  "devDependencies": {
    "@babel/core": "^7.18.10",
    "@types/react": "~18.0.17",
    "@types/react-native": "^0.69.5",
    "babel-preset-expo": "^9.2.0",
    "typescript": "^4.7.4"
  },
  "private": true
}`

**Comment by gasparnd** [comment]
Sure @dennis-gonzales  I hope resolve this issue 

`{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject",
    "postinstall": "patch-package"
  },
  "dependencies": {
    "@codler/react-native-keyboard-aware-scroll-view": "^1.0.1",
    "@expo/config-plugins": "^5.0.0",
    "@pachun/rn-pdf-reader-js": "^0.5.0",
    "@react-native-async-storage/async-storage": "~1.17.3",
    "@react-native-community/datetimepicker": "6.2.0",
    "@react-native-masked-view/masked-view": "0.2.7",
    "@react-navigation/bottom-tabs": "^5.11.1",
    "@react-navigation/native": "^5.8.9",
    "@react-navigation/stack": "^5.12.6",
    "axios": "^0.19.1",
    "buffer": "^6.0.3",
    "expo": "~46.0.7",
    "expo-av": "~12.0.4",
    "expo-camera": "~12.3.0",
    "expo-constants": "~13.2.3",
    "expo-contacts": "~10.3.0",
    "expo-dev-client": "~1.2.1",
    "expo-document-picker": "~10.3.0",
    "expo-file-system": "~14.1.0",
    "expo-font": "~10.2.0",
    "expo-image-manipulator": "~10.4.0",
    "expo-image-picker": "~13.3.1",
    "expo-media-library": "~14.2.0",
    "expo-notifications": "~0.16.1",
    "expo-secure-store": "~11.3.0",
    "expo-updates": "~0.14.4",
    "firebase": "^9.6.7",
    "formik": "^2.1.7",
    "ignore-warnings": "^0.2.1",
    "lottie-react-native": "5.1.3",
    "native-base": "^3.4.12",
    "patch-package": "^6.4.7",
    "pdf-to-base64": "^1.0.3",
    "react": "18.0.0",
    "react-dom": "18.0.0",
    "react-easy-state": "^6.1.3",
    "react-native": "0.69.4",
    "react-native-gesture-handler": "~2.5.0",
    "react-native-page-control": "^1.1.1",
    "react-native-reanimated": "^2.9.1",
    "react-native-redash": "^15.11.0",
    "react-native-safe-area-context": "4.3.1",
    "react-native-screens": "~3.15.0",
    "react-native-svg": "12.3.0",
    "react-native-web": "~0.18.7",
    "react-native-webview": "11.23.0",
    "rn-pdf-reader-js": "^4.1.1",
    "shorthash": "^0.0.2",
    "yup": "^0.29.3"
  },
  "devDependencies": {
    "@babel/core": "^7.18.10",
    "@types/react": "~18.0.17",
    "@types/react-native": "^0.69.5",
    "babel-preset-expo": "^9.2.0",
    "typescript": "^4.7.4"
  },
  "private": true
}`

**Comment by delboy1978uk** [comment]
`expo upgrade` fixes the outdated packages and removes the deprecation warning
