### ISSUE TITLE
Animation gone after toggling appearance / dark mode on iOS

### ISSUE THREAD

**Issue by ferdiamg** [lottie-react-native/lottie-react-native#888]
### Description

Animation gone after toggling appearance / dark mode on iOS. Toggling back to the previously working appearance mode doesn't bring it back.
![lottie_bug](https://user-images.githubusercontent.com/19799412/171849827-54f8e702-1185-42a6-b0ca-81d2763b8e77.gif)

### Steps to Reproduce

1. Have a normal lottie animation going on
2. Toggle appearance in simulator or press Cmd+Shift+A (also happens on real devices)
3. Observe how the animation is hidden/gone now

**Expected behavior:** [What you expected to happen]
The animation should still be there, nothing changed.

**Actual behavior:** [What actually happened]
Animation/graphics are completely gone.

### Versions

"lottie-react-native": "5.0.1"
"expo": "~44.0.6"
"react": "17.0.2"
"react-dom": "17.0.2"
"react-native": "https://github.com/expo/react-native/archive/sdk-44.0.0.tar.gz"

**Comment by abdullascriptbh** [comment]
+1

**Comment by mikasius** [comment]
+1

**Comment by IsaacConDosA** [comment]
+1

**Comment by gHashTag** [comment]
The same thing happens when switching to the browser and back.

https://user-images.githubusercontent.com/6774813/193740267-24c1ac97-d030-4e9d-b8b6-d04b69a0677e.MP4

**Comment by mnassabain** [comment]
Any updates on this? Is it possible to fix by downgrading to a previous working version?
