### ISSUE TITLE
Plans to upgrade packge to support lottie-iOS 3.3.0 ?

### ISSUE THREAD

**Issue by JasbirSwi** [lottie-react-native/lottie-react-native#890]
### Description

When using lottie-ios 3.2.3 (current supported version) with react native, we are facing a bluring issue for some shape layers. This issue is fixed in 3.3.0 version of iOS. Can be found [here](https://github.com/airbnb/lottie-ios/releases).

**Comment by yanush** [comment]
There's already lottie-ios 3.4.0
What should we do in order to use it?

**Comment by thespacemanatee** [comment]
If you really want to, here is a workaround for the moment but I have not yet tested if the new versions work well with this library yet:

```patch
diff --git a/node_modules/lottie-react-native/lottie-react-native.podspec b/node_modules/lottie-react-native/lottie-react-native.podspec
index 72e6d71..db5cd43 100644
--- a/node_modules/lottie-react-native/lottie-react-native.podspec
+++ b/node_modules/lottie-react-native/lottie-react-native.podspec
@@ -22,5 +22,5 @@ Pod::Spec.new do |s|
   s.pod_target_xcconfig = { 'DEFINES_MODULE' => 'YES' }
   s.swift_version = "5.0"
   s.dependency 'React-Core'
-  s.dependency 'lottie-ios', '~> 3.2.3'
+  s.dependency 'lottie-ios', '>= 3.2.3'
 end

```

**Comment by zevmo** [comment]
With 3.4.0 out (https://github.com/airbnb/lottie-ios/releases/tag/3.4.0), and significant improvements, this is the version to shoot for I think

**Comment by zevmo** [comment]
Still interested in this update

**Comment by kg-currenxie** [comment]
https://github.com/lottie-react-native/lottie-react-native/releases/tag/v5.1.4
@zevmo 3.4.0 already supported since early august? 🤔
