### ISSUE TITLE
When create a archive build then give this error

### ISSUE THREAD

**Issue by Salmankhan033** [lottie-react-native/lottie-react-native#891]
error when building ios archive 

<img width="1296" alt="Screenshot 2022-06-08 at 4 46 34 PM" src="https://user-images.githubusercontent.com/58082294/172608656-66f37444-f97c-4066-b2ab-e91b561d69c0.png">

**Comment by matinzd** [comment]
Could you please send us some kind of reproduction repo?

**Comment by Salmankhan033** [comment]
> Could you please send us some kind of reproduction repo?

Sorry, Dear, I replaced it with an animated logo
