### ISSUE TITLE
Some animations stop automatically in the middle of the animation.

### ISSUE THREAD

**Issue by 27leaves** [lottie-react-native/lottie-react-native#893]
### Description

We use the library with a bunch of different animations and until now everything worked fine. Lately we had 2 animations that would just stop in the middle of the animation and start again at the beginning when the loop would be finished (I guess). 

### Steps to Reproduce

I created a minimal example
1. Clone https://github.com/goodbag/MinimalLottieExample
2. yarn, pod install and so on
3. Run the app

**Expected behavior:**
The animations loop smoothly

**Actual behavior:** 
The first animation stops in the middle and in the end it flickers and starts at the beginning again.
The second animation stops in the middle and starts at some point at the beginning again.
The third animation runs smoothly -> just one correct example.

See also the provided video

https://user-images.githubusercontent.com/999419/173605138-a9e588ab-4bb9-47aa-99cd-9c1a23ccd162.mp4

### Versions

```
{
  minimallottieexample: '0.0.1',
  npm: '8.4.1',
  node: '14.19.0',
  v8: '8.4.371.23-node.85',
  uv: '1.42.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.18.1',
  modules: '83',
  nghttp2: '1.42.0',
  napi: '8',
  llhttp: '2.1.4',
  openssl: '1.1.1m',
  cldr: '40.0',
  icu: '70.1',
  tz: '2021a3',
  unicode: '14.0'
}
```

**Comment by toshe** [comment]
Having the same issue. Any development on this?

**Comment by 27leaves** [comment]
This is still an issue.

**Comment by simahero** [comment]
I experience the same issue.

**Comment by matinzd** [comment]
Please make sure that you are using proper JSON file which is supported by lottie in android and iOS.
https://lottiefiles.com/supported-features

**Comment by mmkhmk** [comment]
I made sure that we use supported features, but still having the same issue.

**Comment by 27leaves** [comment]
still an issue

**Comment by matinzd** [comment]
Can you also test this on native ios and android Lottie implementation? @27leaves

**Comment by 27leaves** [comment]
@matinzd Thank you for your interest in this issue and sorry for the late reply. I made now also a minimal example using the native IOS implementation. It has the same problem with the above files. You can find it here:

https://github.com/goodbag/MinimalLottieIosExample

**Comment by TheRogue76** [comment]
Closing this as this was resolved in Lottie iOS
