### ISSUE TITLE
viewprops warning is coming for lottie-react-native

### ISSUE THREAD

**Issue by ckswopnera** [lottie-react-native/lottie-react-native#896]
ViewPropTypes will be removed from React Native. Migrate to ViewPropTypes exported from 'deprecated-react-native-prop-types'.

**Comment by RRaideRR** [comment]
I also got that warning after updating expo sdk to 45 and upgrading "lottie-react-native" to 5.0.1.

**Comment by emilioicai** [comment]
This was fixed in v5.1.1, please update to get rid of this error
