### ISSUE TITLE
Is there a way to handle exceptions from native code?

### ISSUE THREAD

**Issue by dwxw** [lottie-react-native/lottie-react-native#902]
### Description

This is a general question: I have a React Native app with several Lottie animations and I use Sentry to report crashes in a the app.  I know there are some animations that cause Lottie to crash on some less popular Android hardware.  I just wonder if there is a way to catch a bad animation without crashing out the whole app.  I've thought about error boundaries, but I understand that would only work if it was a javascript crash.  I could install a global error handler on the native side, but what I'm after is for that bad animation to show blank and the reset of the app to continue.  

Ideally I would like some like this work:

```
<AnimationErrorBoundary>
  <LottieView
    autoPlay
    source={animation.json}
  />
</AnimationErrorBoundary>
```

Any suggestions?  Thanks.

**Comment by matinzd** [comment]
You can try writing a class component wrapper and try to see if you can receive the error in `componentDidCatch`.   As for support you always need to make sure that your animations are supported in the target platform. https://github.com/airbnb/lottie/blob/master/supported-features.md

Please let us know if this could help you with the issue.
