### ISSUE TITLE
Package.json for 5.1.3 not in sync with master

### ISSUE THREAD

**Issue by pepf** [lottie-react-native/lottie-react-native#905]
### Description

This https://github.com/lottie-react-native/lottie-react-native/pull/900 bumps lottie-ios to 3.4.0, but the current published version on npm results in package.json and .podspec file still referring to 3.2.3.

### Steps to Reproduce

Install according to the instructions for the latest library

**Expected behavior:** Pod should resolve

**Actual behavior:** 
err:
```So when installing according to the instruction
[!] CocoaPods could not find compatible versions for pod "lottie-ios":
  In Podfile:
    lottie-ios (from `../node_modules/lottie-ios`)

    lottie-react-native (from `../node_modules/lottie-react-native`) was resolved to 5.1.3, which depends on
      lottie-ios (~> 3.2.3)
```
### Versions

project package.json:
```
    "lottie-ios": "^3.4.0",
    "lottie-react-native": "^5.1.3",
```

Sure I can install 3.2.3 as well, but love to have the latest version now ;)

**Comment by emilioicai** [comment]
We are releasing 6.0.0 soon with this fix
