### ISSUE TITLE
App build fail with "react-native run-ios" after installation

### ISSUE THREAD

**Issue by Bsingh2697** [lottie-react-native/lottie-react-native#911]
### Description
After installation 
`npm i --save lottie-react-native lottie-ios@3.4.0`
I did pod install
and then if I try to build on simulator build, it just does't work.
lottie_react_native.modulemap' not found
<img width="800" alt="Screenshot 2022-08-09 at 01 40 14" src="https://user-images.githubusercontent.com/36998578/183538161-a8bd7fb5-9360-42d3-99f5-a3b7549af08b.png">

### Solutions Already tried
Tried excluding arm64 from pods and target
Clean build
Deleting derived data

### Versions
"lottie-react-native": v5.1.4
"npm" : v8.12.1
"react": "17.0.2",
"react-native": "0.68.2",

**Comment by chenop** [comment]
Try this:
https://stackoverflow.com/questions/55675694/how-to-fix-cocoapod-modulemap-file-not-found
