### ISSUE TITLE
Source is not able to load local assets passed as string

### ISSUE THREAD

**Issue by maulik54e** [lottie-react-native/lottie-react-native#913]
### Description

When source has asset by a string android throws file not found error and iOS doesn’t  load anything  

### Steps to Reproduce

       <LottieView
                    style={{ flex: 1 }}
                    source={'../../assets/lottie/lottie.json'}
                    autoPlay
                  />

**Expected behavior:** animations gets loaded

**Actual behavior:** Android app crashes and iOS doesn't load anything

**Comment by abdullascriptbh** [comment]
The issue is that you are passing a string to the source

Ex. require('path/to/animation.json')

**Comment by matinzd** [comment]
Follow here: https://github.com/lottie-react-native/lottie-react-native/issues/914
