### ISSUE TITLE
Lottie doesn't load on latest version 5.1.4 - lottie-ios: 3.4.0

### ISSUE THREAD

**Issue by ceyanesb** [lottie-react-native/lottie-react-native#914]
```
      <AnimatedLottieView
        style={{ height: 100, width: 100, backgroundColor: 'green' }}
        autoPlay
        loop
        source={'../../../Assets/Animations/loading.json'}
      />
```

App is not showing the animation, previous version worked

**Comment by matinzd** [comment]
> ```
>       <AnimatedLottieView
>         style={{ height: 100, width: 100, backgroundColor: 'green' }}
>         autoPlay
>         loop
>         source={'../../../Assets/Animations/loading.json'}
>       />
> ```
> 
> 
>     
>  
>   
> 
> App is not showing the animation, previous version worked

Hi
You are passing the source as a string. Please consider using `require('../../../Assets/Animations/loading.json')` .

**Comment by ceyanesb** [comment]
@matinzd still doesn't work, I tried that before. Its something with the version of lottie-ios and lottie-react-native

**Comment by emilioicai** [comment]
did you run `yarn install lottie-ios@3.4.0` and `pod install` after switching to 5.1.3?

**Comment by emilioicai** [comment]
I also had issues with autoloop in the beginning, regenerating node_modules did the trick for me

**Comment by ceyanesb** [comment]
Yes and still no luck, did you manage to get it working with this versioning? even the podspec from lottie-react-native had one error of the lottie ios version, that was alledgedly fixed but latest version didn't work either

**Comment by abdullascriptbh** [comment]
It has a bug with the dark mode, turn it off and it will work

I believe this bug ain't fixed yet.

**Comment by matinzd** [comment]
This issue was tested and I can confirm it is working properly on the project I have.

```json
"react-native": "0.69.4",
"lottie-ios": "3.4.0",
"lottie-react-native": "5.1.4"
```

https://user-images.githubusercontent.com/24797481/184382223-95d01292-270a-4075-874c-16d7f78dd28c.mp4

**Comment by emilioicai** [comment]
I couldn't reproduce. Can you confirm android is fine with your code?

**Comment by bleszerd** [comment]
I have a very similar problem with Android devices

```js
"react-native": "0.65.1"
"lottie-react-native": "^5.1.4",
```
Build log: [android_build.log](https://github.com/lottie-react-native/lottie-react-native/files/9328753/android_build.log)

**Comment by exotexot** [comment]
Can you please make a release out of this?

**Comment by emilioicai** [comment]
Please, use the provided patch, a big refactoring will be coming on the next release
