### ISSUE TITLE
android build issue

### ISSUE THREAD

**Issue by matinzd** [lottie-react-native/lottie-react-native#919]
I have a very similar problem with Android devices

```js
"react-native": "0.65.1"
"lottie-react-native": "^5.1.4",
```
Build log: [android_build.log](https://github.com/lottie-react-native/lottie-react-native/files/9328753/android_build.log)

_Originally posted by @bleszerd in https://github.com/lottie-react-native/lottie-react-native/issues/914#issuecomment-1213340018_

Related to: https://github.com/lottie-react-native/lottie-react-native/discussions/894

**Comment by bleszerd** [comment]
Can you verify that the patch is correct? Thank you for your help.

[patch.log](https://github.com/lottie-react-native/lottie-react-native/files/9328853/patch.log)

**Comment by matinzd** [comment]
> Can you verify that the patch is correct? Thank you for your help.
> 
> [patch.log](https://github.com/lottie-react-native/lottie-react-native/files/9328853/patch.log)

You can just remove that line of code in your node_modules folder and run patch-package.
