### ISSUE TITLE
Could not resolve all task dependencies for configuration ':app:developmentDebugRuntimeClasspath'.

### ISSUE THREAD

**Issue by LucasWili** [lottie-react-native/lottie-react-native#922]
### Description

 "react-native": "0.68.2"

[Description of the bug]

### Steps to Reproduce

1. yarn add lottie-react-native lottie-ios@3.4.0
2. react-native run-android

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:preDevelopmentDebugBuild'.
> Could not resolve all task dependencies for configuration ':app:developmentDebugRuntimeClasspath'.
   > Could not resolve com.airbnb.android:lottie:5.1.1.
     Required by:
         project :app > project :lottie-react-native
      > Could not resolve com.airbnb.android:lottie:5.1.1.
         > Could not get resource 'https://www.jitpack.io/com/airbnb/android/lottie/5.1.1/lottie-5.1.1.pom'.
            > Could not GET 'https://www.jitpack.io/com/airbnb/android/lottie/5.1.1/lottie-5.1.1.pom'.
               > Read timed out

"react-native": "0.68.2",

android/build.gradle

`buildscript {
    ext {
        buildToolsVersion = 30.0.0
        minSdkVersion = 23
        compileSdkVersion = 30
        targetSdkVersion = 30
        supportLibVersion = 29.0.0
        kotlin_version = 1.4.10
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:3.4.3")
        classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version")

        classpath 'com.google.gms:google-services:4.3.8'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.4.1'
    }
}

allprojects {
    repositories {
        mavenLocal()
        maven {
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            url("$rootDir/../node_modules/jsc-android/dist")
        }

        maven { url 'https://maven.google.com' }

        maven { url "https://www.jitpack.io" }

        maven {
            url "https://sdk.smartlook.com/android/release"
        }

        google()
        jcenter()
    }
}

subprojects {
    afterEvaluate {
        project ->
            if (project.hasProperty("android")) {
                android {
                    compileSdkVersion = 29
                    buildToolsVersion = "29.0.3"
                }
            }
    }
}
`

**Comment by matinzd** [comment]
Please remove `jcenter()` from the list of repositories and put `google()` on top of `maven { url "https://www.jitpack.io" }`.

For example:

```gradle
allprojects {
    repositories {
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }
        google()
        maven { url 'https://jitpack.io' }
        mavenCentral {
            // We don't want to fetch react-native from Maven Central as there are
            // older versions over there.
            content {
                excludeGroup "com.facebook.react"
            }
        }
    }
}
