### ISSUE TITLE
Lotties are not working for latest library version after podspec update of the library file

### ISSUE THREAD

**Issue by ceyanesb** [lottie-react-native/lottie-react-native#923]
![Screen Shot 2022-08-17 at 11 29 18 AM](https://user-images.githubusercontent.com/14812351/185180155-7366d243-fd50-481e-9e95-c4f718fe11be.png)
@matinzd 

NPMJS docs tell we should install lottie-ios 3.4.0  but github docs does not said that, allegedly the library should auto install lottie-ios, but its failing for me

![Screen Shot 2022-08-17 at 11 32 43 AM](https://user-images.githubusercontent.com/14812351/185180896-69e09d88-6ef2-4f3e-ae7e-c9a90542ebb5.png)

Its confusing...

**Comment by matinzd** [comment]
Please follow documentation in npmjs. 

https://www.npmjs.com/package/lottie-react-native
