### ISSUE TITLE
Unimplemented component: <LottieAnimationView> error message after following installation instructions

### ISSUE THREAD

**Issue by mcalvinobrandcoders** [lottie-react-native/lottie-react-native#928]
### Description

[Description of the bug]

### Steps to Reproduce

code ***

import React from 'react';
import { StyleSheet, Text, View } from 'react-native';
import LottieView from 'lottie-react-native';
import { bellLottie } from '../animations/index';

export default function Index() {
  return <LottieView source={bellLottie} autoPlay loop />;
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});

**Expected behavior:** [What you expected to happe
![simulator_screenshot_02F3275E-B36B-4DF7-BAC7-DE15C5683C37](https://user-images.githubusercontent.com/84166590/187589469-36224867-9331-478a-96cc-828aea8fbe5c.png)
n]

**Actual behavior:** [What actually happened]

### Versions

You can get this information from executing `npm version`.

**Comment by thiavila-sigma** [comment]
The "Unimplemented component" issue happens when you are using Fabric (new arch) but the component mounted doesn't support it (which is the case for Lottie). Fortunately, @AlexanderEggers is already working on a [version supporting Fabric](https://github.com/lottie-react-native/lottie-react-native/pull/910), so we might as well wait.

**Comment by DevMohamed2023** [comment]
I'm still getting this (unimplemented component)

**Comment by shubhamdhingra98973** [comment]
![Simulator Screenshot - iPad (10th generation) - 2024-09-13 at 19 39 39](https://github.com/user-attachments/assets/555cc78e-c8b5-43ef-b65e-b677489267f5)

I am still getting this issue on IOS after migrating from reactive version 0.71.8 -> 0.73.9

Pods used :-     
"lottie-ios": "3.4.0",
"lottie-react-native": "^5.1.6",   // Facing the same issue on the latest version 6.7.2 

Information :-
System:
  OS: macOS 14.6.1
  CPU: (10) arm64 Apple M1 Pro
  Memory: 758.95 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.9.0
    path: ~/.nvm/versions/node/v18.9.0/bin/node
  Yarn:
    version: 1.22.18
    path: /usr/local/bin/yarn
  npm:
    version: 8.19.1
    path: ~/.nvm/versions/node/v18.9.0/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.15.2
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.4
      - iOS 17.4
      - macOS 14.4
      - tvOS 17.4
      - visionOS 1.1
      - watchOS 10.4
  Android SDK: Not Found
IDEs:
  Android Studio: 2024.1 AI-241.18034.62.2412.12266719
  Xcode:
    version: 15.3/15E204a
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.12
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.3.1
    wanted: ^18.2.0
  react-native:
    installed: 0.73.9
    wanted: 0.73.9
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: true

**Comment by shubhamdhingra98973** [comment]
On IOS i am getting this issue when i upgrade the react native version to 0.71.8 -> 0.73.9 
Then I ill update my react-native/gradle-plugin version to 0.75.1

Update this to package.json  "@react-native/gradle-plugin": "0.75.1"

It works for me !!

**Comment by catmans1** [comment]
For projects using react native, if you run on ios then you have to install the `lottie-ios` library, if android then I think add the `lottie-android` library (I haven't tested this case)
```
"lottie-ios": "^4.5.0",
"lottie-react-native": "^7.1.0",
"react": "18.3.1",
"react-native": "0.76.0",
```
