### ISSUE TITLE
Lottie is autoplaying on iOS even if AutoPlay is turned to False

### ISSUE THREAD

**Issue by NanoPek** [lottie-react-native/lottie-react-native#931]
### Description

My lottie file autoplays directly when component mounts, even if auoplay is off. Only on iOS tho.
![image](https://user-images.githubusercontent.com/74069139/192168660-951136d1-a2e5-43cb-90d2-0f53194a8e7b.png)

**Expected behavior:** to load the lottie without directly playing it

**Actual behavior:** it autoplays anywway

### Versions

"lottie-ios": "3.2.3",
"lottie-react-native": "^5.1.3",
"react-native": "^0.69.3",

**Comment by NanoPek** [comment]
Updated and pod installed to 
"lottie-ios": "3.4.1",
"lottie-react-native": "^5.1.4",
 and still not working...

**Comment by NicholasNations** [comment]
I am getting this exact issue as well. No way to stop autoPlay when using a uri on ios. Any fixes?

**Comment by kalashshah** [comment]
> I am getting this exact issue as well. No way to stop autoPlay when using a uri on ios. Any fixes?

Facing the same issue. Can't seem to find any fixes yet.

**Comment by FettahAud** [comment]
Yo guys, I was facing the same issue
Just don't use it, use this instead https://docs.lottiefiles.com/lottie-player/components/lottie-react/methods

**Comment by epletcher72** [comment]
This appears to still be an issue. Does anyone have a solution?
