### ISSUE TITLE
Execution failed for task ':lottie-react-native:androidJavadocs'

### ISSUE THREAD

**Issue by koploop** [lottie-react-native/lottie-react-native#934]
### Description

Please look at the issue in the link below, this question was closed by the proposer but in fact the problem still exists, it still troubles many developers who use this library

https://github.com/lottie-react-native/lottie-react-native/issues/665

**Comment by kamal-j** [comment]
I am also facing this issue.

**Comment by Libero793** [comment]
confirm, same issue here

**Comment by xcdincay** [comment]
I am also facing with this issues. Is there any update about new arch ? @matinzd

**Comment by matinzd** [comment]
> I am also facing with this issues. Is there any update about new arch ? @matinzd 

You can try it with installing `next` tag from npm.
