### ISSUE TITLE
lottieanimationview is not fabric compatible yet

### ISSUE THREAD

**Issue by roots-ai** [lottie-react-native/lottie-react-native#937]
dispatchcommand called without surfacedId fabric dispatcommand must be called through fabric JSI API

with `react-native 0.70.3` and `new-architecture` enabled.

```
{
  npm: '8.19.2',
  node: '14.17.6',
  v8: '8.4.371.23-node.76',
  uv: '1.41.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.17.2',
  modules: '83',
  nghttp2: '1.42.0',
  napi: '8',
  llhttp: '2.1.3',
  openssl: '1.1.1l',
  cldr: '39.0',
  icu: '69.1',
  tz: '2021a',
  unicode: '13.0'
}
```

**Comment by roots-ai** [comment]
@ljharb @dryganets @Minishlink @jalpedersen

**Comment by dryganets** [comment]
I'm not a Lottie maintainer, so can't help you here.

**Comment by roots-ai** [comment]
What about others?

**Comment by kyle-ssg** [comment]
Duplicate. https://github.com/lottie-react-native/lottie-react-native/pull/910

**Comment by haithem-rihane** [comment]
Having the same issue

**Comment by thanhloc-17** [comment]
same issue

**Comment by nguyenvanphuc2203** [comment]
same isue, any support? 🗡️

**Comment by Vigneshwaran-crypto** [comment]
`    "lottie-react-native": "^6.7.0-rc1",
`

**This version worked fine for me**
