### ISSUE TITLE
Lottie only works locally

### ISSUE THREAD

**Issue by harurang** [lottie-react-native/lottie-react-native#939]
### Description

When using Lottie locally, the animation plays as expected. When running the app **not** locally, the app crashes when the animation is played. 

### Steps to Reproduce

1. Add animation using `LottieView`
2. Use `autoPlay` or call `play` to play the animation
3. Confirm the animation works locally
4. Deploy code
5. Attempt to view animation in non local environment. Note that the app crashes

**Expected behavior:** The animation should play.
**Actual behavior:** The animation crashes the app on play.

### Versions
`"lottie-react-native": "5.0.1"`
` "react-native": "0.68.2"`
`"expo": "^45.0.0"`

- I am on a managed version of expo
- I've tried exporting my animation using [Bodymovin](https://exchange.adobe.com/apps/cc/12557/bodymovin), v5.9.0 and [LottieFiles](https://lottiefiles.com/plugins/after-effects) v3.0.2

### Errors
![screen2](https://user-images.githubusercontent.com/19256679/201499242-c1562b08-425b-40bc-8f41-fcb41f8d0d80.jpg)
![screen1](https://user-images.githubusercontent.com/19256679/201499244-00c1be10-6079-44ec-a64c-3eab212fe485.jpg)

**Comment by matinzd** [comment]
Is this just happening on Android?
