### ISSUE TITLE
some error

### ISSUE THREAD

**Issue by xclidongbo** [lottie-react-native/lottie-react-native#940]
[!] CocoaPods could not find compatible versions for pod "lottie-ios":
  In snapshot (Podfile.lock):
    lottie-ios (= 3.2.3, ~> 3.2.3)

  In Podfile:
    lottie-react-native (from `../node_modules/lottie-react-native`) was resolved to 5.1.4, which depends on
      lottie-ios (~> 3.4.0)

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * changed the constraints of dependency `lottie-ios` inside your development pod `lottie-react-native`.
   You should run `pod update lottie-ios` to apply changes you've made.

**Comment by sebastienlabine** [comment]
@xclidongbo You should rename your issue....

I do encounder this problem too with expo SDK 47

**Comment by matinzd** [comment]
Please run `pod update` and let us know if this can fix the issue.

**Comment by matinzd** [comment]
We updated the readme. Please review the instructions again.
