### ISSUE TITLE
"react/bridging/AString.h" file not found

### ISSUE THREAD

**Issue by roots-ai** [lottie-react-native/lottie-react-native#941]
```
"lottie-ios": "^3.4.0",
"lottie-react-native": "^5.1.4",
"react-native": "^0.70.5",
```

**Expected behavior:** Build should succeed.

**Actual behavior:** 
Even though the file is present in `node_modules/react-native/ReactCommon/react/bridging/AString.h`.
It throws an error `Could not build Objective-C module 'React'` `"react/bridging/AString.h" file not found`

Also tried solution as present here
https://github.com/lottie-react-native/lottie-react-native/issues/708#issuecomment-775175081

### Versions
```
{
  npm: '8.19.2',
  node: '14.17.6',
  v8: '8.4.371.23-node.76',
  uv: '1.41.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.17.2',
  modules: '83',
  nghttp2: '1.42.0',
  napi: '8',
  llhttp: '2.1.3',
  openssl: '1.1.1l',
  cldr: '39.0',
  icu: '69.1',
  tz: '2021a',
  unicode: '13.0'
}
```

**Comment by SoohyungJung** [comment]
I'm facing the same issue!

**Comment by virginiab10** [comment]
I have the same issue! There are no solutions yet?

**Comment by matinzd** [comment]
Would you please share your Podfile configuration?
This can be due to using modular headers being enabled.

@roots-ai 
@SoohyungJung 
@virginiab10

**Comment by tristanheilman** [comment]
Same issue here in RN 0.70.5

**Comment by tristanheilman** [comment]
`require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.4'
install! 'cocoapods', :deterministic_uuids => false

target 'MyApp' do

  #rn_maps_path = '../node_modules/react-native-maps'
  #pod 'react-native-google-maps', :path => rn_maps_path

  permissions_path = '../node_modules/react-native-permissions/ios'

  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'Permission-LocationAccuracy', :path => "#{permissions_path}/LocationAccuracy"
  pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"
  pod 'Permission-Motion', :path => "#{permissions_path}/Motion"
  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications"
  pod 'Permission-FaceID', :path => "#{permissions_path}/FaceID"

  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    # Upcoming versions of React Native may rely on get_default_flags(), but
    # we make it explicit here to aid in the React Native upgrade process.
    :hermes_enabled => true,
    :fabric_enabled => flags[:fabric_enabled],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    :flipper_configuration => FlipperConfiguration.enabled(["Debug"], {'Flipper' => '0.163.0'}),
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'MyApp' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      # Set `mac_catalyst_enabled` to `true` in order to apply patches
      # necessary for Mac Catalyst builds
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
`

Here is what my Podfile looks like.

**Comment by tristanheilman** [comment]
Here's what my pod file pretty much looks like.

```require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.4'
install! 'cocoapods', :deterministic_uuids => false

target 'MyExampleApp' do

  #rn_maps_path = '../node_modules/react-native-maps'
  #pod 'react-native-google-maps', :path => rn_maps_path

  permissions_path = '../node_modules/react-native-permissions/ios'

  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'Permission-LocationAccuracy', :path => "#{permissions_path}/LocationAccuracy"
  pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"
  pod 'Permission-Motion', :path => "#{permissions_path}/Motion"
  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications"
  pod 'Permission-FaceID', :path => "#{permissions_path}/FaceID"

  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    # Upcoming versions of React Native may rely on get_default_flags(), but
    # we make it explicit here to aid in the React Native upgrade process.
    :hermes_enabled => true,
    :fabric_enabled => flags[:fabric_enabled],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    :flipper_configuration => FlipperConfiguration.enabled(["Debug"], {'Flipper' => '0.163.0'}),
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'MyExampleAppTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      # Set `mac_catalyst_enabled` to `true` in order to apply patches
      # necessary for Mac Catalyst builds
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
```

**Comment by matinzd** [comment]
It seems this issue is not related to `lottie-react-native`. Will the build succeed if you uninstall `lottie-react-native`?

**Comment by tristanheilman** [comment]
This is the error Xcode is throwing at me. Directly states lottie-react-native. I can try building without.

```
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "lottie-react-native-umbrella.h"
        ^
/Users/treeeest/Projects/WridzRefactorV2/ios/Pods/Headers/Public/lottie_react_native/lottie-react-native-umbrella.h:13:9: note: in file included from /Users/treeeest/Projects/WridzRefactorV2/ios/Pods/Headers/Public/lottie_react_native/lottie-react-native-umbrella.h:13:
#import "Bridging.h"
        ^
/Users/treeeest/Projects/WridzRefactorV2/node_modules/react-native/ReactCommon/react/bridging/Bridging.h:10:10: error: 'react/bridging/AString.h' file not found
#include <react/bridging/AString.h>
         ^
<unknown>:0: error: could not build Objective-C module 'lottie_react_native'
```

**Comment by tristanheilman** [comment]
I also want to state this is only happening for Release builds. My debug builds have been working fine.

**Comment by tristanheilman** [comment]
Also noting that my versions are slightly different. I was unsuccessfully able to get pods to install using the versions listed [here](https://github.com/lottie-react-native/lottie-react-native#versioning) 
```
"lottie-ios": "3.2.3",
"lottie-react-native": "5.1.3",
"react-native": "^0.70.5",
```

**Comment by tristanheilman** [comment]
My project "built" after removing `lottie-react-native`. It failed to resolve the module when bundling the index file. But other than that every other pod/package built successfully. I'm not going to go through my entire package and comment out Lottie. We utilize it in our splash screen, and it'll be a hassle. Please tag me if there's any updates

**Comment by tristanheilman** [comment]
I was able to strangely get passed this issue. Maybe there was some caching issues in my pods? I'm not sure. But after trying to do the build without Lottie, I reinstalled the most recent version. Pods installed. App built.

**Comment by riku99** [comment]
Try it

```
yarn remove lottie-react-native
cd ios
pod install --repo-update
cd ..
yarn add lottie-react-native
cd ios
pod install --repo-update
cd ..
yarn ios
```

**Comment by JJalit** [comment]
Same issue here in RN 0.71.1!!

**Comment by matinzd** [comment]
We have updated all examples to RN 0.71.1 and we did not face this issue at all. Maybe there is something wrong in your dependencies or your environment. I would suggest you installing `lottie-react-native` on a bare project and see if still happens and let us know again.

**Comment by JJalit** [comment]
I solved problem. I missed _`yarn add lottie-ios@3.4.0`_

**Comment by mMarcos208** [comment]
Same issue, any solutions?

**Comment by FadiAboMsalam** [comment]
@mMarcos208  following @riku99 steps worked for me

**Comment by rodgomesc** [comment]
> lottie-ios

after deleting `ios/build` and also applying this patch to force last version of the lib it solved for me


```diff
diff --git a/node_modules/lottie-react-native/lottie-react-native.podspec b/node_modules/lottie-react-native/lottie-react-native.podspec
index 656fc69..d093697 100644
--- a/node_modules/lottie-react-native/lottie-react-native.podspec
+++ b/node_modules/lottie-react-native/lottie-react-native.podspec
@@ -23,7 +23,7 @@ Pod::Spec.new do |s|
   s.author                  = package["author"]
   s.homepage                = package["homepage"]
 
-  s.ios.deployment_target   = '12.4'
+  s.ios.deployment_target   = '13.0'
   s.osx.deployment_target   = '10.12'
   s.tvos.deployment_target  = '12.4'
 
@@ -33,7 +33,7 @@ Pod::Spec.new do |s|
     'Lottie_React_Native_Privacy' => ['ios/PrivacyInfo.xcprivacy'],
   }
 
-  s.dependency 'lottie-ios', '4.4.1'
+  s.dependency 'lottie-ios', '4.4.3'
 
   s.swift_version = '5.7'
 
```
