### ISSUE TITLE
Android animations not playing with RN 0.70.4 and the new build architecture

### ISSUE THREAD

**Issue by mklb** [lottie-react-native/lottie-react-native#948]
### Description

My Lottie animations do not work on Android anymore after upgrading RN. They work on iOS though.

I suspect it's because of react-native 0.70.4 and the new build architecture.

I tried to trigger the animation with `autoPlay` and `this.animationRef.current.play()`. Both do not work on Android. 

Files are loaded via a require and not as a string `source={require('....')}`

### Steps to Reproduce

Build an app with the RN version and the new build architecture + Hermes.

**Expected behavior:** Animations are animating on Android

**Actual behavior:** Animations are static images on Android

### Versions

react-native 0.70.4
lottie-react-native 5.1.4

**Comment by matinzd** [comment]
Have you turned on new architecture? If yes, please try disabling new architecture since it's not supported yet.

**Comment by pvshum** [comment]
For those who came across the same issue and wonder how to disable new architecture, that's how to do it:

> If you run RCT_NEW_ARCH_ENABLED=0 pod install you'll be effectively disabling the New Architecture.

Source: https://github.com/facebook/react-native/issues/34723#issuecomment-1252636508

**Comment by matinzd** [comment]
> For those who came across the same issue and wonder how to disable new architecture, that's how to do it:
> 
> > If you run `RCT_NEW_ARCH_ENABLED=0 pod install` you'll be effectively disabling the New Architecture.
> 
> Source: [facebook/react-native#34723 (comment)](https://github.com/facebook/react-native/issues/34723#issuecomment-1252636508)

New architecure is disabled by default. No need to pass 0 to disable it. 
You can run it without passing environments variable.

**Comment by FrancoTanzarellaEviivo** [comment]
Any idea when support for new architecture will be available?

**Comment by matinzd** [comment]
> Any idea when support for new architecture will be available?
> 
> **EDIT** Following this [https://github.com/lottie-react-native/lottie-react-native/pull/910](url)

No timeline for this. @AlexanderEggers will start working on iOS integration.
