### ISSUE TITLE
Support for Lottie 4.0 for iOS

### ISSUE THREAD

**Issue by sreuter** [lottie-react-native/lottie-react-native#952]
Is using this library together with Lottie 4.0 for iOS already safe/supported?

Reference: https://medium.com/airbnb-engineering/announcing-lottie-4-0-for-ios-d4d226862a54

**Comment by TomCorvus** [comment]
Some commits seem to include changes in this direction like changes about backwards compatibility type aliases mentioned in https://github.com/airbnb/lottie-ios/releases/tag/4.0.0
Maybe with lottie-react-native 6

**Comment by ansh** [comment]
When will v4.0 come out? I am waiting on this as well.

**Comment by ricardobeat** [comment]
The README mentions "when using <= 5.14" more than once (https://github.com/lottie-react-native/lottie-react-native#versioning) but there doesn't seem to be any version, or even branch, with a more recent version being developed?

**Comment by stianjensen** [comment]
I guess it makes sense for this to stay open until 4.0 is supported.
