### ISSUE TITLE
Using fonts in react native and expo

### ISSUE THREAD

**Issue by JoachimKoenigslieb** [lottie-react-native/lottie-react-native#953]
### Description

[Description of the bug]
I want to use lottie animations with fonts in them. I'm not sure how to load them. I'm also using expo, so hopefully I can do this without resorting to native code?

### Steps to Reproduce

Load an animation in a LottieView which contains fonts.

**Expected behavior:**
I hoped that the fonts would render (and animate!)

**Actual behavior:** 
It uses some kind of system font. Animations works tough!

### Versions
I'm using expo sdk 47,
lottie-react-native 5.1.4

**Comment by Dakuan** [comment]
We've also run into this

**Comment by gregoryharkins** [comment]
Hopefully, someone has some insight on this. 
We tested a basic animation, consisting of only a text layer with fluctuating scale. Several different fonts including system fonts and fonts that are already loaded in app, with/without glyphs, embedding in the json and not, etc. The results are as follows:
iOS displays the text but disregards any font, falling back to its default.
Android doesn't display text at all. (Converting to outlines works as expected).

The package includes props for replacing text both iOS and Android, so the assumption is that text layers are supported on both platforms. Can anyone provide some insight on this?

Our use case requires text be dynamically at runtime before the animation plays. Here is the environment:
Expo SDK 47
lottie-react-native 5.1.4

Any suggestions would be appreciated
