### ISSUE TITLE
[windows] problem installing lottie on RNW

### ISSUE THREAD

**Issue by Victor0814gui** [lottie-react-native/lottie-react-native#964]
## Description

when installing and building the lottie-react-native solution for windows cpp/winrt using the CLI I have errors about IUnknow, when I build the solution from visual studio 2019 errors about a directory that it cannot access in C: \Windows\System32\x64\Debug\Generated Files, the directory does not exist.

## attempts to resolve the issue
- uninstall and reinstall visual studio 2019 community
- use visual studio with system administrator
- install visual studio 2022 community
- use visual studio 2022 as administrator
- use react-native CLI to build the solution

- configure project according to documentation even using <WinUIVersion> with versions 2.7.0 and 2.8.1

### react-native CLI
1. `  yarn install lottie-react-native `
2.  `  yarn react-native run-windows `

### Visual Studio 2019
1. build
2. deploy

## imagens do problema
<img src="https://raw.githubusercontent.com/Victor0814gui/issue-assets/main/lottie-issue/lottie%20-error-visual-studio-2019.png" />

<img src="https://raw.githubusercontent.com/Victor0814gui/issue-assets/main/lottie-issue/lottie%20-errors-powershell-cli.png" />

> [more images](https://github.com/Victor0814gui/issue-assets/tree/main/lottie-issue)

## Expected behavior:
a construction without interface errors or errors that prevent the construction of the solution

##Actual behavior: 
"IUnknow" errors and problematic directory

### Versions
**npm**

{
   lottie-react-native: ^5.1.4,
    "react-native": "0.70.6",
   "react-native-windows": "0.70.10",

   reactNativeCustomGallery: '0.0.1',
   npm: '8.11.0',
   node: '16.16.0',
   v8: '9.4.146.24-node.21',
   uv: '1.43.0',
   zlib: '1.2.11',
   brotli: '1.0.9',
   ares: '1.18.1',
   modules: '93',
   nghttp2: '1.47.0',
   napi: '8',
   llhttp: '6.0.7',
   openssl: '1.1.1q+quic',
   cldr: '40.0',
   icu: '70.1',
   tz: '2021a3',
   unicode: '14.0',
   ngtcp2: '0.1.0-DEV',
   nghttp3: '0.1.0-DEV'
}

**Nuget**
- LottieGen.MsBuild 7.0.5
- Microsoft.UI.Xaml 2.7.0
- Microsoft.UI.Xaml 2.6.0
- Microsoft.Windows.CppWinRT
- Win2D.uwp

## Note
when installing the full lottie-react-native repository and through some modifications I managed to run the sample project from the lottie-react-native repository correctly, but I cannot replicate the same in different projects, either using the build configuration from from nuget packages or from rnw's own codebase

**Comment by matinzd** [comment]
@emilioicai As I don't have a windows machine, would you please try testing this?

**Comment by Victor0814gui** [comment]
yes of course

**Comment by emilioicai** [comment]
I couldn't reproduce this one. @Victor0814gui this looks like a permissions issue, do you have a similar issue with other projects?

**Comment by Victor0814gui** [comment]
@emilioicai yes, in any project that I install, it presents the same error

**Comment by aschultz** [comment]
@Victor0814gui  I'm guessing the `IntDir` property is empty for some reason and so when LottieGen.Cpp.targets tries to build the output path from `$(IntDir)Generated Files\Animations\` it ends up with the relative path `Generated Files\Animations\`. That will cause problems since it can end up getting rooted to whatever the current working directory is (in your case, seems to be system32).

As a quick fix try adding this to your vcxproj project file under the "Globals" property group:
```
    <IntDir>$(MSBuildProjectDirectory)\obj\$(Platform)\$(Configuration)\$(ProjectName)\</IntDir>
    <OutDir>$(MSBuildProjectDirectory)\bin\$(Platform)\$(Configuration)\</OutDir>
    <GeneratedFilesDir>$(IntDir)Generated Files\</GeneratedFilesDir>
```

**Comment by Victor0814gui** [comment]
@aschultz  after many tests, I still didn't get results the error in the IUnknown interface continues, but another error appeared in a copy() method, I'll dig deeper here and I'll describe the problems better

**Comment by Victor0814gui** [comment]
> @aschultz after many tests, I still didn't get results the error in the IUnknown interface continues, but another error appeared in a copy() method, I'll dig deeper here and I'll describe the problems better

I'm going to try a reinstallation of all the tools I'm using, to see if the logs change

**Comment by Victor0814gui** [comment]
downloading the official lottie repository for react-native and running it I managed to run it easily without any problem


https://user-images.githubusercontent.com/92493696/226639339-866a4e67-837c-4190-83f0-a65d793ac555.mp4

**Comment by Victor0814gui** [comment]
> downloading the official lottie repository for react-native and running it I managed to run it easily without any problem



### adding below any Microsoft.Cpp.targets

![Captura de tela 2023-03-21 114133](https://user-images.githubusercontent.com/92493696/226642195-5a1d01b6-e5c6-4892-8655-c5199c37a761.png)

### installing nuget packages through visual studio
- LottieGen.MsBuild
- Microsoft.UI.Xaml

``` next steps I'm not so sure if I'm correct ```

in the example project of the repository the list of PackageProviders is inside the App.cpp file, but in the react-native-windows versions it is in AutolinkedNativeModules.g.cpp and adding the visual studio triggers an error stating that it is necessary to run "npx react -native autolink-windows" which makes the changes I made manually disappear, the other way would be to configure it in the same way as shown in the example project, which initially does not show any errors, but when building the solution the project triggers the errors I mentioned previously

### adding lottie file in json format to project

![Captura de tela 2023-03-21 115440](https://user-images.githubusercontent.com/92493696/226646053-a585aa81-72a6-4dd8-bd45-413b4300e2e9.png)

**Comment by Victor0814gui** [comment]
not sure, but everything is generated in the correct place after the changes that @aschultz suggested, however the problem related to IUnknown is triggered due to some problem related to the files generated by LottieGen since all these interface errors are in the animations files generated by LottieGen

**Comment by Victor0814gui** [comment]
after a few weeks of testing, I found that the cause of the ambiguity in IUnknown was caused by using namespace winrt::Windows::Foundation which comes by default in the pch.h file very similar to this question https://github.com/microsoft /microsoft-ui-xaml/issues/5218
