### ISSUE TITLE
[Documentation] Unclear versioning around lottie-ios

### ISSUE THREAD

**Issue by erheron** [lottie-react-native/lottie-react-native#965]
### Description
Hi folks!

In a [github readme](https://github.com/lottie-react-native/lottie-react-native#ios-and-android) you mention that for `lottie-react-native <=5.1.4` an additional install of `lottie-ios` is needed:

>iOS and Android
> Install lottie-react-native (latest):
> yarn add lottie-react-native
> **For lottie-react-native <= 5.1.4 you also need to install lottie-ios@3.4.1 package:**
> yarn add lottie-ios@3.4.1
> More versioning information: [Here](https://github.com/lottie-react-native/lottie-react-native#versioning)

And right below in [versioning](https://github.com/lottie-react-native/lottie-react-native#versioning) in the last row is is said that for above 5.1.4 no separate install of `lottie-ios` is needed. That last row is very confusing, since at the time I'm writing this, **5.1.4** is lottie latest, so something above `5.1.4` would be in the future.
![image](https://user-images.githubusercontent.com/36896640/212381376-6c2be103-3319-4c2b-ae26-afa510047f4d.png)

Could we maybe remove the last row from that table? Or, if there's a typo somewhere, correct that typo? 🙏🏻 
Thanks in advance!

**Comment by emilioicai** [comment]
I agree it's a bit confusing. I'll remove that line until the new version is released. Thanks for the heads up!
