### ISSUE TITLE
New Arch

### ISSUE THREAD

**Issue by sharifhh** [lottie-react-native/lottie-react-native#966]
It is just a question.

Any estimation of when the new arch implementation will be ready?

I see you are doing some work and commits for that, but just wanted to know if there is a roadmap or an estimation of when will it be ready

Thanks and appreciate the work

**Comment by matinzd** [comment]
Hi @sharifhh 
It's expected to be rolled out soon maybe in two weeks but it will be under beta release with some expected bugs.

**Comment by bukhari-flip** [comment]
Any advice on how to try it from master? I tried to install it from the master branch, but end up moving the `package/core` to the root folder and starting `yarn && yarn build`. It currently works on the clean project, but I'm afraid it's not so comfortable to do it every time I clean `node_modules` or just installed another package.

**Comment by matinzd** [comment]
I would suggest you not to turn on new arch for now. Many apps are still experiencing new arch and even benchmarks are not stable enough. 
New arch is also not recommended for production use. @bukhari-flip

**Comment by xcdincay** [comment]
Are there any updates ?  @matinzd

**Comment by matinzd** [comment]
> Are there any updates ? @matinzd

You can start testing it with installing from `next` channel.

**Comment by joemun** [comment]
@matinzd Quick question regarding your WIP v6 work for New Architecture, what will be the minimum React Native version supported to enable new arch? Thanks!

**Comment by joemun** [comment]
@matinzd Hi since this issue was marked as completed, does that mean V6 is soon to released as stable? Thanks!

**Comment by matinzd** [comment]
> @matinzd Hi since this issue was marked as completed, does that mean V6 is soon to released as stable? Thanks!

Yes!
