### ISSUE TITLE
No onAnimationFinish event when updating loop property on iOS

### ISSUE THREAD

**Issue by swemail** [lottie-react-native/lottie-react-native#968]
Hi and thank you for a great library!

### Description

We have a Lottie component that has its `loop` property set to true and later updated to false. The `onAnimationFinish` event is not triggered. The documentation says that `onAnimationFinish` will be called only if `loop` is set to false but not that updating the `loop` property from true to false will have no effect on `onAnimationFinish`. Works as expected on Android but not iOS

### Steps to Reproduce

1. Create a component with `loop` set to some truthy state and `onAnimationFinish` to a callback 
2. Update the state to falsy

**Expected behavior:** onAnimationFinish callback to have been called when animation has finished

**Actual behavior:** Animation stops but onAnimationFinish callback is never called

### Versions
"lottie-ios": "3.4.4",
"lottie-react-native": "5.1.4"

**Comment by matinzd** [comment]
Hi @swemail,

I could not reproduce the issue with the latest version. Even while changing state between starting and ending the animation.

**Comment by swemail** [comment]
> Hi @swemail,
> 
> I could not reproduce the issue with the latest version, even while changing the state between starting and ending the animation.
> 
> Can you try installing `next` version from npm and give us feedback if it is fixed?
> 
> ```
> yarn add lottie-react-native@next
> ```

Thanks, will test it out in a bit.
