### ISSUE TITLE
How to use server  Url  for json file from server 

### ISSUE THREAD

**Issue by skjangid** [lottie-react-native/lottie-react-native#969]
### Description

How to use server  Url  for json file from server 

### Steps to Reproduce

I want to manage the lottie files from backend, admin user can upload the json file from admin and that json file will be use for animation. Is there any way to use the Url ?

**Comment by matinzd** [comment]
Hi

You can also pass `uri` to source prop. 

For example:
```ts
<AnimatedLottieView
  source={{ uri: "https://link.to/animation/url.json" }}
  ...
/>
```
