### ISSUE TITLE
Lottie File with custom font gets cut short on iOS

### ISSUE THREAD

**Issue by Jakebluhm** [lottie-react-native/lottie-react-native#971]
Lottie file can be viewed here: https://app.lottiefiles.com/share/ac6c3dea-703b-4b1f-b85d-b67cad1558ed

Or here is the json:
[ButtonBaseMod(changed to txt bc github doesnt allow json).txt](https://github.com/lottie-react-native/lottie-react-native/files/10471380/ButtonBaseMod.changed.to.txt.bc.github.doesnt.allow.json.txt)

Screen shots when running on iOS:

Clipping on the d:
![IMG_5835](https://user-images.githubusercontent.com/41808367/213838296-f2a3cef0-ab94-4aa4-ac9a-98aef77e378a.jpeg)

Adding a . to json shows how a 'd' should look:
![IMG_5836](https://user-images.githubusercontent.com/41808367/213838289-baeb7514-d48b-4550-936d-ace772998dc6.jpeg)

I'm using the Pacifico font here : https://fonts.google.com/specimen/Pacifico

AE Project
[HoldButton.zip](https://github.com/lottie-react-native/lottie-react-native/files/10471370/HoldButton.zip)

Any one experience similar issues with custom font and Lottie Files? Let me know if any more information is needed to help diagnose this issue.

**Comment by matinzd** [comment]
This can be related to `lottie-ios`. Can you open an issue here as well? https://github.com/airbnb/lottie-ios/issues
