### ISSUE TITLE
A problem occurred configuring project ':lottie-react-native'. Could not set unknown property 'classifier' for task ':lottie-react-native:androidJavadocsJar' of type org.gradle.api.tasks.bundling.Jar.

### ISSUE THREAD

**Issue by footios** [lottie-react-native/lottie-react-native#983]
### Description

When I try to run the app, I get the following error:

A problem occurred configuring project ':lottie-react-native'.
Could not set unknown property 'classifier' for task ':lottie-react-native:androidJavadocsJar' of type org.gradle.api.tasks.bundling.Jar.

Note: I updated lottie-react-native to 5.1.4 (latest) but the problem remains.

### Steps to Reproduce

Run:`npm react-native run-android `

**Expected behavior:** 
Build the app in an emulator

**Actual behavior:** 
After 13% build, I get the aforementioned error.

### Versions

{
  ...: '0.1.3',
  npm: '6.14.15',
  ares: '1.17.2',
  brotli: '1.0.9',
  cldr: '39.0',
  icu: '69.1',
  llhttp: '2.1.4',
  modules: '83',
  napi: '8',
  nghttp2: '1.42.0',
  node: '14.18.1',
  openssl: '1.1.1l',
  tz: '2021a',
  unicode: '13.0',
  uv: '1.42.0',
  v8: '8.4.371.23-node.84',
  zlib: '1.2.11'
}

**Comment by footios** [comment]
I don't get this error if I change the Gradle version. 
Thanks

**Comment by wq13718048209** [comment]
May I ask what version of Gradle you have changed? I have also encountered the same problem @footios

**Comment by footios** [comment]
In Android Studio, File/Project Structure:

Android Gradle Plugin Version
7.4.1

Gradle Version
7.6

**Comment by wq13718048209** [comment]
@footios  thanks
