### ISSUE TITLE
Lottie for iOS when using uri always autoplays

### ISSUE THREAD

**Issue by NicholasNations** [lottie-react-native/lottie-react-native#985]
I am on the most recent version and no matter what I do, it autoplays once on ios when using uri source. With a local source, or a direct json animation, it doesn't only when I use uri source does it do this.
<LottieView
            style={{height: '100%', width: '100%'}}
            source={makeNull ? 'nothing' : asset}
            enableMergePathsAndroidForKitKatAndAbove
            ref={attackRef}
            autoPlay={false}
            loop={false}
            resizeMode="contain"
            progress={progress}
          />

**Comment by matinzd** [comment]
Hi Nicholas

Can you please install `next` version and send us feedback if the issue is resolved?
You can install it by running:
``
yarn add lotti-react-native@next
```

**Comment by NicholasNations** [comment]
any idea when these fixes are going to be released? I want to wait to update my app, but only if it won't be too long.

**Comment by matinzd** [comment]
@NicholasNations Even after merging, it will be available under `rc` release which I won't recommend using that version. Try to use `patch-package`.

**Comment by cavemon** [comment]
Posting in case this is helpful for anyone who comes across this autoPlay issue in iOS.

I ended up controlling the progress of the Lottie animation via the Animated API.

In my example below, I needed to pause the animation a specific frame (`65`), and continue after the user taps.

```js
const TOTAL_FRAMES = 184
const FRAME_RATE = 30

export default function MySweetAnimation({route}) {
    const lottieStage = useRef(0)
    const animationProgress = useRef(new Animated.Value(0))

    useEffect(() => {
        Animated.timing(animationProgress.current, {
            toValue: 65 / TOTAL_FRAMES, // <-- frame at which to pause on / total frames
            duration: 65 / FRAME_RATE * 1000, // <-- frame at which to pause on, in milliseconds
            easing: Easing.linear,
            useNativeDriver: true
        }).start();
    }, [])

    const handlePress = () => {
        if (lottieStage.current < 2) {            
            Animated.timing(animationProgress.current, {
                toValue: 1,
                duration: ((TOTAL_FRAMES - 65) / FRAME_RATE) * 1000, // <-- remainder of the animation
                easing: Easing.linear,
                useNativeDriver: true
            }).start(() => {
                lottieStage.current++
            });
        }
    }

    return (
        <ScrollView>
            
            <Pressable onPress={() => handlePress()}>
                
                <LottieView
                    loop={false}
                    autoPlay={false}
                    autoSize={true}
                    progress={animationProgress.current}
                    source={require('assets/animations/my-sweet-animation.json')}
                />
                
            </Pressable>
            
        </ScrollView>
    );
}
```
