### ISSUE TITLE
[Windows] Styles with positional attributes are applied twice, resulting in incorrect positioning.

### ISSUE THREAD

**Issue by aschultz** [lottie-react-native/lottie-react-native#989]
### Description
LottieView is implemented as:

```
<View style={[aspectRatioStyle, sizeStyle, style]}>
    <AnimatedNativeLottieView style={[
            aspectRatioStyle,
            sizeStyle || { width: '100%', height: '100%' },
            style,
          ]}
    />
</View>
```

Here we can see the incoming style property is applied twice, once to outer view and again to the native control. This means that if the style contains positional settings, such as `{ left: 50 }`, they first cause the outer View container to be translated relative to its parent, and then the animation itself to be translated further.

### Steps to Reproduce
```
<View style={{ backgroundColor: "blue"}}>
    <LottieView style={ { left: 50, width: 50, height: 50, backgroundColor: "red" } } />
</View>
```
**Expected behavior:** Animation is positioned 50 units way from the left side of the surrounding blue box, and the red color is only behind the animation.
![image](https://user-images.githubusercontent.com/1130900/219801161-876f5a06-42d1-4960-bd42-6f8b78f9608b.png)

**Actual behavior:** Red box is positioned 50 units from the left of the surrounding blue box top-left corner, animation is positioned a further 50 units to the right.
![image](https://user-images.githubusercontent.com/1130900/219801083-72f4281a-8ca1-49c6-8234-fbaca7776d78.png)

### Versions
lottie-react-native: 5.1.5
react: 18.0
react-native: 0.69.3
react-native-windows: 0.69.19

Tested on Windows only

### Thoughs on a fix
The View wrapper is needed to support attributes like backgroundColor or accessibility props that aren't directly supported on the native control. Since the View already has the sizing and positioning styles applied, could the native control just be set to fill 100% of the space of the View container? 

```
<View style={[aspectRatioStyle, sizeStyle, style]}>
    <AnimatedNativeLottieView style={StyleSheet.absoluteFill} />
</View>
```

**Comment by matinzd** [comment]
This should get fixed in v6. I will close this for now. 
Feel free to reopen it.

**Comment by aledebla03** [comment]
same issue here in v6,
my code: 
```
<View
      style={{
        paddingHorizontal: 30,
        paddingTop: insets.top ,
        flex:1,
        paddingBottom: insets.bottom + 10,
        backgroundColor: colors.background,
      }}
    >
      <LottieView
      source={require("../../../../assets/lottie/error.json")}
      style={{width: 100, height: 100, backgroundColor: "blue"}}
      autoPlay
      loop
    />
</View>
```

<img width="434" alt="Screenshot 2023-08-01 alle 11 23 07" src="https://github.com/lottie-react-native/lottie-react-native/assets/56274206/1d24fe70-02c0-42b8-9b2d-418d58bda5c7">
