### ISSUE TITLE
Request: add support for dotlottie

### ISSUE THREAD

**Issue by viv3kk** [lottie-react-native/lottie-react-native#996]
Support dotLottie file format :

Since both lottie-ios and lottie-android now support .lottie files, maybe now is a good time add support for dotlottie?

https://github.com/airbnb/lottie-ios/pull/1785
add support for dotLottie  airbnb/lottie-android#1660

**Comment by anurag-dadheech** [comment]
+1, smaller dotlottie files help a lot in reducing RN bundle size.

**Comment by feedthedevil** [comment]
+1

**Comment by mujehoxe** [comment]
+1
